### ISSUE TITLE
Headless Browser showing different Google Login screen

### ISSUE THREAD

**Issue by sardar1592** [laravel/dusk#1005]
- Dusk Version: 6.25.2
- Laravel Version: 8.83.23
- PHP Version: 7.4
- php-webdriver: 1.13.1
- Database Driver & Version:

### Description:

I am facing a really weird issue with Laravel Dusk. All my tests are working fine without headless mode. As soon as I switch on headless mode, the Google login screen just changes to a legacy screen. The identifier input field is no longer there and the test fails. The weirdest part is it happens for live URLs as well. This is causing all my tests in the GitHub actions pipeline to fail. The same is happening on my local machine using Laravel Valet.

Any ideas on how to fix this or what could be happening? Please see screenshots below:

Headless: https://www.dropbox.com/s/6kw6o1kswl666yd/failure-Tests_Browser_Live_Text_testASingleTextIsBeingSentFromProd-0.png?dl=0

In Browser: https://www.dropbox.com/s/zr4u8ajf7t81tko/google_new.png?dl=0

### Steps To Reproduce:

Run a test in browser mode. Runs fine. 
Run a test in headless mode. Shows a legacy Google login screen completely different  from browser version.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by sardar1592** [comment]
I have tried at laracasts. No luck. https://laracasts.com/discuss/channels/testing/headless-browser-showing-different-google-login-screen

**Comment by sardar1592** [comment]
This might help us understand the issue better. How can I change the user-agent in dusk headless mode? 

https://groups.google.com/a/chromium.org/g/headless-dev/c/D1Fzxe4SH0A

**Comment by sardar1592** [comment]
For anyone else landing here, adding the user-agent is what solved it for me. 

`protected function driver()
    {
        $options = (new ChromeOptions)->addArguments(collect([
            $this->shouldStartMaximized() ? '--start-maximized' : '--window-size=1920,1080',
        ])->unless($this->hasHeadlessDisabled(), function ($items) {
            return $items->merge([
                '--disable-gpu',
                '--headless',
                '--no-sandbox',
                **'--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36',**
            ]);
        })->all());

        return RemoteWebDriver::create(
            $_ENV['DUSK_DRIVER_URL'] ?? 'http://localhost:9515',
            DesiredCapabilities::chrome()->setCapability(
                ChromeOptions::CAPABILITY, $options
            )->setCapability('acceptInsecureCerts', TRUE)
        );
    }`
