### ISSUE TITLE
Custom chromedriver install path

### ISSUE THREAD

**Issue by underdpt** [laravel/dusk#1006]
Hello,

While using dusk for browser automation with [Laravel-Zero](https://github.com/laravel-zero/laravel-zero) we found it's not possible to run the chromedriver when the laravel-zero app is built into a phar file, as all vendor files are copied into the phar file, including the chromedriver binaries.

This also generates other issues, like the final user being unable to install the chromedriver if his chrome version changes.

I would like to send a PR to allow specifying the chromedriver install path, being that path used also when creating the process. I'm not sure what would be the best way to specify the install path. Would a `config/dusk.php` configuration file be fine for you? I think a configuration file would open other possibilities (like configuring the sreenshots and logs path, setting custom options for the driver, etc.).

Related: https://github.com/laravel-zero/laravel-zero/issues/193#issuecomment-1310197874

**Comment by driesvints** [comment]
Feel free to attempt a PR and we'll see how it goes 👍
