### ISSUE TITLE
Screenshots folder hardcoded in several places

### ISSUE THREAD

**Issue by ThibaudDauce** [laravel/dusk#101]
Hi,

I don't want to have a `Browser/screenshots` into my tests directory. I already have a folder for my artifacts elsewhere. But I notice that the call to `base_path('tests/Browser/screenshots')` is hardcoded in several places https://github.com/laravel/dusk/blob/90a8cc325d0c2859071f5bb3e7fd600dee418ea0/src/Console/DuskCommand.php#L93 https://github.com/laravel/dusk/blob/d78bfd1088d8411226267936629e399aebc8f45e/src/TestCase.php#L42

Is it possible to create a config file for Dusk allowing to change this parameter? I manage to fix the TestCase with:
```php
    /**
     * Prepare for Dusk test execution.
     *
     * @beforeClass
     * @return void
     */
    public static function prepare()
    {
        Browser::$storeScreenshotsAt = storage_path('tests/screenshots');

        static::startChromeDriver();
    }
```

But I can't find a way to fix the `DuskCommand` class…
I can make a PR if wanted.

Thanks,

**Comment by mario-hoyvoy** [comment]
I do it creating custom command and custom dusk class in my case by modules, but I put you the command for your file system.

### DuskTestCase

```
<?php

namespace Tests;

use Tests\DuskTestCase AS BaseTestCase;

abstract class DuskTestCase extends BaseTestCase
{
    /**
     * Register the base URL with Dusk.
     *
     * @before
     * @return void
     */
    public function propagateScaffoldingToBrowser()
    {
        $return = parent::propagateScaffoldingToBrowser();
        Browser::$storeScreenshotsAt = base_path('tests/screenshots');
        return $return;
    }
}
```

### DuskCommand

```
<?php

namespace Hoyvoy\Console\Commands;

use Laravel\Dusk\Console\DuskCommand AS LaravelDuskCommand;
use Symfony\Component\Finder\Finder;
use Symfony\Component\Process\ProcessBuilder;

class DuskCommand extends LaravelDuskCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'custom-dusk';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Run the Dusk tests for the application';

    /**
     * Actual absolute module folder
     * 
     * @var mixed
     */
    protected $screenshotsFolder = 'tests/screenshots';

    /**
     * Purge the failure screenshots
     *
     * @return void
     */
    protected function purgeScreenshots()
    {
        $files = Finder::create()->files()
                        ->in(base_path($this->screenshotsFolder))
                        ->name('failure-*');
        foreach ($files as $file) {
            @unlink($file->getRealPath());
        }
    }
}

```

**Comment by helmut** [comment]
I agree that it would be nice to easily be able to configure the screenshots directory if possible.

**Comment by mario-hoyvoy** [comment]
I think it's also very good, but at the moment it can only be as this way

**Comment by deleugpn** [comment]
@mario-hoyvoy 1.0.13 might be a breaking change for you.

**Comment by mario-hoyvoy** [comment]
@deleugpn Thanks, I'll correct it when you launch the update.

**Comment by driesvints** [comment]
Gonna close this in favor of https://github.com/laravel/dusk/issues/393
