### ISSUE TITLE
Error message too unspecific

### ISSUE THREAD

**Issue by wq9578** [laravel/dusk#1017]
- Dusk Version: 7.4.0
- Laravel Version: 9.45.1
- PHP Version: 8.2.0
- Database Driver & Version: MySQL v8.0.31

### Description:

This is a follow-up to: https://github.com/laravel/dusk/issues/1016

The error message 

> Failed to connect to localhost port 9515

was given since the following lines were missing in the test file:
```
use Tests\DuskTestCase;
uses(DuskTestCase::class);
```
after commenting out `#uses(DuskTestCase::class)->in('Browser');` in _Pest.php_, which previously specified that all tests in directory _Browser_ should use this class.

The error message is extremely unspecific and should be improved, as users with little experience concerning Dusk will spend much time for finding the cause. It should be easy to check whether this class was loaded or otherwise throw a more specific error message. 

### Steps To Reproduce:

See above.

**Comment by driesvints** [comment]
Thanks @wq9578. It looks like this is an improvement and we'd welcome PR's.

**Comment by wq9578** [comment]
**Update**

The same error message:

> Failed to connect to localhost port 9515 after 0 ms: Couldn't connect to server

occurs if `php artisan dusk:chrome-driver` for updating the driver is called immediately before running the Dusk test(s). I'm using Pest.
In the past, this hasn't been a problem.

In my case this was from a Makefile, but the error is also reproducible within shell only.

Examples:
- Failure on: `php artisan dusk:chrome-driver && php artisan test -v --bail --group=installation`
- Success on: `php artisan test -v --bail --group=installation`

Current versions:
- Dusk Version: 8.2.1
- Laravel Version: 11.16.0
- PHP Version: 8.3.6
- Database Driver & Version: MySQL v8.3.0
