### ISSUE TITLE
Version 7.6.1 not compatible with laravel 9

### ISSUE THREAD

**Issue by joelharkes** [laravel/dusk#1025]
- Dusk Version: 7.6.1
- Laravel Version: 9.52.0
- PHP Version: 8.1
- Database Driver & Version:

### Steps To Reproduce:

```
Error: PHP Fatal error:  Declaration of Illuminate\Foundation\Testing\TestCase::onNotSuccessfulTest(Throwable $exception): void must be compatible with PHPUnit\Framework\TestCase::onNotSuccessfulTest(Throwable $t): never in /home/runner/work/mobilityshop-api/mobilityshop-api/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php on line 301
Error: Process completed with exit code 255.
```

**Comment by driesvints** [comment]
Which PHPUnit version are you using?

**Comment by joelharkes** [comment]
Nothing excit but I expect it might have gotten upgraded as subdeoendency. I will check

**Comment by driesvints** [comment]
Just want to note that PHPUnit 10 isn't compatible with Laravel v9.

**Comment by driesvints** [comment]
@joelharkes did you have a change to check this?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
