### ISSUE TITLE
Enable performance logging for Chrome Driver

### ISSUE THREAD

**Issue by Riley19280** [laravel/dusk#1030]
I would like to add support for saving performance logs from the browser similar to the way console logs are stored (see [here](https://github.com/laravel/dusk/blob/7.x/src/Concerns/ProvidesBrowser.php#L69-L85)). These logs are useful to profile performance, as well as see which network requests a page is making. Would a PR for this functionality for the Chrome driver be accepted?

**Comment by driesvints** [comment]
If you could send in a PR for us to look at we may consider it 👍
