### ISSUE TITLE
Allow a test class to be retried

### ISSUE THREAD

**Issue by eseligquest** [laravel/dusk#1031]
I would like something like 

```
<?php

namespace Tests\Browser;

use Tests\DuskTestCase;

class SomeStuffTest extends DuskTestCase
{
    protected int $retries = 2;
    public function testSomeStuff(): void
    {
    }
}
```
This would re-run the test again if it fails the first time. I wouldn't mind trying to implement this myself with Laravel's retry function but I can't find where in code each test is looped through and ran.

**Comment by driesvints** [comment]
If you could whip up a PR for us to look at that'd be great thanks 👍
