### ISSUE TITLE
A way to have different environment variables

### ISSUE THREAD

**Issue by robertmylne** [laravel/dusk#1037]
A way to dynamically change the .env variables in tests. Currently you can only have a single .env file and cannot change a variable at runtime.

I need a way to test 2 different sets of .env files. This is because we have 2 sites (brands) that share a single Laravel codebase with the only differences being the env files. 

I have found multiple users with the same issues online. There doesn't seem to be a working solution to the problem though. And dusk doesn't have a way to allow multiple .env.dusk.{environment}. It is purely for the environment, to which there is 1 at a time and unfortunately it is also located the .env file.

**Comment by driesvints** [comment]
You can always set environment variables from the CLI:

```bash
env APP_NAME="Dusk" php artisan dusk
```

**Comment by robertmylne** [comment]
Environment variables set via the command line have no effect.

**Comment by kenth-israel-goteam** [comment]
Sorry late to the party. This package helped me: alebatistella/duskapiconf
