### ISSUE TITLE
Can't type() into date input fields

### ISSUE THREAD

**Issue by leewillis77** [laravel/dusk#104]
I'm trying to fill in a form that has a date field in it. Note that this is a plain HTML5 date field,  no JS datepickers or anything to complicate matters, e.g. 

```html
<input class="form-control" name="walk_date" type="date" id="walk_date">
```

Trying to input into that field in a dusk test using type() fails. Sample code:

```php
$browser->type('walk_date', '01-02-2017')
```

Results in the following exception:

```
Facebook\WebDriver\Exception\InvalidElementStateException: invalid element state: Element must be user-editable in order to clear it.
  (Session info: chrome=55.0.2883.95)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.12.3 x86_64)

/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:112
/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:321
/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:597
/vendor/facebook/webdriver/lib/Remote/RemoteExecuteMethod.php:40
/vendor/facebook/webdriver/lib/Remote/RemoteWebElement.php:66
/vendor/laravel/dusk/src/Concerns/InteractsWithElements.php:154
/tests/MhbHelpers.php:21
```

I'm currently working around this using keys(), but it seems like this should be fixed - or at least documented.

Example workaround

```php
 $browser 
     ->keys('#walk_date', '{backspace}')
     ->keys('#walk_date', $walkDate->format('d'))
     ->keys('#walk_date', '{backspace}')
     ->keys('#walk_date', $walkDate->format('m'))
     ->keys('#walk_date', '{backspace}')
     ->keys('#walk_date', $walkDate->format('Y'))
```

**Comment by georaldc** [comment]
Tested this just now and it works for me, but my setup works through selenium and firefox. I could never get chromedriver to work on centos 6

**Comment by leewillis77** [comment]
Hmm, maybe just a ChromeDriver issue then? If someone can confirm then happy to report this elsewhere?

**Comment by thijsvdanker** [comment]
It looks like this issue has been around for at least 3 years:
http://stackoverflow.com/questions/15360362/clear-date-input-fails-on-chromewebdriver

I've created a PR (https://github.com/laravel/dusk/pull/125) to allow typing into a field without clearing it, but I'm not sure if that's the way to go.

**Comment by devinfd** [comment]
fyi; as a work around I have been use the script method to set the date. It's annoying but it works.

```php
$this->browse(function ($browser) use ($user) {
    $browser->loginAs($user)
        ->visit('/sompage')
        ->script([
            "document.querySelector('#the_date_field').value = '2017-02-23'",
        ]);

    $browser->{do other stuff}
});
```
One thing to keep in mind is that `script` does not return the `$browser` instance so it needs to be terminated and the browser variable recalled.

**Comment by devdorego** [comment]
A is use _keys_ method

`keys('.selector', 'datetotype');`


[Laravel Dusk Doc.](https://laravel.com/docs/master/dusk#using-the-keyboard)

**Comment by devinfd** [comment]
@devdorego I tried use the keys method but every time it would misconfigure the date. Maybe you found a reliable way?

```
->keys('#date', '2017-03-01')
```

**Comment by leewillis77** [comment]
@devinfd If you look at my original report I gave an example of how keys() can be used as a workaround.

**Comment by devinfd** [comment]
Follow up, I just end up creating a macro for this:

```php
use Laravel\Dusk\Browser;

Browser::macro('typeDate', function ($selector, $year, $month, $day) {
    $this->keys($selector, $day)
        ->keys($selector, $month)
        ->keys($selector, $year);

        return $this;
});

$this->browse(function ($browser) use ($user) {
    $browser->loginAs($user)
        ->visit("/somepage")
       ->typeDate('#some_date', '2017', '04', '11');
});
```
The problem with this is that its depended on the users system date format. Ie: the date may not be displayed in day/month/year format.

**Comment by Zhastreaus** [comment]
@devinfd 
Replace
```
->keys('#date', '2017-03-01')
```
with
```
->keys('#date', '20170301') // omit the dashes
```

**Comment by devinfd** [comment]
Yea I actually started doing it that a few weeks ago.

Devin Dombrowski
dddesigns3@gmail.com

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by devinfd** [comment]
I ultimately resolved this by not using an input[type="date"] field. Partly because of this issue but also my users were complain about the browser venders date UI.

**Comment by driesvints** [comment]
Just found out there's already a method for this: `append`.

**Comment by amiranagram** [comment]
This worked perfectly fine for me with Chrome driver:

```php
use Carbon\CarbonInterface;
use Facebook\WebDriver\WebDriverKeys;
use Illuminate\Support\Carbon;
use Laravel\Dusk\Browser;

Browser::macro('inputDate', function ($selector, $date) {
    $date = $date instanceof CarbonInterface ? $date : Carbon::parse($date);

    $this->resolver->findOrFail($selector)
        ->sendKeys([
            $date->format('d'),
            $date->format('M'),
            WebDriverKeys::TAB,
            $date->format('Y'),
        ]);

    return $this;
});
```

```php
$browser
    ->inputDate('@date', $tomorrow = carbon()->addDay())
    ->assertInputValue('@date', $tomorrow->format('Y-m-d'))
```
