### ISSUE TITLE
Driver won't download with Telescope enabled

### ISSUE THREAD

**Issue by MSnoeren** [laravel/dusk#1049]
### Dusk Version

7.9.1

### Laravel Version

10.16.1

### PHP Version

8.2

### PHPUnit Version

10.2.6

### Description

When Laravel Telescope is enabled the Chrome driver won't download. A RuntimeException is thrown with the message `Cannot read from non-readable stream`. Disabling Telescope (using `TELESCOPE_ENABLED`) fixes it. I've had the issue on both Github Actions and local (using Sail).

The issue appeared after upgrading to Telescope 4.15.2.

### Steps To Reproduce

1. Install and enable Laravel Telescope.
2. Run `php artisan dusk:chrome-driver --detect`
3. `RuntimeException` is thrown.
4. Disable Telescope.
5. Run `php artisan dusk:chrome-driver --detect` again.
6. Driver installs succesfully.

**Comment by driesvints** [comment]
Heya. Why are you using Telescope on CI?

**Comment by MSnoeren** [comment]
It was enabled by accident. I never noticed it being enabled because all tests my succeeded. I found the issue after upgrading Telescope today and then tried it locally where it failed too :)

**Comment by driesvints** [comment]
@crynobone what are your thoughts? Should we get HTTP client out of that command again?

**Comment by crynobone** [comment]
There few options we can do:

* Change HTTP Client to `GuzzleHttp\Client` explicitly for downloading request. PR #1050 

Other solutions that feel too complex to solve a small issue:

* Disable Telescope recording for downloading requests. Request checking if Telescope is installed. 
* Update Telescope to skip handling such requests, this may be useful for other use cases too.

**Comment by wesselstam** [comment]
Could you please create a new tag for this fix? I cant install this fix without using "dev-master".

Thanks!

**Comment by CamKem** [comment]
Has this fix been published? I am still getting this error locally running 7.9.1.

**Comment by crynobone** [comment]
v7.9.2 has been released.
