### ISSUE TITLE
Error This version of ChromeDriver only supports Chrome version 114 Current browser version is 118.0.5975.0 

### ISSUE THREAD

**Issue by KelvynCarbone** [laravel/dusk#1055]
### Dusk Version

6.25.2

### Laravel Version

8

### PHP Version

8.0

### PHPUnit Version

9.6.11

### Database Driver & Version

8

### Description

When i try run my tests with laravel dusk i receive this error:

Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 118.0.5975.0 with binary path /Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary

I'm installed canary after many tries to solve the problem, but still same error, i think the problem is in the package of dusk

### Steps To Reproduce

Run php artisan dusk Test with php 8, laravel 8 and chrome 116 or 118

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by nbyloff** [comment]
Hi @driesvints ,  I am on PHP v8.1 & Laravel 9. I get a bunch of timeout issues trying to use headless Chrome, so I assumed Chrome got updated and my driver was out of date. When trying to update the chrome driver with dusk, I got the error below. I checked the URL, it does not work but [https://chromedriver.storage.googleapis.com/LATEST_RELEASE_114](https://chromedriver.storage.googleapis.com/LATEST_RELEASE_114) works correctly.

I am looking for a way to revert back to Chrome 114 or how to get my browser & dusk chrome driver back in sync. 

````
# php artisan dusk:chrome-driver --detect

   ErrorException 

  file_get_contents(https://chromedriver.storage.googleapis.com/LATEST_RELEASE_117): Failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

  at vendor/laravel/dusk/src/Console/ChromeDriverCommand.php:325

````
