### ISSUE TITLE
Assertion failure can lead to timeout if using multiple browsers

### ISSUE THREAD

**Issue by stefanvdlugt** [laravel/dusk#1058]
### Dusk Version

7.9.3

### Laravel Version

10.13.5

### PHP Version

8.1.22

### PHPUnit Version

10.2.2

### Database Driver & Version

MySQL 8.0.32 Docker container

### Description

Hello, we may have found a bug with assertion failure handling when multiple browsers are being used. If you open multiple browsers, and an assertion fails before all browsers have been instructed to visit a page, the `captureFailuresFor` method throws a `TimeoutException`.

We have implemented a crude workaround by overriding the `Browser` class so that it sets a boolean to true when the method `visit` is called and only takes screenshots if that boolean is true, but perhaps there is a better solution.

We are using Laravel Sail with Selenium in Docker containers.

### Steps To Reproduce

0. (Not sure if necessary) Use Selenium containers
1. Write a test that uses multiple browsers;
2. Using the first browser, navigate to a webpage, and make an assertion that will fail.

```php
    public function test_this_is_going_to_timeout(): void
    {
        $this->browse(function (Browser $browser1, Browser $browser2) {
            $browser1->visit('https://github.com/laravel/dusk/')
                ->assertSee('THIS_STRING_DOES_NOT_OCCUR');
        });
    }
```

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by mavenik** [comment]
Hi @crynobone @driesvints 

I have been experiencing this issue today. I have created a fresh repository and been able to reproduce the problem consistently. However, I do not use any native installs of PHP, Composer, or Laravel.

Could you help me with relevant instructions to issue a bug report using a docker image or any alternative method please?

Here's the repository for your reference:

1. Repo link - https://github.com/mavenik/dusk_timeouts
2. Commit ref - https://github.com/mavenik/dusk_timeouts/commit/aac7546d736a157bc13008433d87ac986e95233b
3. Terminal output
````php
$ sail dusk --filter TimeoutTest

   FAIL  Tests\Browser\TimeoutTest
  ✓ dusk timeout page has accurate title                                                                                                                                                                    0.60s  
  ⨯ dusk timeout page has header                                                                                                                                                                           60.22s  
  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  
   FAILED  Tests\Browser\TimeoutTest > dusk timeout page has header                                                                                                                             TimeoutException   
  timeout: Timed out receiving message from renderer: 10.000
  (Session info: chrome=119.0.6045.123)

  at vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:136
    132▕                     throw new StaleElementReferenceException($message, $results);
    133▕                 case 'detached shadow root':
    134▕                     throw new DetachedShadowRootException($message, $results);
    135▕                 case 'timeout':
  ➜ 136▕                     throw new TimeoutException($message, $results);
    137▕                 case 'unable to set cookie':
    138▕                     throw new UnableToSetCookieException($message, $results);
    139▕                 case 'unable to capture screen':
    140▕                     throw new UnableToCaptureScreenException($message, $results);

      +8 vendor frames 
  9   tests/Browser/TimeoutTest.php:28


  Tests:    1 failed, 1 passed (2 assertions)
  Duration: 60.94s
````
4. Screenshot of failure 
![Screenshot from 2023-11-22 17-18-33](https://github.com/laravel/dusk/assets/717284/1c1418f2-68ea-41de-ae36-873ade64a71f)

I'm running a [sail](https://laravel.com/docs/10.x/sail) setup. Here are my setup steps if it helps

1. Setup a fresh Laravel Sail application

```bash
curl -s https://laravel.build/dusk-timeouts | bash`
cd dusk-timeouts
./vendor/bin/sail up
````
2. Install Dusk

````bash
./vendor/bin/sail composer require --dev laravel/dusk
./vendor/bin/sail artisan dusk:install
````
3. Test Dusk scaffolding (was successful)

````bash
./vendor/bin/sail dusk
````

4. Create a new browser test

````bash
./vendor/bin/sail artisan dusk:make TimeoutTest
````

5. Execute TimeoutTest

````bash
./vendor/bin/sail dusk --filter TimeoutTest
````

**Comment by Rubrasum** [comment]
### I have the same issue it seems. 

Dusk Version
7.11.4
Laravel Version
10.34.0
PHP Version
8.1.22
PHPUnit Version
10.4.2

### Description
I have a script that visits many pages and does a lot but none of that comes into play. It used to work for the most part and now I am getting this timeout. I am using head, and what I see is a quick flash of a page (maybe?) and then the blank data page. See attached video. 

Here is code where the visit is called: 
```
retry(10, function () use ($browser, $scrape_source, $source_item) {
 $browser->visit($scrape_source->url_root . $source_item->uri)
 ->waitForText('Description', 100);
 }, 2000);
```

**Comment by Rubrasum** [comment]
My issue seemed to be the method I was using with this retry(). I was successful with other tests not using visit like this.

**Comment by TonisfelTr** [comment]
Are there persons who get this error for now?

**PHP**: v8.3.6
**Laravel**: v10.48.8
**Laravel Sail**: v1.29.1
**Laravel Dusk**: v8.2.0

**My code of DuskTestCase implemented class**
```php private const mainLink = 'https://mkb-10.com/index.php?pid=4001';

    public function test_icd_page_read_correctly() {
        $this->browse(function (Browser $browser){
            $mainPage = $browser->visit(self::mainLink)->setChromeOptions("--headless");
            // Tests if page has been got correctly.
            $mainPage->assertSeeLink('https://mkb-10.com/index.php?pid=4002');
        });
    }
```

**Error**:
```
FAIL  Tests\Browser\ExampleTest
  ⨯ basic example                                                                                                                                                                                                                                                        60.68s  
  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  
   FAILED  Tests\Browser\ExampleTest > basic example                                                                                                                                                                                                          TimeoutException   
  timeout: Timed out receiving message from renderer: 10.000
  (Session info: chrome=123.0.6312.86)

  at vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:136
    132▕                     throw new StaleElementReferenceException($message, $results);
    133▕                 case 'detached shadow root':
    134▕                     throw new DetachedShadowRootException($message, $results);
    135▕                 case 'timeout':
  ➜ 136▕                     throw new TimeoutException($message, $results);
    137▕                 case 'unable to set cookie':
    138▕                     throw new UnableToSetCookieException($message, $results);
    139▕                 case 'unable to capture screen':
    140▕                     throw new UnableToCaptureScreenException($message, $results);

      +8 vendor frames
  9   tests/Browser/ExampleTest.php:16


  Tests:    1 failed (1 assertions)
  Duration: 60.80s
```

**Comment by PerryRylance** [comment]
I am seeing this when using two browsers - the exception is thrown during Dusk trying to take a screenshot of the failure.
