### ISSUE TITLE
Support for LTS version of Laravel.

### ISSUE THREAD

**Issue by Modelizer** [laravel/dusk#106]
Most of the products which are built on Laravel are mostly not on the latest version of Laravel. Will it be a breakable change to push dusk on Laravel 5.1 support? Practically speaking its look very weird to upgrade product in every 6 months. Product team focuses on adding new features rather focusing on upgrading framework. For me, there should be at least one version in every series which has LTS support. This way team can focus on upgrading from one LTS to another.

https://laravel-news.com/laravel-release-process

**Comment by garrensweet** [comment]
I don't believe that Laravel 5.1 will get any new functionality, especially no dusk. This is because Laravel's LTS (and most LTS I've encountered) only support bug and security fixes, not new functionality. I would suggest upgrading your code-base.

**Comment by Modelizer** [comment]
Dusk is a separate package. If it would be inside Laravel core then I would not have any objection.

**Comment by DivineOmega** [comment]
@Modelizer I have recently been working on a package that might be of interest to you. It allow you to test JavaScript functionality, by using a headless PhantomJS browser. Like you, I exclusively use Laravel 5.1 LTS and this package is designed for it.

Here's a link: https://github.com/DivineOmega/PhantomJS-Laravel-Testing

**Comment by driesvints** [comment]
We have no plans on offering support for LTS versions. We focus on supporting the latest Laravel framework versions and, if PRs allow it, previous versions.
