### ISSUE TITLE
waitForTextIn() broken in dusk 7.11.2

### ISSUE THREAD

**Issue by emil-nasso** [laravel/dusk#1065]
### Dusk Version

7.11.2

### Laravel Version

10.28.0

### PHP Version

8.2

### PHPUnit Version

10.4.1

### Database Driver & Version

sqlite

### Description

It seems like the behavior of `->waitForTextIn()` was changed/broken in version `7.11.2`.

We have a test case where a button is clicked, the button changes, and is then changed back again after three seconds. The relevant parts look something like this:

```php
$browser->visit(new MyPage($secret))
  ->press('@copy-button')
  ->assertSeeIn('@copy-button', 'Copied!')  
  ->waitForTextIn('@copy-button', 'Copy', 3);
```

The `waitForTextIn()` method asserts that a text can be seen in a selector, and is expected to try repeatedly until it sees the text, or the specified number of seconds have passed.

```php
return $this->waitUsing($seconds, 100, function () use ($selector, $text) {
  return $this->assertSeeIn($selector, $text);
}, $message);
```

When the assertion fails, an exception is thrown, but in the old code, all exceptions were caught:
https://github.com/laravel/dusk/commit/ae5a90c43a22c05f278894370f14eb2058ff1470#diff-61e17fcc4f9de0e83ca12934a78df293a652555e735631e83c53c37977b930b2L404

If I read it correctly, this is no longer the case. When the first assertion fails, the test fails.

Please let me know if I can provide any more information.

### Steps To Reproduce

Use `->waitForTextIn(...);` in a test that expects at least two iterations before it succeeds.

**Comment by voidgraphics** [comment]
Same problem here. I have tracked it down a bit further.

In `vendor/php-webdriver/webdriver/lib/WebDriverWait.php`:

Line 56 throws a `PHPUnit\Framework\ExpectationFailedException` _(from calling `$this->assertSeeIn(...)` in `vendor/laravel/dusk/src/Concerns/WaitsForElements.php` at line 127)_ but the catch statement at line 61 only handles `NoSuchElementException`, so it does not get caught, thus does not re-try after the interval and just fails immediately.

**Comment by crynobone** [comment]
Upon reviewing this bug, `waitForTextIn()` is the only method that doesn't return `bool` using `waitUsing()` but instead make an assertion. Will fix this soon.
