### ISSUE TITLE
Dusk suddenly always fails with "unknown command"

### ISSUE THREAD

**Issue by JVMartin** [laravel/dusk#107]
After upgrading my application to 5.4, I began converting all my integration tests to Dusk browser tests.

This was going very well for the first few tests, when suddenly all of my tests started failing, with this screenshot saved in the `screenshots` folder (simply says `unkown command:`):
![failure-testaccountnormaluser-0](https://cloud.githubusercontent.com/assets/4450814/22681390/c8fc0c92-ecc1-11e6-9ed5-81450ebfd4bb.png)

Now, even on a totally fresh Laravel install, that is what every test gives me every time.

I don't even know where to begin to fix this, `php artisan dusk -vvv` does not give any information.  The browser simply will not load anything anymore.

Can anyone give me guidance on how to debug this?

**Comment by JVMartin** [comment]
If anyone finds this, the issue was in my `.env.dusk.local file`.

It contained:
```
APP_URL=http://127.0.0.1:9515
```

It should have been:
```
APP_URL="http://127.0.0.1:9515"
```

**Comment by martinbean** [comment]
@JVMartin I’m still getting this “Unknown command” response, even with the `APP_URL` value quoted.

**Comment by JVMartin** [comment]
@martinbean I ended up getting this error in a few different situations, and was able to isolate the problem and solve it - the ultimate reason for the error wasn't the lack of quotes or anything to do with the dusk environment file, I don't think.  However, this was so long ago and I've never had the issue again, so I don't remember what the ultimate fix was.

I do remember how I fixed it though.  I found my last working commit - where dusk was still working properly - and slowly replayed commits until I found what was breaking it.  Please let me know if you're able to get it working again.  Good luck!

**Comment by ferdinandfrank** [comment]
@martinbean Did you find a solution? I'm still getting this error. It only opens the browser where it says: "Unknown command: " and then the relative path of the page it tried to view.

So for this test:
```php
public function testBasicExample()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/register')
                    ->assertSee('Laravel');
        });
    }
```
it shows the following screen in the browser:
![failure-testbasicexample-0](https://cloud.githubusercontent.com/assets/19409640/25247788/3ddb2484-260c-11e7-967d-601f482a5e76.png)

I've installed phpunit 6.1.0 and Laravel Dusk v1.0.12.
