### ISSUE TITLE
Dusk slows down after call to dump()

### ISSUE THREAD

**Issue by damms005** [laravel/dusk#1095]
### Dusk Version

8.0.0

### Laravel Version

10.48.2

### PHP Version

8.2.8

### PHPUnit Version

10.5.12

### Database Driver & Version

mysql Ver 8.0.32 for Linux on x86_64 (MySQL Community Server - GPL)

### Description

In a Sail project, when a test is `dump()`'ed, subsequent test runs takes minutes to complete, instead of seconds as in the first run.

### Steps To Reproduce

- Create a new laravel project by following the documentation
- [Add sail to the project](https://laravel.com/docs/10.x/sail#installation)
- [Add dusk to the project](https://laravel.com/docs/10.x/dusk)
- [Add the selenium image](https://laravel.com/docs/10.x/sail#laravel-dusk)
- Bring up your docker containers by running `sail up`
- [Create a new test](https://laravel.com/docs/10.x/dusk#generating-tests) that dumps output and run `sail dusk`

Test code should look like the following
```
public function testExample(): void
{
    $this->browse(function (Browser $browser) {
        $browser->visit('/')
            ->dump('Laravel');
    });
}
```

On first test run, output should be similar to below:
```

```

**Comment by driesvints** [comment]
Thanks! @crynobone has sent in a PR to address this.
