### ISSUE TITLE
php artisan dusk:chrome-driver --detect throw exception

### ISSUE THREAD

**Issue by generationia** [laravel/dusk#1120]
### Dusk Version

6.25.2

### Laravel Version

8.0

### PHP Version

8.0

### PHPUnit Version

9.6

### Database Driver & Version

Maria DB 10.4 on mac

### Description

The command "php artisan dusk:chrome-driver --detect" produces the following error

ErrorException 

  file_get_contents(https://chromedriver.storage.googleapis.com/LATEST_RELEASE_127): Failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

  at vendor/laravel/dusk/src/Console/ChromeDriverCommand.php:325
    321▕         }
    322▕ 
    323▕         $streamContext = stream_context_create($contextOptions);
    324▕ 
  ➜ 325▕         return file_get_contents($url, false, $streamContext);
    326▕     }
    327▕ }
    328▕ 

      +16 vendor frames 
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

### Steps To Reproduce

Type php artisan dusk:chrome-driver --detect

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by crynobone** [comment]
@generationia you should upgrade to latest Laravel Dusk 8 as soon as possible or utilise alternative Chrome Driver installation such as https://github.com/orchestral/dusk-updater
