### ISSUE TITLE
Not compatible with Chrome v128

### ISSUE THREAD

**Issue by muhammadsaeedparacha** [laravel/dusk#1123]
### Dusk Version

8.2.4

### Laravel Version

11.21.0  

### PHP Version

8.3

### PHPUnit Version

11.1.3

### Description

Fails to start with latest chrome version, Chrome 128

Tests\Browser\ExampleTest > basic example                                                                                                                                        WebDriverCurlException   
  Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","goog:chromeOptions":{"args":["--window-size=1920,1080","--disable-gpu"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"ANY","goog:chromeOptions":{"args":["--window-size=1920,1080","--disable-gpu"]}}}

### Steps To Reproduce

Fresh Laravel Installation
Update Chrome to 128

`php artisan dusk` fails

**Comment by crynobone** [comment]
What's your Chrome version?

**Comment by wq9578** [comment]
This might be the same problem as mine [here](https://github.com/laravel/dusk/issues/1122). My full error message is:

>   Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","goog:chromeOptions":{"args":["--window-size=1920,1080","--disable-gpu","--disable-search-engine-choice-screen"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"ANY","goog:chromeOptions":{"args":["--window-size=1920,1080","--disable-gpu","--disable-search-engine-choice-screen"]}}}
> 
> Failed to connect to localhost port 9515 after 0 ms: Could not connect to server

My Chrome version is the newest:
Version 128.0.6613.85

**Comment by crynobone** [comment]
You should be able to fix the issue by updating the following line from `tests/DuskTestCase.php`:

```diff
    /**
     * Prepare for Dusk test execution.
     */
    #[BeforeClass]
    public static function prepare(): void
    {
        if (! static::runningInSail()) {
-           static::startChromeDriver([]);
+           static::startChromeDriver(['--port=9515']);
        }
    }
````

**Comment by 35grain** [comment]
> You should be able to fix the issue by updating the following line from `tests/DuskTestCase.php`:
> 
> ```diff
>     /**
>      * Prepare for Dusk test execution.
>      */
>     #[BeforeClass]
>     public static function prepare(): void
>     {
>         if (! static::runningInSail()) {
> -           static::startChromeDriver([]);
> +           static::startChromeDriver(['--port=9515']);
>         }
>     }
> ```

This did resolve the issue for me.
