### ISSUE TITLE
chrome-driver command "successfully" installs binary even when chromedriver binary doesn't exist.

### ISSUE THREAD

**Issue by iansweeney** [laravel/dusk#1127]
### Dusk Version

8.2.5

### Laravel Version

10.35.0

### PHP Version

8.2.13

### PHPUnit Version

10.5.2

### Description

On Mac OS Sonoma 14.6;
Dusk suddenly started failing ("Curl error thrown for http POST to ..") for me. I realized my chrome and chromedriver were out of sync. I attempted to manually update the driver using the chromedriver command:

php artisan dusk:chrome-driver 128.0.6613.120 

It seemed to update the driver but when I executed the driver directly it was still the old driver (119).  This makes sense as the chromedriver on the [chrome-for-testing page](https://googlechromelabs.github.io/chrome-for-testing/) shows 128.0.6613.119 as the current stable chromedriver. My installed chrome browser is 128.0.6613.120, i.e. the chrome browser is one version ahead of the chromedriver version. Note this was an issue last week two (although the versions were different).

Playing around a bit more I realized I could make up a chromedriver version and the command would execute successfully.

### Steps To Reproduce

Execute the chrome driver command to update the dusk chrome driver using a nonsense string that at least has the major version, e.g. 128.randomstring. The response is that the binary (that doesnt exist) is installed;

> php artisan dusk:chrome-driver 128.randomstring
ChromeDriver binary successfully installed for version 128.randomstring

**Comment by crynobone** [comment]
The command will only rely on the major version to pull in ChromeDriver. The API itself only provide a single install URL for each major version.

**Comment by iansweeney** [comment]
So you're saying that if I ask for 128.0.6613.120, I will get the version google decides to provide (i.e. 128.0.6613.119 in this case)? If I ask for 128.0.6613.113, I will also get 128.0.6613.119.

Isn't that confusing? Why allow the specification of a specific version if its always just getting the major version Google decides to provide? Shouldn't the response at least detail the actual version downloaded, rather than saying you got the version you asked for.

Sidenote; it appears you can manually download a specific version, e.g. https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.120/mac-arm64/chromedriver-mac-arm64.zip. I opened the executable and it confirmed it was 128.0.6613.120.
