### ISSUE TITLE
Dusk Doesn't Recognize Attribute-based Grouping

### ISSUE THREAD

**Issue by paulrrogers** [laravel/dusk#1128]
### Dusk Version

8.2.5

### Laravel Version

11.22

### PHP Version

8.2

### PHPUnit Version

11

### Description

Dusk doesn't recognize attribute grouping (`#[Group('special')]`), while PHPUnit 11 complains about `/** @group … */` comments:

> WARN  Metadata found in doc-comment for class … . Metadata in doc-comments is deprecated and will no longer be supported in PHPUnit 12. Update your test code to use attributes instead.

### Steps To Reproduce

1. put `#[Group('special')]` above a Dusk test method
2. `php artisan dusk --group=special`
3. expect to see just that test run, yet "No tests found" appears instead

**Comment by nielsvh2103** [comment]
yeah i think dusk needs to update their testcase for it to work with attributes, i have the same thing, but thats gonna be an issue starting from phpunit 12, for now you only get a warning

**Comment by crynobone** [comment]
Did you import the correct attribute class?

```php
use PHPUnit\Framework\Attributes\Group;
```

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
