### ISSUE TITLE
Dusk doesn't run after installation.

### ISSUE THREAD

**Issue by digitalroll** [laravel/dusk#1135]
### Dusk Version

7.13

### Laravel Version

10.48.22

### PHP Version

8.3.3

### PHPUnit Version

10.5.35

### Description

Dusk doesn't run after installation.

### Steps To Reproduce

After installing Dusk with the command `composer require --dev laravel/dusk`, I see the following block in the file `./vendor/laravel/dusk/src/Chrome/ChromeProcess.php`:

Line 42:
```
            $filenames = [
                'linux' => 'chromedriver-linux',
                'mac' => 'chromedriver-mac',
                'mac-intel' => 'chromedriver-mac-intel',
                'mac-arm' => 'chromedriver-mac-arm',
                'win' => 'chromedriver-win.exe',
            ];
```

The problem is that after running the command `php artisan dusk:install`, I get a file installed at `./vendor/laravel/dusk/bin/chromedriver-mac-x64/chromedriver`, meaning instead of `chromedriver-mac-intel`, I get `chromedriver-mac-x64`. Consequently, nothing launches or works.

Is this how it's supposed to be, or am I doing something wrong?

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by crynobone** [comment]
you should upgrade to latest Laravel Dusk 8 as soon as possible or utilise alternative Chrome Driver installation such as https://github.com/orchestral/dusk-updater

Alternatively, you can also install Chrome For Testing v126 and Dusk will install ChromeDriver 126 locally. However, your CI would still depends on current available version so this can only be reliable on local machine.

**Comment by digitalroll** [comment]
> you should upgrade to latest Laravel Dusk 8 as soon as possible or utilise alternative Chrome Driver installation such as https://github.com/orchestral/dusk-updater
> 
> Alternatively, you can also install Chrome For Testing v126 and Dusk will install ChromeDriver 126 locally. However, your CI would still depends on current available version so this can only be reliable on local machine.

The thing is, in version 8 of Dusk, I see the same fragment. So, the problem is not in this at all. 

https://github.com/laravel/dusk/blob/8.x/src/Chrome/ChromeProcess.php
```
            $filenames = [
                'linux' => 'chromedriver-linux',
                'mac' => 'chromedriver-mac',
                'mac-intel' => 'chromedriver-mac-intel',
                'mac-arm' => 'chromedriver-mac-arm',
                'win' => 'chromedriver-win.exe',
            ];
```

What should I do?

**Comment by crynobone** [comment]
The problem isn't in the filename but instead new file structure introduced with ChromeDriver 128. Only Laravel Dusk 8 handle this changes

**Comment by digitalroll** [comment]
> The problem isn't in the filename but instead new file structure introduced with ChromeDriver 128. Only Laravel Dusk 8 handle this changes


Okay, thanks for the response. 

I specified version 8 of Dusk in the `composer.json` file, deleted the `vendor` folder, the `composer.lock` file, and reinstalled everything from scratch. 

Now I have the correct file downloaded as `htdocs/vendor/laravel/dusk/bin/chromedriver-mac-x64`. 

However, now I am getting a different error, which was not present in version 7 of Dusk :)

`Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","goog:chromeOptions":{"args":["--window-size=1400,1080","--disable-gpu","--headless"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"ANY","goog:chromeOptions":{"args":["--window-size=1400,1080","--disable-gpu","--headless"]}}}`

**Comment by digitalroll** [comment]
> The problem isn't in the filename but instead new file structure introduced with ChromeDriver 128. Only Laravel Dusk 8 handle this changes

Okay, thanks for the response. 

I specified version 8 of Dusk in the `composer.json` file, deleted the `vendor` folder, the `composer.lock` file, and reinstalled everything anew. Now everything is fine.

Furthermore, now when running tests I get an error that did not occur in version 7 of Dusk.

`Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","goog:chromeOptions":{"args":["--window-size=1400,1080","--disable-gpu","--headless"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"ANY","goog:chromeOptions":{"args":["--window-size=1400,1080","--disable-gpu","--headless"]}}}`

**Comment by crynobone** [comment]
Are you using `DuskTestCase` installed from v7 or the one coming from v8?

**Comment by digitalroll** [comment]
> Are you using `DuskTestCase` installed from v7 or the one coming from v8?

Yes, I copied this file from v8, but the tests only run if I execute `./vendor/laravel/dusk/bin/chromedriver-mac-intel` in the terminal and copy the port number from there into the DuskTestCase.php file. It seems I have to do this every time, which is quite inconvenient. For some reason, the default port 9515 specified there is not accessible. 

Do you have any ideas?

**Comment by crynobone** [comment]
See https://github.com/laravel/dusk/commit/e641800393ce4ad39f0a47133f51aae67ceb01ad

**Comment by digitalroll** [comment]
Okay, I changed the line in the `/tests/Browser/DuskTestCase.php` file from `static::startChromeDriver();` to `static::startChromeDriver(['--port=9515']);` and now the tests are running properly.

Perhaps it should also be changed in the repository itself?

**Comment by digitalroll** [comment]
Perhaps I'm mistaken, but isn't this the main file used in projects when installing Dusk?

[https://github.com/laravel/dusk/blob/8.x/tests/Browser/DuskTestCase.php](https://github.com/laravel/dusk/blob/8.x/tests/Browser/DuskTestCase.php)

In it, I see this line: `static::startChromeDriver();`

**Comment by tomphilpotts** [comment]
> Okay, I changed the line in the `/tests/Browser/DuskTestCase.php` file from `static::startChromeDriver();` to `static::startChromeDriver(['--port=9515']);` and now the tests are running properly.
> 
> Perhaps it should also be changed in the repository itself?

This fixed the issue I was having
