### ISSUE TITLE
Dusk browser testing scripts stopped working - ChromeDriver not supported

### ISSUE THREAD

**Issue by bobclewell** [laravel/dusk#1136]
### Dusk Version

7.13.0

### Laravel Version

10.45.1

### PHP Version

8.1.29

### PHPUnit Version

n/a

### Database Driver & Version

n/a

### Description

I'm using Laravel v10.45.1 and my Dusk browser testing scripts stopped working on my Apple M3 Pro running Sonoma 14.5. I think an upgrade to my Google Chrome browser app may have broken it. 
When I run the following command: `php artisan dusk`

The error I see is:
```
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: 
This version of ChromeDriver only supports Chrome version 126
Current browser version is 129.0.6668.71 with binary path 
/Applications/Google Chrome.app/Contents/MacOS/Google Chrome
```

I tried installing the support driver version...
`php artisan dusk:chrome-driver 126`

I get the following feedback..
`ChromeDriver binary successfully installed for version 126.0.6478.182.`

But I rerun `php artisan dusk`, and get the same error.

I updated Dusk to the latest v7.13.0.
I tried clearing configs and clearing cache.

How can I fix this issue?

### Steps To Reproduce

see above.

**Comment by bobclewell** [comment]
I found this issue that looked similar: https://github.com/laravel/dusk/issues/1123

But explicitly setting the port in `DuskTestCase.php` didn't fix the issue. 

```
// DuskTestCase.php

    public static function prepare(): void
    {
        if (! static::runningInSail()) {
            static::startChromeDriver(['--port=9515']);
        }
    }
```

I tried clearing caches and configs after making this change. Could there have been something that I missed? Or is it unrelated?

**Comment by bobclewell** [comment]
The bug (?) is that Dusk appears to be using the Google Chrome browser app installed on my computer which is using Chrome Driver v129. But, I tried removing that application, and when I do that Dusk fails to find the ChromeDriver altogether.

Can I either?

1. Point Dusk to an instance of the Chrome Driver that is not the web browser?

2. Or, install an instance of the Google Chrome web browser that is using v126 of the Chrome Driver?

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by crynobone** [comment]
@bobclewell you should upgrade to latest Laravel Dusk 8 as soon as possible or utilise alternative Chrome Driver installation such as https://github.com/orchestral/dusk-updater

**Comment by crynobone** [comment]
Alternatively, you can also install Chrome For Testing v126 and Dusk will install ChromeDriver 126 locally. However, your CI would still depends on current available version so this can only be reliable on local machine.
