### ISSUE TITLE
ChromeDriver Does not seem to update when running php artisan dusk:chrome-driver

### ISSUE THREAD

**Issue by roarkmccolgan** [laravel/dusk#1139]
### Dusk Version

7.13

### Laravel Version

9.52.16

### PHP Version

8.1.29

### PHPUnit Version

9.5.10

### Database Driver & Version

MySql Mac

### Description

I'm on a mac 2,3 GHz 8-Core Intel Core i9

My dusk tests were not running, I would get:
```
Failed to connect to localhost port 9515 after 0 ms: Couldn't connect to server
```
I run artisan dusk:chrome-driver --detect (or no params or even provide version 129)

Same issue would occur, I removed all the files from /vendor/laravel/dusk/bin except for jquery.js (as it is on the repo)
I run artisan dusk:chrome-driver again and chromedriver-mac-x64.zip is put into the bin folder, and is unzipped,
the `chromedriver` file is in the chromedriver-mac-x64 folder and now structure looks like this:
```
bin
     chromedriver-mac-x64 (folder)
            chromedriver(file)
            LICENSE.chromedriver(file)
    THIRD_PARTY_NOTICES.chromedriver-mac-intel (file)
    jquery.js
```

The file ChromeProcess is looking for is: `chromedriver-mac-intel` (one of the files I removed) and it is never replaced, so I get a new error:

```
 Invalid path to Chromedriver [/Users/roark/Code/nano/vendor/laravel/dusk/src/Chrome/../../bin/chromedriver-mac-intel]....
```
Not sure why or how I can force the script to replace chromedriver-mac-intel

Thanks!

### Steps To Reproduce

Delete all files from vendor/laravel/dusk except jquery.js
Run php artisan dusk:chrome-driver

files are not replaced

**Comment by crynobone** [comment]
See https://github.com/laravel/dusk/issues/1136#issuecomment-2381825379
