### ISSUE TITLE
assertStringContainsString doesn't display the specified message

### ISSUE THREAD

**Issue by efcor** [laravel/dusk#1146]
### Dusk Version

8.2.9

### Laravel Version

11.28.1

### PHP Version

8.3.12

### PHPUnit Version

11.4.2

### Description

When doing $this->assertStringContainsString('foo', 'bar', 'My custom message.'); in a test, Dusk's output for that test does not display "My custom message." I double checked and assertStringContainsString does have a third parameter for a message, similar to assertSame.

If you do $this->assertSame('foo', 'bar', 'My custom message.'); in a test, Dusk's output for that test will render "My custom message" as expected.

$this->assertSame('foo', 'bar', 'My custom message.');

![Screenshot 2024-10-21 at 11 53 06 AM](https://github.com/user-attachments/assets/cff26aad-987e-457c-96bc-4cc49b013bcc)

$this->assertStringContainsString('foo', 'bar', 'My custom message.');
![Screenshot 2024-10-21 at 11 53 22 AM](https://github.com/user-attachments/assets/1aee3219-30bc-476d-9ebf-af5e624e5578)

### Steps To Reproduce

Be on Mac OS 14.6.1 (Apple Silicon)
Have Chrome Version 130.0.6723.59 (Official Build) (arm64)

Run:
laravel new laravel (no scaffolding etc in the wizard)
composer require laravel/dusk --dev
cd laravel
herd link

php artisan dusk:install
php artisan dusk:chrome-driver

Add $this->assertStringContainsString('foo', 'bar', 'My custom message.'); to the Tests\Browser\ExampleTest test.

Run php artisan dusk.

**Comment by crynobone** [comment]
Can you test if the output is the same after `composer remove nunomaduro/collision --dev`?

**Comment by efcor** [comment]
The output does contain the "My custom message" after doing that.

![Screenshot 2024-10-23 at 1 44 23 PM](https://github.com/user-attachments/assets/17408957-cfb1-47de-99fa-9b432228c937)

**Comment by crynobone** [comment]
`nunomaduro/collision` overrides PHPUnit's default printer, I believe this should and can only be solved by reporting the issue to the correct repository: https://github.com/nunomaduro/collision/
