### ISSUE TITLE
Filter option no longer working

### ISSUE THREAD

**Issue by Jmrich** [laravel/dusk#116]
Just went to add a test to my dusk suite and noticed that the `--filter` option is no longer supported with phpunit 5.7.11. In my other project it is using 5.7.8, and dusk works fine with the `--filter` option. So not sure if this is something purely dusk related vs phpunit.

**Comment by timleland** [comment]
This works for me
php artisan dusk --filter=testPage

**Comment by sileence** [comment]
Same here, using `--filter=something` works

**Comment by fvasquezl** [comment]
Not for me
Curl error thrown for http DELETE to /session/5af9f37d83b9de7a4df8b8b58a976006

Using --filter option
Laravel 5.8   Dusk 5.1    ChromeDriver version 75.0.3770.90
