### ISSUE TITLE
Cannot mock notification in dusk test

### ISSUE THREAD

**Issue by melihovv** [laravel/dusk#121]
I try to write dusk test for password restore feature. 
```php
use Illuminate\Auth\Notifications\ResetPassword;

class RestorePasswordTest extends DuskTestCase
{
    use DatabaseMigrations;

    public function testResetPassword()
    {
        $user = factory(User::class)->create();

        $this->browse(function (Browser $browser) use ($user) {
            Notification::fake();

            $browser
                ->visit('/password/reset')
                ->type('email', $user->email)
                ->press('Send Password Reset Link')
                ->assertPathIs('/password/reset');

            Notification::assertSentTo($user, ResetPassword::class);
        });
    }
}
```
When I run this dusk test it fails with error
```
There was 1 failure:

1) Tests\Browser\RestorePasswordTest::testResetPassword
The expected [Illuminate\Auth\Notifications\ResetPassword] notification was not sent.
Failed asserting that false is true.

/home/melihovv/Projects/seo-service/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/NotificationFake.php:39
/home/melihovv/Projects/seo-service/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/NotificationFake.php:31
/home/melihovv/Projects/seo-service/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
/home/melihovv/Projects/seo-service/tests/Browser/RestorePasswordTest.php:37
```
And it actually sends email, not mocks it.
But in other project using browser-kit-testing syntax the [same test](https://github.com/melihovv/grammar_review_tool/blob/acce96d/tests/Http/Controllers/Auth/ForgotPasswordControllerTest.php) passes

We cannot use mocking in dusk tests?

laravel/dusk 1.0.5, laravel/framework 5.4.9

**Comment by georaldc** [comment]
I don't think it's possible at the moment to modify the framework's environment because your test files and dusk run separately. 5.3 testing/unit testing/browserkit works because that isn't the case with those

**Comment by ryancwalsh** [comment]
@georaldc In a Dusk test, I wanted to use `Bus::fake();` (https://laravel.com/docs/5.7/mocking#bus-fake) so that I could prove that a certain job would have been dispatched. 

I didn't understand your comment. Do you have a suggestion for how I can assert in Dusk that a certain job is called? Thanks.

**Comment by ryancwalsh** [comment]
Oh man... using the package suggested here looks super complicated: https://github.com/laravel/dusk/issues/152#issuecomment-368570756

https://hackernoon.com/asserting-jobs-in-queue-with-laravel-dusk-adb03654ca43 and https://medium.com/@iantonioribeiro/asserting-email-was-sent-with-laravel-dusk-35510995d605 look interesting and maybe simpler (although less flexible).
