### ISSUE TITLE
Iterate throw elements

### ISSUE THREAD

**Issue by ahmedash95** [laravel/dusk#126]
Hi , I don't find any solution for my case using dusk. let's say I have an html table with 5 rows, what is the method I should use to iterate .. for example

```php
public function testBasicExample()
{
    $this->browse(function (Browser $browser) {
        $browser->visit('/support/messages')
        		->each('tr.message',function($el){
        			$el->click('view')
        				->assertSee('View Message');
        		});
    });
}
```

so with the function ```each``` I could perform actions for each page .

**Comment by Numline1** [comment]
+1

**Comment by deleugpn** [comment]
I think I might have faced a similar problem. I assumed that we would be able to interact with elements like jQuery while in reality it is not that simple. Facebook WebDriver is pretty great, but it poses some limitations nonetheless. Perhaps the Chrome Driver itself imposes such limitations.

**Comment by Numline1** [comment]
Actually, I was able to go around this issue and I found a solution, however dirty may it be. You can use the element() or elements() method on your browser instance, meaning that you're easily able to grab the underlying element (for example a table). You can then search for a specific elements, using WebDriver's WebDriverBy class methods (for example WebDriverBy::css() or xpath() or others). This will get you an array of elements, on which you can then iterate and get it's elements values etc.

**Comment by nateritter** [comment]
@Numline1 can you provide a code example of what you're doing?

**Comment by Numline1** [comment]
@nateritter sure, here's a quick sample we've used in our project. I suggest reading some docs about using Facebook WebDriver, which is the underlying solution used by Dusk to work with browsers/Selenium.

```php
public function addMenu($restaurantName, $date, $note)
    {
        $this->browse(function ($browser) use ($restaurantName, $date, $note) {
            // First step is to retrieve all <tr> elements within the table on menu list page. These lines
            // contain all the menus that were defined so far.
            $elements = $browser->visit('/some/censored/path/winkyface')
                                ->elements('.table tr');
            // Setting the removal link to null. This will later be filled with an actual value if the menu
            // already exists.
            $removalLink = null;
            // Now we iterate through all the elements within each <tr>. These are usually <td> elements with
            // restaurant name, menu date and others.
            foreach ($elements as $element) {
                $subElements = collect($element->findElements(WebDriverBy::xpath('*')));
                // Now we check if the restaurant name matches, if the date matches and then we get the menu
                // removal link.
                if ($subElements->slice(1, 1)->first()->getText() === $restaurantName) {
                    if ($subElements->slice(2, 1)->first()->getText() === $date->format('d.m.Y')) {
                        $removalLink = $subElements->slice(5, 1)
                            ->first()
                            ->findElement(WebDriverBy::tagName('a'))
                            ->getAttribute('href');
                    }
                }
            }
            // If the menu and the removal links exist, we access the page via visit() method and remove the menu.
            if ($removalLink) {
                $browser->visit(explode('.sk', $removalLink)[1])
                    ->assertSee('Menu bolo odstránené.');
            }
            // Finally, we add the new menu with our desired parameters.
            $browser->visit('/admin/menu/pridat-menu')
                ->select('#admin_menuType_store', $restaurantName)
                ->type('#admin_menuType_date', $date->format('d/m/Y'))
                ->type('#admin_menuType_information', $note)
                ->press('Uložiť')
                ->assertSee('Menu bolo pridané.');
        });
    }
```

**Comment by nateritter** [comment]
Thanks @Numline1.  While waiting for your answer, I found a solution which just counts the elements and then iterate through them using `nth-child` CSS selector.  In my particular case, I wanted to start on an element which wasn't the first one in the list, but you get the drift.

Thanks for responding with your version though. That gives more insight into what's possible with the behind-the-scenes dependencies.

```
public function testClickingAccountImportButtonsForAllAccounts()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/users/login')
                ->waitFor('.button-primary')
                ->assertSee('Sign In')
                ->type('.login-username', config('ynab.email'))
                ->type('.login-password', config('ynab.password'))
                ->press('.users-form .button-primary')
                ->waitFor('li.navlink-accounts')
                ->assertSee('All Accounts')
                ->click('li.navlink-accounts > a');

            $this->importAccounts($browser, '.onBudget .nav-account-row');
            $this->importAccounts($browser, '.offBudget .nav-account-row');
        });
    }

    /**
     * Imports accounts underneath the given element
     *
     * @param  object $browser The browser object we are using
     * @param  string $element Parent element selector of a list of accounts
     * @return void
     */
    private function importAccounts($browser, $element)
    {
        // $output = new ConsoleOutput(); // To be able to write debug info to the console.
        // $output->writeln('Something: ' . $foo); // Example of writing output to the console.

        $numAccounts = count($browser->elements($element));

        for ($i = 2; $i <= $numAccounts; $i++) {
            $browser->click($element . ':nth-child(' . ($i) . ') .nav-account-value');

            $text = $browser->text('.accounts-toolbar-left button:nth-child(3)');
            $class = $browser->attribute('.accounts-toolbar-left button:nth-child(3) > i', 'class');

            // If $class contains 'download-document', it's because it's a file import
            // If $text contains "(!)", it's because there's something wrong with the account

            if (strpos($class, 'download-document') === false && strpos($text, '(!)') === false) {
                $browser->click('.accounts-toolbar-left button:nth-child(3)');
            }

            $browser->pause(500);
        }
    }
```

**Comment by bozhkos** [comment]
i`m using this little trick. Pretty useful, if your multiple components have unique ID`s

`    /** @test */
    public function super_user_can_see_currencies_settings_page()
    {
        $user = factory(User::class)->create();

        $this->browse(function (Browser $browser) use ($user) {
            $checker = $browser->loginAs($user)->visit(new CurrenciesPage);

            $checker->assertSee('Currencies history graph');
            $checker->assertSee('Current rates');

            \Artisan::call('service:refresh-rates');
            $checker->pause(200);

            Currency::all()->each(function (Currency $currency) use ($checker) {
                $checker->assertSee($currency->rate->ccy);
                $checker->assertSee($currency->rate->base_ccy);
                $checker->assertSee($currency->rate->created_at);
                $checker->assertSee($currency->rate->updated_at);
                $checker->click("currencies-details-{$currency->id}");
               //  Do whatever you need 
            });
        });
    }
`

**Comment by furqanfreed** [comment]
In my scenario i had to iterate through input and select elements on form so i did 

`$formInputElements = $response->elements('.is-form input, .is-form select');

\Log::info('total elements on form '. count($formInputElements).'   Elements:  '. json_encode($formInputElements));`


which return 

`total elements on form 12   Elements:  [{},{},{},{},{},{},{},{},{},{},{},{}] `

but when i deploy on server i get 

total elements on form 0   Elements:  []


so i updated that to

`$formInputBoxElements = $response->elements('form.is-form input');
$formSelectElements = $response->elements('.is-form select');

$formInputElements = array_merge($formInputBoxElements,$formSelectElements);
`

and its worked perfectly fine.

**Comment by dadigu** [comment]
I've been looking for a similar feature where I can the same assertions/actions with-in multiple elements. Finally found this issue. I liked the solution by @Numline1 So I've made a macro so I can use this in multiple tests. 

I needed to assert that all list items or table rows contained the same text after doing some filtering on the table/list. 

I'm not sure if this is the optimal solution, but It works in my case, so I'll share it here if someone is looking for some thing similar.

```php
Browser::macro('withinEach', function (string $selector, Closure $callback) {

     $elementsCount = count($this->elements($selector));

     for ($i = 1; $i <= $elementsCount; $i++) {
          $this->within($selector . ":nth-child({$i})", function ($browser) use ($callback) {
               $callback($browser);
          });
     }

     return $this;
});
```

Then you can use it like this in a Dusk test

```php
$this->browse(function (Browser $browser) {
    $browser
        ->visit(new MyPage())
        // Doing some filtering here..
        ->withinEach('@listItem', function (Browser $listItem) {
            $listItem->assertSee('Hello world');
        });
});
```

**Comment by troccoli** [comment]
I know this issue is closed, but his was exactly what I was trying to do and @dadigu solution helped, but didn't work. I hope my solution can help someone else.

My HTML contains multiple `<div>` with the same `dusk` attribute. This makes sense to me, as they all represent the same this: a post

```html
<div>
    <div dusk="post">
        <!-- ... -->
    </div>
    <div dusk="post">
        <!-- ... -->
    </div>
    <div dusk="post">
        <!-- ... -->
    </div>
</div>
```

My test was

```php
$browser->loginAs($this->editor)
    ->visitRoute('dashboard')
    ->clickLink('Posts')
    ->withinEach('@post', function (Browser $post): void {
        $post->assertPresent('@edit-post')
            ->assertMissing('@delete-post');
        })
    ->logout();
```

But @dadigu solution threw this error

`Element [body [dusk="post:nth-child(1)"] [dusk="edit-post"]] is not present.`

Initially I changed the selector in my test to `withinEach('[dusk="post"], ...)` and that worked, so I have now updated the `withinEach` macro to the following

```php
Browser::macro('withinEach', function (string $selector, Closure $callback) {

     $elementsCount = count($this->elements($selector));

     if (Str::startsWith($selector, '@')) {
         $selector = Str::replaceFirst('@', '[dusk="', $selector) . '"]';
     }

     for ($i = 1; $i <= $elementsCount; $i++) {
          $this->within($selector . ":nth-child({$i})", function ($browser) use ($callback) {
               $callback($browser);
          });
     }

     return $this;
});
```

and now my test works.
