### ISSUE TITLE
phpunit.dusk.xml not preserved

### ISSUE THREAD

**Issue by SebastianS90** [laravel/dusk#130]
Is it intentional that the `phpunit.dusk.xml` file is [always overwritten](https://github.com/laravel/dusk/blob/v1.0.6/src/Console/DuskCommand.php#L113) before running the tests and [deleted](https://github.com/laravel/dusk/blob/v1.0.6/src/Console/DuskCommand.php#L116) afterwards?

**Comment by head82** [comment]
I can aggree to that but it seems, that phpunix.dusk.xml is not used for environment handling. see this: https://laravel.com/docs/5.4/dusk#environment-handling

**Comment by SebastianS90** [comment]
Sure, you cannot change the environment in the XML file because it won't be available for the app running in your web server.
But you can setup different test suites or change other phpunit parameters.
