### ISSUE TITLE
Setting value of a selected element to 0 fails

### ISSUE THREAD

**Issue by robertravnik** [laravel/dusk#131]
Hi guys,

I've been migrating some testing of my projects to Dusk and it is amazing. However, I've come to a situation, where i think that `Browser`'s class method `value($selector, $value = null)` does not behave as expected.

Consider we have a select element

```
<select id="enabled">
  <option value="1">Enabled</option>
  <option value="0">Disabled</option>
</select>
```

Using the following sample code:

```
$this->browse(function ($browser) {
    $browser->value('#enabled', 0);
});
```

or

```
$this->browse(function ($browser) {
    $browser->value('#enabled', '0');
});
```

I would expect that value of element #enabled will be set to 0, but it is not. Instead method returns element's value. After examining value() source code in `InteractsWithElements.php:`

```
public function value($selector, $value = null)
{
    if (! $value) {
        return $this->resolver->findOrFail($selector)->getAttribute('value');
    }

    $selector = $this->resolver->format($selector);

    $this->driver->executeScript(
        "document.querySelector('{$selector}').value = '{$value}';"
    );

    return $this;
}
```

I believe that the problem is in initial $value checking which should be changed to:

```
if (is_null($value)) {
    return $this->resolver->findOrFail($selector)->getAttribute('value');
}
```

Keep up the good work! r

**Comment by KKSzymanowski** [comment]
Although this is a bug in my opinion, I think you should use `Browser::select()`(or more precisely `InteractsWithElements::select()` to change the value of a drop-down input.

**Comment by browner12** [comment]
just an FYI, you will run into issues when trying to 'select' integer values.

I am currently trying to address it here:  https://github.com/laravel/dusk/issues/134#issuecomment-284976513
