### ISSUE TITLE
Cannot 'select' non-string values

### ISSUE THREAD

**Issue by browner12** [laravel/dusk#134]
I am filling out a form and trying to `select` an element that has an integer value.

```html
<select name="director_id">
    <option value="1">Joe</option>
    <option value="2">Karen</option>
    <option value="3">Bill</option>
</select>
```

I have the following test.

```php
$client = factory(Client::class)->make();

$this->browse(function ($browser) use ($client) {
    $browser->loginAs(User::find(1))
            ->visit('clients/create')
            ->type('name', $client->name)
            ->select('director_id', $client->director_id)
            ->click('#submit');
});
```

`$client->director_id` is returned as an `integer`, and it is failing to select the element.  If I cast to a string, it works.

```php
$client = factory(Client::class)->make();

$this->browse(function ($browser) use ($client) {
    $browser->loginAs(User::find(1))
            ->visit('clients/create')
            ->type('name', $client->name)
            ->select('director_id', (string)$client->director_id)
            ->click('#submit');
});
```

I've found the source of the issue [here](https://github.com/laravel/dusk/blob/master/src/Concerns/InteractsWithElements.php#L186), specifically the strict comparision

```php
if ($option->getAttribute('value') === $value) {
```

It appears that the `$option->getAttribute('value')` always returns a string.

Would it be more correct to do a loose comparison here? 

Or should automatically cast it to a string?

```php
if ($option->getAttribute('value') === (string)$value) {
```

Or should we leave it up to the user to do this? If so, a docs update would probably be in order to note this issue.

Let me know which option looks good, and I can submit a PR.

**Comment by KKSzymanowski** [comment]
Everything is a string in HTML as far as I know, so it's probably best to cast the `$value` to string.

However `RemoteWebElement::getAttribute` can return `null`
```php
/**
 * Get the value of a the given attribute of the element.
 *
 * @param string $attribute_name The name of the attribute.
 * @return string|null The value of the attribute.
 */
public function getAttribute($attribute_name);
```

I think, to approach this properly, you'd need to do check if both values are null and if not, perform a loose comparison:
```php
$attributeValue = $option->getAttribute('value');

if (($attributeValue === null && $value === null) || $attributeValue == $value) {
    //
}
```

**Comment by browner12** [comment]
to keep it shorter why don't we just normalize **both** sides to a string?

```php
if ((string)$option->getAttribute('value') === (string)$value) {
```

This would take care of the pesky `null` value from `getAttribute()`.

**Comment by KKSzymanowski** [comment]
I agree.

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute) `document.getElementById('id').getAttribute('attr')` always returns a string.
As far as I can work out, `RemoteWebElement::getAttribute` returns `null` only when no WebDriver executor is available so I suppose you can safely cast it all to string.

Also, if you cast both values to string, you won't need the strict comparison operator.
