### ISSUE TITLE
Include querystring assertions

### ISSUE THREAD

**Issue by murribu** [laravel/dusk#149]
I would benefit from the presence of $browser->assertHasQueryStringParam() and $browser->assertQueryStringValue().

I attempted to code these functions myself, but ran into trouble in their testing. You can see my attempt [here](https://github.com/murribu/dusk).
I would love some feedback on what I did wrong. It seems that PHPUnit::assertTrue() and PHPUnit::assertEquals() are always returning null in my tests.

**Comment by devinfd** [comment]
I needed such assertions as well. I cleaned up you work and send in a PR: https://github.com/laravel/dusk/pull/151

**Comment by deleugpn** [comment]
Can this be closed?

**Comment by murribu** [comment]
Yep
