### ISSUE TITLE
.env is overridden with .env.dusk if Dusk doesn't stop cleanly

### ISSUE THREAD

**Issue by SebastianS90** [laravel/dusk#153]
See [this comment](https://github.com/laravel/dusk/issues/152#issuecomment-282120330) by @georaldc

- Have a `.env.dusk` file which is different from your `.env` file
- Start `php artisan dusk`
  - Your original `.env` will be backed up to `.env.backup`
  - Your `.env.dusk` file will be copied over the normal `.env` file
- Assume dusk somehow fails, or you simply abort it with `Ctl+C`
  - The backup is **not** restored, leaving your Dusk configuration in `.env`
- Start `php artisan dusk` again
  - It will copy the `.env` file (which contains the Dusk configuration) to `.env.backup`, thus deleting your normal environment configuration

**Comment by bbashy** [comment]
This needs to be fixed. Just had the same issue and I've now got to redo my .env file.

Need to do a check when deleting `.env.backup` to make sure it's the same content as `.env`.

**Comment by SebastianS90** [comment]
Yes, my PR would have been an easy solution, but somehow got closed without a working alternative approach. Try+finally doesn't do the job as I commented in the PR.

So far it is best to backup your `.env` file as `.env.pleaseDuskDontDeleteThisFile` and you can restore it from there when needed  :roll_eyes:

**Comment by bbashy** [comment]
See how this goes on testing #155

**Comment by themsaid** [comment]
@bbashy I think comparing the file content is a good and simple idea.

**Comment by SebastianS90** [comment]
Closed by #155

**Comment by ryancwalsh** [comment]
I still have this problem. (Should I open a new issue? What information would be helpful in figuring out how this problem can still be happening?)

If I <kbd>CTRL</kbd>-<kbd>C</kbd> while `php artisan dusk` is running (using Git Bash, Homestead, on Windows), I'll then see that my `.env` contains the values from `.env.dusk.local`. And then I need to look into `.env.backup` to see what *used* to be in `.env` so I can paste back into `.env` to fix it. I would have expected this to be automatic, but maybe I'm misunderstanding.

**Comment by SebastianS90** [comment]
@ryancwalsh Just run `php artisan dusk` again and let it complete. It will restore the settings by renaming `.env.backup` to `.env`.

This issue was about your `.env.backup` file getting completely lost in the next run of dusk and that was fixed. What you are asking for might be related to #483

**Comment by ipontt** [comment]
I lost my .env. This is still happening on dusk 5.5.0.
