### ISSUE TITLE
Cannot make selections like '#id > .class'

### ISSUE THREAD

**Issue by richartkeil** [laravel/dusk#161]
Because of the `findById()` method in `ElementResolver` it's currently not possible to make selections like `#my-id > .foo-bar`. 
The decision whether an expression is an id selector is based on the '#' at the beginning, not the whole expression.

**HTML**
```
<div id="my-id">
    <input class="foo-bar" type="text" name="multiple[]">
</div>
```
**Test**
```
public function testInput()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/')
                    ->type('#my-id > .foo-bar', 'test');
        });
    }
```
The code above will throw an error because "no element with id `my-id > .foo-bar` could be found".

As a workaround change the `->type(...)` line to `->type(' #my-id > .foo-bar', 'test');`.

**Comment by deleugpn** [comment]
Can this be closed?

**Comment by richartkeil** [comment]
Yeah sure. Sorry, I didn't notice it has been fixed :)
