### ISSUE TITLE
Breaking out of test can lose .env file

### ISSUE THREAD

**Issue by ctschetter** [laravel/dusk#168]
Shouldn't have done it, but I CTRL-C'ed out of a running dusk test, and the cp / mv dusk does to the .env to switch to the .env.dusk.* file did not get undone - leaving me without my original .env file. Didn't realize until my stripe keys failed because they weren't there anymore.

**Comment by deleugpn** [comment]
Your .env will be at the .env.backup file. If you do this twice in a row, then you lost it.

**Comment by SebastianS90** [comment]
This should already be resolved by #155. If you abort Dusk, then you have your `.env` as `.env.backup`. You can manually copy it over `.env` or run Dusk again, it will restore the file once it finishes. The backup should not be lost by running Dusk again, except for the case I outlined in https://github.com/laravel/dusk/pull/155#issuecomment-282330560

**Comment by bbashy** [comment]
Do you have the latest version?

**Comment by ctschetter** [comment]
Indeed resolved by #155. Thanks guys.
