### ISSUE TITLE
Standalone Driver problem 

### ISSUE THREAD

**Issue by aios** [laravel/dusk#173]
Just excuse me for my lousy English

I spent debug problems more than 5 hours, which would have to try to understand what is still happening when running Laravel Dusk

Stack a Laravel starts in the slit, the host machine is Windows 10.
ChromeDriver default set would not run.

The host machine start-up result was
Chrome library not found
The result was a docker
Curl connection refused on host 127.0.0.1 localhost 10.0.75.2 etc. port 9515

I installed Selenium container docker and have another link in DuskTestCase and it worked quickly enough. Solving this problem took 5 minutes. If someone was in the same situation as I no longer want to waste time, the solution is here in what

Set the container
```
docker pull selenium / standalone-chrome:3.0.1-germanium
docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.0.1-germanium
```
or
**docker-compose.yml**
```
  chrome:
    image: selenium/standalone-chrome:3.0.1-germanium
    volumes:
      - ./dev/shm:/dev/shm
    ports:
      - "4444:4444"
```
`docker-compose up`

**DustTestCase**
```php
...
    protected function driver()
    {
        return RemoteWebDriver::create(
            'http://localhost:4444/wd/hub/', DesiredCapabilities::chrome()
        );
    }
...
```
Result is

![image](https://cloud.githubusercontent.com/assets/737550/23591890/a2e031f6-0200-11e7-920c-8dc6713296fb.png)

Thank you for a great product @taylorotwell , but the installation takes too much time if someone do not know the nuances of his work. Hopefully this will save someone some time.

**Comment by lkmadushan** [comment]
You need to set APP_URL to application container service name. Check it.
```
APP_URL=http://app
```

**Comment by adiachenko** [comment]
I'll repost my own guide [from here](https://www.reddit.com/r/laravel/comments/61b5ez/quick_tip_how_to_run_laravel_dusk_inside_docker/).

Hey, guys, it seems like for now Laravel Dusk [provides documentation](https://laravel.com/docs/5.4/dusk) only for Valet and similar host-based setups which is, frankly, a bit underwhelming.

If any of you are using Docker, here is how to cleanly run Laravel Dusk inside a container:

1. Add service based on `selenium/standalone-chrome` image to your docker-compose.yml. Note, that you must use actual virtual hosts in `extra_hots`, localhost won't cut it. Also, pay attention to your network setup: nginx (nginx-proxy), php and selenium services must be visible to each other.

```
    selenium:
        image: selenium/standalone-chrome
        extra_hosts:
            - laravel.dev:${DOCKER_PROXY_HOST}
```

2. In your `.env` file set `DOCKER_PROXY_HOST` to the IP address that points to your site (normally, this will be the value of `$_SERVER['REMOTE_ADDR']`).

3. Set `APP_URL` appropriately (e.g. `laravel.dev` in our case)

4. In `DuskTestCase` comment out `static::startChromeDriver();` and replace `http://localhost:9515` with `http://selenium:4444/wd/hub`.

5. Run `docker-compose exec php php artisan dusk` or whatever else you use to communicate with artisan inside a container. The first execution may be a bit long, try to be patient.

6. Enjoy

**Comment by aios** [comment]
@adiachenko Just is красава.

**Comment by tpraxl** [comment]
Thanks @aios and @adiachenko ! Your guides helped me a lot.

It might be inconvenient to look up the IP (might also change if you deal with multiple projects simultaneously).

So I tried to get rid of this requirement and the following configuration worked very well for me:

Set APP_URL appropriately (with protocol prefix):

```
# laravel .env
APP_URL=http://myapp.dev
```

In DuskTestCase comment out `static::startChromeDriver();` and replace `http://localhost:9515` with `http://selenium:4444/wd/hub`.

Add the following service configuration to docker-compose.yml:

```
selenium:
    image: selenium/standalone-chrome
    links:
      - php:myapp.dev
```

Where `php` is the name of the service in your docker-compose.yml that runs the webserver and myapp.dev is the host defined in APP_URL.

Please note that I make use of jwilder/nginx-proxy in order to provide name resolution for the virtual host, but the general setup might very well work without it as far as I understood the requirements and pitfalls. 

AFAIK, the problem is that selenium can usually not resolve myapp.dev but dusk uses APP_URL. So all you need to do is link to the container. Virtual hosts seem not to be required.

**Comment by adiachenko** [comment]
@tpraxl Wow, I never knew that you can use links in such a way with `jwilder/nginx-proxy`. Saves a lot of trouble. Thx for the tip.

**Comment by tpraxl** [comment]
@adiachenko This should be independent of jwilder/nginx-proxy. I'm just telling selenium that myapp.dev maps to php, which is the apache/php service of my laravel docker-containers. It should work without jwilder/nginx-proxy, because it's all about container internal resolution.

**Comment by adiachenko** [comment]
@tpraxl Aha, now I get it. It doesn't actually pass `Host` header. You're just kinda fooling selenium service into thinking that `myapp.dev` is php service. 

So, you can effectively achieve the same by having `http://php` (in my case, it's `http://nginx`) as your APP_URL without adding alias after colons in `docker-compose.yml`. 

BTW, this trick won't work with actual virtual hosts when, say, you have subdomains in you application and still need to test it with Dusk. I wish there was an automated way to add actual hosts entry to selenium service.
