### ISSUE TITLE
[Question] is OFFLINE workflow not supported?

### ISSUE THREAD

**Issue by gabbydgab** [laravel/dusk#175]
Anyone here tried to run dusk offline (disabled internet connection)?

I got this error when I detached myself from the internet:

`Facebook\WebDriver\Exception\InvalidElementStateException: invalid element state: Element is not currently interactable and may not be manipulated`

Any idea why?

**Comment by browner12** [comment]
does not sound like a connection issue.  sounds like your element may be hidden, or possibly readonly, or maybe disabled.

**Comment by gabbydgab** [comment]
I get it now. Due to CDN endpoint not being available offline. Thanks @browner12.
