### ISSUE TITLE
Dusk won't run in Chrome 57 (now stable)

### ISSUE THREAD

**Issue by bbashy** [laravel/dusk#182]
I've been watching [this](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1625) bug report for 2 weeks since I previously used the beta channel for chrome. I then switched to stable to get around it but now v57 is stable, it's now not working on stable.

I believe it's fixed in canary or beta but not an option for people really.

**This is for if any single test failed (screenshot functionality)**

This is just a note for anyone opening issues in the next few days/weeks until it gets fixed 👍 

```
Facebook\WebDriver\Exception\UnknownServerException: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=57.0.2987.98)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.12.3 x86_64)
```

Bugged: chromedriver=2.27
Pending fix: chromedriver=2.28

**Comment by bbashy** [comment]
@SimZal Yeah that's definitely a solution.

Here's the release notes https://chromedriver.storage.googleapis.com/2.28/notes.txt you can also [download it](https://chromedriver.storage.googleapis.com/index.html?path=2.28/)

**Comment by deleugpn** [comment]
Is this closed, then?

**Comment by bbashy** [comment]
@deleugpn Has Chrome updated their version?

**Comment by deleugpn** [comment]
I don't know, that's what I inferred by your last comment. That's why I'm asking. Should I still keep an eye for chrome version or can I forget about this?

**Comment by bbashy** [comment]
@deleugpn My previous reply was just linking to the release of chromedriver that's working. This isn't released into Chrome [stable] yet. It's still not working unless you download it manually and put it into Dusk bin folder.

Still broken in latest update of Chrome: 57.0.2987.110
```
Facebook\WebDriver\Exception\UnknownServerException: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=57.0.2987.110)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.12.3 x86_64)
```

**Comment by deleugpn** [comment]
I see, so the fix is to upgrade chromedriver-linux that comes with Dusk. Thank you 👍

**Comment by bbashy** [comment]
@deleugpn I think I can submit a PR which updates the chromedriver bin files. Can do that in the meantime!

```
----------ChromeDriver v2.28 (2017-03-09)----------
Supports Chrome v55-57
```

**Comment by MrBoutte101** [comment]
had the same issue. As stated above, just download the new 2.28 driver, after you unzip it you'll move it in to vendor/laravel/dusk/bin/  

but before you do, make sure that you rename it chromedriver-win.exe so that you're replacing the 2.27 driver

![image](https://cloud.githubusercontent.com/assets/15992455/24455636/5acca1f4-145e-11e7-8229-6b277527d3ee.png)

**Comment by bbashy** [comment]
@MrBoutte101 It's because Dusk hasn't been tagged yet with the merge I did.

cc @taylorotwell

**Comment by T3KN0KRAT** [comment]
I'm still running into this. I had Chromedriver 2.7 running, then I read this thread and updated it so that it's running Chromdriver 2.8:
```
┌─[+][~/ts/c/IP/archie]─────[11:50:05]─
└-[dev|+5|…]─ ➤ vendor/laravel/dusk/bin/chromedriver-mac
Starting ChromeDriver 2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9) on port 9515
Only local connections are allowed.
^C

┌─[+][~/ts/c/IP/archie]─────[11:51:45]─
└-[dev|+6|…]─ ➤ vendor/laravel/dusk/bin/chromedriver-mac
Starting ChromeDriver 2.28.455517 (2c6d2707d8ea850c862f04ac066724273981e88f) on port 9515
Only local connections are allowed.
^C
```

I tried both by running `chromedriver-mac` manually, and by letting dusk run it, and I still get:
```
Facebook\WebDriver\Exception\UnknownServerException: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.12.3 x86_64)
```

My `.env.dusk` and `.env.*` files all have the correct `APP_URL`.

Is there anything else that I should try?

**Comment by bbashy** [comment]
You just download the new binary and run dusk like normal :)

**Comment by enderandpeter** [comment]
I just wanted to mention that if you see this error only with certain tests while other Dusk tests in your project run fine, it is probably because there are runtime errors in the problematic tests.
