### ISSUE TITLE
php artisan dusk keep opening http://localhost for testing

### ISSUE THREAD

**Issue by nezaboravi** [laravel/dusk#185]
I have .env and .env.dusk file in my root.
In both i have set APP_URL=http://blog.dev
I am using Valet (installed a week ago), dusk (installed 2 day ago) so all is pretty fresh there.

In DuskTestCase method driver looks like:
`protected function driver()
    {
        return RemoteWebDriver::create(
            'http://localhost:9515', DesiredCapabilities::chrome()
        );
    }`

I tried to change there to http://blog.dev but it opens localhost anyway.

**Comment by deleugpn** [comment]
`localhost:9515` is the connection with the browser and has nothing to do with your application URL.

**Comment by nezaboravi** [comment]
Thanks for the info, as i said, it goes to localhost in any case

**Comment by deleugpn** [comment]
How do you know that?

**Comment by nezaboravi** [comment]
Because i am looking at screen. When i run test, chrome get open and it goes to http://localhost and get 404. Then dusk also creates a log + screenshoot where you can see that it hits localhost:

`{
        "level": "SEVERE",
        "message": "http:\/\/localhost\/ - Failed to load resource: the server responded with a status of 404 (Not Found)",
        "source": "network",
        "timestamp": 1489218285009
    },`

**Comment by devcircus** [comment]
Try changing your .env.dusk fiel to .env.dusk.local per the docs:

> To force Dusk to use its own environment file when running tests, create a  .env.dusk.{environment} file in the root of your project. **For example, if you will be initiating the  dusk command from your local environment, you should create a .env.dusk.local file.**

may do nothing, just thought it may be worth trying if you haven't already.

**Comment by nezaboravi** [comment]
Thanks devcircus, i have that file as well adn APP_URL points to http://blog.dev.

**Comment by nezaboravi** [comment]
UPDATE:
Ok, i just removed dusk, deleted cache, views, restarted computer, and what not...
Then followed install steps, and installed dusk again. 
Laravel version i am on is Laravel Framework 5.4.15
Dusk freshly installed laravel/dusk (v1.0.10).
As per documentation, dusk should copy my original .env file during the test and then revert it back. Anyway, since it did not working, i created .env.dusk.local file
Still keep going to localhost and returning 404. I did not make any changes to original tests.

I swap over to another project i started a couple days ago, and it worked perfectly.
i checked every single dependencies i pulled into composer and no luck. On blog project  still getting localhost. On new project works fine.
So next thing i did is to open two finder windows, and start removing folders in new app replacing them by folders from blog app. Eventually, when i replaced all folders into new app (i wanted to keep all work i did so i copied paste it) php dusk was still working in new project. 
Even when i change APP_URL to point to old project URL, it still works. 
So, i have no idea what happen with blog.dev project and why it kept poining to localhost. 
Anyway i think it is an issue that can be closed now, since i got it working on completely new project.

**Comment by bbashy** [comment]
@nezaboravi I hate when that happens and you can't, for the life of you, work out what was wrong!

**Comment by nezaboravi** [comment]
Yup - i had no idea, its working perfectly ever since.

**Comment by benargo** [comment]
Just a thought, as this happened to me: check `[config\app.php](https://github.com/laravel/laravel/blob/master/config/app.php#L54)` as I had upgraded my app from Laravel 5.1 and I missed [this change](https://github.com/laravel/laravel/commit/278c41887ce73914dc0ee645eb13ae4e5b60f1b0#diff-ea70a5765dbab9fd8032c1d439521db8).

**Comment by pablopaul** [comment]
@benargo Thank you so much, I was missing that update also!

**Comment by ryancwalsh** [comment]
@nezaboravi I wonder if this was the issue: https://github.com/laravel/dusk/issues/96#issuecomment-277936674

**Comment by mirorauhala** [comment]
If anyone is still having issues, try clearing the config cache:
```
php artisan config:cache
```
