### ISSUE TITLE
PHP Fatal error when the test time exceeds 3minutes

### ISSUE THREAD

**Issue by masterwto** [laravel/dusk#188]
I was using selenium and running tests with firefox 43.

when I run the tests separately, every test results OK, when I run a group of tests that total execution time is less than 3 minutes, tests are also successful, However, when I run all tests, I will get some errors like this:

..........EEEEEEEEEEEEEEEE

PHP Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target Illuminate\Contracts\Debug\ExceptionHandler is not instantiable. in....

What's wrong with this? Am I using selenium correctly?

Thanks for reading.

**Comment by bbashy** [comment]
@masterwto Are you loading a custom driver? If I run all my tests (lasting 6 minutes), it completes.

Looks like you have some other error related to code?

**Comment by masterwto** [comment]
I found the resason. Selenium is started and stopped in each test class....

I then modified phpunit.bat, starting selenium before running tests and stopping selenium after all tests are done, and solved the problem.

thanks.
