### ISSUE TITLE
[Feature Request] assertPathIs does not play well with pound symbol

### ISSUE THREAD

**Issue by dominiquedutra** [laravel/dusk#189]
Hey,

Just noticed that the current available assertPathIs does not play well with javascript routing.
Some libraries (flatiron/director) add a # (pound/sharp) to the URL:

http://foo.com/url/#/bar

$browser->assertPathIs() reads this as /url and stops there.

Best regards

**Comment by deleugpn** [comment]
What do you think about this kind of usability?

```
$this->browse(function (Browser $browser) use ($user) {
    $browser->visit('http://laravel-admin.herokuapp.com/#/login')
        ->assertPathIs('/')
        ->assertFragmentIs('/login');
});
```

@taylorotwell is this what you meant on #191 ?

**Comment by dominiquedutra** [comment]
@deleugpn that would be perfect in my opinion.

**Comment by KKSzymanowski** [comment]
@deleugpn I already tried that with #103

**Comment by driesvints** [comment]
Heya. Browser class is macroable so feel free to overwrite or add methods for your use case.
