### ISSUE TITLE
Laravel Dusk ignoring APP_URL possible issue with proxy?

### ISSUE THREAD

**Issue by haakym** [laravel/dusk#198]
<h3>Overview of the problem</h3>
I am trying to get started with Laravel Dusk, however, I cannot get it to run correctly. Based on the output after running it in the console and some google searches and the fact I'd experienced the same issues with a similar package (https://github.com/Modelizer/Laravel-Selenium/issues/15) before Dusk was released I am guessing the issue is down to being behind a proxy at my work-place. I could of course be wrong about it being about the proxy but it's the only thing I have to go on for now. If I'm honest I don't even understand why it needs to know my proxy settings for running tests locally?

<h3>Set up</h3>

- Windows 7 64bit
- Laravel 5.4.15
- Dev env:Laragon
- PHP 7

<h3>Dusk Installation</h3>

I did the following to install dusk:

- `composer require laravel/dusk`
- Set the following in **.env**: `APP_URL=http://ticket.dev`
- Added the following to my `AppServiceProvider` `register()` method:

**app/Providers/AppServiceProviders.php**
```
use Laravel\Dusk\DuskServiceProvider;

//...

public function register()
{
    if ($this->app->environment('local', 'testing')) {
        $this->app->register(DuskServiceProvider::class);
    }
}
```

<h3>Running Dusk</h3>

When I run `php artisan dusk`, I get the following in my console:
```
1) Tests\Browser\ExampleTest::testBasicExample                                           
Facebook\WebDriver\Exception\WebDriverException: JSON decoding of remote response failed.
Error code: 4                                                                            
The response: '<!DOCTYPE html>                                                           
<html>                                                                                   
    <head>                                                                               
        <title>Laragon</title>                                                           
// the rest of the output is what http://localhost produces
```

So it appears to be hitting http://localhost and not my `APP_URL`?

<h3>Attempted solutions</h3>

I found this github wiki page https://github.com/facebook/php-webdriver/wiki/HowTo-Work-with-proxy and after browsing through the vendor folders related to Dusk I tried setting the proxy when the driver is set up in the `driver()` function in the file `tests/DuskTestCase.php`.

I've tried the following, but I get the same console output as mentioned before:
```
protected function driver()
{
    // same as DesiredCapabilities::chrome() except with proxy info
    $capabilities = new DesiredCapabilities([
        WebDriverCapabilityType::BROWSER_NAME => WebDriverBrowserType::CHROME,
        WebDriverCapabilityType::PLATFORM => WebDriverPlatform::ANY,
        WebDriverCapabilityType::PROXY => [
            'proxyType' => 'manual',
            'httpProxy' => 'http://proxy:8080',
            'sslProxy' => 'http://proxy:8080',
        ],
    ]);

    return RemoteWebDriver::create(
        'http://localhost:9515',
        $capabilities,
    );

    // original code after installation
    // return RemoteWebDriver::create('http://localhost:9515', DesiredCapabilities::chrome());
}
```

and ... 
```
protected function driver()
{
    $capabilities = new DesiredCapabilities([
        WebDriverCapabilityType::BROWSER_NAME => WebDriverBrowserType::CHROME,
        WebDriverCapabilityType::PLATFORM => WebDriverPlatform::ANY,
        WebDriverCapabilityType::PROXY => [
            'proxyType' => 'manual',
            'httpProxy' => 'http://proxy:8080', // have also tried without specifying http://
            'sslProxy' => 'http://proxy:8080', // have also tried without specifying http://
        ],
    ]);

    return RemoteWebDriver::create(
        'http://localhost:9515',
        $capabilities,
        null,
        null,
        $http_proxy = 'http://proxy', // have also tried without specifying http://
        $http_proxy_port = '8080',
        null
    );
}
```
Any help on getting this working would be appreciated, thank you!

**Comment by deleugpn** [comment]
I don't think Dusk even requires internet connection. If your web page doesn't load stuffs from CDN, you might even be able to test it without internet. The proxy would only be an issue **IF** your computer is unable to bypass the proxy for local connections (which might be unlikely).

Perhaps your index.blade.php (or similar) is badly configured and Facebook Web Driver doesn't understand it. Try a clean installation and see if you can run. After that you can start debugging your project with the assumption that you know how to get Dusk up and running.

**Comment by haakym** [comment]
@deleugpn Thanks a lot for your reply!

> I don't think Dusk even requires internet connection.

Same here! Unlikely this is the issue I'd imagine.

> If your web page doesn't load stuffs from CDN, you might even be able to test it without internet.

I don't have any external calls to any CDN.

> The proxy would only be an issue IF your computer is unable to bypass the proxy for local connections (which might be unlikely).

Perhaps this could be the issue, how would I know? It is hitting `http://localhost` instead of `http://ticket.dev` would this mean it can bypass the proxy for local connections but somehow is not getting the correct URL?

> Perhaps your index.blade.php (or similar) is badly configured and Facebook Web Driver doesn't understand it. Try a clean installation and see if you can run. After that you can start debugging your project with the assumption that you know how to get Dusk up and running.

I've tried a fresh install and have the same issue.

Just to expand on some points from my original post on this issue:

- I'm using a local development tool name Laragon which is kinda like Laravel Valet for Windows. When I run the `php artisan dusk` it is reading the Laragon splash page accessed at `http://localhost` and not my `APP_URL`, `http://ticket.dev` which I've defined both in `.env` and `.env.dusk.local`. So it appears to me that the test is essentially failing as it's hitting the wrong URL. Please note I have run the test with my Laragon Apache server on and off and it still returns the Laragon splash page.

Here's the full output from the console on a fresh laravel + dusk install...

```
c:\laragon\www\blog
λ php artisan dusk
PHPUnit 5.7.16 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 700 ms, Memory: 8.00MB

There was 1 error:

1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\WebDriverException: JSON decoding of remote response failed.
Error code: 4
The response: '<!DOCTYPE html>
<html>
    <head>
        <title>Laragon</title>

        <link href="https://fonts.googleapis.com/css?family=Karla:400" rel="stylesheet" type="text/css">

        <style>
            html, body {
                height: 100%;
            }

            body {
                margin: 0;
                padding: 0;
                width: 100%;
                display: table;
                font-weight: 100;
                font-family: 'Karla';
            }

            .container {
                text-align: center;
                display: table-cell;
                vertical-align: middle;
            }

            .content {
                text-align: center;
                display: inline-block;
            }

            .title {
                font-size: 96px;
            }

            .opt {
                margin-top: 30px;
            }

            .opt a {
              text-decoration: none;
              font-size: 150%;
            }

            a:hover {
              color: red;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="content">
                <div class="title" title="Laragon">Laragon</div>

                <div class="info"><br />
                      Apache/2.4.23 (Win32) mod_authnz_sspi/0.1.0 OpenSSL/1.0.2h PHP/7.0.10<br />
                      PHP version: 7.0.10   <span><a title="phpinfo()" href="/?q=info">info</a></span><br />
                      Document Root: C:/laragon/www<br />

                </div>
                <div class="opt">
                  <div><a title="Getting Started" href="http://laragon.org/?q=getting-started">Getting Started</a></div>
                </div>
            </div>

        </div>
    </body>
</html>'


C:\laragon\www\blog\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php:293
C:\laragon\www\blog\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php:121
C:\laragon\www\blog\tests\DuskTestCase.php:32
C:\laragon\www\blog\vendor\laravel\dusk\src\TestCase.php:208
C:\laragon\www\blog\vendor\laravel\framework\src\Illuminate\Support\helpers.php:652
C:\laragon\www\blog\vendor\laravel\dusk\src\TestCase.php:209
C:\laragon\www\blog\vendor\laravel\dusk\src\TestCase.php:115
C:\laragon\www\blog\vendor\laravel\dusk\src\TestCase.php:87
C:\laragon\www\blog\tests\Browser\ExampleTest.php:21

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

- The reason I thought it was to do with being behind a proxy is that when I googled "Facebook\WebDriver\Exception\WebDriverException: JSON decoding of remote response failed. Error code: 4" a lot of the links lead to github issues that discuss dealing with selenium and proxy issues.

**Comment by haakym** [comment]
Just a thought, when I create a new project my dev tool Laragon creates a new vhost in apache and also in my windows hosts file at `C:\Windows\System32\drivers\etc\hosts`

For example, when I created the `ticket` project it created the following entry in the hosts file: 
```
127.0.0.1      ticket.dev           #laragon magic!
```

Could dusk be hitting `http://localhost` as I mentioned in my last comment because `http://ticket.dev` is wired up to `127.0.0.1` in the hosts file?

**Comment by deleugpn** [comment]
I wouldn't bet on it. Try to go to `Laravel\Dusk\TestCase.php` in the `propagateScaffoldingToBrowser` method and `dd(Browser::$baseUrl)` right after it gets set. If that's `localhost` then your environment is set incorrectly. If that's `ticket.dev`, then we have a real pickle.

**Comment by haakym** [comment]
Thanks again for your reply.

Sorry to say we have a pickle...

```
    public function propagateScaffoldingToBrowser()
    {
        Browser::$baseUrl = $this->baseUrl();

        dd(Browser::$baseUrl);

        // ...
```

```
c:\laragon\www\ticket (develop)
λ php artisan dusk
PHPUnit 5.7.15 by Sebastian Bergmann and contributors.

"http://ticket.dev"
```

**Comment by deleugpn** [comment]
How do you know the browser is accessing `localhost`?

**Comment by haakym** [comment]
@deleugpn 

I'm using a development tool named [Laragon ](laragon.org) which is similar to valet but for Windows, or you could just think of it as WAMP or XAMPP with extra features.

When Laragon is running and I visit `http://localhost` I can see the Laragon splash page which sits at the Laragon web root: `C:/laragon/www/index.php`. When running `php artisan dusk` the failing test spits out the markup from the page it has hit and the markup is the same as `C:/laragon/www/index.php`. This is why I assumed it was hitting `http://localhost`. The ticket project is located at `C:/laragon/www/ticket`.

I could, of course, be wrong and rather `http://ticket.dev` is just responding with the `index.php` file at the web root for some reason, hence why I was asking about the windows hosts file showing `tickets.dev` linked to 127.0.0.1 earlier.

Hope that all made sense?

**Comment by deleugpn** [comment]
Okay, so if you're running Dusk on Windows and it is pointing to `ticket.dev`, it should open the same result as when you open your browser manually and type `ticket.dev`. Like I said, to further debug this would be a hard task, what I can suggest you is to just use `php artisan serve --env=dusk.local` and have `.env.dusk.local` pointing to `http://127.0.0.1:8000`. Dusk will definitely be able to find the server and run the tests for you.

**Comment by haakym** [comment]
I've set `APP_UL=http://127.0.0.1:8000` in `env.dusk.local` and ran `php artisan serve --env=dusk.local`. Surprisingly that didn't make a difference?!

I am going to make a post in the Laragon forum and I'll post back here if I find any solutions. Thanks a lot for all your support and suggestions @deleugpn

**Comment by deleugpn** [comment]
Go to your Network LAN Configuration and see if it`s allowing to bypass the proxy for local connections:

https://puu.sh/uOkbZ/edc79ee53d.png

**Comment by deleugpn** [comment]
Also check this https://github.com/laravel/dusk/issues/200

**Comment by haakym** [comment]
@deleugpn Thanks for your help, I've tried your suggestions and more but still the same result. I'm giving up on trying to get it to work for now.

**Comment by sullyfischer** [comment]
Did you figure this out eventually? I'm also looking for this and I'd appreciate a working solution.

**Comment by haakym** [comment]
@sullyfischer 

Sorry to say I never worked it out! I did recently try Dusk on a VM running Linux and it worked okay so if you're running Windows you could always try that if you're desperate. I'm pretty sure it was something to do with proxy settings at my work place but for now, it will continue to remain a mystery. Hope you can work it out!

**Comment by sullyfischer** [comment]
@haakym I'm on mac (and later I intend to run it on Linux). Thanks anyways man

**Comment by haakym** [comment]
@sullyfischer Cool. It may be worth opening up your own issue I reckon.

**Comment by kariolos** [comment]
Set the APP_URL to the same URL you are using in the browser for your local development environment. This can be `http://localhost but also a custom URL:`

`APP_URL=http://dusk.local`
For [Laravel ](https://laravel.com/docs/5.4/homestead#configuring-homestead)Homestead you can manage your sites within your `Homestead.yaml ` file.

The `APP_URL` is somehow important as commands from the terminal require this information as pointed out in detail in this answer.

The `port 9515` is the default port number of the Selenium server URL as provided in `DuskTestCase.php`. There's no need to change it at the beginning as it should work out of the box.

By default, the ports are forwarded to your Homestead environment.

**Comment by sullyfischer** [comment]
@haakym I got it working using the extension (like said in the URL).  There's no other way for connecting to proxies using authentication. Lemme know if you needed help with it.

**Comment by martinash78** [comment]
Just leaving this here as I stumbled across this page seeking a solution but this wasn't quite what I needed. In case anyone else is in the same situation, the instructions on  [this page](https://www.jesusamieiro.com/using-laravel-dusk-with-vagrant-homestead/) got Laravel Dusk working for me
