### ISSUE TITLE
chromedriver version update

### ISSUE THREAD

**Issue by acappelgryn** [laravel/dusk#207]
Currently running laravel dusk v1.0.10:
```
MacBook-Pro:default_project test_user$ composer show | grep dusk
laravel/dusk                          v1.0.10 Laravel Dusk provides simple end-to-end testing and browser automation.
```
Noticed these commits from release `v1.0.10` have the comments:
```
@bbashy	         bbashy	      upgrade chromedriver versions  ac89e45
@taylorotwell  taylorotwell  Merge pull request #199 from bbashy/upgrade-chromedriver  351ee59
```

Just not sure which version upgrade that should have been for chromedriver. Version 2.28 was released on Mar 8-9. Checking the version installed with `v1.0.10` shows:
```
MacBook-Pro:default_project test_user$ vendor/laravel/dusk/bin/chromedriver-mac -v
ChromeDriver 2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9)
```
There are some issues `2.27` has with the latest chrome update. I do not know if that is in the works for the next release, but `2.28` help solve those issues the latest stable chrome version has with `2.27`.

**Comment by deleugpn** [comment]
Try to use the master branch for now (dev-master) until @taylorotwell tags a new version release.

**Comment by acappelgryn** [comment]
Thanks @deleugpn I already went ahead and did that. Just wanted to post this one there in case someone else has the same issue.

**Comment by deleugpn** [comment]
This has been dealt with on #199

**Comment by acappelgryn** [comment]
Alright thanks.
