### ISSUE TITLE
Command "dusk" is not defined. Larave 5.4 vagrant Homestead. 

### ISSUE THREAD

**Issue by KevinLeht** [laravel/dusk#211]
Hei,

Yesterday I was following Adam Wathan test driven laravel lesson and relised that it's kinda out of date if you use latest laravel. 
So I found that Dusk is the new way to test but can't it to work and losing my mind already.

Steps I have made:

vagrant update

composer require laravel/dusk
composer update
Update AppServiceProvider register method
php artisan dusk:install => gives error that no "dusk" command defined
Tried googling but nobody had problem with dusk install step..

Using vagrant homestead on Ubuntu 16.04

**Comment by deleugpn** [comment]
Share your AppServiceProvider.

**Comment by KevinLeht** [comment]
Sorry for wasting internet space. Just had to rename .env.example to .env.
Apologies.
Can be closed fast.

**Comment by deleugpn** [comment]
No problem (L)

**Comment by browner12** [comment]
@KevinLeht FYI as the original author of the issue, you can close it as well.  does not need to be a project maintainer.

**Comment by ryancwalsh** [comment]
Dusk was just working an hour ago, after having woken my computer but prior to doing my usual `homestead.bat reload --provision` of the morning. (I'm on a Windows 10 machine with a Laravel Homestead Vagrant VirtualBox.) Then I did a reload of Homestead, and now Dusk isn't working. I get: 

 
```
php artisan dusk tests/Browser/MailcheckTest.php
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "dusk" is not defined.
```


So I tried deleting the `vendor\laravel\dusk` folder and running `composer require --dev laravel/dusk` again, and that gave me a fresh copy of all of those files. My `AppServiceProvider` still looked good, according to the [installation docs](https://laravel.com/docs/5.4/dusk#installation).

Then I tried running `php artisan dusk:install` but get:

```
 [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "dusk" namespace.
```

I am driving myself **crazy** trying to figure out why Dusk suddenly stopped working and how to fix it. I'd love help if anyone has a suggestion. Thanks.

**Comment by ryancwalsh** [comment]
My problem was that `.env.dusk.local` said `APP_ENV=dusklocal` and `.env.dusk.testing` said `APP_ENV=dusktesting` (which are both invalid), and the reason Dusk *had* been working until *recently* is because those `.env.dusk` files *earlier* had had  `APP_ENV=local` and `APP_ENV=testing`, and Artisan must have cached those values. So then my reload of Homestead must have cleared the cache, and then Dusk wasn't working til I fixed the `APP_ENV` values in my `.env.dusk` files and cleared the cache again.  Wow. Wasted several hours of my life. Hope this helps someone.

**Comment by t202wes** [comment]
By default the `AppServiceProvider` only allows dusk commands to be run on `local` and `testing` environments.  Our problem was that we were trying to call `php artisan dusk`, but we were on an unsupported laravel environment for dusk. Once we changed the environment back to `testing`, we were able to call dusk again. 

```
        if ($this->app->environment('local', 'testing')) {
            $this->app->register(DuskServiceProvider::class);
            $this->commands(DuskCommand::class);
        }
````
