### ISSUE TITLE
How to handle browser popups?

### ISSUE THREAD

**Issue by vinayakkulkarni** [laravel/dusk#224]
So, I've been using dusk for few weeks, everything works perfectly but I am stuck at `auth.basic.once` middleware where I need to fetch data via API and it requires the credentials to be entered. Is there a way to fill those via tests or is there any other alternative?

<img width="388" alt="screen shot 2017-04-18 at 1 52 52 pm" src="https://cloud.githubusercontent.com/assets/19776877/25121214/99acba7c-243e-11e7-897e-a613569a3f20.png">

**Comment by deleugpn** [comment]
If you found a solution, consider providing it for future reference.

I was about to suggest the URL approach (http://user:password@127.0.0.1:8000/route).

**Comment by vinayakkulkarni** [comment]
Yes, replaced `auth.basic.once` from my api `auth`

Added 
```php
\App\Http\Middleware\EncryptCookies::class,
\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
\Illuminate\Session\Middleware\StartSession::class,
```
to my `\App\Http\Kernel.php` in middlewareGroups for api.

**Comment by markdwhite** [comment]
For the record if you do want to keep basic auth in place, change your APP_URL in .env.dusk.local (as appropriate), then use relative paths in in calls to $browser->visit(). Eg:

`APP_URL=http://user:password@localhost`

`$browser->visit('/')...`
