### ISSUE TITLE
Dusk fails with message on browser window: "unknown command: "

### ISSUE THREAD

**Issue by ferdinandfrank** [laravel/dusk#241]
When I try running a _DuskTestCase_ a Chrome browser window pops up, but instead of executing the test it only displays a blank page with the text "unknown command: [page title]". The [page title] is the name of the page the test tries to view. So for this test case:
```php
public function testBasicExample()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/register')
                    ->assertSee('Laravel');
        });
    }
```
I get a browser window with this screen:
![failure-testbasicexample-0](https://cloud.githubusercontent.com/assets/19409640/25280956/005645d0-26ac-11e7-941c-92ac49670884.png)

In the console there's also this error message, which makes sense, as the correct page couldn't be viewed:
```console
1) Tests\Browser\ExampleTest::testBasicExample
Did not see expected text [Laravel] within element [body].
Failed asserting that false is true.
```

My installed version of phpunit is 6.1.0 and the version of Laravel Dusk is v1.0.12.

Does anyone has a solution for this?

**Comment by deleugpn** [comment]
I don't think 1.0.12 is compatible with PHPUnit 6.1.0. Try again with `dev-master` branch.

**Comment by ferdinandfrank** [comment]
Thanks for your response, but I've just tried different versions of Dusk and PHPUnit (even 5.x) and I'm still getting this error :/

**Comment by deleugpn** [comment]
Can you check your `APP_URL` environment settings during the tests?

**Comment by ferdinandfrank** [comment]
Yes, I created a file named `.env.dusk.local` with the following content:
```text
APP_NAME="Example"
APP_ENV=local
APP_KEY=base64:sNRZxiHAk6hd+xeD9jfCML4o+vrAr35dHo+kzAcOO24=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_TIMEZONE=Europe/Berlin
APP_LOCALE=de
APP_URL="http://localhost:9515"
```
So the `APP_URL` is the same as specified in the class `DuskTestCase`:
```php
    protected function driver() {
        return RemoteWebDriver::create(
            'http://localhost:9515', DesiredCapabilities::chrome()
        );
    }
```

I've also tried writing the `APP_URL` without quotes but it doesn't work either,

**Comment by deleugpn** [comment]
That is exactly your problem. `localhost:9515` is not the address of the application, but the chromedriver server. Your APP_URL should point to a valid web address for your application. If you use `artisan serve` for your tests, it should be `http://127.0.0.1:8000`, if you use Apache or Nginx, it should be the address for that.

**Comment by ferdinandfrank** [comment]
Ohhh now I got this! Thank you very much! :)
