### ISSUE TITLE
#command not found exception

### ISSUE THREAD

**Issue by mesuntos** [laravel/dusk#245]
when i want to call my console from my route for running the test i get the error of command not found ....
while other command for artisan works fine ... the thing i wanted to do was to run all my test from url typing test,  Is it possible to do this or not I defined my route as 

Route::get('/test', function()
{
    Artisan::call('dusk');
    
});

**Comment by deleugpn** [comment]
Dusk is only registered when running on console directly. [Source](https://github.com/laravel/dusk/blob/master/src/DuskServiceProvider.php#L46). You can override the `register` method to remove this restriction and then you might also need to override the `DuskCommand` to remove the `PHP_BINARY` from the binary array in case Symphony cannot resolve the path. [Source](https://github.com/laravel/dusk/blob/master/src/Console/DuskCommand.php#L85).

**Comment by mesuntos** [comment]
@deleugpn  when i override the register method to remot this restriction i get a new error 
http://imgur.com/D84nudr

**Comment by deleugpn** [comment]
@mesuntos do a `$_SERVER['argv'] = []` right before you call `Artisan` from your controller/callback, but leave this issue open because I want to try a PR for this.

**Comment by mesuntos** [comment]
yes i did 
Route::get('/test', function()
{
    $_SERVER['argv'] = [];
    Artisan::call('dusk');

});
but when doing it my dusk doesnot run i get a blank screen 
http://imgur.com/a/0ijyT

**Comment by bkkrishna** [comment]
Thanks to @deleugpn's insights and this [discussion](https://laracasts.com/discuss/channels/testing/invoking-the-artisan-dusk-command-outside-the-cli?page=2), I was able to achieve this. But I guess this should be supported by Laravel by default, I guess.

Anyways, thanks guys!
