### ISSUE TITLE
[Feature Request] Implement scrollTo

### ISSUE THREAD

**Issue by pablopaul** [laravel/dusk#252]
I need `scrollTo` an element all the time, could we have this in Dusk?

Codeception implements it here https://github.com/Codeception/Codeception/blob/5e056c7df7843bda91f5857dc30cbc8e18aedcbf/src/Codeception/Module/WebDriver.php#L2813

**Comment by deleugpn** [comment]
Could you post a legit use-case where this is actually needed?

**Comment by pablopaul** [comment]
@deleugpn Sure, the use case:

I want to click an element which is not in the current viewport.

**Comment by deleugpn** [comment]
Have you tried just clicking it through the selector? It will auto scroll.

**Comment by pablopaul** [comment]
@deleugpn I will check it, thanks for the reply.

Does waitFor() also work for Elements which are not currently in the viewport?

**Comment by deleugpn** [comment]
AFAIK, if the element if visible (not in the sense of viewport, but in the sense of not being `display: hidden`), waitFor won't wait, it will just see the element and return in the first attempt.

**Comment by pablopaul** [comment]
@deleugpn thanks again, for my current use case I do not need a `scrollTo()` since `click()` scrolls to the element as @deleugpn pointed out.
