### ISSUE TITLE
Does Dusk work with Select2?

### ISSUE THREAD

**Issue by eduardocruz** [laravel/dusk#253]
I have a project which uses Select2 https://select2.github.io/

And it seems, that Dusk does not have suppot for it.
On the other hand, if you google Select2 and dusk, the first link is the one below, which only has one follower. I also didn't find any discussions where people complained about Dusk didn't work with Select2.

https://github.com/roquie/laravel-dusk-select2

That, said, I feel like, either people does not have this problem, or there is another workaround out there, which I didn't find.

**Comment by browner12** [comment]
select2 has worked okay for me with Dusk.

try making a simple page with only a select2 dropdown, and see if you can get that to work.

**Comment by rohithmeethal** [comment]
Select 2 has programmatic access as explained here [Select 2 programmatic access documentation](https://select2.github.io/examples.html#programmatic).

My current approach to select2 fields is like this:

```javascript
// view
<script>
        var permissions_select2 = null;
        $(function(){
            permissions_select2 = $("#permissions").select2();
        });
</script>
```
```php
// test
$browser->script('permissions_select2.val(["1","2","3","4","5"]).trigger("change");');
```
> Not that you can't chain `$browser->script()` function with others, since it returns an array.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by tjhunkin** [comment]
> select2 has worked okay for me with Dusk.
> 
> try making a simple page with only a select2 dropdown, and see if you can get that to work.

Do you have an example of how you selected a value using a select2, please?
