### ISSUE TITLE
Proposal: "waitForReload" method

### ISSUE THREAD

**Issue by calebporzio** [laravel/dusk#255]
In my javascipt I often complete an ajax action by just reloading the page:
```
axios.get(...).then(() => {
    window.location.reload();
});
```
Assuming nothing changes on the page (eliminating the use of `waitFor`), what is the best way to wait for a page reload.

For now, I have created a `waitForReload` macro:
```
->click()
->waitForReload()
->assertSee()
```
It's implementation is here: https://gist.github.com/calebporzio/eb5cae2064a96e4fbf8f2ecf01626305

Let me know if this is something worth pull requesting. I could see this implementation being to "janky" to exist in Dusk so maybe we can brainstorm a better alternative.

Thanks for the hard work on this great tool guys!

**Comment by erikwestlund** [comment]
I like this idea -- and your method works for me.  It's superior to a pause.

**Comment by calebporzio** [comment]
@erikwestlund - this was pulled in #261
