### ISSUE TITLE
Laravel dusk error on js submit failed to load resource: err_file_not_found

### ISSUE THREAD

**Issue by plateena** [laravel/dusk#257]
I have an error on

`php artisan dusk`

error on cosole said

`Failed to load resouces: net::ERR_FILE_NOT_FOUND`

Manually run the test on browser the no such error found. The routes is correct and tested. The js is working.

I use http://malsup.com/jquery/form/ for form submission.

google-chrome version 58.0.3029
php 7.0.15-1ubuntu4
ubuntu 17.04
apache2 2.4.25

**Comment by deleugpn** [comment]
Looks like Dusk is trying to access `{APP_URL}/your_file.js` and cannot find it. The symptoms describe a potential environment problem. 

- Which `APP_URL` you have set for Dusk?
- Do you have the same environment between Dusk and direct access?

**Comment by plateena** [comment]
Sorry my bad.
After rewrite the code, it seem that the file $browser->attach() i'm using not have permission to read the file. 
It seem okay when the file name is displayed in the form while the file itself doesn't have the right permission or even file not exist.

**Comment by ihsanberahim** [comment]
Hi guys,

i faced the same issue.

```
$browser->attach('#profile_photo__file_input', storage_path($fakeUserProfile->photo))
```

I saw ***it attached*** but ERR_FILE_NOT_FOUND comes out in the submission process.
