### ISSUE TITLE
Existing text sometimes is not found by assertSeeIn()

### ISSUE THREAD

**Issue by antonioribeiro** [laravel/dusk#262]
Well, I was getting those impossible 'could not see' errors, and after some debugging I could not really understand what is the matter, so I changed `assertSeeIn()` to be:

```
    public function assertSeeIn($selector, $text)
    {
        $fullSelector = $this->resolver->format($selector);

        $element = $this->resolver->findOrFail($selector);

        if (! Str::contains($element->getText(), $text) && strpos($element->getText(), $text) !== false) {
            throw new \Exception('Yeah, you can call me crazy, but I sense a problem somewhere in here...');
        }

        PHPUnit::assertTrue(
            Str::contains($element->getText(), $text),
            "Did not see expected text [{$text}] within element [{$fullSelector}]."
        );

        return $this;
    }
```

And I'm getting these, intermittently:

![image](https://cloud.githubusercontent.com/assets/3182864/25766779/fa0aa7a0-31ca-11e7-8084-4c930cd865a4.png)

I have made some tests with Str::contains(), the problem does not look like inside it

**Comment by antonioribeiro** [comment]
I did this in my Browser class, and it did not happen again:

    /**
     * Assert that the given text appears within the given selector.
     *
     * @param  string  $selector
     * @param  string  $text
     * @return $this
     */
    public function assertSeeIn($selector, $text)
    {
        if (strpos($this->resolver->findOrFail($selector)->getText(), $text) !== false) {
            return $this;
        }

        return parent::assertSeeIn($selector, $text);
    }

**Comment by icamys** [comment]
Got the same issue. Dusk version v3.0.7

**Comment by staudenmeir** [comment]
Does the same test always fail?

Since `Str::contains()` uses `mb_strpos()`: Does the workaround also work with `mb_strpos()`?

**Comment by drbyte** [comment]
In one case of intermittent test failures like this I discovered that the test data had been generated with apostrophes, and blade was (appropriately) outputting them as html equivalents, so there wasn't an exact match for the assertions to find.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by juliobitencourt** [comment]
> In one case of intermittent test failures like this I discovered that the test data had been generated with apostrophes, and blade was (appropriately) outputting them as html equivalents, so there wasn't an exact match for the assertions to find.

It saved me from loosing all my hair
