### ISSUE TITLE
Dusk form submit hangs and doesn't assert 

### ISSUE THREAD

**Issue by akash-dangal** [laravel/dusk#265]
I am on Window 8.1 system..
I have following code:
```
//Add superadmin user through factory
        $user = factory(\App\User::class)->create(
            [
                'permission' => 1,
                'password' => bcrypt('secret'),
            ]
        );
        $imageFile = rand(1, 10) . '.jpg';
        $testImgPath = public_path('test_resources/test_pics/');
        $image = $testImgPath . $imageFile;
        //login witht the user and test user add
        $this->browse(function (Browser $browser) use ($user, $image) {
            $browser->loginAs($user)
                    ->visit(route('user-add'))
                    ->type('name', 'Test Name')
                    ->type('email', 'testuser@orguser.com')
                    ->select('country_id', 58)
                    ->select('language_id', 1)
                    ->attach('image', $image)
                    ->type('phone', '602323232323')
                    ->press('Submit')
                    ->pause(1000)
                    ->assertSee('User added successfully');
        });
```
The `user-add` page opens and  `->type` , `->select` and `->attach` all working fine..
press('Submit') also works , after Submitted, the page should post data to `user-add-post`.
The `user-add-post`, shows in the url, but no data is posted and added to database and the page is never redirected to the `user-listing` page which has successful message `User added successfully` .
It didn't work how much I tried and badly stuck here.
 I thought it may be due to middleware, csrf , the localization plugins [https://github.com/mcamara/laravel-localization] and disabled all of them and tested still no luck..
Does it is due to Window 8.1 ?? or Session or what else ??
What do I missed here, any help urgently would be hearty appreciated..
Thanks in Advance

**Comment by akash-dangal** [comment]
Console 
```
       "level": "SEVERE",
        "message": "http:\/\/app.project.local\/en-US\/admin\/user-submit - Failed to load resource: the server responded with a status of 400 (Bad Request)",
        "source": "network",
        "timestamp": 1494474648256
```
and the screenshots shows blank image ..
the link `http://app.project.local/en-US/admin/user-submit` shows bad url with dusk, however is working fine while manually accessing through browser..

**Comment by deleugpn** [comment]
Does `app.project.local` points to `127.0.0.1` or are you using VirtualHost and Virtual Machine (Homestead, Vagrant, VirtualBox, etc)?

**Comment by akash-dangal** [comment]
app.project.local is a virtual host that points to 127.0.0.1 , I am not using Virtual Machine..

**Comment by deleugpn** [comment]
Check `laravel.log` and Apache `error_log` for extra information on why the Request became a 400.

**Comment by akash-dangal** [comment]
Nothing in the laravel.log and Apache error_log, however Apache access log shows following:
```
127.0.0.1 - - [11/May/2017:14:16:48 +0545] "POST /en-US/admin/user-listing HTTP/1.1" 400 - "http://app.project.local/en-US/admin/user-add" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36"

```

**Comment by akash-dangal** [comment]
Anything you can suggest..? does it may be due to OS..? is Dusk working fine Windows

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
