### ISSUE TITLE
ChromeDriver doesn't start in cygwin

### ISSUE THREAD

**Issue by jk3us** [laravel/dusk#267]
When I run dusk in cygwin, the chromedriver doesn't start automatically, and I have to start it manually.  But I found that adding a test for `CYGWIN` in [`SupportsChrome::driverSuffix()`](https://github.com/laravel/dusk/blob/a0de2692ef4e5ec6aff4ccfcdec3519b11d28f5e/src/SupportsChrome.php#L102-L117) makes it work as expected:

    protected static function driverSuffix()
    {
        switch (PHP_OS) {
            case 'Darwin':
                return 'mac';
            case 'WINNT':
            case 'CYGWIN':         # Add this line
                return 'win.exe';
            default:
                return 'linux';
        }
    }

The `chromeEnvironment()` function also references `PHP_OS`, and may need to be changed as well, but the one line above makes it work for me.

**Comment by deleugpn** [comment]
Could you `dd(PHP_OS)`?

**Comment by jk3us** [comment]
`string (6) "CYGWIN"`

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
