### ISSUE TITLE
Travis CI: Why is "sudo: required" necessary?

### ISSUE THREAD

**Issue by pablopaul** [laravel/dusk#273]
Why is "sudo: required" necessary in `.travis.yml` to run on Travis CI?

**Comment by alexbowers** [comment]
Perhaps because it needs to install Chrome?

**Comment by pablopaul** [comment]
@alexbowers I do not think so, this is the example `.travis.yml` from the docs, no Chrome installation in there:

```
sudo: required
dist: trusty

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - ./vendor/laravel/dusk/bin/chromedriver-linux &
    - cp .env.testing .env
    - php artisan serve > /dev/null 2>&1 &

script:
    - php artisan dusk
```

**Comment by alexbowers** [comment]
Good point. Hmm. @themsaid

**Comment by derpartment** [comment]
[https://docs.travis-ci.com/user/reference/trusty/](url)
