### ISSUE TITLE
[Feature Request] Elements with own methods

### ISSUE THREAD

**Issue by novitskiy-aleksei** [laravel/dusk#278]
Sometimes, single element (eg some menu or custom date time selector) present on various pages and it would be nice to use its own methods to manipulate with it. At this time we can only define methods in pages:
```php
$browser->visit(new Calendar)
        ->startTime('now')
```
But what if we whould have element-relate methods and use them on different pages, something like this:

```php
$browser->visit(new Calendar)
    ->pageElement((new DateTimePicker())->start('now'))

$browser->visit(new Dashboard)
    ->pageElement((new DateTimePicker())->start('now'))
```

What you think about that? If this needed by anyone except me, I can make PR to show how I see this.

**Comment by driesvints** [comment]
Thanks for your suggestion but since this has been open so long and nobody else responded to this I'm going to close this.
