### ISSUE TITLE
How to click specific icon link (not text link ) on the table laravel dusk

### ISSUE THREAD

**Issue by batmahir** [laravel/dusk#280]
1.  This is for clicking normal text link stated at the documentation: $browser->clickLink($linkText); , this is applicable to situation like `<a href='/somewhere'>Create Somewhere</a>`
2.  But what i want is i want to click the icon link (not text link) for example 

```
 <a href="/somewhere " class="btn btn-primary btn-user-edit" title="Edit" data-id="3">
                 <i class="fa fa-edit"></i>
   </a>
```
 And based on the above , that icon link is in the table so it have more that one ,ex: 
<img width="720" alt="user list table v2" src="https://cloud.githubusercontent.com/assets/20837786/26292489/fab0a3dc-3ee8-11e7-822c-2f998efd6488.png">

How do i do this with laravel dusk?

**Comment by deleugpn** [comment]
You can resolve the element using `$browser->element('your-selector-here').click();`, but beware that this will break the chain. Instead of

```
$browser->visit('/')
          ->clickLink('blah')
          ->assert('bla')
          ->click('blah');
```

You'll have to 

```
$browser->visit('blah')->element('selector').click();
$browser->click('blah);
```

**Comment by bathulah** [comment]
@deleugpn  what's the difference between 
`$browser->element('selector').click();`
and 
`$browser->click('blah);`

both of them are click , can you tell me what's the difference ? i wanna know

**Comment by bathulah** [comment]
@deleugpn i already tried your code :  
`$browser->visit('/somewhere')->element("data-id='2'").click();//this throw an error of  Call to undefined function click()`

and also already tried with : 

`$browser->visit('/somewhere')->element("data-id='2'").click();//this throw an errorof  Call to a member function click() on null`

**Comment by janaka120** [comment]
@bathulah 
Did you find a way do this?

**Comment by janaka120** [comment]
I found a way to do this. I use a table to show the data.

**Edit icon code**
```
 <a id="button-id" href="/somewhere " class="btn btn-primary btn-user-edit" title="Edit">
                 <i class="fa fa-edit"></i>
 </a>
```
**testing code**
```
$browser->with('#table-id', function ($table) {
                $table->assertSee('row-text')
                    ->click('#button-id');
 });
```

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by davyjiang** [comment]
->click('a[class="btn btn-primary"]');
