### ISSUE TITLE
how to get the value/text of the checkbox laravel dusk

### ISSUE THREAD

**Issue by batmahir** [laravel/dusk#281]
Okay here the ticked values that i want to get using laravel dusk , how do i do get this checkbox values/text?
![image](https://cloud.githubusercontent.com/assets/20837786/26307820/1ddc1dce-3f29-11e7-804a-cfc5d912ff51.png)

I already using

` $browser->value('selector');//this one worked on the normal input field like text and select`

when i used the same method and apply on the checkbox , it's not return me the value/text of the checkbox , but it return me "on" when i dd() that result.

Below are the current code that i apply for the checkbox with id='role'

 ```
$role = $browser->value('#role');
            dd($role); // the output on the console is "on"
```

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
