### ISSUE TITLE
Scoping on page give a wrong selector and make page's assertions based on selector fail

### ISSUE THREAD

**Issue by mikaelpopowicz** [laravel/dusk#283]
Maybe `Browser::with()` should not call `Browser::on()`

```php
public function with($selector, Closure $callback)
{
    ...
    if ($this->page) {
        $browser->on($this->page);
    }
    ...
}
```

Let's define a page assert function :
```php
public function assert(Browser $browser)
{
    $browser->assertSeeIn('div.some_class', 'something');
}
```

Now test our page :
```php
public function testMyPage()
{
    $this->browse(Browser $browser, function ($browser) {
        $browser->visit(new MyPage()) // this will call assert on page
            ->with('.foo', function($element) { // set resolver prefix to : body .foo and call assert on page
                $element->assertSeeLink('bar');
            });
    });
}
```

When `with` is called, the element resolver prefix is set to `body .foo` and call again `Page::assert()`. Assertions based on selector will fail because of the new prefix.
Here `$browser->assertSeeIn('div.some_class', 'something');` will fail because the selector is now `body .foo div.some_class` instead of `body div.some_class`

**Comment by wideivan** [comment]
If I use Scoping Selector in assert method of Page class, then I got max memory limit because 
```
if ($this->page) {
        $browser->on($this->page);
    }
```

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
