### ISSUE TITLE
Default resolution

### ISSUE THREAD

**Issue by xakzona** [laravel/dusk#294]
How to set default resolution?
Now I make like this
````
$this->browse(function (Browser $browser){
            $browser->resize(1440, 900); 
}
````
But better if I can setup this once. Thank you

**Comment by xakzona** [comment]
May be I have found a solution:
`
protected function driver()
    {
        $options = new ChromeOptions();
        $options->addArguments([
            '--window-size=1440,900',
            '--disable-web-security'
        ]);
        return RemoteWebDriver::create(
            env('SELENIUM_HUB', 'http://localhost:4444/wd/hub'),
            DesiredCapabilities::chrome()->setCapability(ChromeOptions::CAPABILITY, $options)
        );
    }
`

**Comment by Lopez-i** [comment]
Hi this is possible using phantomjs ?

**Comment by xakzona** [comment]
Good news, I have found better multi-browser method:
`protected function driver()
    {
        $driver = RemoteWebDriver::create(
            env('SELENIUM_HUB', 'http://localhost:4444/wd/hub'),
            DesiredCapabilities::chrome()
        );
        $size = new WebDriverDimension(1440,900);
        $driver->manage()->window()->setSize($size);
        return $driver;
    }`

**Comment by Lopez-i** [comment]
@xakzona thanks a lot

**Comment by jontroncoso** [comment]
if you don't want to go digging, be sure to add 
```
use Facebook\WebDriver\WebDriverDimension;
```
