### ISSUE TITLE
Some wait operations are crashing silently

### ISSUE THREAD

**Issue by NoelDeMartin** [laravel/dusk#298]
Whenever a script is called on the browser to wait for a condition, exceptions resulting from the script are silenced, as can be found on  [Concerns/WaitsForElements.php:167](https://github.com/laravel/dusk/blob/1.0/src/Concerns/WaitsForElements.php#L167):

    try {
        if ($callback()) {
            break;
        }
    } catch (Exception $e) {
        //
    }

I think this should be logged somewhere, maybe on the console logs. I was trying to figure out why a condition was not completed in one of my tests, when at the end it resulted in a typo on a variable name. The browser was throwing an `Uncaught ReferenceError`, but since the exception is silenced I thought my condition was executed correctly and returning false.

I can understand why this approach was taken, since the script is executed multiple times while waiting for the condition to succeed, it may saturate the logs. But I think there should be a way to handle this. One solution could be to log the last exception that occurred once the wait is over. That would not saturate the logs and it would give some insights on what is failing after the wait.

**Comment by deleugpn** [comment]
Dusk have no power over the browser exception. That `catch` statement, on the PHP side, is incapable of catching exceptions throw in JavaScript (visible in the browser).

**Comment by NoelDeMartin** [comment]
@deleugpn That is not true, before opening this issue I played a bit with that, and the exception that is being silenced there returns the following message: `unknown error: foobar is not defined`. Where *foobar* is the name of the javascript variable I was typing incorrectly, so the information to what happened on the script failing is definetly there.

**Comment by driesvints** [comment]
You now have a console directory where you should be able to find these errors. Can you check there?
