### ISSUE TITLE
[Feature Request] Always catch and report Whoops

### ISSUE THREAD

**Issue by ninthspace** [laravel/dusk#301]
Is it possible for Dusk to catch and report Whoops errors?

At present one has to visually inspect the browser window and try and ascertain the error before it's replaced with the next test.

This would be even more useful as and when Dusk has built-in headless support.

**Comment by thepenguin1** [comment]
I second this.

**Comment by driesvints** [comment]
Do the errors not appear in your `laravel.log` file?
