### ISSUE TITLE
Use of [attribute~=value] Selector

### ISSUE THREAD

**Issue by MickaelTH** [laravel/dusk#303]
Hi,

Is it possible to use dusk to click or find element like a link or image that contains a given name/id?

In short, can we use CSS [attribute~=value] Selector
https://www.w3schools.com/cssref/sel_attribute_value_contains.asp

Thanks

**Comment by shadoWalker89** [comment]
You could use the $browser->script() to execute some javascript (in your case using jquery) and return the value

```php
$inputValue = $browser->script("return $('input[attribute~=value]').val()");
```

**Comment by MickaelTH** [comment]
Hi @shadoWalker89 

Thank you for having taking time to comment.

Your idea is quite good as the $browser->script wasn't referred in the Laravel Dusk page. Thank you for that.

I was able to edit to make it search for the full ID name containing a word (very useful for me as the ID are dynamic).

So here is what I did:
`$test = $browser->script("return $('a[id*=\"xxxxxx\"]').attr('id')");
$browser->click('#'.$test[0])`

Not sure if this is the perfect way to do it without impacting performance.
