### ISSUE TITLE
[question] How are you dealing with radios and labels?

### ISSUE THREAD

**Issue by antonioribeiro** [laravel/dusk#305]
According to [twitter bootstrap](http://getbootstrap.com/css/#forms), this is how we do a radio:

```
<div class="radio">
  <label>
    <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
    Option one is this and that&mdash;be sure to include why it's great
  </label>
</div>
```
With the input inside the label tag. But the problem is that Dusk (actually Facebook Webdriver) is not able to find it this way. It keeps raising:

    Facebook\WebDriver\Exception\ElementNotVisibleException: element not visible

To make it work I have put the input outside the label, but then, of course, the boostrap radio does not show as it should anymore.

```
<div class="radio">
  <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
  <label>
    Option one is this and that&mdash;be sure to include why it's great
  </label>
</div>
```

So, how are you doing this?

**Comment by zoispag** [comment]
Have u tried `$browser->radio('input[name=optionsRadios]:checked'), 'option1');` ?

**Comment by antonioribeiro** [comment]
Nope. Not even setting an ID to the input:

```
<input 
   type="radio" 
   name="sitesActive" 
   id="sitesActive3" 
   value="2"
>
```

And using it this way:

    ->radio('#sitesActive3', '2')

The problem is that Dusk (Webdriver) cannot even see the element in the page, as this simple like fails the exact same way:

    $browser->waitFor('#sitesActive3');

Resulting in:

    Facebook\WebDriver\Exception\TimeOutException: Waited 5 seconds for selector [#sitesActive3].

And that happens every time I have a form with an input with a label surrounding it, if I take the input out of the label, it works. But that's not as simple with radios, as it was with some other inputs, radios.

This is a properly coded radio:

![image](https://user-images.githubusercontent.com/3182864/27808759-8d064586-6020-11e7-9565-46f5d7b575c0.png)

This is a radio with the input outside the label tag:

![image](https://user-images.githubusercontent.com/3182864/27808749-6f21b730-6020-11e7-8d6d-7b403f6c3629.png)

**Comment by antonioribeiro** [comment]
Also posted in Facebook Webdriver's repo: https://github.com/facebook/php-webdriver/issues/451

**Comment by antonioribeiro** [comment]
Since boostrap move actual radios to out of visible area, the best way is to click the <i> element it adds to the document:

```php
$browser->click('#elementId + i')
```

**Comment by chilio** [comment]
@antonioribeiro thanks for the hint, which guided me to solution in my case.
I actually need to use 
`$browser->click('#elementId + ins')`
I believe this is specific to different bootstrap versions.
Worth noting is that this solution is only a workaround for using radio() and check() methods, and modifying views for the sake of testing doesn't seem right. Hopefully it will work in next dusk versions.
