### ISSUE TITLE
Laravel\Dusk\Concerns\InteractsWithAuthentication::currentUserInfo() return null?

### ISSUE THREAD

**Issue by feryardiant** [laravel/dusk#307]
Here my test

```php
$this->browse(function (Browser $browser) {
    $user = factory(User::class)->create([
        'password' => $password = 'secret'
    ]);

    $browser->visit(new Pages\Login)
        ->value('@credential', $user->email)
        ->value('@password', $password)
        ->press('@submit')
        ->assertSee('You are logged in!')
        ->assertAuthenticatedAs($user);

    $this->seeIsAuthenticatedAs($user);
});
```

and this causing error on my travis build and here [video recorded](https://youtu.be/DaiDT1UzDYA) from my browserstack return not found when accessing `{BASE_URL}/_dusk/user/` url.

![image](https://user-images.githubusercontent.com/508665/27797028-45b88f98-6036-11e7-8495-2886abd735a3.png)

Just noticed that url path `/_dusk/user/{$guard}` return not found on my test.

My question is, is that `/_dusk/*` -prefixed url path need additional setup in routes files on something?

**Comment by deleugpn** [comment]
> My question is, is that `/_dusk/*` -prefixed url path need additional setup in routes files on something?

No. They are setup automatically by the DuskServiceProvider.

Could you remove the line `$this->seeIsAuthenticatedAs($user);` and see if it works?

**Comment by feryardiant** [comment]
> Could you remove the line $this->seeIsAuthenticatedAs($user); and see if it works?

The problem is actuali came from `assertAuthenticatedAs($user)` line not `seeIsAuthenticatedAs($user)`. To verify that, you can see the error message (in the image above) and see where it come from.

When I remove `assertAuthenticatedAs($user)` line, the test is passed.
