### ISSUE TITLE
Fix bug : Error insert textbox value with single quote

### ISSUE THREAD

**Issue by muswanto** [laravel/dusk#312]
Hai bro developers...:)
I got this error message : Facebook\WebDriver\Exception\UnknownServerException: unknown error: Runtime.evaluate threw exception: SyntaxError: Unexpected identifier
Issue appear when my faker provide **single quote in textbox value.**
**I changed this line to fix it:** https://github.com/laravel/dusk/blob/1.0/src/Concerns/InteractsWithElements.php#L97
from : `"document.querySelector('{$selector}').value = '{$value}';"`
into this one : `"document.querySelector('{$selector}').value = \"{$value}\";"`

Can you add this to next release ? thank you :)

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
