### ISSUE TITLE
unknown error: $ is not defined

### ISSUE THREAD

**Issue by MickaelTH** [laravel/dusk#315]
I'm getting this a lot of time, any idea how to fix it? :(

![2017-07-11 001777](https://user-images.githubusercontent.com/26375917/28075240-17824088-6685-11e7-8cc9-4322d25fe69d.png)

**Comment by hackel** [comment]
Just looks like you're trying to call jQuery before it is loaded.  Don't think this is a Dusk error.  Only use $ inside of a `jQuery(function ($) {})` call.

**Comment by MickaelTH** [comment]
Hi @hackel 

Thanks for your suggestion, I've found that JQUERY wasn't present in the page reload, so I was able to fix this by adding this line after each new page reload:

$browser->ensurejQueryIsAvailable();
