### ISSUE TITLE
Dusk looking for non-existent bootstrap/autoload.php

### ISSUE THREAD

**Issue by hackel** [laravel/dusk#316]
I am testing Laravel 5.5, and when I run `artisan dusk`, I get:
`Cannot open file ".../bootstrap/autoload.php".`

This just needs to be changed in stubs/phpunit.xml to `vendor/autoload.php`.  In the meantime, I've just created a symlink in my bootstrap directory and it seems to be working fine.

**Comment by dbpolito** [comment]
Got the same issue, fixed by copying the stub file and changing it myself:

````
cp vendor/laravel/dusk/stubs/phpunit.xml phpunit.dusk.xml
````

And update `phpunit.dusk.xml`, `Dusk` checks if you have this file and basically uses it.

**Comment by balping** [comment]
Same issue here. @dbpolito 's soultion worked for me.

**Comment by nasirouwagana** [comment]
I have a same issue with Laravel 5.5

**Comment by envision** [comment]
I had same issue but @dbpolito's solution worked.

**Comment by janaka120** [comment]
I have the same issue with Laravel 5.4.
I solve like this.
create a file **autoload.php** in **my_project/bootstrap** folder. With this content.
```
<?php

define('LARAVEL_START', microtime(true));

require_once __DIR__.'/../vendor/autoload.php';
```

that's it. Then I run the `php artisan dusk`. it works find.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
