### ISSUE TITLE
assertSelected() does not have support for selects with multiple attribute

### ISSUE THREAD

**Issue by Stetzon** [laravel/dusk#317]
Currently it appears that the [selected](https://github.com/laravel/dusk/blob/7206e77aaec865917414b25d30b1061ac5b9d83f/src/Concerns/MakesAssertions.php#L653) function does not support select dropdowns where multiple options can be selected.  If there are multiple options selected, the `resolveForSelection` helper will return the first one.  Because of this, `assertSelected` will fail in cases where you are checking for a selected option that comes _after_ the first selected option

Ex.
```
<select multiple="multiple" name="users" >
  <option value="1">Barton</option>
  <option value="2">Ebert</option>  <!-- selected -->
  <option value="3">Kunze</option> <!-- selected -->
  <option value="4">Mitchell</option> <!-- selected -->
  <option value="5">Schmitt</option>
</select>
```
```
assertNotSelected('select[name="users"]', 1)  // OK
assertSelected('select[name="users"]', 2)  // OK
assertSelected('select[name="users"]', 3)  // fails
assertSelected('select[name="users"]', 4)  // fails
assertNotSelected('select[name="users"]', 5)  // OK
```

**Comment by Stetzon** [comment]
I was able to get it working by changing the selected function to resolve only the options matching the passed in value and individually checking if that option is selected using [isSelected()](https://facebook.github.io/php-webdriver/1.1.3/Facebook/WebDriver/Remote/RemoteWebElement.html#method_isSelected):

```
    /**
     * Determine if the given value is selected for the given select field.
     *
     * @param  string  $field
     * @param  string  $value
     * @return bool
     */
    public function selected($field, $value)
    {
        $options = $this->resolver->resolveSelectOptions($field, [$value]);

        foreach ($options as $option) {
            if($option->isSelected()) return true;
        }

        return false;
    }
```

**Comment by driesvints** [comment]
Judging from the current code I think this is still an issue. I'll try to look at this at some point. In the meantime feel free to send in a PR with a test.
