### ISSUE TITLE
Call to undefined method [waitForReload]?

### ISSUE THREAD

**Issue by scofield-ua** [laravel/dusk#321]
Hello. 

I'm trying to use `waitForReload` but keep getting `BadMethodCallException: Call to undefined method [waitForReload]`.

I'm on Windows 7 x64.

### Steps to reproduce
Basic installation
- `composer create-project laravel/laravel:5.4`
- Install Dusk `composer require laravel/dusk`
- Register the `Laravel\Dusk\DuskServiceProvider` service provider.
- Install dusk for current project `php artisan dusk:install`
- Update `tests\Browser\ExampleTest` file like this: 
```
<?php

namespace Tests\Browser;

use Tests\DuskTestCase;
use Laravel\Dusk\Browser;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class ExampleTest extends DuskTestCase
{
    /**
     * A basic browser test example.
     *
     * @return void
     */
    public function testBasicExample()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/')
                    ->waitForReload();
        });
    }
}
```
- Run `php artisan dusk`

Please advise.

**Comment by MickaelTH** [comment]
Agree I have the same issue, using "pause" for now.

Based on the doc https://laravel.com/docs/5.4/dusk#waiting-for-elements it should work or only reserved for click?

`$browser->click('.some-action')
        ->waitForReload()
        ->assertSee('something');`

**Comment by scofield-ua** [comment]
@MickaelTH actually, same thing for `click()->waitForReload()` sequence

**Comment by scofield-ua** [comment]
There is not such method in [`/src/Concerns/WaitsForElements.php`](https://github.com/laravel/dusk/blob/master/src/Concerns/WaitsForElements.php), if you installing Dusk  using Composer.

**Comment by jgrossi** [comment]
It seems when installing Dusk from Composer it installs `v1.1.0` which doesn't have the `waitForReload()` method, because this version is from Apr 2017, and that method was introduced just on May 2017, in `v1.0.15`.

Just install `v1.0.15` and you'll have this `waitForReload()` method.

**Comment by oele-code** [comment]
Why was not the method added to version 1.1 ?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
