### ISSUE TITLE
PHP Fatal error:  Trait 'Tests\Facebook\WebDriver\Chrome\ChromeOptions' not found in /u10/html/TDD/tests/DuskTestCase.php on line 13

### ISSUE THREAD

**Issue by ArtisanTinkerer** [laravel/dusk#326]
I am trying to get Dusk working on Centos.

This is the error I am currently getting:
```
PHP Fatal error:  Trait 'Tests\Facebook\WebDriver\Chrome\ChromeOptions' not found in /u10/html/TDD/tests/DuskTestCase.php on line 13
```

Mick

**Comment by zoispag** [comment]
Did u add anything about ChromeOptions in your /DuskTestCase.php while trying to figure out a way to make it work on CentOS?
I also had problem while trying to make it work on CentOS using Chrome web driver, and I used phantomJS as a solution which worked just fine for me.

**Comment by ArtisanTinkerer** [comment]
No not added anything.

**Comment by zoispag** [comment]
What is in `DuskTestCase.php` on **line 13**?

**Comment by ArtisanTinkerer** [comment]
Sorry, I had actually modified this file. 

 It looks like the Chrome folder is missing in `Facebook\WebDriver\Chrome\ChromeOptions;`

```
abstract class DuskTestCase extends BaseTestCase
{
    use CreatesApplication;

    use Facebook\WebDriver\Chrome\ChromeOptions;

    /**
     * Prepare for Dusk test execution.
     *
     * @beforeClass
     * @return void
     */
    public static function prepare()
    {
        static::startChromeDriver();
    }

    /**
     * Create the RemoteWebDriver instance.
     *
     * @return \Facebook\WebDriver\Remote\RemoteWebDriver
     */
    protected function driver()
    {

        $options = (new ChromeOptions)->addArguments(['--headless']);

        return RemoteWebDriver::create(
            'http://localhost:9515', DesiredCapabilities::chrome()->setCapability(
            ChromeOptions::CAPABILITY, $options
        )
        );
    }
}
```

**Comment by zoispag** [comment]
Yeah, so this line is causing the issue

`        $options = (new ChromeOptions)->addArguments(['--headless']);`

I had the same issue trying to use ChromeOptions and because I couldn't figure out a way to bypass that and use chrome, I started using phantomJS

**Comment by ArtisanTinkerer** [comment]
Yes, but I think that is happening because I don't have this:

`use Facebook\WebDriver\Chrome\ChromeOptions;`

**Comment by zoispag** [comment]
Probably. Take a look in this. It may help you figure tthat out.

[https://github.com/laravel/dusk/issues/222](https://github.com/laravel/dusk/issues/222)

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
