### ISSUE TITLE
Dusk fails to kill Chromedriver process if no `APP_KEY` is present

### ISSUE THREAD

**Issue by rask** [laravel/dusk#328]
When `.env` has no `APP_KEY` defined, Dusk fails to kill the Chromedriver process that it started.

After the `APP_KEY` is defined (e.g. via `artisan key:generate`) then Dusk terminates the Chromedriver process properly.

The issue with this is that Dusk tests run via `artisan dusk` will not work until the developer finds out that the Chromedriver processes are still running from a failed attempt, which leads to frustration when running Dusk tests all test cases fail with a 30 second timeout with no apparent reason.

Even after the `APP_KEY` has been defined Dusk tests continue to fail until the rogue process(es) are killed manually via `pkill` or something.

To repro:

1. Create new Laravel App and install Dusk
2. Create test cases and features as normally
3. Now set `APP_KEY` to `null` (empty in `.env`)
4. Attempt to run Dusk tests a few times via `artisan dusk`
5. Observe test results and `ps aux | grep chromedriver`

This issue happened when I cloned an older project and forgot to set `APP_KEY` via `artisan key:generate`.

I think the tests fail with the cipher error messages regarding missing `APP_KEY` and that somehow jams the test process until `APP_KEY` is added and rogue Chromedriver processes are killed.

---

Not sure if this is a code fix or a documentation fix. `APP_KEY` should always be defined anyway. This is mainly a silly human-error annoyance that took a long time to resolve.

**Comment by rask** [comment]
Oh wait a minute, happens even with `APP_KEY` defined for some reason now.

Need to investigate. I'll close this one and create a new one in case this is an actual issue in Dusk and not something I broke myself.

The issue is now that I need manually `pkill chromedriver` after each and every `artisan dusk` test run in order to run the tests again, otherwise the tests hang and timeout.

**Comment by dotnetCarpenter** [comment]
@rask I just released the same while testing audio and the audio keeps playing after the tests has runned. Seems that Dusk is missing something and it doesn't have to do with the environment variables.

**Comment by dotnetCarpenter** [comment]
Ok. This only happens when I run a single test class.
