### ISSUE TITLE
Disabling browser password popup

### ISSUE THREAD

**Issue by nicolasbeauvais** [laravel/dusk#330]
My tests were running fine but now chrome trigger a popup to ask if we want to store a password which freeze the test suite. I tried to disable this behavior in the browser configuration but it is reset every time I execute the test suite.

![screenshot-2017-08-05_23-45-14](https://user-images.githubusercontent.com/2951704/28999018-909c4cee-7a39-11e7-9380-d50e59523465.png)

Dusk version: v1.1.0
Chrome version:  58.0.3029.110
OS: Debian jessie

Here are the parameters to use to disable the password popup:
https://makandracards.com/makandra/45091-how-to-disable-chrome-s-save-password-bubble-for-selenium-tests

I couldn't find some sort of configuration passed to the Chrome browser in the code so I did not make a PR. Thank you for your help :)

**Comment by deleugpn** [comment]
According to the link you provided

> Sadly, there are no command line switches for this.

**Comment by deleugpn** [comment]
According to the link you provided

> Sadly, there are no command line switches for this.

**Comment by nicolasbeauvais** [comment]
The popup doesn't appear anymore, closing the issue
