### ISSUE TITLE
no document about console.log

### ISSUE THREAD

**Issue by xralphack** [laravel/dusk#349]
there is a function named storeConsoleLog in Browser class,
but I can't find document about it.

Can anyone help me on how to debug js by using console.log, thx

**Comment by deleugpn** [comment]
Short answer is that you can't. The browser splits console messages into 4 different categories. Console.log is not an actual error log, so it doesn't get picked up by Facebook WebDriver.

**Comment by xralphack** [comment]
@deleugpn if so, how can I debug whether my js function get called

**Comment by deleugpn** [comment]
Using `alert` and checking the screenshot would be my first suggestion. You can also try to assert the outcome of the javascript functionality.

**Comment by xralphack** [comment]
got it, thx ~
