### ISSUE TITLE
Could not find package laravel/dusk at any version for your minimum-stability (stable). 

### ISSUE THREAD

**Issue by godruoyi** [laravel/dusk#35]
When i run ` composer require laravel/dusk`, get a error 

```shell
[InvalidArgumentException]
  Could not find package laravel/dusk at any version for your minimum-stability (stable). Check the package spelling
  or your minimum-stability
```

**Comment by mstnorris** [comment]
@godruoyi You need the `--dev` flag as it hasn't been released yet.

**Comment by godruoyi** [comment]
Ok, Thanks, But when I run `composer require laravel/dusk --dev` on `centos` or `window10`,  and I try recreated a new folder run this command, This error is still here

```shell
 [InvalidArgumentException]
  Could not find package laravel/dusk at any version for your minimum-stability (stable). Check the package spelling
  or your minimum-stability

```

**Comment by mstnorris** [comment]
@godruoyi apologies, the message is referring to your composer.json file. Ensure that your minimum stability is set to "dev":

`"minimum-stability": "dev",`

**Comment by ruchern** [comment]
On Laravel 5.3, can confirm that `--dev` flag no longer works. Just wait for 5.4 now which is anytime soon.
