### ISSUE TITLE
How to click overlay element?

### ISSUE THREAD

**Issue by gfd6th** [laravel/dusk#353]
I have an element with the attribute: ' position: fixed '. 
so the dusk will fail for this element is not clickable at point (333, 333), the element under this fixed element will be click. 

I try use mouseover(element), but how to click at current mouse point. click() method need pass selector.

**Comment by lsfiege** [comment]
I have the same trouble here, but with an element with static position, guess it's caused by a newest google chrome update. Yesterday all my tests where passing, but today some tests are failing with this "Element is not clickable at point" error message

**Comment by gfd6th** [comment]
I changed to selenium with firefox, It could select overlay element
