### ISSUE TITLE
Access Dusk outside of CLI

### ISSUE THREAD

**Issue by dk4210** [laravel/dusk#356]
I would like to run dusk outside of the CLI. Basically I'm trying to run my tests via a route or controller
like this

Route::get('runtests', function() 
{
    echo '<br>init Dusk...';
    Artisan::call('dusk');
    echo 'done dusk';
});

Is there a way to access dusk through the artisan facade?

**Comment by dk4210** [comment]
I found that I needed to remove this if statement from DuskServiceProvider.php
"if ($this->app->runningInConsole()) {"

When I run this code now 

 $_SERVER['argv'] = []; 
    echo '<br>init Dusk...';
    Artisan::call('dusk');
    echo 'done dusk';

I get this error message

Warning: TTY mode is not supported on Windows platform.\r\n
Could not open input file: vendor/phpunit/phpunit/phpunit\n

The warning is normal. I get that even when I run via CLI. The second one in regards to phpunit is what i'm trying to figure out now.

**Comment by poxin13** [comment]
I too would like to be able to cleanly call Dusk via a controller for aspects outside of pure testing. Could be used as a neat automation tool in certain scenarios. Example if the endpoint doesn't have an API.

**Comment by huglester** [comment]
maybe someone managed to run dusk from controller?

**Comment by staudenmeir** [comment]
You can create your own Chrome browser like this @poxin13:

    $process = (new ChromeProcess)->toProcess();
    $process->start();
    $options = (new ChromeOptions)->addArguments(['--disable-gpu', '--headless']);
    $capabilities = DesiredCapabilities::chrome()->setCapability(ChromeOptions::CAPABILITY, $options);
    $driver = retry(5, function () use($capabilities) {
        return RemoteWebDriver::create('http://localhost:9515', $capabilities);
    }, 50);
    $browser = new Browser($driver);
    $browser->visit('https://www.google.com');
    $browser->quit();
    $process->stop();

**Comment by cdubant** [comment]
I used this code and prefixed it with the required namespaces like so 

`$process = (new \Laravel\Dusk\Chrome\ChromeProcess)->toProcess();
        $process->start();
        $options = (new \Facebook\WebDriver\Chrome\ChromeOptions)->addArguments(['--disable-gpu', '--headless']);
        $capabilities = \Facebook\WebDriver\Remote\DesiredCapabilities::chrome()->setCapability(\Facebook\WebDriver\Chrome\ChromeOptions::CAPABILITY, $options);
        $driver = retry(5, function () use($capabilities) {
            return \Facebook\WebDriver\Remote\RemoteWebDriver::create('http://localhost:9515', $capabilities);
        }, 50);
        $browser = new Browser($driver);
        $browser->visit('https://www.google.com');
        $browser->quit();
        $process->stop();`

Unfortunately it seems like it's not starting the browser process correctly whereas it does perfectly when using Dusk with phpunit as in the official doc.

I need to run this and have control on the process, make it visit pages, dump the HTML, etc... from a controller.

Has anyone managed to get through this ?

**Comment by cdubant** [comment]
After a few research, it seems that when running as dusk tests, the chromedriver runs nicely and I guess it's instanciated on a random port as I see 

> DevTools listening on ws://127.0.0.1:12723/devtools/browser/b2dc83c4-5bfa-4df5-9db9-0bf7bc4befb2

Here it's 12723 but it's always a different port.

It seems that the port is defined at launch and the fact that I hardcode http://localhost:9515 seems to be what's causing the issue.

Any help on this?

Thanks in advance.

**Comment by staudenmeir** [comment]
Maybe the port is already being used. Did you try a different one?

**Comment by cdubant** [comment]
I tried several others and everytime it says 

> Failed to connect to localhost port XXXX: Connection refused

I also tried with ports > 10000 just to be sure, several times with the same error again and again.

**Comment by poxin13** [comment]
This is working great, thanks @staudenmeir

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by decadence** [comment]
@staudenmeir thanks! Works perfectly.

**Comment by nirmalgoswami** [comment]
@decadence i am not able to see browser, i want to see progress by disabling headless, 
using screenshot i can see that code is working fine but i want GUI to deal with captcha

**Comment by staudenmeir** [comment]
@nirmalgoswami Use this line instead:

```php
$options = new ChromeOptions;
```

**Comment by nirmalgoswami** [comment]
Thanks, i tried your solution but still i am not able to see browser

my code as follow
          
            use Facebook\WebDriver\Chrome\ChromeOptions;
            use Facebook\WebDriver\Remote\DesiredCapabilities;
            use Facebook\WebDriver\Remote\RemoteWebDriver;
            use Laravel\Dusk\Browser;
            use Laravel\Dusk\Chrome\ChromeProcess;
            use Laravel\Dusk\ElementResolver;

            $process = (new ChromeProcess)->toProcess();
            //$process->start();
            $process->start(null, [
                'SystemRoot' => 'C:\\WINDOWS',
                'TEMP' => 'C:\Users\MAHAVIR\AppData\Local\Temp',
            ]);
            $options = new ChromeOptions;
            $options->setBinary("C:\Program Files\Google\Chrome\Application\chrome.exe");
            $capabilities = DesiredCapabilities::chrome()->setCapability(ChromeOptions::CAPABILITY, $options);
            $driver = retry(5, function () use($capabilities) {
                return RemoteWebDriver::create('http://localhost:9515', $capabilities);
            }, 50);
            $browser = new Browser($driver);
            $browser->visit('https://www.google.com');
            $browser->quit();
            $process->stop();
```

**Comment by maxillarious** [comment]
> Thanks, i tried your solution but still i am not able to see browser
> 
> my code as follow
> 
> ```
>         use Facebook\WebDriver\Chrome\ChromeOptions;
>         use Facebook\WebDriver\Remote\DesiredCapabilities;
>         use Facebook\WebDriver\Remote\RemoteWebDriver;
>         use Laravel\Dusk\Browser;
>         use Laravel\Dusk\Chrome\ChromeProcess;
>         use Laravel\Dusk\ElementResolver;
> 
>         $process = (new ChromeProcess)->toProcess();
>         //$process->start();
>         $process->start(null, [
>             'SystemRoot' => 'C:\\WINDOWS',
>             'TEMP' => 'C:\Users\MAHAVIR\AppData\Local\Temp',
>         ]);
>         $options = new ChromeOptions;
>         $options->setBinary("C:\Program Files\Google\Chrome\Application\chrome.exe");
>         $capabilities = DesiredCapabilities::chrome()->setCapability(ChromeOptions::CAPABILITY, $options);
>         $driver = retry(5, function () use($capabilities) {
>             return RemoteWebDriver::create('http://localhost:9515', $capabilities);
>         }, 50);
>         $browser = new Browser($driver);
>         $browser->visit('https://www.google.com');
>         $browser->quit();
>         $process->stop();
> ```

If posible may I know where you placed this code, thanks.

**Comment by nirmalgoswami** [comment]
@maxillarious controller method

**Comment by maxillarious** [comment]
> @maxillarious controller method

Thanks, I tried it and it worked.

**Comment by maxillarious** [comment]
[https://github.com/laravel/dusk/issues/356](john)

**Comment by maxillarious** [comment]
[Link](https://github.com/laravel/dusk/issues/356)
