### ISSUE TITLE
unlink sqlite file problem

### ISSUE THREAD

**Issue by xralphack** [laravel/dusk#359]
I used sqlite.

ErrorException: unlink(...\dusk.sqlite): Resource temporarily unavailable

the exception throwed from     

```
    public function refreshDatabaseFile()
    {
        unlink($this->connection->getDatabaseName());

        touch($this->connection->getDatabaseName());
    }
```

after I comment the unlink line, it works again.
seems touch() can overwrite the existing file
anyone has same issue?

**Comment by AdamEsterle** [comment]
Yes, Same issue when running Dusk Browser tests.

**Comment by Infrantic** [comment]
I temporarily fixed this by changing our DatabaseMigrations.php file to use migrate:refresh again instead og migrate:fresh. No permanent fix found yet, though.

**Comment by xralphack** [comment]
by the way, the issue occurs on Windows10. macOS seems not have this problem

**Comment by AdamEsterle** [comment]
@xralphack Yes. My mac is not with me, but if I remember correctly, Windows only (I'm on 7), Mac is fine. I am running homestead on both Mac and Windows.

**Comment by xralphack** [comment]
@AdamEsterle I run laravel on both platform by docker, so may be platform specific problem

**Comment by tyler36** [comment]
Same issue on Win10

**Comment by KristofMorva** [comment]
https://github.com/laravel/framework/pull/21720 may be related to this, can you check if that PR fixes this issue for any of you?

**Comment by tyler36** [comment]
Works for me on Win10. Thanks

**Comment by alexeycrystal** [comment]
KristofMorva, Thank you very much! I have also solved this issue by using your solution. Nice!

**Comment by AdamEsterle** [comment]
@KristofMorva Worked for me!

**Comment by ddarshana** [comment]
Me to got this error in my local working environment.
I just close the my SQLite browser. 
Then command executed as expected.
It seems, the issue was SQLite browser was locking the database file.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
