### ISSUE TITLE
How to assert an element has special classname after I click some button

### ISSUE THREAD

**Issue by gfd6th** [laravel/dusk#360]
How to assert an element has special classname or element computed style after I click some button

I haven't see an assertion  works like like

**Comment by Joucke** [comment]
Does $browser->assertSeeIn('newSelector', 'Element contents') work?

**Comment by ttakahashi2013** [comment]
I have similar issue.
Made vue component to avoid multi click by user not to register duplicate data.
So want to implement test user multi click.

```
browser->assertVue('isSubmitting', false, '@submit-button-component')
              ->click('@submit-button-component')
              ->click('@submit-button-component')
```

or 

```
browser->assertVue('isSubmitting', false, '@submit-button-component')
              ->click('@submit-button-component')
              ->assertVue('isSubmitting', true, '@submit-button-component')
```

but 1st test got error,
`no such element: Unable to locate element: {"method":"css selector","selector":"body [dusk="submit-button-component"]"}`

and 2nd test is the following
`Facebook\WebDriver\Exception\UnknownServerException: unknown error: Cannot read property '__vue__' of null
`

is there a way to check the vue component change or test user double click?




Just for code reference.
SubmitButton single file vue component
```
<template>
  <div>
    <input type="submit" class="button_orange button_big" :value="value" v-show="!isSubmitting" @click="startSubmit">
    <div class="button_white button_big" v-show="isSubmitting">{{ value }}</div>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        isSubmitting: false,
      };
    },
    props: {
      value: {
        type: String,
        default: '',
      },
    },
    methods: {
      startSubmit() {
        this.isSubmitting = true;
      },
    },
  };
</script>

```

blade call
`<submit-button value="{{ $submitButton }}" dusk="submit-button-component"></submit-button>`

**Comment by bitzor** [comment]
Assertion on conditional elements shown when some property changes in vue apparently fails with Dusk. Dusk won't evaluate the condition. I am having the exact same issue right now.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
