### ISSUE TITLE
Javascript confirm dialog does not work with headless mode

### ISSUE THREAD

**Issue by Sander00** [laravel/dusk#373]
When I try to use `$browser->acceptDialog()` on headless mode I always get the error `Facebook\WebDriver\Exception\NoAlertOpenException: no alert open`

When I disable headless mode it runs perfectly fine. 

Is this a bug on my side?

**Comment by cerzzwiz** [comment]
I have the same problem. It seems that the alert doesn't popup at all

**Comment by Sander00** [comment]
@cerzzwiz Yes, seems like that is the problem. You can't see it in the failure screenshot.

**Comment by muhzak** [comment]
Also having this issue.

**Comment by prateekobi** [comment]
Same here :(

**Comment by deleugpn** [comment]
Unfortunately, this is a Chrome bug.

https://bugs.chromium.org/p/chromium/issues/detail?id=718235

**Comment by aaronranard** [comment]
Looks like it will be fixed in chrome v62, the Facebook WebDriver is v61. Anyone know when they are planning to update to v62?

**Comment by Sander00** [comment]
@aaronranard I think it was released on October 17th according to https://www.chromium.org/developers/calendar

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
