### ISSUE TITLE
Having issues with TravisCI

### ISSUE THREAD

**Issue by dmarcos89** [laravel/dusk#380]
Hi, i am having issues when trying to integrate dusk with travis-ci.
This is what my `travis.yaml` looks like:
```
sudo: required
language: php
dist: trusty

php:
  - 7.1

install:
  - travis_retry composer install --no-interaction

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.dusk .env
  - php artisan serve &

script:
  - php artisan dusk
```

and this is what i keep getting on travis console:
```
  [Exception]                              
  It is unsafe to run Dusk in production.  
                                           
Script php artisan optimize handling the post-install-cmd event returned with error code 1
The command "composer install --no-interaction" failed. Retrying, 2 of 3.
```
Any help will be much appreciated 😃

**Comment by deleugpn** [comment]
Inside your `.env.dusk`, set `APP_ENV` to something different than `production`.

**Comment by dmarcos89** [comment]
Hi @deleugpn , thanks for your answer, but i have tried that already on my `.env.dusk`:
```
APP_NAME=Laravel
APP_ENV=testing
APP_KEY=base64:asd321SIj4IjIxlpETKfUZtuBT8iO1ijtuX3fyKzU=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://fa_admin.dev

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=fa_admin_test
DB_USERNAME=root
DB_PASSWORD=
```
Any idea on how to override this in Travis?

**Comment by deleugpn** [comment]
Are you sure that file is not git ignored?

**Comment by dmarcos89** [comment]
yeap.. i can see the file on the repo..

**Comment by dmarcos89** [comment]
Hi @deleugpn. Ok, so after a couple of days coming back to this, at least it started working. 
Now the thing is, this simple test works locally but fails in Travis...
```
$this->browse(function (Browser $browser) {
   $browser->visit('/')->assertSee('Laravel');
});
```
This is what my travis file looks like:

```
sudo: required
language: php
dist: trusty

php:
  - 7.1

install:
  - cp .env.travis .env

before_script:
    - travis_retry composer install --no-interaction
    - export DISPLAY=:99.0
    - mysql -e 'create database test;'
    - sh -e /etc/init.d/xvfb start
    - ./vendor/laravel/dusk/bin/chromedriver-linux &
    - php artisan serve > /dev/null 2>&1 &

script:
    - php artisan dusk
```

Is there anything i need to do with the APP_URL? 

Then, what happens when working with databases? Should i create it with `- mysql -e 'create database test;'` and set it in the .env file?

Many thanks for your help!!

**Comment by georaldc** [comment]
Is `http://fa_admin.dev` accessible by your travis build? I have no experience with travisci but with circleci, I always setup my environment before tests run to ensure that I can get acceptance tests like Dusk working. For example, I use PHP's built in web server on my project's web entry point directory and point my test URL to that (eg. 127.0.0.1:8000)

**Comment by dmarcos89** [comment]
Hi @georaldc, sorry i didn't close the issue. Exactly, i noticed i should use 127.0.0.1:8000 on the app url.
Thanks for your kind response!
