### ISSUE TITLE
Error: Call to undefined method Facebook\Webdriver\Remote\RemoteWebDriver::getCapabilities()

### ISSUE THREAD

**Issue by masterwto** [laravel/dusk#385]
I upgraded my laravel vendor and run the tests, then got this error.

I then fall back the Facebook Webdriver and it works OK.

**Comment by masterwto** [comment]
php 7.1.8
mariadb 10.2
laravel 5.5.14
Facebook\webdriver 1.1.1

**Comment by masterwto** [comment]
I think it's related to newest composer. My composer is recently newly installed, and I found I got Facebook\Webdriver of version 1.1.1. In fact, Facebook\Webdriver\Remote\RemoteWebDriver::getCapabilities()  is introduced in version 1.3.

updating composer.json may help.

**Comment by dborovsky** [comment]
I installed dusk and  facebook/webdriver has version 1.4.1 and i got same error.

**Comment by masterwto** [comment]
@dborovsky
1.3 is working fine.

**Comment by josensanchez** [comment]
if this keep happens to anybody... in my case was

  Problem 1
    - facebook/webdriver 1.5.x-dev requires ext-zip 

and because of that, composer updates webdriver to 1.2 only.  

run  
$ composer require facebook/webdriver

maybe it's this or some other dependency that is missing.

**Comment by pacoorozco** [comment]
As @josensanchez mentioned you need `facebook/webdriver` version 1.5+ but if you're trying to do a `composer update facebook/webdriver` and 1.5 is not installed, please assure yourself you have installed PHP zip extension.

In my ubuntu:
```
$ apt install php-zip
$ composer update facebook/webdriver
  - Updating facebook/webdriver (1.2.0 => 1.6.0): Downloading (100%)
$ php artisan dusk
```
Now, **It's working**
