### ISSUE TITLE
Setting a consistent language preference

### ISSUE THREAD

**Issue by vpratfr** [laravel/dusk#390]
My application has a middleware which sets the locale according to the user preferences sent by the browser.

How can we tell Dusk to always send EN as the preferred language when running the tests?

Indeed, when running on my own machine, all tests fail because the pages all show French.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
