### ISSUE TITLE
what the command to run dusk test used page

### ISSUE THREAD

**Issue by developerMerna** [laravel/dusk#394]
How can I run dusk test use page ??
I try 
 
    php artisan dusk tests/Browser/Pages/EditProfile.php 

its give me 

    Class 'tests/Browser/Pages/EditProfile' could not be found in '/home/projects/folder/tests/Browser/Pages/EditProfile.php'.

**Comment by unglud** [comment]
Page it's not a test, it's just class (blocks) to help you in your tests https://laravel.com/docs/master/dusk#pages
