### ISSUE TITLE
Dusk times out when loading pages due to slow internet

### ISSUE THREAD

**Issue by digitlimit** [laravel/dusk#399]
Error below occurs 

Dusk operation timed out after 30000 milliseconds with 0 bytes received

Only for pages that requires access to external assets/resources e.g Google Geo location service 

Dusk timesout while waiting for page to load due to slow internet.

I can't change my internet speed, is it possible to increase dusk timeout value

**Comment by deleugpn** [comment]
That error usually means you don't have Chrome Driver running. It has nothing to do with connectivity.

**Comment by chilio** [comment]
Are you running dusk test cases on ssl enabled site?
If not, this might be kind of expected result since chrome is blocking access to browsers geolocation functions and then whole test might timeout...

**Comment by digitlimit** [comment]
@deleugpn I am able to confirm this only happens for any page that requires external assets ...if I comment those tests other tests passes

@chilio I suspected this earlier so I remove ssl rules from nginx, now using non secured http, but issue persists

I'm sure it's my internet speed, assets not loaded before timeout

**Comment by chilio** [comment]
@digitlimit I meant that **you need to have it on and use ss**l -> https:// site for retrieving browser location functions
Btw you can try other external assets (not geo services) to check if that's not the case...

**Comment by digitlimit** [comment]
@chilio I'm using https to external assets already. :)

**Comment by digitlimit** [comment]
@chilio have tried that, same problem :( 
Anyway I can increase timeout? I can see it's currently set at 60 seconds

**Comment by HughVolpe** [comment]
It seems odd that you would need to increase the timeout, but chrome will be re-downloading all the remote assets each test as it wont store them in cache. You can change that as well by setting a cache directory, but I don't think thats a good idea for testing. I guess you would have thought of this, but if you can move the assets to be served locally that would fix this (may not be possible depending on what they are obviously). 

If you run the version of chrome without it being headless you can normally see what is going on better and fix what is wrong.

In answer to how to increase the timeout, the message you are seeing (operation timeout after 30000ms etc) is from the facebook's remote web driver. 

The RemoteWebDriver instance is created in DuskTestCase in the Driver() function. Pass in 2 more parameters as a number of milliseconds to increase the time it will wait for the page to fully load e.g:
`
        return RemoteWebDriver::create(
            'http://localhost:9515', 
            DesiredCapabilities::chrome()->setCapability(
                ChromeOptions::CAPABILITY, $options
            ),
            60*1000,
            60*1000,
        );
`

Hope this helps, but it if you can fix the problem some other way I would suggest doing that instead. It would be very slow to run your tests like this.

**Comment by driesvints** [comment]
@digitlimit try mocking the geolocation as suggested here: https://github.com/laravel/dusk/issues/459

**Comment by istvan73** [comment]
@digitlimit  I had the same error for two days, but I finally solved it. I will sound strange, but you must remove headless start from the chrome options. 

` $options = (new ChromeOptions)->addArguments([
            '--disable-gpu',
            '--no-sandbox'
        ]);
        return RemoteWebDriver::create(
            'http://localhost:9515', DesiredCapabilities::chrome()->setCapability(
            ChromeOptions::CAPABILITY, $options
        )
        );`

Having it start headless made it run in 7.8 seconds for me, good luck with that, everyone! :)
