### ISSUE TITLE
Trait 'Tests\CreatesApplication' not found in DuskTestCase.php

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [laravel/dusk#40]
Trait 'Tests\CreatesApplication' not found in ../tests/DuskTestCase.php on line 11

**Comment by KKSzymanowski** [comment]
Assuming you have the class in the correct namespace, `composer dump-autoload` might help.

**Comment by Vasiliy-Bondarenko** [comment]
nope.
i've tried to find it in all codebase of dusk. looks like it just does not exist.

**Comment by KKSzymanowski** [comment]
Ah, you need to manually add it if you upgraded from <5.4 to 5.4. Take a look at the develop branch of `laravel/laravel`. [This is the file](https://github.com/laravel/laravel/blob/develop/tests/CreatesApplication.php).

**Comment by Vasiliy-Bondarenko** [comment]
ok. got it. it works.
i think it should be mentioned in upgrade guide :)
thank you.

**Comment by KKSzymanowski** [comment]
I agree. You can create a pull request to `laravel/docs` but maybe there is a better solution than copying all needed files. Upgrade guide says you don't need to rewrite all your existing tests in order to run them, but it doesn't say how to integrate Dusk with them. 

@taylorotwell I will be thankful for your opinion on this subject, because soon I too will be upgrading couple of apps to 5.4.

**Comment by Vasiliy-Bondarenko** [comment]
i think for now that only thing is missing from the docs is creating that trait. all the rest worked fine.

**Comment by djaiss** [comment]
To me 2 things were missing from 5.3 to 5.4:

In `composer.json`:
- add `"Tests\\": "tests/"` in 
```json
"autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
            "Tests\\": "tests/"
        }
    },
```
* replace `"phpunit/phpunit": "~4.0",` by `"phpunit/phpunit": "~5.0",`

**Comment by prodes** [comment]
Thanks for you reply @djaiss! This is really missing in the docs!

**Comment by nlocascio** [comment]
@djaiss For performance reasons, avoid autoloading your tests in production. You can use autoload-dev instead, as in the Laravel 5.4 repo ([https://github.com/laravel/laravel/blob/master/composer.json](url)):

```
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
```

[https://getcomposer.org/doc/04-schema.md#autoload-dev](url):

> Classes needed to run the test suite should not be included in the main autoload rules to avoid polluting the autoloader in production and when other people use your package as a dependency.

**Comment by browner12** [comment]
there is a 'Miscellaneous' section at the bottom of the upgrade guide that I added, that suggests you look at the comparison of the `laravel/laravel` repository between the current version and the previous. If you follow that you'll pick up on all these random changes.

**Comment by djaiss** [comment]
Thanks @nlocascio @browner12 for your reply.

**Comment by deleugpn** [comment]
Can this be closed?

**Comment by akttt** [comment]
composer dump-autoload

**Comment by iqbalhussain931** [comment]
> To me 2 things were missing from 5.3 to 5.4:
> 
> In `composer.json`:
> 
> * add `"Tests\\": "tests/"` in
> 
> ```json
> "autoload": {
>         "classmap": [
>             "database"
>         ],
>         "psr-4": {
>             "App\\": "app/",
>             "Tests\\": "tests/"
>         }
>     },
> ```
> 
> * replace `"phpunit/phpunit": "~4.0",` by `"phpunit/phpunit": "~5.0",`

It worked. After updating the composer.json file you would need to run command 
`composer du -o`

**Comment by vilferalvarez** [comment]
In my case I had to add  "Tests\\": "tests/" in the autoload section into composer.json file

Good luck
