### ISSUE TITLE
Network.deleteCookie' wasn't found error

### ISSUE THREAD

**Issue by digitlimit** [laravel/dusk#401]
I'm getting error message below.
Can someone point me in the right direction?
Is this issue Laravel Dusk related or Chrome issue

Facebook\WebDriver\Exception\UnknownServerException: unknown error: unhandled inspector error: {"code":-32601,"message":"'Network.deleteCookie' wasn't found"}
  (Session info: chrome=62.0.3202.62)
  (Driver info: chromedriver=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f),platform=Linux 4.4.0-31-generic x86_64)

ERRORS!
Tests: 1, Assertions: 2, Errors: 1.

**Comment by digitlimit** [comment]
Seems this issue only happens in latest version of Google Chrome.
I downgraded by installing https://www.slimjet.com/chrome/download-chrome.php?file=lnx%2Fchrome64_56.0.2924.87.deb

And everything works fine.
Thanks for this URL https://www.slimjet.com/chrome/google-chrome-old-version.php

**Comment by PriKahar** [comment]
Is there going to be a permanent solution for this error instead of going back on the older version on Chrome ?

**Comment by saulwilcox-jisc** [comment]
Getting a similar error on 61.0.3163.100 (Mac OS Sierra)
Chrome Version reported in error: 62.0.3202.94

In this issue:

https://github.com/timgrossmann/InstaPy/issues/813

@converge mentions a bug in chromedriver. Updating to currently 2.33.2 fixed it for me:
brew remove chromedriver
brew install chromedriver

**Comment by huangcaiyan520** [comment]
chrome version is too low
you can run : 
`brew upgrade chromedriver`
