### ISSUE TITLE
GetAttribute adds 'string:' to the value

### ISSUE THREAD

**Issue by dericlima** [laravel/dusk#402]
I'm using Laravel Dusk v1.1.0 and I found this curious issue trying to select a element using $browser->select()

```
<select ng-options="country.isoAlpha3 as country.countryName for country in countries
name="company_country" id="company_country" required>
    <option value="">Select Country...</option>
</select>
```

And I'm trying to select a element with:
```
$this->browse(function (Browser $browser) use ($user) { \n
            $browser->loginAs($user)
                ->visit('/')
                ->type('company_name', 'TestComp')
                ->type('company_website', 'test.com')
                ->select('company_country', 'AND');
```
My element is not being selected. After some debug I found out this:
[debug](https://www.dropbox.com/home/Public?preview=Screenshot+from+2017-10-26+11-47-33.png)

Looks like when getAttribute is called is adding 'string:' to the value, so it doesn't match and it cant select a option.
If I return to my test and change the select to:

`->select('company_country', 'string:AND');`

It matches and everything works like expected. Some ideas? I really don't want to add 'string:' in every select that I need to perform. Thanks guys
The JSON can be found here: [Countries.json](https://www.dropbox.com/home/Public?preview=countries.json)
*Some info about my environment:*
* Angular 1.4
* Laravel Dusk v1.1.0
* Laravel v5.4.36
* Php-webdriver version: 1.4.1
* PHP version: 7.1

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
