### ISSUE TITLE
Dusk using Facebook OAuth 

### ISSUE THREAD

**Issue by pr0ph0z** [laravel/dusk#403]
When i trying to use `php artisan dusk` it displays  :
`Warning: TTY mode is not supported on Windows platform.
PHPUnit 6.4.1 by Sebastian Bergmann and contributors.`

`[1027/131959.444:ERROR:devtools_http_handler.cc(786)]
DevTools listening on 127.0.0.1:12049`

`[1027/132003.511:INFO:CONSOLE(1)] "Tidak Dapat Memuat URL: Domain dari URL ini tidak termasuk dalam domain aplikasi ini. Untuk dapat memuat URL
 ini, tambahkan semua domain dan subdomain dari aplikasi Anda ke kolom Domain Aplikasi dalam pengaturan aplikasi Anda.", source: https://www.fa
cebook.com/connect/ping?client_id=277385395761685&domain=localhost&origin=1&redirect_uri=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbi
ter%2Fr%2FhsBwMj6iLmk.js%3Fversion%3D42%23cb%3Df1c74f8cd5242e%26domain%3Dlocalhost%26origin%3Dhttp%253A%252F%252Flocalhost%252Ffea2cc4292ff34%2
6relation%3Dparent&response_type=token%2Csigned_request%2Ccode&sdk=joey (1)
F[1027/132007.189:ERROR:devtools_http_handler.cc(786)]
DevTools listening on 127.0.0.1:12945`

`[1027/132012.862:INFO:CONSOLE(1)] "Tidak Dapat Memuat URL: Domain dari URL ini tidak termasuk dalam domain aplikasi ini. Untuk dapat memuat URL
 ini, tambahkan semua domain dan subdomain dari aplikasi Anda ke kolom Domain Aplikasi dalam pengaturan aplikasi Anda.", source: https://www.fa
cebook.com/connect/ping?client_id=277385395761685&domain=localhost&origin=1&redirect_uri=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbi
ter%2Fr%2FhsBwMj6iLmk.js%3Fversion%3D42%23cb%3Df7e94f30b1a5d4%26domain%3Dlocalhost%26origin%3Dhttp%253A%252F%252Flocalhost%252Ffd70b22deed5ec%2
6relation%3Dparent&response_type=token%2Csigned_request%2Ccode&sdk=joey (1)`

any idea?

**Comment by astierler** [comment]
@pr0ph0z  Literally Google Translated the error:
```Can not Load URL: The domain of this URL is not included in this app domain. To be able to load this URL, add all the domains and subdomains of your app to the Application Domain column in your app settings.```

Facebook is denying you because Facebook's Apps have settings to only allow oauth connections from their verified webpages.  You're out of luck, unless you are the owner of the app and add test URL's to the app in Facebook Developer Console.

**Comment by pr0ph0z** [comment]
@astierler why i should sent a request to Facebook's Apps?

**Comment by zoe606** [comment]
@pr0ph0z have same problem here

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
