### ISSUE TITLE
running 'php artisan dusk' without '.env.dusk.environment' file

### ISSUE THREAD

**Issue by Gavrisimo** [laravel/dusk#407]
Is it possible to stop the execution of dusk if the `.env.dusk.environment` file is not found?

What happened to us is that we ran `php artisan dusk` without `.env.dusk.environment` and it picked up our database credentials and re-migrated everything. This happened locally, so we are just thinking what if that happens in production.

What I am thinking now is maybe just to add a check to see what environment we are in, if it is production and the `.env.dusk.production` file does not exist - throw an exception and stop the execution?

https://github.com/laravel/dusk/blob/29127c21d72ab5bff53ed3b8eb914c0059c77763/src/Console/DuskCommand.php#L136

```
if ( $this->laravel->environment() === 'production' && !file_exists(base_path('.env.dusk.production')) {
    // throw exception
}
```

Or just don't run dusk if there is no `.env.dusk.environment` file.

**Comment by deleugpn** [comment]
This will never happen in production because Dusk cannot be registered in production. 

https://github.com/laravel/dusk/blob/2.0/src/DuskServiceProvider.php#L42

**Comment by Gavrisimo** [comment]
Great! Thanks!
