### ISSUE TITLE
ERROR: devtools_http_handler.cc

### ISSUE THREAD

**Issue by zhukovsergey** [laravel/dusk#409]
Hello everyone.
Anybody know how to fix this error:
![image](https://user-images.githubusercontent.com/1946769/32702314-c097e59e-c817-11e7-884b-61263623fdd3.png)

On every test i have getting error:
[1113/020331.881:ERROR:devtools_http_handler.cc(786)]
This is default settings with the last versions laravel and dusk.

**Comment by masterwto** [comment]
I got this problem, too.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
