### ISSUE TITLE
Can not interact with dynamically inserted elements

### ISSUE THREAD

**Issue by salarmehr** [laravel/dusk#411]
Trying to click on `.bar` that is appended after an Ajax call:
This does not work:
```
        $this->browse(function(Browser $b) {
            $b->visit('tes.dev');
            $b->click('.foo');
            $b->waitFor('.bar');           
            $b->click('.bar');
        })
```

Using corresponding driver function works:

```
        $this->browse(function(Browser $b) {
            $b->visit('tes.dev');
            $b->click('.foo');
            $element = WebDriverBy::cssSelector('.foo');;
            $b->driver->wait()->until(WebDriverExpectedCondition::presenceOfElementLocated($element));
            $b->driver->findElement($element)->click();
        })
```

Really frustrating to figure out it was related to Dusk itself.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by AmirrezaNasiri** [comment]
@salarmehr Have you solved the issue? I'm facing the same problem.

**Comment by salarmehr** [comment]
@AmirrezaNasiri This ticket is for three years ago, as far as I remember I used https://github.com/php-webdriver/php-webdriver

**Comment by AmirrezaNasiri** [comment]
Oh sorry! These are side effects of being awake for a long time. I'll read more about this web driver, thank you.
