### ISSUE TITLE
Change pixel ratio on Chrome (PPP, DPI, ...)

### ISSUE THREAD

**Issue by peterpan666** [laravel/dusk#414]
Hi all,

Is there a way to set the pixel ratio (PPP, DPI, or whatever you name it 😅) on Chrome?

What I want to do is take a screenshot for mobile apps.

I know I can set the dimensions with `$browser->resize(414, 736);` then I would like to set the DPI to 3 so final screenshot would be 1242 x 2208 (5.5-Inch Retina Display).

Is there anyway to do this?

**Comment by driesvints** [comment]
Not sure if that's possible. Try asking first on one of these support channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by peterpan666** [comment]
Hi Dries, thanks for the reply :)

I think the solution would come from the Facebook web driver side.

PS : Congrats on your new job!

**Comment by driesvints** [comment]
@peterpan666 thanks! :)
