### ISSUE TITLE
Local script causing Failed to load resource: net::ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by zachcoss** [laravel/dusk#416]
I'm testing a platform checkout page which itself is configured to load: https://subdomain-local.domain.com/AgeVerification.js?domain_token=testtoken (which loads fine when testing in my actual Chrome Browser), but my tests neither find the elements associated with the script load, or the actual object in the window.

These are the options I tried inside driver() in DuskTestCase, but the error logs still show _ERR_INSECURE_RESPONSE_:

      $options = (new ChromeOptions)->addArguments([
            '--disable-gpu',
            '--headless',
           '--ignore-certificate-errors',
           '--allow-insecure-localhost',
           '--ignore-urlfetcher-cert-requests',
           '--reduce-security-for-testing'
        ]);

The .log file inside Browser/console displays this error:
```
[
    {
        "level": "SEVERE",
        "message": "http:\/\/testeraccount.mybigcommerce.com\/cigars-1\/ 50:0 Uncaught ReferenceError: pageTracker is not defined",
        "source": "javascript",
        "timestamp": 1511553756354
    },
    {
        "level": "SEVERE",
        "message": "http:\/\/beaconhttp.choice.ai\/site\/ethno\/mybigcommerce687\/minewhat.js - Failed to load resource: the server responded with a status of 500 (Internal Server Error)",
        "source": "network",
        "timestamp": 1511553758283
    },
    {
        "level": "SEVERE",
        "message": "https:\/\/store-rp0dhg.mybigcommerce.com\/checkout 46:0 Uncaught ReferenceError: pageTracker is not defined",
        "source": "javascript",
        "timestamp": 1511553761269
    },
    {
        "level": "SEVERE",
        "message": "https:\/\/verify-local.bluecheck.me\/platforms\/bigcommerce\/js\/AgeVerification.js?domain_token=testtoken - Failed to load resource: net::ERR_INSECURE_RESPONSE",
        "source": "network",
        "timestamp": 1511553761291
    }
]
```

Any idea what else I can do? Should I still be getting those network errors with all those options configured?

**Comment by mpash** [comment]
I'm also getting this issue, even when using the '--disable-web-security' option.

**Comment by kamui545** [comment]
Not sure this will fix your issue but can you try with `--allow-running-insecure-content`?

Otherwise, you will probably have to wait for this PR https://github.com/laravel/dusk/pull/468 to be merged.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
