### ISSUE TITLE
[QUESTION] Program to save click and keyboard to import in dusk?

### ISSUE THREAD

**Issue by MickaelTH** [laravel/dusk#418]
Hi,

Anyone has a program that save clicks and keys in order to import in dusk? This will save some time instead of creating basic php code like click on link enter name etc.

Thanks

**Comment by anurbol** [comment]
I am sure there is no such software, I searched it too, with no success.

**Comment by kubk** [comment]
@MickaelTH how about Laravel Test Tools? 

https://laravel-news.com/laravel-testtools-dusk
