### ISSUE TITLE
[Feature Request] allow disabling of web security

### ISSUE THREAD

**Issue by fibble** [laravel/dusk#42]
I have a legacy screen scraper that needs --disable-web-security passing to the WebDriver to allow my Jquery snippets to manipulate elements in Cross Origin iframes.

I foresee dusk as a great way to test my App, but also as a way to integrate my external scraper into one codebase. Being able to specify that the Chrome instance that is instantiated disregards some brower security rules would be very useful.

**Comment by KKSzymanowski** [comment]
I think you can do this yourself by overriding the `driver` method in your `/tests/DuskTestCase.php` and passing additional options to the web driver.

**Comment by fibble** [comment]
Hi

Thanks for the pointer. Tried a few things in here and cant seem to get it
working. Dont suppose you might have an example or could suggest some
resources for further investigation?

Thanks!

**Comment by fibble** [comment]
Got it

Inside DustTestCase.php in the driver() method this works.

`$options = new ChromeOptions();
        $options->addArguments(array(
            '--window-size=571,428',
            '--disable-web-security'
        ));

        return RemoteWebDriver::create(
            'http://localhost:9515', DesiredCapabilities::chrome()->setCapability(ChromeOptions::CAPABILITY, $options)
        );`

**Comment by timleland** [comment]
@fibble Do you mind sharing how you are able to type into an iframe input?

**Comment by fibble** [comment]
Hi,

I could not work out if there was an easy way to execute arbitrary jquery/jjavascript in Dusk so i edited vendor/laravel/dusk/src/Concerns/InteractsWithElements.php and added this method:

`public function jqexec($script){
        $this->driver->executeScript($script);
        return $this;
}`

Then inside my test file (still called ExampleTest.php :) I do something like this:

`$this->browse(function ($browser) {
            $browser->visit('http://www.yoursite.com/')
                ->jqexec("window.jQuery('#signInLink').click();")
                ->jqexec("$('#sign-in-dropdown-frame').contents().find('#input-email').val('signin@email.com')")
                ->jqexec("$('#sign-in-dropdown-frame').contents().find('#input-pwd').val('pass1')")
                ->jqexec("$('#sign-in-dropdown-frame').contents().find('#button-sign-in').click()")`

**Comment by mikerogne** [comment]
Poking around in Browser class, I saw it uses Macroable trait. This article was helpful: https://medium.com/@splatEric/writing-tests-with-laravel-dusk-bb755c0dcb1f#.xzjwcvgh1
