### ISSUE TITLE
Tests not see database updates

### ISSUE THREAD

**Issue by igorfaria6** [laravel/dusk#435]
`public function testCreateBook()`
`    {`
`        $book = factory(Book::class)->make();`
`        $this->browse(function (Browser $browser) use ($book) {`
`            $browser->loginAs($this->userAdmin())`
`                ->visit(new BookCreatePage())->criarBook($book)`
`                ->assertTitleContains("EDITAR");`
`            $browser->pause(1000);`
`        });`

`        $this->assertDatabaseHas(Book::table(), $this->toUpper($book), 'firebird');`
`    }`

There was 1 failure:

1) Tests\Browser\BookCreateTest::testCreateBook
Failed asserting that a row in the table [BOOK] matches the attributes {
    "TITULO": "86F7E437FAA5A7",
    "DIRETOR": "CE15D1DDCB9EAEAEA",
    "COORDENADOR": "377667B8",
    "SUPERVISOR": "DA23614E02",
    "PERIODO": "469A0D7C7BD"
}.

The table is empty.

D:\FONTES\Php\firebird\vendor\laravel\framework\src\Illuminate\Foundation\Testing\Concerns\InteractsWithDatabase.php:22
D:\FONTES\Php\firebird\tests\Browser\BookCreateTest.php:37

FAILURES!
Tests: 1, Assertions: 3, Failures: 1.

but in database the row is inserted correctly.

i already tried `sleep(1)`, but unsuccessfully.

thanks so much!

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by Lukasz93P** [comment]
I have encountered same issue, identical.
