### ISSUE TITLE
Cannot use trait SupportsChrome in a custom Browser class to start ChromeDriver 

### ISSUE THREAD

**Issue by envision** [laravel/dusk#437]
## Versions
  - Vagrant: 2.0.1
  - Provider: Virtualbox 5.2.4
  - Homestead: 7.0.1
  - Homestead box: 5.0.1
  - Laravel: 5.5.28
  - Laravel Dusk: 2.0.8
  - ChromeDriver: 2.33.506092

## Host operating system
macOS 10.13.

## Expected behavior
Expected to be able to start ChromeDriver by using trait _SupportsChrome_ and it's function `static::startChromeDriver();`

## Actual behavior
Getting error:
```
Call to undefined method App\Browser::afterClass() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0):
Call to undefined method App\\Browser::afterClass() at /home/vagrant/app/thisproject/vendor/laravel/dusk/src/Chrome/SupportsChrome.php:38)
```
Problem seems to be in that this trait is coupled to be used only by _abstract class TestCase extends FoundationTestCase_ in namespace _Laravel\Dusk_.

## Steps to reproduce
1. Copy this custom Browser class under _app/_ : https://gist.github.com/envision/29d050894ee4bdb912ec6433b6208c5b
2. Add this route to _routes/web.php_ and trigger the route in your browser:
```
Route::get('/testing', function () {
    (new App\Browser)->browse(function ($b) {
        $b->visit('https://laracasts.com');
    });
    return 'ok';
});
```

## Additional observations

If the browse function is triggered via _artisan tinker_ rather than in a route, there is an additional error produced:

```
PHP Deprecated:  Not inheriting environment variables is deprecated since Symfony 3.3 and will always happen in 4.0. Set "Process::inheritEnvironmentVariables()" to true instead.
in /home/vagrant/app/thisproject/vendor/symfony/process/Process.php on line 310
PHP Error:  Call to undefined method App\Browser::afterClass()
in /home/vagrant/app/thisproject/vendor/laravel/dusk/src/Chrome/SupportsChrome.php on line 38
```

**Comment by driesvints** [comment]
Can you upgrade to the latest Dusk and Laravel versions and see if the problem persists?
