### ISSUE TITLE
.env file doesn't back up when stopping dusk while running.

### ISSUE THREAD

**Issue by vietlubu** [laravel/dusk#439]
When I run `php artisan dusk`. Dusk make a backup for `.env` file. And copy content from `.env.dusk.testing` or `.env.dusk.local` to base `.env`

```diff
# .env file while dusk running
APP_ENV=local
APP_KEY=base64:MFq1CpjknaMNLvatEZT2owRp2J8Z9RJtqyLKT3N3/Hk=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=192.168.33.10
DB_PORT=3306
- DB_DATABASE=homestead
+ DB_DATABASE=testing
DB_USERNAME=homestead
DB_PASSWORD=secret


BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync
```

But when I stop dusk by `ctrl+c`. `.env` file doesn't restore data from `.env.backup`. So, when I run Laravel app by browser, Laravel run with `testing` database not `homestead`

`.env.backup` and  `phpunit.dusk.xml` not be delete.
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.env.backup
	phpunit.dusk.xml
```

I think when dusk has been stopped by `ctrl+c` or terminate. Dusk need to restore `.env` file and delete `.env.backup` and `phpunit.dusk.xml` like when `php artisan dusk` complete run.

Update: In PHP CLI and Laravel `artisan` how we can handle event press `ctrl+c` on terminal?

**Comment by driesvints** [comment]
Yeah, if you stop the command mid-process then it won't get to the end of what it's trying to do. I think you could catch a signal when the command is stopped to restore the contents but that would require unnecessary dependencies for a small thing like this.

**Comment by driesvints** [comment]
Just realized this is the same issue as https://github.com/laravel/dusk/issues/483
