### ISSUE TITLE
Issues running tests on Mac/Valet

### ISSUE THREAD

**Issue by igormatkovic** [laravel/dusk#44]
While trying out Dusk it looks like its trying to launch my Chrome browser and not the Chrome driver

**Environment**
- Mac OS X
- Laravel Valet 2.0.3
- PHP 7.1.0
- Fresh install of Laravel 5.4 (current dev-master)
- Default (dusk:install) test only

**Test run**
```sh
php artisan dusk
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

E         1 / 1 (100%)

Time: 2.85 seconds, Memory: 10.00MB

There was 1 error:

1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\UnknownServerException: unknown error: Chrome version must be >= 54.0.2840.0
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.12.1 x86_64)

./vendor/facebook/webdriver/lib/Exception/WebDriverException.php:114
./vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:321
./vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:121
./tests/DuskTestCase.php:32
./vendor/laravel/dusk/src/TestCase.php:178
./vendor/laravel/framework/src/Illuminate/Support/helpers.php:639
./vendor/laravel/dusk/src/TestCase.php:179
./vendor/laravel/dusk/src/TestCase.php:109
./vendor/laravel/dusk/src/TestCase.php:83
./tests/Browser/ExampleTest.php:21
```

**Comment by spyric** [comment]
It's launching ChromeDriver. 

But ChromeDriver requires chrome. You can read more [here](https://sites.google.com/a/chromium.org/chromedriver/getting-started)

```
ChromeDriver expects you to have Chrome installed in the default location for your platform. You can also force ChromeDriver to use a custom location by setting a special capability.
```

In your case. You need to update your browser

**Comment by igormatkovic** [comment]
My chrome version is 55 ( latest version available)

**Comment by igormatkovic** [comment]
Downgraded to the specified version and still nothing. 

The Chromedriver does not want to start

Switched to Phantomjs and works flawlessly

**Comment by marcusmyers** [comment]
@igormatkovic If you used homebrew to install Chrome you could get this error.  I would remove `~/Applications/Google Chrome.app` from your home direcotry and try again.

**Comment by igormatkovic** [comment]
@marcusmoore thanks that helped debug things.

I deleted the chromedriver from brew and all related brew components.
I also deleted chrome, chrome canary from my /Applications and ~/Applications and reinstalled a fresh chrome version from desktop. 

Now it works perfectly.

thanks
