### ISSUE TITLE
Running Dusk on Homestead gives timeouts

### ISSUE THREAD

**Issue by marijnhurkens** [laravel/dusk#440]
I have a lot of problems getting Dusk to run smoothly on Homestead. I have the following testcase:

```
$bike = Bike::where('status', 'in_use')->first();

        $this->browse(function(Browser $browser) use ($bike) {
            $browser->visit('/dashboard/bike/' . $bike->id)
                ->assertSee('Status: in_use')
                ->click('.button.change-status-storage');
        });
```

After 30 seconds I get the following error message:

```
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http GET to /session/1175f14f3e491e41fcc85c5de1958baa/screenshot

Operation timed out after 30001 milliseconds with 0 bytes received
```

The following test works fine:

```
public function testBikeViewStudent() {
        $bike = Bike::with('student')->first();


        $this->browse(function(Browser $browser) use ($bike) {
            $browser->visit('/dashboard/bike/' . $bike->id)
                ->assertSee('Associated student: '. $bike->student->name .' ('.$bike->student->status.')')
                ->assertSee('Student');
        });
    }
```

So it seems the `->click()` function gives the timout. The link is just a normal link which performs a controller action which returns a redirect to a page:

```
return redirect()
            ->route('dashboard.bike.show', ['bike' => $bike])
            ->withInput()
            ->withMessage('Status updated!');
```

Running the latest Laravel, Homestead and Dusk. I tried manually starting the chromium driver but this didn't work.

Any ideas?

**Comment by vietlubu** [comment]
I think you can check this issue: #10

**Comment by jamesgraham** [comment]
We are also seeing this on a fresh VM

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by et-nik** [comment]
I see one solution -- dont use Laravel =(
