### ISSUE TITLE
Dusk tests fail when using ./vendor/bin/phpunit tests/

### ISSUE THREAD

**Issue by JordanDalton** [laravel/dusk#45]
Problem overview: phpunit and Dusk tests cannot run parallel

The scenario: `./vendor/bin/phpunit tests/` triggers all tests (including Dusk). However the Dusk specific tests fail. If I execute `php artisan dusk` they pass.

It's worth pointing out that you can run tests without Dusk by running `./vendor/bin/phpunit`

**Comment by splatEric** [comment]
II would suggest that you edit your phpunit.xml to exclude the tests/Browser folder so you only run your dusk tests with php artisan dusk
