### ISSUE TITLE
Browser::type does not accept any CSS selector, only id or input name

### ISSUE THREAD

**Issue by jarnoan** [laravel/dusk#451]
$browser->type() does not accept any CSS selector as the first argument even though the documentation at https://laravel.com/docs/5.5/dusk#using-forms in "Typing values" section implies so:

> Note that, although the method accepts one if necessary, we are not required to pass a CSS selector into the type method [...]

It does accept an element id selector or input name. Either the documentation should be changed, or ElementResolver::resolveForTyping changed to support any selector (which might break some existing tests, though).

**Comment by jarnoan** [comment]
Relates to #209

**Comment by vesper8** [comment]
I was just having a problem with this. I was trying to type inside a textarea using this code

```
$browser1->type('.chat-input textarea', $testString);
```

And was getting the very misleading message 

```
Facebook\WebDriver\Exception\InvalidElementStateException: invalid element state: Element is not currently interactable and may not be manipulated
```

After some trial and error I figured out the problem was that I had many inputs on the page which matched this selector, and I guess the fallback error when there are many selectors is to give the above error

After I made it more specific like this:

```
$browser1->type('#chat179 .chat-input textarea', $testString);
```

Then it works just fine.. so to confirm.. the type() method DOES accept CSS selectors

**Comment by jarnoan** [comment]
Ok, it accepts CSS selectors as long as they start with an id selector. I still think the documentation should be clarified, or the behavior changed to not require an id selector in the beginning.

**Comment by staudenmeir** [comment]
It does accept any CSS selector.

@vesper8's first selector didn't work because Dusk uses the first match it finds and in this case that textarea was disabled, hence the error message. So he just had to use a more specific selector.

**Comment by jarnoan** [comment]
Am I missing something? [InteractsWithElements::type](https://github.com/laravel/dusk/blob/3.0/src/Concerns/InteractsWithElements.php#L142) calls [ElementResolver::resolveForTyping](https://github.com/laravel/dusk/blob/3.0/src/ElementResolver.php#L81), which first tries [ElementResolver::findById](https://github.com/laravel/dusk/blob/3.0/src/ElementResolver.php#L278), which checks whether the parameter matches /^#[\w\-:]+$/ , i.e. is a proper element id. In that case it calls WebDriverBy::id, otherwise it returns nothing. If ElementResolver::findById didn't find an element, [ElementResolver::resolveForTyping](https://github.com/laravel/dusk/blob/3.0/src/ElementResolver.php#L88) tries to find an input or textarea with the parameter as a name. I don't see how it would work with anything else than an element ID or input name.

**Comment by staudenmeir** [comment]
It's easy to miss. `ElementResolver::resolveForTyping()` first tries to use the parameter as a CSS selector and then as an input/textarea name:

    return $this->firstOrFail([
        $field, "input[name='{$field}']", "textarea[name='{$field}']"
    ]);

**Comment by jarnoan** [comment]
You are right, I totally missed that. Now I wonder what was wrong in my code in the first place... I'm sorry for wasting your time. Closing.
