### ISSUE TITLE
can I mock the geolocation request that my app makes?

### ISSUE THREAD

**Issue by vesper8** [laravel/dusk#459]
the first barrier to entry on my new app is that you must share your location.. right now the little popup where you can block or approve doesn't show up in my dusk screenshots.. can I still press "Allow" even though I don't see the box?

otherwise what is the best way to mock this?

**Comment by staudenmeir** [comment]
I don't think you can access this kind of dialogs.

You could mock `window.navigator.gelocation`: https://stackoverflow.com/a/9996658

Or create a custom Chrome profile that grants your website the geolocation permission.

**Comment by driesvints** [comment]
Try @staudenmeir's solution.
