### ISSUE TITLE
Alert caused by asynchronous requests makes next test fail

### ISSUE THREAD

**Issue by Teerr** [laravel/dusk#460]
Hi, I might have found a bug. I have got following test:

```php
public function testButtonCreateArticle()
{
        $flag = factory(Flag::class)->create();

        $this->browse(function (Browser $browser) use ($flag) {
            $browser->login()
                ->visit(route('articles.index', $flag->url))
                ->clickLink('Create', '.create-button')
                ->assertUrlIs(route('admin.articles.create', $flag->url));
        });
}
```

and `tearDown` method, which deletes all the flags after each test:

```php
public function tearDown()
{
        parent::tearDown();
        Flag::getQuery()->delete();
}
```

Test that is running after `testButtonCreateArticle` fails, because the testing page loads some resources associated with flag via AJAX. When the visit method is called, the flag still exist, but when the AJAX request is fired, it returns 404 because the flag does not exist.

**EDIT:** After little bit more testing I found out, what causes the problem. Step by step:
1. `testButtonCreateArticle` creates flag and visits the page.
2. On the page is requested resource associated with flag.
3. Before the resource is loaded, test is done.
4. `tearDown` method is called.
5. Next test `testCreateArticle` starts.
6. Loading resource via AJAX from the first test fails, because flag does not exist anymore. Page return 404, so alert pops up.
7. Test `testCreateArticle` fails, because of the error `Facebook\WebDriver\Exception\UnexpectedAlertOpenException`

**SOLUTION:** I figured out, that adding `$this->closeAll()` to `tearDown` method solves the problem. But is it correct solution?

**Comment by staudenmeir** [comment]
If I understand your problem correctly, you could solve it by waiting for the AJAX request(s) to finish before the test ends.

If you use jQuery: `$browser->waitUntil('!$.active');`

**Comment by Teerr** [comment]
Yes, this solves the problem. But still, it's not really obvious. Maybe something like that should be made automatically by dusk, because not every body knows that omitting `->waitUntil('!$.active')` can cause unexpected behaviour and influence other tests.
