### ISSUE TITLE
Changing the directory of [screenshots, console]

### ISSUE THREAD

**Issue by andrewmclagan** [laravel/dusk#466]
I cant determine a method (seems like its been hardcoded) to change the directories for storing screenshots and console output.

Anyone aware of this limitation?

**Comment by staudenmeir** [comment]
https://github.com/laravel/dusk/issues/393

**Comment by envision** [comment]
https://github.com/laravel/dusk/pull/36

**Comment by driesvints** [comment]
Duplicate of #393
