### ISSUE TITLE
Fails to type into field when its name is part of another

### ISSUE THREAD

**Issue by barnabaskecskes** [laravel/dusk#473]
Consider the following form: 
```
<input name="phone_number">
<input name="phone_number_2">
```
and the following test:
```
$browser
    ->type('phone_number', 123456789)
    ->type('phone_number_2', 123456789);
```

Dusk fails to fill the first field. (I assume it maybe matches _both_ fields and can't type into an array, or something along those lines.)

If `phone_number` is changed to `phone_number_1`, it works as expected.

**Comment by staudenmeir** [comment]
It works for me.

How does it fail? Is there an error or is the input just empty?
Are there any other elements with the name/id `phone_number`?

**Comment by barnabaskecskes** [comment]
@staudenmeir I'm checking it on a new project trying to see if I can replicate.

**Comment by barnabaskecskes** [comment]
@staudenmeir Hmmm, it seems I was just being dumb, sorry. :) There is a search field with the same name in the header of the page and that's what Dusk was filling out. Thanks for the pointers!
