### ISSUE TITLE
Proposal: Artisan alert (when env.backup is around) and restore .env command

### ISSUE THREAD

**Issue by drakakisgeo** [laravel/dusk#483]
I think it would be great to have an alert in the shell  each time an artisan command is executed that checks if env.backup is around. In most cases -and if you are not currently running any dusk test- your .env file needs to be restored from the .env.backup file.

I know that there is #155 about this, but this actually means that you need to re-run dusk at least once to restore your .env file.

Maybe an alert in the console and possibly a command like "artisan dusk:restore_env" could make things much easier.

**Comment by driesvints** [comment]
Isn't this done already? The backup file is always restored, no?

**Comment by rovansteen** [comment]
@driesvints not if you cancel the command for example

**Comment by drakakisgeo** [comment]
Exactly @rovansteen . That's the problem.

**Comment by driesvints** [comment]
Okay. I found some time to look into this. Unfortunately there's no way to restore the backup file when you terminate the command yourself. Tried using the `pcntl_signal` function and looked into Symfony events but no dice.

Throwing a warning when running any Artisan command is a bit overkill imo. Plus it would couple Artisan to a specific use case for Dusk which isn't wanted.

I'm afraid there really isn't a good solution for this. If anyone can come up with a way to solve this then feel free to share but unfortunately at the moment there isn't a good way to do it as far as I can see.

**Comment by sweet-greg** [comment]
Wouldn't it already help if artisan:dusk stops executinig if it detects a env.backup file already exists?
What we experience often times is that we lose our env.backup because we terminate the process, forget to manually restore it, run it again... Just a thought
