### ISSUE TITLE
dusk so slow in Chrome 65

### ISSUE THREAD

**Issue by adrianriyadi** [laravel/dusk#485]
I'm using Laravel Dusk 2.0.14 for Laravel 5.5 with phpunit 6.5.7.
After Chrome updated to latest version 65, php artisan dusk will run dusk with so slow performance (can take up to 10 minutes) and sometimes failed (supposed to be success) compared to Chrome 64 (great performance, under 2 minutes without single weird fail). Is this a bug or there's a way to fix it?

**Comment by staudenmeir** [comment]
Do you use the latest ChromeDriver 2.36?

**Comment by adrianriyadi** [comment]
@staudenmeir I guess not. How can I check my ChromeDriver version and how to upgrade it? I try via npm install but it just doesn't work.

**Comment by carltondickson** [comment]
Try this to check what version of chrome driver your dusk is using
```
./vendor/laravel/dusk/bin/chromedriver-linux --version
./vendor/laravel/dusk/bin/chromedriver-mac --version
```
I'm also finding that some tests that worked are no longer working with Chrome 65 and Dusk 2.0.14...mainly with iframes.

**Comment by staudenmeir** [comment]
You can download the latest version here:
https://chromedriver.storage.googleapis.com/index.html?path=2.36/

The files are located here: `vendor/laravel/dusk/bin`

**Comment by browner12** [comment]
Are you running this on Homestead by chance?

**Comment by rafalglowacz** [comment]
Same issue here. When I do this in  a Dusk test:

```php
	$time = microtime(TRUE);
	$this->browse(function($browser) {
		dd(microtime(TRUE) - $time);
```

I get 12-13 seconds. 

I tried the driver version 2.36 - I put it in `vendor/laravel/dusk/bin`. Unfortunately that didn't change anything.

**Comment by adrianriyadi** [comment]
@browner12 no. I'm using valet on Linux which has no problem with Chrome 64 before. But I'll try some advice from @staudenmeir and thanks a lot for all of you guys :) @carltondickson

**Comment by adrianriyadi** [comment]
by the way, is there an option for make vendor chromedriver always pull latest version when I run `composer install` command?

**Comment by adrianriyadi** [comment]
UPDATE: Still doesn't work with updated ChromeDriver to 2.36, instead I upgrade my Laravel version to 5.6.11. It got normal but with ChromeDriver 2.36 it much faster.

**Comment by curtjenk** [comment]
If I manually start the chromedriver (./vendor/laravel/dusk/bin/chromedriver-linux) , the test speed returns to normal.  Running Laravel 5.5.39, dusk 2.0.14, phpunit 6.5.7,  PHP 7.0.25-0ubuntu0.16.04.1 with Xdebug 2.4.0

**Comment by javfres** [comment]
I have the same problem using Chrome 66, the driver 2.38, and dusk 2.0.14. But starting the chromedriver manually as @curtjenk suggested works for me

**Comment by driesvints** [comment]
Can you all upgrade to the latest Dusk and Laravel versions and check if the problem persists?

**Comment by khalilst** [comment]
@curtjenk 
I've tried both auto-start and manual start for chromedriver, but the speed was same for both.
