### ISSUE TITLE
Cannot update dusk w/ new chromedriver in Laravel 5.4 app

### ISSUE THREAD

**Issue by JesseLeite** [laravel/dusk#490]
I realize we're behind on Laravel 5.4, but we cannot update laravel/dusk in our app any more without illuminate/console constraint error.  I -think- we just need updated chromedriver, nothing new in the code itself?

I've heard talks of an artisan command to update dusk's chromedriver, regardless of laravel version or dusk version.  Thoughts?

PS. Not complaining.  Maybe this will push us to finally upgrade to 5.6 🙈

**Comment by staudenmeir** [comment]
What's the error message?

**Comment by JesseLeite** [comment]
I've done that already, but should users have to manually mess with vendor files?

**Comment by staudenmeir** [comment]
Only if they use unsupported Laravel versions ;-) Does it work?

**Comment by JesseLeite** [comment]
Yezzir.

**Comment by staudenmeir** [comment]
I created an Artisan command for updating the ChromeDriver binaries on all Dusk versions: https://github.com/staudenmeir/dusk-updater

**Comment by driesvints** [comment]
Heya, really sorry about this but unfortunately we cannot provide support for Laravel 5.4 anymore. Please try upgrading or the solution proposed by @staudenmeir.

**Comment by ryancwalsh** [comment]
@staudenmeir What a great idea! Thanks.
