### ISSUE TITLE
Unable to locate service manifest for metrics

### ISSUE THREAD

**Issue by sumanta-ghosh** [laravel/dusk#491]
![image](https://user-images.githubusercontent.com/2699051/37545961-c99b57e0-2990-11e8-9423-3f90946d1241.png)

OS: Win 8.1
PHP: 7.1.15
Laravel: 5.6
Chrome: Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by staudenmeir** [comment]
What version of Dusk are you using?

Can you post the screenshot from `tests/Browser/screenshots`?

**Comment by sumanta-ghosh** [comment]
I miss the APP_URL setting in .env file. By default it was http://localhost but for me it is http://localhost/dusk-test/public , after set the correct APP_URL it's working fine. 
Thanks @staudenmeir
