### ISSUE TITLE
Dusk neither using correct .env file nor running database migration.

### ISSUE THREAD

**Issue by amirpiri** [laravel/dusk#493]
I am using Laravel Dusk for browser testing and of course add `use DatabaseMigrations;` in test file. But not only my database is not migrated, but also Dusk using the old .env file.
I have to mention that I am running Laravel in my docker container and all files permissions is set to 777.

**Comment by staudenmeir** [comment]
Please post your `.env.dusk.*` file and the `connections` array in your `config/database.php` file.

**Comment by splatEric** [comment]
@amirpiri did you have any luck resolving this problem, I am having a similar issue

**Comment by essteffan** [comment]
APP_NAME="dada"
APP_VERSION="1.0"
APP_ENV=testing
APP_KEY=base64:+3h/labdosk9vSmoak9hHEhhVqHc07ArriJdyhKsBjU=
APP_DEBUG=true

APP_URL=http://localhost:8000

DB_CONNECTION=dusk_testing

Database.php 


        'dusk_testing' => [
            'driver' => 'sqlite',
            'database' => database_path('testing.sqlite'),
            'prefix' => '',
        ],


The test passes but i don't see any migration.

Why is that?

Thanks

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
