### ISSUE TITLE
Dusk not working with factories and/or migrations in Homestead

### ISSUE THREAD

**Issue by Chesdrik5** [laravel/dusk#495]
Using a fresh install of Laravel and dusk, then copying the exact test from the docs for logging in the user, I get an error that the users table doesn't exist.

I don't get any error when using a factory to create a user, but when trying to login as that user, i can see the browser window opening (screenshoots), typing in the creds, then seeing the error that user can't be found.

I see that Dusk tests never ran the migrations.

I change my config/database.php and .env.dusk.local

// config/database.php

'connections' => [
    'testing' => [
        'driver' => 'sqlite',
        'database' => database_path('testing.sqlite'),
        'prefix' => '',
    ],
],

`// .env.dusk.local

APP_URL=http://project.dev
APP_ENV=testing
DB_CONNECTION=testing`

and ran composer update but the error persist :(

**Comment by browner12** [comment]
Welcome to Laravel! We are glad to have you as part of the community.

Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!
