### ISSUE TITLE
Page classes created using dusk:page command extend the wrong base class

### ISSUE THREAD

**Issue by dweingart** [laravel/dusk#496]
The initial HomePage example page created by dusk:install extends \Tests\Browser\Pages\Page but any subsequent Page classes created by dusk:page extend \Laravel\Dusk\Page.

This means that any custom shortcuts defined in \Tests\Browser\Pages\Page::siteElements() aren't available to tests.

Console/stubs/page.stub should be updated to extend from the correct class.

**Comment by driesvints** [comment]
Should be fixed now 👍
