### ISSUE TITLE
Please provide release notes

### ISSUE THREAD

**Issue by hackel** [laravel/dusk#498]
The CHANGELOG hasn't been updated since v1.0.13 a year ago.  Please provide release notes, *particularly* when releasing a major version like 3.0.  Does this exist somewhere that I am missing?  I've also checked the Laravel documentation and can't find anything.

Obviously it's important to know what has changed and if there are any backward-incompatible changes when upgrading from 2.x to 3.x.  If nothing has changed and it is 100% backward compatible, that should be specified as well.  (Although that would be very confusing with the major version change.)

Thank you

**Comment by carltondickson** [comment]
@hackel This would be useful.

I'm also looking for what may break following an upgrade to v3

I think these are the differences between branches
61 commits in 3.0 not in 2.0 - https://github.com/laravel/dusk/compare/2.0...3.0
4 commits in 2.0 not in 3.0 - https://github.com/laravel/dusk/compare/3.0...2.0 (Think this is just an upgrade to the chrome driver)

**Comment by tillkruss** [comment]
How do you feel about maintaining it?

**Comment by deleugpn** [comment]
I actually started the changelog for Dusk, but the fact that the PRs doesn't have versioning like the Framework is a bummer.

**Comment by tillkruss** [comment]
Dusk has tags and releases: https://github.com/laravel/dusk/releases

**Comment by driesvints** [comment]
We're accepting PRs for this.
