### ISSUE TITLE
Issues running tests on Mac/Laradock

### ISSUE THREAD

**Issue by dontinhqt** [laravel/dusk#501]
Initially, I ran into errors

`Failed to connect to localhost port 9515: Connection refused`

then I run some commands like here
https://github.com/laravel/dusk/issues/50#issuecomment-275155974
and change some information
.env
APP_URL=http://saigon.me:9515
tests/DuskTestCase.php ->driver()
```
return RemoteWebDriver::create(
            'http://saigon.me:9515', DesiredCapabilities::chrome()
        );
```
**Test Run**

php artisan dusk
PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 2.52 minutes, Memory: 12.00MB

There was 1 error:

1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"chrome","platform":"ANY"}}

Operation timed out after 30001 milliseconds with 0 bytes received

/var/www/haha/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:286
/var/www/haha/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:126
/var/www/haha/tests/DuskTestCase.php:38
/var/www/haha/vendor/laravel/dusk/src/TestCase.php:209
/var/www/haha/vendor/laravel/framework/src/Illuminate/Support/helpers.php:706
/var/www/haha/vendor/laravel/dusk/src/TestCase.php:210
/var/www/haha/vendor/laravel/dusk/src/TestCase.php:116
/var/www/haha/vendor/laravel/dusk/src/TestCase.php:88
/var/www/haha/tests/Browser/ExampleTest.php:21

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.

**Comment by claytonrcarter** [comment]
You shouldn't need to change your `.env` at all. When Chrome is started, it listens for commands on port 9515. The `connection refused` error is most likely that Chrome didn't start at all.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
