### ISSUE TITLE
Problems with clickLink() and assertSeeLink()

### ISSUE THREAD

**Issue by staudenmeir** [laravel/dusk#509]
`clickLink()` and `assertSeeLink()` both have (different) problems with special characters.

Having a link like `<a>)'</a>`, `clickLink()` fails on the parenthesis and `assertSeeLink()` fails on the quote:

    $browser->clickLink(")");
    $browser->assertSeeLink("'");

Is there a way we can get this to work with all possible texts?

If `clickLink()` wouldn't support other elements besides `<a>`, we could remove jQuery and wouldn't have to worry about special characters:

    $browser->driver->findElement(WebDriverBy::partialLinkText($text));

A jQuery-less alternative with support for other elements is XPath:

    $browser->driver->findElement(WebDriverBy::xpath("//a[contains(text(), '{$text}')]"))->click();

We would still have to take care of quotes but it would be easier than with jQuery.

**Comment by SlothAphrodite** [comment]
clickLink () = is usually used for html code a href.
while Assert shows that on the page you entered there is the same word as your assert.

if your html code is a button then use the press while if <a href use clickLink (). assert is only used for confirmation

**Comment by driesvints** [comment]
You'll have to escape the characters.

```php
$browser->clickLink("\)");
```
