### ISSUE TITLE
ErrorException while using assertPresent()

### ISSUE THREAD

**Issue by Akhileshvk** [laravel/dusk#510]
Hi,

I am pretty new to dusk and thanks for this awesome tool.

I am getting 
`ErrorException: count(): Parameter must be an array or an object that implements Countable`

from 
` $browser->assertPresent('#resetOrder');`

**Comment by staudenmeir** [comment]
Which PHP and Dusk versions are you using?

Am 26. April 2018 19:43:37 schrieb Akhilesh VK <notifications@github.com>:
Hi,
I am pretty new to dusk and thanks for this awesome tool.
I am getting
ErrorException: count(): Parameter must be an array or an object that 
implements Countable
from
$browser->assertPresent('#resetOrder');
