### ISSUE TITLE
How to click on the Li element？

### ISSUE THREAD

**Issue by esolo0121** [laravel/dusk#516]
`<ul class="ui-nav" id="J-loginMethod-tabs">
                <li class="active" data-status="show_qr">扫码登录</li>
                <li class="" data-status="show_login">账密登录</li>
                 <br class="clear-float">
</ul>`

> <ul class="ui-nav" id="J-loginMethod-tabs">
                <li class="active" data-status="show_qr">扫码登录</li>
                <li class="" data-status="show_login">账密登录</li>
                 <br class="clear-float">
</ul>

I want to simulate the click of "account density login", but try jQuery selector can not be realized.
expect a reply

**Comment by staudenmeir** [comment]
"expect a reply" is not a very polite way to ask for help.

Which one is "account density login"?
What did you try?

**Comment by esolo0121** [comment]
Looking forward to everyone's help
Sorry, I can only speak a little English, which is translated by Google.

The following are the target sites
https://auth.alipay.com/login/index.htm

Finally, I want to realize the analog login and grab the data.

The following is the way I try：

$browse->press('#J-loginMethod-tabs > li:eq(1)');
$browse->click('#J-loginMethod-tabs > li:eq(1)');

**Comment by staudenmeir** [comment]
Use this:

    $browser->click('#J-loginMethod-tabs li[data-status="show_login"]');

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
