### ISSUE TITLE
Dusk does not work out of the box

### ISSUE THREAD

**Issue by rickshawhobo** [laravel/dusk#518]
Following the installation instructions I cannot get dusk to work out of the box

OS: MacOS 10.13
PHP 7.1.7
Laravel v5.6.22
laravel/dusk v3.0.8
facebook/webdriver: 1.6.0

Steps to reproduce

- laravel new dusk-test
- cd dusk-test
- composer require --dev laravel/dusk
- php artisan dusk:install
- php artisan serve --port=9515 &
- php artisan dusk

Observe this error

1) Tests\Browser\ExampleTest::testBasicExample
TypeError: Argument 1 passed to Facebook\WebDriver\Remote\DesiredCapabilities::__construct() must be of the type array, null given, called in /Users/dev/Code/dusk-test/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php on line 127

**Comment by staudenmeir** [comment]
Did you try `php artisan serve` without a port?

Does the website work in a browser?

**Comment by rickshawhobo** [comment]
I got it working. This was a misunderstanding on what port 9515 is.

The key is this
- sudo php artisan serve --port=80

Instead of what I posted above. For some reason I had to do sudo
