### ISSUE TITLE
Dusk multi select.

### ISSUE THREAD

**Issue by Akhileshvk** [laravel/dusk#519]
Hi, 
I did this workaround for select multiple and the values are passed as an array. I don't know if there is an easy way other than this.

   ```
 public function select($field, $value = null)
    {
        $select = new WebDriverSelect($this->resolver->resolveForSelection($field));
        $select->deselectAll();
        $options = $select->getOptions();
        if ($select->isMultiple() && is_array($value)) {
            foreach ($options as $option) {
                if ( in_array($option->getAttribute('value'),  $value) ) {
                    $option->click();
                }
            }
        } else if (is_null($value)) {
            $options[array_rand($options)]->click();
        }  else {
            foreach ($options as $option) {
                if ((string) $option->getAttribute('value') === (string) $value) {
                    $option->click();
                    break;
                }
            }
        }

        return $this;
    }
```

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
