### ISSUE TITLE
Use outside of Laravel

### ISSUE THREAD

**Issue by bruno-barros** [laravel/dusk#52]
Is possible to use Dusk outsite of a Laravel project?

**Comment by akalongman** [comment]
Yes, but with some hacks

**Comment by acacha** [comment]
You can use a Laravel project to test other projects (that can be no Laravel projects). See https://laravel-news.com/automatically-making-monthly-payments-with-dusk

**Comment by unglud** [comment]
Or use this package https://github.com/unglud/dusker

**Comment by bruno-barros** [comment]
Wow man. Nice!

**Comment by driesvints** [comment]
Unfortunately Dusk is meant to be used in combination with the Laravel framework. We have no plans on offering support outside Laravel.
