### ISSUE TITLE
Leave Chrome open on failed assertion?

### ISSUE THREAD

**Issue by InstanceOfMichael** [laravel/dusk#524]
Of course we don't want this by default, but when writing or debugging specific tests, but it would be very useful to have the ability to leave the browser window open on a failed assertion or unexpected exception. After the test has failed, it's often important to inspect around to see what actually happened or to inspect logs.

example syntax:
```
php artisan dusk --leave-browser-open tests/Browser/SalamiTest.php
```

Adding `->pause(60000)` is really obtuse. The milliseconds picked could be too short. If you pick too long, you have to `ctrl-C` manually, causing your test to skip the teardown. It would be nicer if the window could stay open, then closing the window would trigger the teardown.

**Comment by staudenmeir** [comment]
How would you inspect the browser when it's running in headless mode?

**Comment by InstanceOfMichael** [comment]
Turn off headless mode?

**Comment by staudenmeir** [comment]
I don't think a lot of people need such a feature.

In most cases, the screenshot is probably enough to find the problem.
Or you can just use a debugger and set a breakpoint.

I'm also not sure whether it's even possible to trigger the teardown when the browser window is closed.

**Comment by driesvints** [comment]
You should already have your console output and screenshots to debug. I don't believe something like the above is wanted tbh.
