### ISSUE TITLE
Pseudo-classes with the dusk `@` selector aren't formatted properly

### ISSUE THREAD

**Issue by jgill-inhouse** [laravel/dusk#526]
Because of the way that https://github.com/laravel/dusk/blob/3.0/src/ElementResolver.php#L390 formats selectors, the `@` dusk selector doesn't allow for the use of pseudo-classes.

##### Current behavior: 
```
$resolver->format('@test-dusk-selector:first-of-type') == '[dusk="test-dusk-selector:first-of-type"]'
```

##### Expected behavior:
```
$resolver->format('@test-dusk-selector:first-of-type') == '[dusk="test-dusk-selector"]:first-of-type'
```

This isn't a huge deal because I can just do
`$browser->click('[dusk="..."]:first-of-type')` but it's definitely more cumbersome than just `@`.

I forked the repo and made a fix for it here https://github.com/laravel/dusk/compare/2.0...inhousemarketing:53c3533?expand=1

If it's an issue that you are interested in merging in, I will submit a PR. Otherwise I'm just using my fork.

**Comment by driesvints** [comment]
Hey @jgill-inhouse I don't see the fix anymore. Is this still a problem?
