### ISSUE TITLE
Take screenshot when UnexpectedAlertOpenException is thrown

### ISSUE THREAD

**Issue by jeremy-smith-maco** [laravel/dusk#529]
Currently it tells you that there is an unexpected alert open with the text but in my case it says the text is blank and I am not sure why it is open. A screenshot would more than likely help to clarify the reason as I run it in headless most of the time.

**Comment by staudenmeir** [comment]
Hard to say why the alert is open. Can you post the test's code?

Screenshots can only capture the rendered HTML, but not alerts.

**Comment by jeremy-smith-maco** [comment]
I figured out why it was open, it would have just been much easier to figure it out of there was a screenshot. I didn't know it could only capture the HTML and not the alert. If it's not possible to do so then you can probably just close this. Would just be helpful.
