### ISSUE TITLE
unrecognized option --env

### ISSUE THREAD

**Issue by zgosalvez** [laravel/dusk#53]
- Laravel Version: 5.5.0
- PHP Version: 7.1.0
- Database Driver & Version: N/A

### Description:
Setting the environment when running `php artisan dusk --env=testing` throws `unrecognized option --env`. However, when running `php artisan dusk -h`, it includes the following option `--env[=ENV]       The environment the command should run under`. Probably a conflict with PHPUnit?

### Steps To Reproduce:

1. Setup Laravel
2. Setup Dusk
3. Create .env.dusk.testing
4. Run `php artisan dusk --env=testing`

### Workaround
Run `APP_ENV=testing php artisan dusk`. **N.B.** For some reason, the Dusk will pick up `.env.dusk.testing`, but you'll have to set `APP_ENV=testing` in `.env.dusk.testing`, else the app will assume it's running in the production environment.

**Comment by splatEric** [comment]
The initial environment settings are driven by the contents of the `.env` file. 

If `.env` is not present, it defaults to production.

I think your env option is being picked up by artisan, but the call to phpunit that the DuskCommand makes passes the arguments through to phpunit ... I wonder if there would be any benefit to stripping out options that artisan can consume?

**Comment by mstnorris** [comment]
This doesn't work for me

**Comment by melihovv** [comment]
`unrecognized option --env` it is from phpunit

You can extend DuskCommand and override arguments, which are passed to phpunit.
```php
class DuskCommand extends \Laravel\Dusk\Console\DuskCommand
{
    protected function phpunitArguments($options)
    {
        $arguments = parent::phpunitArguments($options);

        for ($i = 0, $count = count($arguments); $i < $count; ++$i) {
            if (Str::startsWith($arguments[$i], '--env')) {
                unset($arguments[$i]);
            }
        }

        return $arguments;
    }
}
```

**Comment by deleugpn** [comment]
Any value you set as your `APP_ENV` in your `.env` will be used to load a `.env.dusk.{YOUR_ENV}`. You can combine Dusk with Serve:

```
php artisan serve --env=dusk.local &
php artisan dusk
```

PHP Internal Server will provide you an application with `.env.dusk.local` file and if you set `.env`'s APP_ENV to `local`, when running dusk it will default to the same `.env.dusk.local`.

**Comment by sgitkene** [comment]
sorry to necro such an old issue, but:

```
C:\x\x\PhpstormProjects\x>php artisan dusk --help
Usage:
  dusk [options]

Options:
      --without-tty     Disable output to TTY
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --env[=ENV]       The environment the command should run under   <---- 
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Run the Dusk tests for the application

C:\Users\sgitkene\PhpstormProjects\IP34-17vt_Leseportal>
```

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
