### ISSUE TITLE
creating a user and logging in with the DatabaseMigrations trait

### ISSUE THREAD

**Issue by alexkb** [laravel/dusk#531]
Despite a lot of other users having issues with the initial setup of dusk, I've managed to get dusk running using `php artisan serve --quiet &` (http://localhost:8000) and then running `php artisan dusk`. The example Browser test works fine (after changing the `->assertSee('Laravel');` to my site title of course).

However, as per the docs - when I move onto creating a LoginTest example, using the `DatabaseMigrations` trait, create a user and attempt to login, the authentication never finds the user. When i do a `->dump()`, I see the message *"These credentials do not match our records."*. If I try do a query on the database (to dump the users table contents to confirm its being created) during the test, when I run the tests it just sits there and never completes.

I tried what's in the documentation:

    $user = factory(User::class)->create([
        'email' => 'taylor@laravel.com',
    ]);

    $this->browse(function ($browser) use ($user) {
        $browser->visit('/login')
            ->type('email', $user->email)
            ->type('password', 'secret')
            ->press('Login')
            ->dump();
    });
~~and thought that that wouldn't work, due to the password not matching.~~ It should work because the `database/factories/UserFactory.php` class that comes with laravel, set's this password if you don't pass it to `$user = factory(User::class)->create(`. 

If I open up the sqlite database, I can see the taylor user there, so it looks like it's getting created ok.

**Comment by staudenmeir** [comment]
Are you using a `.env.dusk.local` file?

**Comment by alexkb** [comment]
@staudenmeir yes. My non-dusk setup uses MySQL and Dusk uses sqlite, which is being written to when I run dusk, as mentioned above.

**Comment by staudenmeir** [comment]
Please post the SQLite connection from `config/database.php`.

**Comment by alexkb** [comment]
Thanks @staudenmeir.

My config/database.php:

    ....
    'connections' => [
        'sqlite' => [
            'driver' => 'sqlite',
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
        ],
    ....

My .env.dusk.local:

    APP_URL=http://localhost:8000
    DB_CONNECTION=sqlite
    APP_DEBUG=TRUE
    CACHE_DRIVER=array
    SESSION_DRIVER=array
    DB_DATABASE=./database/portal.sqlite
    DEBUGBAR_ENABLED=false

And the sqlite file:

    root@240ba91d54e3:/var/www# ls -la database/portal.sqlite
    -rwxr-xr-x 1 root root 12288 Jul 11 08:13 database/portal.sqlite

**Comment by staudenmeir** [comment]
That's a known problem with `.env` vaues (can't find the issue right now).

Replace `env('DB_DATABASE', database_path('database.sqlite'))` with `database_path('portal.sqlite')`.
Do you use the SQLite connection anywhere else?

**Comment by alexkb** [comment]
> Do you use the SQLite connection anywhere else?

No.

> Replace env('DB_DATABASE', database_path('database.sqlite')) with database_path('portal.sqlite').

The sqlite database is being written to, so why would changing `config/database.php` not to use the env value help things?

**Comment by staudenmeir** [comment]
Which database does your login page's controller use?

**Comment by alchermd** [comment]
@alexkb I'm experiencing a similar issue. Have you found a solution yet?

**Comment by alexkb** [comment]
@staudenmeir the login controllers are the default ones that came with laravel - there's been no customization to those.

@alchermd no luck yet, but I haven't had time to try it again. Just making do with HTTP tests for now. I will try again at some point. Good to know I'm not the only one having issues. 

FYI - I've re-written the OP above, as I recently realised the UserFactory sets the password correctly, so there's no need to explicitly set it to 'secret'.

**Comment by staudenmeir** [comment]
Please put `dd(config('database.default'))` in one of your controllers and visit the page with Dusk. Does it correctly use the `sqlite` connection?

**Comment by alchermd** [comment]
@alexkb maybe it's worth trying since I got mine to work now:

1. Create a sqlite file for testing ex: `database/dusk.sqlite`
2. Create a `.env.dusk.local` file and customize as needed, obviously using the db from step 1.
3. Specify the environment when running the web server with `php artisan serve --env=dusk.local`
4. Same concept as step 3 when running dusk `php artisan dusk --env=dusk.local`

This is the only path that consistently worked for me. Other workarounds either consumes (i.e re-migrates and deletes) my main database or produce the same error as your OP. Hope it helps!

**Comment by staudenmeir** [comment]
Custom `.env.dusk` files don't work with `php artisan serve`: https://github.com/laravel/dusk/issues/162

**Comment by alchermd** [comment]
@staudenmeir errrr, my tests fail (same errors as the OP) when I run `php artisan serve` without the `--env=dusk.local`. So I guess custom Dusk env files do work?

**Comment by staudenmeir** [comment]
Did you check [`dd(config('database.default'))`](https://github.com/laravel/dusk/issues/531#issuecomment-411953141)?

**Comment by alchermd** [comment]
When using `php artisan env --port=8001 --env=dusk.local`, I get "dusk" which is the custom `DB_CONNECTION` in my `.env.dusk.local` file.

When using `php artisan env --port=8001`, I get "pgsql" which is what's inside the `.env` file.

**Comment by staudenmeir** [comment]
This is a great solution, can you post it in #162?

**Comment by alchermd** [comment]
@staudenmeir sure thing

**Comment by driesvints** [comment]
Gonna close this as this seems to be resolved. Thanks guys.

**Comment by biniyam17** [comment]
Wow, this is great. Thank you @alchermd  for the suggestion.  Using php artisan serve --env=dusk.local fixed my issue of using the correct testing database in my test class but not using the test database when hitting the browser via dusk but since now I am forcing the env to be the dusk local it will use the testing database for the browser as well.

**Comment by AntoscencoVladimir** [comment]
Guys if you force the **--env=dusk.local** that's not how it should work, in docs written that it should backup current **.env** file, rename the **env.dusk.{env}** to **.env** and use it. But unfortunately it not do that. Once you run **php artisan dusk** it use the current **.env** file for DB connection for ex. ....
