### ISSUE TITLE
Front-end (Vue.js, Nuxt.js) Code Coverage?

### ISSUE THREAD

**Issue by InstanceOfMichael** [laravel/dusk#541]
Is it possible to get code coverage of front-end JS code from Dusk? The other issues I've seen only discuss coverage of PHP code. I'm using Vue.js and Nuxt.js if that's relevant.

**Comment by clovenlife** [comment]
Definitely would be nice. I am curious how that would work with multiple sessions through xdebug.

**Comment by driesvints** [comment]
Can you provide some detailed info on how this would work and what the benefits are?

**Comment by InstanceOfMichael** [comment]
A lot of companies are interested in holding strict policies like "we have 100% code coverage" (maybe not always 100%) and it would be nice to be able to measure what is covered by our dusk tests. Here's an example of somebody doing it with other tooling: https://medium.com/@the1mills/front-end-javascript-test-coverage-with-istanbul-selenium-4b2be44e3e98

**Comment by driesvints** [comment]
Well. I have no idea how this would even be implemented. I'll flag this as a feature request for now.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/dusk/issues/258
