### ISSUE TITLE
dusk timestamps

### ISSUE THREAD

**Issue by An-AngryBear** [laravel/dusk#545]
I'm going through a repo that uses Dusk, and I found these timestamps after every test.

Anyone have any idea where they are coming from or how to disable?

![image](https://user-images.githubusercontent.com/25972741/43974407-1a4f1d5c-9ca0-11e8-8a01-7ea86ee2fffc.png)

**Comment by deleugpn** [comment]
These looks like access logs from your web server.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
