### ISSUE TITLE
Is it possible for Dusk to accept a flag that runs it in non-headless mode?

### ISSUE THREAD

**Issue by alchermd** [laravel/dusk#547]
Hello!

For presentations and general debugging, I sometimes run Dusk in non-headless mode by commenting out the relevant flags in the `DuskTestCase.php`

```php
/**
 * Create the RemoteWebDriver instance.
 *
 * @return \Facebook\WebDriver\Remote\RemoteWebDriver
 */
protected function driver()
{
    $options = (new ChromeOptions)->addArguments([
        // '--disable-gpu',
        // '--headless'
    ]);

    return RemoteWebDriver::create(
        'http://localhost:9515', DesiredCapabilities::chrome()->setCapability(
            ChromeOptions::CAPABILITY, $options
        )
    );
}
```

Is there a way so that I can just run `php artisan dusk --some-flag-to-run-in-non-headless-mode`?

**Comment by browner12** [comment]
if you (or anyone) can figure out a way to do this, it would be much appreciated.  I have looked at it many times, but it's not very straightforward.

**Comment by derekmd** [comment]
I've decided to only enable headless mode when running in a CI environment. At least in CircleCI you can check the OS current working directory to decide that. Editing file tests/DuskTestCase.php:

```php
protected function driver()
{
    $browser = DesiredCapabilities::chrome();

    if ($this->isRunningCircleCI()) {
        $options = (new ChromeOptions)->addArguments([
            '--disable-gpu',
            '--headless'
        ]);

        $browser->setCapability(
            ChromeOptions::CAPABILITY, $options
        );
    }

    return RemoteWebDriver::create(
        'http://localhost:9515', $browser
    );
}

protected function isRunningCircleCI()
{
    return getcwd() === '/root/your-project-dir';
}
```

So desktop Dusk runs always show the browser.

**Comment by driesvints** [comment]
Since this has been denied in the past, I'm going to close this. You're free to update the class as you see fit or as @staudenmeir suggested.

https://github.com/laravel/dusk/pull/376

More info for CI setups can be found here: https://laravel.com/docs/5.7/dusk#continuous-integration
