### ISSUE TITLE
Select Button

### ISSUE THREAD

**Issue by SlothAphrodite** [laravel/dusk#548]
I want to choose button like this? 
how i can choose it?
![screenshot from 2018-09-04 15 56 42](https://user-images.githubusercontent.com/40817102/45021215-2db2b880-b05b-11e8-9e26-d69a425ae8c9.png)
the example.. i want to delete data number 2 .. how can i pick it?

**Comment by staudenmeir** [comment]
Please post your HTML.

**Comment by SlothAphrodite** [comment]
`                    @php $no = 1; @endphp
                    @foreach($data as $datas)
                        <tr>
                            <td>{{ $no++ }}</td>
                            <td>{{ $datas->project_name}}</td>
                            <td>{{ $datas->issue_status_name }}</td>
                            <td>{{ $datas->issue_title }}</td>
                            <td>{{ $datas->username }}</td>
                            <td>{{ $datas->estimated_hours ." Hours : "}}{{ $datas->estimated_minutes. " Minutes"}}</td>
                            <td>{{ $datas->progress_percentage ."%"}}</td>
                            <td>

                                <form action="{{ route('issue.destroy', $datas->issue_id) }}" method="post">

                                    {{ csrf_field() }}

                                    {{ method_field('DELETE') }}
                                    <a href="{{ route('issue.edit',$datas->issue_id) }}" class=" btn btn-sm btn-primary">Edit</a>
                                    @authorize('removeIssue')
                                    <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Are your sure want to delete this issue?')">Delete</button>
                                    @endauthorize
                                    <a href="{{ route('issue.show',$datas->issue_id) }}" class=" btn btn-sm btn-primary">Detail</a>
                                </form>

                            </td>
                        </tr>
                    @endforeach

                </table>`  this is my html

**Comment by staudenmeir** [comment]
You can use this:

```php
$browser->element('.path-to-the-table tbody tr:nth-child(2) button.btn-danger')->click();
```

**Comment by jokerg04** [comment]
if using it, a message appears' Error: Call to a member click () on null

**Comment by staudenmeir** [comment]
What selector are you using? Does your table have a `tbody`?

**Comment by jokerg04** [comment]
yes

**Comment by staudenmeir** [comment]
What selector are you using?

**Comment by SlothAphrodite** [comment]
i use button

**Comment by driesvints** [comment]
Can you please post the full view file and test class?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
