### ISSUE TITLE
acceptDialog() and derivatives don't work properly

### ISSUE THREAD

**Issue by worldofswift** [laravel/dusk#552]
When the alert presented we encountered a problem:
1. Dusk don't want to execute this method waiting for clicking for confirmation.
2. It encountered in bot headless and non- modes.
3. With included chromedriver-mac and standalone chromedriver via brew.
4. In non-headless mode it also causes chromedriver freezing. 
5. Chrome 69, macOS 10.13.latest

**Comment by staudenmeir** [comment]
Are you using the latest ChromeDriver (2.42)? Check `vendor/laravel/dusk/bin/chromedriver-mac --v`.

**Comment by staudenmeir** [comment]
Can you provide a simple website with the corresponding Dusk test that allows us to reproduce the issue?

**Comment by worldofswift** [comment]
It's easy - in my environment it is reproducable via simple js `alert` function with custom text.

**Comment by driesvints** [comment]
Can you provide some sample code/test app so we can test things out? Perhaps create a repo with a basic app in it that reproduces the problem?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
