### ISSUE TITLE
Is it possible to use Dusk inside laravel package?

### ISSUE THREAD

**Issue by muharihar** [laravel/dusk#557]
Hi team,

Is it possible to use Dusk inside laravel package?

use case:

```
<author>/<package_name>/src/tests/<Dusk>
```

Thanks

**Comment by driesvints** [comment]
Yeah should be possible as long as you can render and serve a web page. Please do try to keep this issue tracker for issues with the library only and use one of the below channels for support on usage:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
