### ISSUE TITLE
Type value is wrong in iframe inputs

### ISSUE THREAD

**Issue by sdellow** [laravel/dusk#558]
In one of my Dusk tests I'm testing a Stripe elements form. When I switch to the iframe for the card number it 9 times out of 10 inputs the number incorrectly. If I use a non iframe input everything works fine. 

A sample of my test:

    /** @test */
    public function it_can_save_a_card()
    {
      $this->browse(function ($browser) {
        $browser->loginAs($this->user)
          ->visit('/account/business/billing')
          ->type('name', 'Mr Test User')
          ->type('noniframecardnumber', '4242424242424242');

        $browser->click('#stripe-card-number');
        $browser->waitFor('#stripe-card-number iframe', 15);
        $browser->driver->switchTo()->frame($browser->script('return $("#stripe-card-number iframe").attr("name");')[0]);
        $browser->type('cardnumber', '4242424242424242');

        $browser->driver->switchTo()->defaultContent();
      });
    }

The failure screenshot (I included a standard input at the bottom):

![failure-it_can_save_a_card-0](https://user-images.githubusercontent.com/1047476/46347486-9cc40280-c643-11e8-8aa0-73117b8b365b.png)

Any ideas why this might be happening?

Thanks.

**Comment by staudenmeir** [comment]
Does the Stripe iframe have any JavaScript?

**Comment by sdellow** [comment]
Yea the Stripe Elements drop in is pretty Javascript heavy. For example, it validates credit card numbers on the fly and also formats the output with spaces and such.

I forgot to mention, this test is pretty old and has always worked fine until recently. That said I understand something could have changed within Stripe just as much as it could have Dusk.

**Comment by staudenmeir** [comment]
Could be a timing issue, maybe Dusk is typing too fast.

Try a pause after each character:

```php
foreach (str_split('4242424242424242') as $char) {
    $browser->append('cardnumber', $char)->pause(100);
}
```

**Comment by sdellow** [comment]
That got it. Thanks so much.
