### ISSUE TITLE
clickLink does not escape quotes

### ISSUE THREAD

**Issue by r-moiseev** [laravel/dusk#56]
Code like `$browser->clickLink($user->name)` causes error if name contains quotes (something like `Bert O'Keefe`)

Full error output:

```
1) Tests\Browser\LayoutTest::testBasicNavigation
Facebook\WebDriver\Exception\UnknownServerException: unknown error: Cannot read property 'click' of undefined
  (Session info: chrome=54.0.2840.100)
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.4.0-59-generic x86_64)

/home/rmoiseev/PhpstormProjects/app/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:114
/home/rmoiseev/PhpstormProjects/app/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:321
/home/rmoiseev/PhpstormProjects/app/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:597
/home/rmoiseev/PhpstormProjects/app/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:335
/home/rmoiseev/PhpstormProjects/app/vendor/laravel/dusk/src/Concerns/InteractsWithElements.php:60
/home/rmoiseev/PhpstormProjects/app/tests/Browser/LayoutTest.php:36
/home/rmoiseev/PhpstormProjects/app/vendor/laravel/dusk/src/TestCase.php:88
/home/rmoiseev/PhpstormProjects/app/tests/Browser/LayoutTest.php:47
```

Everything works fine If link text does not contain quotes.

**Comment by Modelizer** [comment]
Have you tried by escaping or encoding it? Not sure but worth to give it a try.

**Comment by ebisbe** [comment]
I'm trying to CI with circle and I have the same error. 
```
Facebook\WebDriver\Exception\UnknownServerException: unknown error: Cannot read property 'click' of undefined
  (Session info: headless chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.9.60-linuxkit-aufs x86_64)
```
but it's triggering from 
```
->clickLink('Sign up')
```

Any ideas @Modelizer ?

**Comment by ajlango** [comment]
@ebisbe Did you find any solution?

`  $browser->visit('/')
                ->waitForLink("Sign In")
                ->clickLink("Sign In")
                `
I'm doing this and getting the same error.

`Facebook\WebDriver\Exception\UnknownServerException: unknown error: Cannot read property 'click' of undefined
  (Session info: chrome=72.0.3626.81)
  (Driver info: chromedriver=2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f),platform=Linux 4.15.0-45-generic x86_64)
`

**Comment by ebisbe** [comment]
@ajlango Sorry but I don't really remember what I did and if I really fix that issue. I no longer use Circle Ci nor Laravel...

**Comment by monaye** [comment]
I am getting the same error. using laravel 5.4. I can see that browser click on the link but throw error after successfully click... 
```
->visit('/admin/customers/'.$reservation->customer_id)
                    ->pause(5000)
                    ->clickLink($reservation->places->name)
                    ->pause(5000);
```

**Comment by monaye** [comment]
solved the issue by updating the Chrome Driver by following https://github.com/staudenmeir/dusk-updater
