### ISSUE TITLE
Problem with TAB keys ({tab}) on Dusk

### ISSUE THREAD

**Issue by linhnh95** [laravel/dusk#562]
I'm trying to create a test function with the TAB key.
Idea :
When you are at an input and pressing the TAB key will move to another Input field.
Problem :
When I use keys to execute the TAB key. It does not work
Can anyone answer this question?
Thank you

My code 

`$browser->visit('/customers')
                ->click('@global__btnAddKH')
                ->waitFor('#addCustomer', 5)
                ->whenAvailable('#addCustomer', function ($modal) {
                    $modal->click('@modal__textName')
                        ->assertFocused('@modal__textName')
                        ->keys('@modal__textName', '{tab}')
                        ->assertFocused('@modal__textEmail');
                });`

**Comment by staudenmeir** [comment]
What version of Dusk are you using?

**Comment by linhnh95** [comment]
I using 
Chromedriver : 2.42
Laravel : 5.6.38
PHP : 7.2.10
PHPUnit : 7.3.4

**Comment by staudenmeir** [comment]
Can you create a simple https://jsfiddle.net? I tested a basic form with two inputs and it worked for me.

**Comment by linhnh95** [comment]
Basically this is the function I want to test.
https://jsfiddle.net/7z9f6ut5/3/
The user press Tab to move the Input box

**Comment by staudenmeir** [comment]
Are you using the same JavaScript code on your actual site?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
