### ISSUE TITLE
After tests chrome process remains

### ISSUE THREAD

**Issue by loic-lopez** [laravel/dusk#563]
Hello,

After running dusk tests with Atlassian bamboo Chrome process remains as "zombie".

Bellow my driver code: 
```php
$options = (new ChromeOptions())->addArguments(['--disable-gpu', '--headless', '--no-sandbox', ]);

$chrome = DesiredCapabilities::chrome()->setCapability(ChromeOptions::CAPABILITY,$options)->setCapability('acceptInsecureCerts', true);

return RemoteWebDriver::create('http://localhost:9515', $chrome);
```

Composer.json:
```json
 "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.5",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "laravel/dusk": "^4.0",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0",
        "squizlabs/php_codesniffer": "3.*"
    },
```

<img width="1440" alt="capture d ecran 2018-10-06 a 22 37 09" src="https://user-images.githubusercontent.com/17724398/46577613-83f77c00-c9b8-11e8-9a4f-33f5be443437.png">

Thanks for reply.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
