### ISSUE TITLE
need assertHasChecked assertation

### ISSUE THREAD

**Issue by yilmazerhakan** [laravel/dusk#566]
Hello,

While testing with dusk i need an assertation like as 'assertHasChecked' or 'assertIsChecked'

I have a toggle-switcher and this could be checked or unchecked belongs to its db value.

But

`->assertChecked('#switch-toggle-notification')`

or

`->assertNotChecked('#switch-toggle-notification')`

are inadequate such a position.

`->assertHasChecked('#switch-toggle-notification', (bool) $notifications_allow)`

maybe a good solution.

**Comment by staudenmeir** [comment]
How is the toggle-switcher implemented in HTML?

**Comment by yilmazerhakan** [comment]
The toggle-switcher code below
```
<div class="switch">
       <input id="switch-toggle-notification" class="switch-toggle" type="checkbox" {{ ($notifications_allow) ? "checked" : "unchecked" }}>
       <label for="switch-toggle-notification"></label>
</div>
```

And my working solution

```
<?php 

namespace Tests\Browser;

use Tests\DuskTestCase;
use Laravel\Dusk\Browser;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use App\User;
use PHPUnit\Framework\Assert;

class SettingsTest extends DuskTestCase
{    

    /**
     * Settings test.
     *
     * @return void
     */
    public function testSettingsPage()
    {
        $user = User::find(1);
        $this->browse(function ($browser) use ($user) {
            
            $browser->loginAs($user)
            ->visit('/user/settings')
            ->assertTitleContains($user->username);
            
            // Notification Check
            $status = $browser->attribute('input#switch-toggle-notification', $notifications_allow ? 'checked' : 'unchecked');
            Assert::assertEquals($status, $notifications_allow ? true : '');
        });
    }

```

I suggested a new assertation because this solution is not stabile.

**Comment by driesvints** [comment]
I don't really understand what you're trying to do. Could you perhaps try and ask on one of the below support channels for help first? I do believe it's possible to check all this with the current methods.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by yilmazerhakan** [comment]
If you read carefully above, you would understand what I **suggest** and then I answered contributor's question and showed my long solution.
I know the functions of the platforms you linked.
I posted an issue as a suggestion for the next versions.
And I think this was the right place for it!

**Comment by driesvints** [comment]
What is `$notifications_allow`? Where does this value come from? Your code of your test is either incomplete or doesn't makes sense. I really believe that this can be solved with the current methods available.

As this isn't a support channel, please try one of the channels above and report back if you really believe this is a feature which can be added.
