### ISSUE TITLE
Explicit environment whitelisting

### ISSUE THREAD

**Issue by splatEric** [laravel/dusk#57]
Not sure if this is the best place for this, but I wanted to make the suggestion that the Dusk login route only be exposed for specific environments.

Whilst the docs do point out that you should only include the service provider in local or testing, I wonder whether it would be better if Service Provider itself was checking this as well. To ensure full flexibility, there could be a white listing environment variable so if people wanted to expose it in other environments as well they could.

My reasoning for this is that it would be very simple for someone to skim read the docs and not pick up on this detail. If they simply included the service provider as standard, this would be something of a security flaw.

Something like:

```
class DuskServiceProvider extends ServiceProvider
{

    public function boot()
    {
        if (in_array(env('APP_ENV'), array_merge(['local','testing'], explode(',', env('DUSK_WHITELIST', ''))), false)) {
            Route::get('/_dusk/login/{userId}', [
                'middleware' => 'web',
                'uses' => 'Laravel\Dusk\Http\Controllers\LoginController@login'
            ]);

            $this->app->booted(function () {
                $this->makeLogoutAccessibleViaGet();
            });
        }
    }
```

**Comment by Modelizer** [comment]
I think this would go to https://github.com/laravel/internals :)

**Comment by ninthspace** [comment]
The [installation docs mention updating AppServiceProvider](https://laravel.com/docs/master/dusk#installation) to detect the environment before including the route. This is better than modifying the internals because it allows developers to **explicitly** define the environments once there rather than relying on another environment variable.

```php
 if ($this->app->environment('local', 'testing')) {
     $this->app->register(DuskServiceProvider::class);
 }
```

**Comment by splatEric** [comment]
One final point to make, then I promise I will shut up about it. 

With most errors of configure, the system either doesn't work, or there's an awkward side effect such as log files filling up. If you get this one wrong, you will be opening up a hole in your authentication layer without any clue that you've done it.

**Comment by SebastianS90** [comment]
@JeffreyWay Are you aware that you [present (at 0:40)](https://laracasts.com/series/whats-new-in-laravel-5-4/episodes/9) a nice way to open a huge security hole in production? Just browse to example.com/_dusk/login/1 and visit another route afterwards. You will be logged in as the user with id 1 :warning:
That works with any id, but usually id=1 is more powerful then another random user.

@taylorotwell isn't this the best example why we should protect developers from a silly mistake that has a tremendous impact?

**Comment by taylorotwell** [comment]
Sure, if someone wants to submit a PR for it I will take a look.
