### ISSUE TITLE
Stripe Elements requires upgrade of ChromeDriver

### ISSUE THREAD

**Issue by alphametric** [laravel/dusk#570]
Simple one here... 

Working with iframes led to a test failure (example in question was Stripe Elements related). Upgrading the ChromeDriver to the latest version solved the issue. My guess is it relates to the recent Google Chrome update.

**Comment by alexbowers** [comment]
Unfortunately, this doesn't seem to be as easy as just updating the files.

Whilst that does work, and locally for me in Vagrant and on the mac the tests all pass, for some reason Travis isn't having it.

https://github.com/laravel/dusk/pull/576

If anybody can figure that out, that'd be great.

**Comment by staudenmeir** [comment]
@alexbowers Is Travis using the latest Chrome version?

**Comment by staudenmeir** [comment]
You can try my updater package: https://github.com/staudenmeir/dusk-updater

Install it with `composer require --dev staudenmeir/dusk-updater` and then add `php artisan dusk:update` to your `.travis.yml` file.

I just tested it on Travis, I can get the latest Chromedriver binaries. I verified it with `echo exec(base_path('vendor/laravel/dusk/bin/chromedriver-linux --v'));`.

**Comment by davidhemphill** [comment]
I just had this same issue working on a site, and updating the ChromeDriver binaries solved it. Thanks 👍

**Comment by driesvints** [comment]
Sent in a PR which updates the chromedriver to 2.45: https://github.com/laravel/dusk/pull/591

**Comment by driesvints** [comment]
@staudenmeir used your package for this. Worked really well. Thanks for this!
