### ISSUE TITLE
HTML geolocation in headless mode?

### ISSUE THREAD

**Issue by dmitry-ivanov** [laravel/dusk#572]
Is it possible to test html geolocation in the headless mode?

I've found this list of the supported arguments:
https://peter.sh/experiments/chromium-command-line-switches/

And also this issue of the Chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=834808

Now, I'm using "non-headless" mode and --disable-search-geolocation-disclosure to test geolocation.

**Comment by dmitry-ivanov** [comment]
I'm trying to test that by clicking the button, I would be redirected to the "geolocated" page.

Here is my test:

```php
/** @test */
public function geolocation_button_click_causes_the_redirection_to_the_geolocated_page()
{
    $this->browse(function (Browser $browser) {
        $browser->visit(new DefaultForecastPage)
            ->assertOnPage()
            ->clickHtmlGeoLocation()
            ->on(new GeolocatedForecastPage($browser))
            ->assertOnPage()
            ->clearSettings();
    });
}
```

**Comment by staudenmeir** [comment]
Does #459 help you?

**Comment by dmitry-ivanov** [comment]
Yes, it's awesome! Thank you!

Now my test became:

```php
/** @test */
public function geolocation_button_click_causes_the_redirection_to_the_geolocated_page()
{
    $this->browse(function (Browser $browser) {
        $browser->visit(new DefaultForecastPage)
            ->assertOnPage()
            ->mockHtmlGeoLocation()
            ->clickHtmlGeoLocation()
            ->on(new GeolocatedForecastPage)
            ->assertOnPage()
            ->clearSettings();
    });
}
```

And here is the `mockHtmlGeoLocation()` method:

```php
public function mockHtmlGeoLocation(Browser $browser)
{
    $location = Location::geolocated();

    $browser->driver->executeScript(
        "window.navigator.geolocation.getCurrentPosition = function(onSuccess) {
            var position = {
                'coords': { 'latitude': {$location->latitude()}, 'longitude': {$location->longitude()} }
            };
            onSuccess(position);
        }"
    );
}
```

Thank you so much, @staudenmeir !!

**Comment by enderandpeter** [comment]
I am not having luck with this. In the app I'm building, which uses Jetstream and Livewire, `navigator.geolocation.watchPosition` is used instead. When I overwrite it, for some reason this data does not get set in the database, despite confirming that the overwritten geolocation is present in the JavaScript that calls the `Livewire.emit` method to trigger an event. Also, in the corresponding Livewire component PHP code, I have confirmed that the correct value is there too, right before the line that saves it to the database. 

I see no reason why this value won't simply be written to the database. Yet for some reason, if I overwrite the `navigator.geolocation.watchPosition` function in JavaScript, this somehow prevents the data from being saved in the DB. It is only saved if I do not overwrite that function, even if I hard code specific values in the JavaScript or the component method.

It's been hard to find support with Dusk. The previous version in Laravel 8 at least let me use the geolocation functions like in a normal browser session. With the Dusk in Laravel 9, now it's giving the `PERMISSION_DENIED` error for getting geolocation data.
