### ISSUE TITLE
Cannot navigate to invalid URL

### ISSUE THREAD

**Issue by IManAsap** [laravel/dusk#575]
Hi,

On Laravel 5.7 with basic intall of dusk :

Facebook\WebDriver\Exception\UnknownServerException: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot navigate to invalid URL"}
  (Session info: headless chrome=64.0.3282.140)
  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 10.0.17134 x86_64)

**Comment by staudenmeir** [comment]
What's the value of `APP_URL` in your `.env[.dusk.local]` file?

**Comment by IManAsap** [comment]
Hi staudenmier,

I had no .env.dusk.local, i create it and set APP_URL=http://localhost:8000, and I have no more the error.

But, my assert fails and no browser appears.

My code : 
         $this->browse(function (Browser $browser) {
            
            $browser->visit(route('commandes.index'))
                    ->assertSee('Liste');
        });

**Comment by staudenmeir** [comment]
Are you using Dusk in combination with `php artisan serve`?

**Comment by IManAsap** [comment]
I have se same result if php artisan serve run or not

**Comment by staudenmeir** [comment]
Try `APP_URL=http://localhost:8000` in the `.env` file (instead of `.env.dusk.local`).

**Comment by driesvints** [comment]
Please try @staudenmeir's suggestion :)

**Comment by IManAsap** [comment]
Hi @staudenmeir, hi @driesvints,

i try php artisan serve and set APP_URL=http://localhost:8000 in the .env file and in the  .env.dusk.local file, i have the same result

**Comment by staudenmeir** [comment]
This is hard to debug remotely.

Try a fresh Laravel installation and set `APP_URL=http://localhost:8000` in your `.env` file. Then run Laravel with `php artisan serve` and check `php artisan dusk`. Does it work?

**Comment by IManAsap** [comment]
Yes :  

```
php artisan dusk
Warning: TTY mode is not supported on Windows platform.
PHPUnit 7.4.3 by Sebastian Bergmann and contributors.

[1102/170712.186:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:12687/devtools/browser/a624256a-11f5-4184-a2f6-b95251bff116
.                                                                   1 / 1 (100%)

Time: 5.78 seconds, Memory: 12.00MB

OK (1 test, 1 assertion)
```

**Comment by IManAsap** [comment]
@staudenmeir, Thank you very much of your help

**Comment by staudenmeir** [comment]
I noticed that you were using `http://localhost:8000` before. Just to rule this out, try `http://127.0.0.1:8000`.

If that doesn't work: Does the screenshot show anything or is it blank?

**Comment by IManAsap** [comment]
Hi,

It's work with http://127.0.0.1:8000
