### ISSUE TITLE
dusk doesnt go to table in database

### ISSUE THREAD

**Issue by ruibranco** [laravel/dusk#579]
![dusk](https://user-images.githubusercontent.com/43033565/48615858-efeedc00-e989-11e8-94ab-4c3fba1edbb1.PNG)

this is the error that gives, well indeed the table user_model doesnt exist, but that´s the name of the model that i m using
![tempo](https://user-images.githubusercontent.com/43033565/48615948-2cbad300-e98a-11e8-9e48-c74891cf9baa.PNG)

why can t he go to the correct table and get the id that i give in the test? 

PS if i alter the table name he runs 100%, but i can t change the name of the table

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
