### ISSUE TITLE
assertVueContains With Vue Object Properties

### ISSUE THREAD

**Issue by mikeminckler** [laravel/dusk#583]
In Dusk I've been trying to test in Vue the presence of a property value for an object that's in an array. The problem seems to come up due to Vue Observer returning a multidimensional array for an array of objects which is fair enough, but phpunit assertContains appears to only deal with single dimensional arrays. 

I looked into `MakesAssertions` and was able to get the query selector to flatMap my data but it feels like too much of a hack. 

`->assertVueContains('$store.state.feedback.flatMap(f => f.message)', 'Logged In', '@app');`

Any ideas on this?

**Comment by driesvints** [comment]
Seems like an additional method could help? Can you perhaps post some example code how this would be used?

**Comment by sadnub** [comment]
I have come across a scenario where I need this exact thing. 

The data in my Vue component looks something like this:

```
data(){
  return {
    users: []
  }
}
```

The users array contains many user objects. Something like:

```
{
  name: 'Josh',
  email: 'josh@example.com'
}

Using the assertVueContains assertion takes some hacking to get it to detect if a user object has been added to the array.

My assertion looks like this:

```
                    ->assertVueContains('users', [
                                          'name' => 'Josh Brocheck',
                                          'email' => 'sadnub@gmail.com',
                                          'role' => 'Admin',
                                          'active' => true
                                        ], '@route-component');
```

**Comment by u01jmg3** [comment]
- What work is still required in this ticket?
- Do we need to support flattening the properties array if it is multi-dimensional?

**Comment by driesvints** [comment]
Seems like it's already supported using @sadnub's method.
