### ISSUE TITLE
ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by tyler36** [laravel/dusk#585]
Started having trouble today running Dusk tests.
I have multiple test files, with most containing multiple test.

I started getting failures this morning, well, I noticed it this morning after updating Win10 (some hotfixes) & Chrome (v71).

The first test of each file passes, everything else in the same test file fails
If I change the order, the new first test passes, everything else in the same test file fails.
If I run a single test file by itself (using ```--filter```), the first test passes, everything else fails
If I run a "failing" test by itself (using ```--filter```), it passes
If I run a "failing" test multiple times (using ```--filter {name} --repeat 5```, it passes
If I disable ```'--headless',``` in DuskTestCase everything passes.

When a test fails, the console Dusk log file shows:
```
    {
        "level": "SEVERE",
        "message": "https:\/\/fonts.gstatic.com\/s\/materialicons\/v41\/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2 - Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME",
        "source": "network",
        "timestamp": 1543991809360
    },
    {
        "level": "SEVERE",
        "message": "http:\/\/127.0.0.1:8000\/js\/place-show.js?id=9643535560d6bc3832e0 - Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME",
        "source": "network",
        "timestamp": 1543991809557
    }
```

Dusk shows these type of errors for ```JS```, ```PNG```, ```JPG``` files and external calls in other tests.
If I check the URL in Chrome, compensating for the escaped values, I get the proper resource:
```http:\/\/127.0.0.1:8000\/js\/place-show.js?id=9643535560d6bc3832e0``` => ```http://127.0.0.1:8000/js/place-show.js?id=9643535560d6bc3832e0```

The site loads and works fine in Chrome v71, Firefox v63.0.3, & Edge. 

I've tried restarting my system (it's Win10 after all)
I've tried changing the server from ```php artisan serve``` => ```Xampp``` with same results

Laravel: 5.7
PHP: 7.2.9
OS: Win10

**Comment by tyler36** [comment]
Perhaps related to this: https://github.com/GoogleChrome/puppeteer/issues/3463

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by tyler36** [comment]
Sorry ... thought the laravel/dusk issue tracker was for laravel/dusk issues. My bad.

**Comment by tyler36** [comment]
Confirmed. Laravel/Dusk is not compatible with current version of Chrome.

1. Downgrade Chrome to ```Version 70.0.3538.77 (Official Build) (64-bit)```, tests work
2. Upgrade Chrome to ```Version 71.0.3578.80 (Official Build) (64-bit)```, test fail.

**Comment by staudenmeir** [comment]
Are you using the latest ChromeDriver 2.44? Run `vendor/laravel/dusk/bin/chromedriver-win.exe --v`.

**Comment by tyler36** [comment]
@staudenmeir 
Chrome driver reports as ```ChromeDriver 2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73)```

Removed ```laravel/dusk``` and re-installed.
```
 - Installing facebook/webdriver (1.6.0)
 - Installing laravel/dusk (v4.0.3)
```
but it installs the same driver version (```ChromeDriver 2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73)```)

I tried your excellent package, ```staudenmeir/dusk-updater```, which updated my ChromeDriver to ```ChromeDriver 2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90)```.
Still no luck.

Tried downgrading Chrome to 70, and everything works. Upgrading to Chrome 71 and everything fails.
Seems like ```larvael/dusk``` is using the OS version for something instead of the ChromeDriver?

**Comment by staudenmeir** [comment]
Looks like we can't do anything about this at the moment.
