### ISSUE TITLE
Cannot click on multiple checkboxes with the same name field

### ISSUE THREAD

**Issue by dericcain** [laravel/dusk#59]
I have a rather lengthy form that I am trying to test with Dusk and I cannot figure out how to check a box that is part of an array of checkboxes. For instance, take this...

```
@foreach($physicalNeeds as $item)
    <div class="checkbox">
        <label>
            <input type="checkbox" value="{{ $item->id }}" name="physical_needs[]">
                {{ ucfirst($item->name) }}
        </label>
    </div>
@endforeach
```

Now, for my test, I have...

```
->check('physical_needs', 'Water')
->check('physical_needs', 'Meals')
```

Before I do that, I fill out a number of other fields so I know it's working in that regard and is strictly an issue with the checkboxes. For instance, a couple lines up, I do this and it is working:

```
->check('has_power')
```

The error that I am getting is this:
```
Facebook\WebDriver\Exception\InvalidSelectorException: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=55.0.2883.95)
```
Unfortunately, the docs do not specify how to handle this. If someone can point me in the right direction, I would love to fix my issue, but also update the docs so that others know how to do this.

**Comment by dericcain** [comment]
Looks like #83 is an explanation of how to resolve this issue.

**Comment by anam-hossain** [comment]
How do you fix this? Does `->check("'physical_needs[]'", 'Water')` works?

**Comment by dericcain** [comment]
@anam-hossain look at #83. I cannot remember since it’s been so long.

**Comment by JeyKeu** [comment]
#83 Does not seem to work. I'm using Dusk ^3
