### ISSUE TITLE
Possible to configure dusk test with PHP VCR?

### ISSUE THREAD

**Issue by taufek** [laravel/dusk#592]
I wish to run Dusk tests while mocking any external requests. Is it possible to configure [PHP VCR](https://github.com/php-vcr/php-vcr) to work with Laravel Dusk Tests?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
