### ISSUE TITLE
Is dusk for Laravel only or is this a generic tool?

### ISSUE THREAD

**Issue by wowcut** [laravel/dusk#593]
From the documentation it became no clear to me, if this tool is usable only for Laravel applications, like depending on the code of the actual app, or if this can be used as a generic tool for any website to test.

It would be helpful to add one sentence to help with this point.

**Comment by driesvints** [comment]
All Laravel official packages are meant to work with just Laravel.

**Comment by wowcut** [comment]
Ah, ok - such a pitty! I actually liked the docs, but I need to test things that are not only Laravel. Would be great if you could add this important clarification to the docs, thank you!

**Comment by staudenmeir** [comment]
You can test any website, but you might not be able to use all of Dusk's features.

https://github.com/laravel/dusk/issues/356#issuecomment-375941569 shows how to run Dusk outside of Laravel.
