### ISSUE TITLE
Auth::user() is null on Laravel Spark?

### ISSUE THREAD

**Issue by nbyloff** [laravel/dusk#597]
I am using Laravel Spark 7.1.1 and my testing started off fine until one of my routes contained Auth::user(). Here is the query scope causing issue:

```
class CurrentTeamScope implements Scope
{

  public function apply(Builder $builder, Model $model)
  {
    if (!Auth::check()) {
  	throw new \Exception('Session error while running query');
    }
    $user = Auth::user();
    $builder->where('team_id', '=', $user->currentTeam->id);;
  }
}
```

I just added the Auth::check() and it does throw the exception, but before putting that in place the `Auth::user()` just below it always returns `null` in Laravel Dusk, but works as expected in your typical local dev & production environments.

The login process is working because I run this test and it passes.

```
$this->browse(function (Browser $browser) {
      $browser->loginAs($this->user)
        ->visit(new DashboardPage)
	->assertSee('Plan Types')
	->createNewApplication('Test Application Name');
});
```

The only middleware being applied to the route group is the default `auth`. 

`'auth' => \Illuminate\Auth\Middleware\Authenticate::class,`

**Comment by staudenmeir** [comment]
How/where are you using the `CurrentTeamScope` scope?

**Comment by nbyloff** [comment]
@staudenmeir  `CurrentTeamScope` is a global query scope applied to most eloquent models like this

```
protected static function boot()
{
    parent::boot();
    static::addGlobalScope(new CurrentTeamScope);
}
```

**Comment by staudenmeir** [comment]
Which model are you querying when the error occurs? Where are you querying the model?

**Comment by nbyloff** [comment]
Here's what is happening.

Created this test
```
public function testUserCanCreateProductLine()
{
	$application = Application::first();
	dd($application);
}
```

Here's the model it's trying to query:


```
class Application extends Model
{
  protected $fillable = ['plan_name', 'plan_type', 'team_id', 'user_id'];

  protected static function boot()
  {
    parent::boot();
    static::addGlobalScope(new CurrentTeamScope);
  }
  ...
  ...
  ...
}
```

When I run the test, I get this error. Line 16 is the `Auth::check()`. When I remove the `Auth::check()` it fails on the Query builder line saying it can't get a property from non-object. IE: `currentTeam` can't be fetched because `Auth::user()` is null.
```
There was 1 error:

1) Tests\Browser\DashboardTest::testUserCanCreateProductLine
Exception: Session error while running query

/home/vagrant/code/app/Models/Scopes/CurrentTeamScope.php:16
```

**Comment by nbyloff** [comment]
Duh! The scope was lost on me; thanks for sobering me up today. Happy New Year!
