### ISSUE TITLE
Unable to use shorthand selectors

### ISSUE THREAD

**Issue by jevm** [laravel/dusk#603]
Hi,

I am unable to use shorthand selectors. I have this code:

```
public function elements()
    {
        return [
            '@loginIcon' => 'span.ico-login.ico',
			'@username' => '#user_login_username',
			'@password' => '#user_login_password',
			'@loginButton' => 'input[value=Login]',
        ];
    }
	
public function clickLogin(Browser $browser)
	{
		$browser->click('@loginIcon');
	}

```

And always getting this exception:

`Facebook\WebDriver\Exception\NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"body [dusk="loginButton"]"}
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.17134 x86_64)`

What am I missing here?

**Comment by staudenmeir** [comment]
Are you using the page that contains the shorthand selectors with `visit()` or `on()`?

See https://laravel.com/docs/dusk#navigating-to-pages.

**Comment by jevm** [comment]
@staudenmeir Could you please be more specific? I've already had some reading into the documentation you've mentioned and I am definitely on the page which is needed. If I click that exact selector 'span.ico-login.ico' it is working, but if I am trying to use shortcuts it doesn't work at all.

**Comment by staudenmeir** [comment]
Please post more of your code. Where are you calling `clickLogin()`?

**Comment by jevm** [comment]
```
<?php

namespace Tests\Browser;

use Tests\DuskTestCase;
use Laravel\Dusk\Browser;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\Browser\Pages\MainPage;

class OlyBetTest extends DuskTestCase
{
    
    public function testLogin()
    {
		
		    $this->browse(function (Browser $browser) {
			$mainPage = new MainPage;
            $browser->visit($mainPage->url());
            $mainPage->clickLogin($browser);
	    $browser->pause(10000);			
        });
    }
}
```

**Comment by staudenmeir** [comment]
Replace `$browser->visit($mainPage->url());` with `$browser->visit(new MainPage);`

**Comment by staudenmeir** [comment]
`$browser->visit($mainPage->url())` doesn't work because Dusk has no connection to the `MainPage` class.

You can only use the page's shorthand selectors, if you specify the class: `$browser->visit(new MainPage)`

When you do that, Dusk automatically executes the assertions from `MainPage::assert()`.

So you either have to remove/fix the assertions or use [global shorthand selectors](https://laravel.com/docs/dusk#navigating-to-pages).

**Comment by jevm** [comment]
If I put it in global, it is still not found, the same issue that selector could not be found.

**Comment by staudenmeir** [comment]
Sorry, the global shorthand selectors also require `$browser->visit(new MainPage)`.

Why does the `assertPathIs()` assertion fail? Are you redirected to the login page?

**Comment by jevm** [comment]
Absolutely not, the path is just exactly the same as the original specified... I can observe it visually. Tried pausing for a second, it also doesn't help.

One more question. If I use the way you've mentioned here, how do I appropriately access methods from this new MainPage object in my test case?

**Comment by staudenmeir** [comment]
Try only the returning the *path* from `url()`, e.g. `/`. Then `assertPathIs()` should work.

See https://laravel.com/docs/dusk#page-methods:

```php
$this->browse(function (Browser $browser) {
    $browser->visit(new MainPage)
        ->clickLogin();
});
```

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
