### ISSUE TITLE
Issues Redirecting to SSO page in headless chrome

### ISSUE THREAD

**Issue by mjvezzani** [laravel/dusk#604]
### Issue
I have a system that when I navigate to `http://fuse.test`, if I am not logged in, I am redirected to an SSO auth page. I wrote a Dusk test that leverages a method to account for the need to log in:

```
public function loginUat()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/')
                ->type('usr', env('DUSK_USER'))
                ->type('pwd', env('DUSK_PWD'))
                ->screenshot('after vist slash')
                ->assertPathIs('/')
                ->press('Login');
        });
    }
```

When I get to this portion of the code, it seems like the `$browser->visit('/')` line is running, but when I get to `->type('usr', env('DUSK_USER'))`, it says it can't locate that element. When I look in the screenshots directory, I see a blank page.

### Expected Behavior
What I expect is that Dusk is able to automatically handle redirects and take me to the pages I need to interact with for the test.

### Question
What extra (if any) configuration needs to happen to support redirecting in a Dusk test that uses chrome in headless mode?

**Comment by staudenmeir** [comment]
So after `$browser->visit('/')`, you should be on the SSO page?

What does `$browser->visit('/')->screenshot('sso');` show?

Do you know whether Dusk is working at all? Do you have any other tests?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by mjvezzani** [comment]
@staudenmeir Sorry for the delayed response.

It is my understanding that after `$browser->visit('/')`, I should be on the SSO page.

When I run `$browser->visit('/')->screenshot('sso');`, I get a screenshot of a blank page.

When I navigate to `https://www.yahoo.com` and take a screenshot, I see yahoo's homepage. When I make assertions like `assertVisible('Sports')`, I get a passing test.

So as far as I can tell, I have Dusk set up correctly, but for one reason or another it is having an issue following the redirect built into our application.

What steps, if any, can I take to further debug this issue?

**Comment by staudenmeir** [comment]
Do you have any working Dusk test that tests your application?

What's the value of `APP_URL` in your `.env[.dusk.local]` file?

How are you running Dusk? In Homestead? Are you using `php artisan serve`?
