### ISSUE TITLE
loginAs should work with http basic auth

### ISSUE THREAD

**Issue by eXorus** [laravel/dusk#608]
In dusk, if my app used http basic auth I cannot use loginAs().

It doesn't work and I think it only work with Laravel Auth (/login and /register).

It could be great to have loginAs works exactly the same with http basic auth.

**Comment by staudenmeir** [comment]
I don't think Dusk can access the login form.

You can add the credentials to the URL:

```php
$browser->visit('https://user:password@example.com');
```

**Comment by driesvints** [comment]
I think @staudenmeir's solution will work. Right after that call you should be able to visit other pages: https://stackoverflow.com/questions/44542740/chrome-59-and-basic-authentication-with-selenium-fluentlenium

**Comment by eXorus** [comment]
Yes this trick works but I think it's not the good way to do it.

In Laravel with basic.auth you can plugin your credential with the users table. So you don't want to change your env file for each user.
The loginAs function could just send the correct header for basic auth in the request with the login and password of the user like he did for the classic login via the /login page.

**Comment by driesvints** [comment]
@eXorus how would you practically solve this?

**Comment by eXorus** [comment]
I don't know how loginAs works but the algo should be:

- Get the user email and password
- base64(email:password) = yourbasic
- send the first request with the header "Authorization" and the value "Basic yourbasic"

**Comment by staudenmeir** [comment]
It's not possible for Dusk to send custom headers.

I just tested `loginAs()` with the `auth.basic` middleware and does actually work for me.

**Comment by eXorus** [comment]
I did also the test this morning on a new project and that's true it works. Sorry for that.

I don't know why it doesn't work on my current project maybe because:
- I have a custom auth based on authe.basic
- it's a vueJS app with API, maybe the web works but not the call to the API.

**Comment by staudenmeir** [comment]
What does your custom auth look like?

**Comment by driesvints** [comment]
Gonna close this then since this isn't an issue.

**Comment by eXorus** [comment]
@driesvints Agree for closing.

@staudenmeir Thanks for your help. My custom auth is just a middleware to check a config file to do the basic.auth or not. Nothing special.

I did a test on a fresh install of laravel with the example component in vuejs and with the classic basic.auth and I confirm it doesn't work. Maybe I'm wrong somewhere....

**tests/Browser/ExampleTest.php**
```php
namespace Tests\Browser;

use Tests\DuskTestCase;
use Laravel\Dusk\Browser;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class ExampleTest extends DuskTestCase
{
    public function testBasicExample()
    {
        $this->browse(function (Browser $browser) {
		factory(\App\User::class)->create();

            $browser->loginAs(1)->visit('/')
                    ->assertSee('Laravel')
                    ->assertSee('example component')
                    ->assertVue('name', 'vincent', '@example-component') // failed
                    ->assertSee('vincent'); // failed
        });
    }
}

```

**routes/api.php**
```php
Route::middleware('auth:api')->get('/name', function (Request $request) {
    return 'vincent';
});

```


**routes/web.php**
```php
Route::get('/', function () {
    return view('welcome');
})->middleware('auth.basic');
```
**resources/js/components/ExampleComponent.vue**
```
<template>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card card-default">
                    <div class="card-header">Example Component</div>

                    <div class="card-body">
                        I'm an example component.
                        <span>{{ name }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {


        data() {
            return {
                name: '',
            }
        },

        mounted() {
            console.log('Component mounted.')

                axios.get('/api/name').then(function(response) {
                    this.name = response.data
                }.bind(this));
        }
    }
</script>

```


If I remove the auth.basic in the web and api it works.
If I keep the auth.basic in the web and remove the auth.basic in the api it works.
If I remove the auth.basic in the web and keep the auth.basic in the api it doesn't work.

Any idea ?

**Comment by staudenmeir** [comment]
It does work in the browser, right?

Can you create a simple application and upload it to GitHub?

**Comment by eXorus** [comment]
Yes it works in the browser.

```
git clone git@github.com:eXorus/dusk-auth.basic.git
cp .env.example .env
touch database/database.sqlite
composer install
php artisan migrate:refresh --seed
php artisan serve
php artisan dusk
```
Login: test@example.com
Password: secret

**Comment by staudenmeir** [comment]
It's a fundamental issue: By default, `api` routes don't support sessions.

From https://laravel.com/docs/passport:

> APIs typically use tokens to authenticate users and do not maintain session state between requests.

Your app only works in the browser, because the browser automatically sends the `Authorization` header every time you call `/api/protected`. Somehow, Chrome doesn't do that when running with Dusk.

If you were using the `auth` middleware with a login form, your app wouldn't even work in the browser.

I see two ways of solving this:
- Add the `EncryptCookies` and `StartSession` middleware to `Kernel::$middlewareGroups['api']`.
- Move the `api` routes to the `web` group (IMO, cleaner).

**Comment by driesvints** [comment]
FYI: we're planning on making Passport completely stateless in a future release and thus removing the need for any web routes.

**Comment by eXorus** [comment]
Thanks @staudenmeir for your investigation. 

I don't use Passport because it was easier for me to do a basic auth. But I plan to use it in the next months.

I think I gonna continue to test with dusk but without authentication because I know the browser works well with it.
