### ISSUE TITLE
Support for '*.xml.dist' configuration

### ISSUE THREAD

**Issue by klimov-paul** [laravel/dusk#609]
PHPUnit reads its configuration from 'phpunit.xml' file, however if it does not present it attempts to read configuration from 'phpunit.xml.dist' file. Such approach gives developer flexibility regardless VCS project management, allowing to place default configuration file ('*.xml.dist') under the version control, while local configuration file ('*.xml') can be used for local environment.

Unfortunally Dusk does not support '*.xml.dist' file for its own config. It reads configuration from 'phpunit.dusk.xml' and that is all. It will be nice if it will be able to use 'phpunit.dusk.xml.dist' file in case 'phpunit.dusk.xml' does not exist in same manner as PHPUnit does. This will allow putting default Dusk configuration under version control, leaving ability to override it at local environment.

**Comment by staudenmeir** [comment]
Can you submit a PR?

**Comment by klimov-paul** [comment]
Will do.
