### ISSUE TITLE
Executing dusk command shows sh: 1: php: not found

### ISSUE THREAD

**Issue by adityapurwa** [laravel/dusk#61]
Running `php artisan dusk` command returns `sh: 1: php: not found`.
Other command such as `php artisan dusk:make` is working.

**Comment by spyric** [comment]
What OS do you use? Windows?

**Comment by adityapurwa** [comment]
I use Linux Ubuntu 16.04 using LAMPP for the server stack.

Dusk seems to be not detecting php even though `/opt/lampp/bin` is in the $PATH variable.

Note: Creating symlinks of `/opt/lampp/bin/php` as `/usr/bin/php` solved the issue.

**Comment by splatEric** [comment]
out of curiosity, are you using the latest version? I put in a recent change (#51) to force the php call from the DuskCommand to use the same php binary as had been used to execute itself. But it only got into master recently ..

**Comment by adityapurwa** [comment]
From the composer.lock, I am using this [https://api.github.com/repos/laravel/dusk/zipball/d78bfd1088d8411226267936629e399aebc8f45e](https://api.github.com/repos/laravel/dusk/zipball/d78bfd1088d8411226267936629e399aebc8f45e), from `composer show -i` it is version 1.0.0.

**Comment by splatEric** [comment]
1.0.2 is out now ... do composer update and you should be sorted

**Comment by adityapurwa** [comment]
Ran `composer update laravel/dusk` and tried running `php artisan dusk` again.

Confirmed its working now, thanks!
