### ISSUE TITLE
calling browser macros throws exception

### ISSUE THREAD

**Issue by JoshPJackson** [laravel/dusk#611]
I've defined the following macro in the `app/Providers/DuskServiceProvider` file but dusk is throwing a BadMethodCallException:

    Browser::macro('logoutOfWave', function () {
            $this->visit(env('DUSK_URL'))
                ->script("localStorage.clear()");
            $this->visit(env('DUSK_URL'));

            return $this;
    });

I'm using it in a dusk test:

    public function testUnauthedUserIsRedirectedToLogin()
    {
        $this->browse(function (Browser $browser) {
            $browser->logoutOfWave()->visit(env('DUSK_URL') . '/systems/create')->assertPathIs('/login');
        });
    }

This gives the following error: 

    1) Tests\Browser\AddSystemsTest::testUnauthedUserIsRedirectedToLogin
    BadMethodCallException: Call to undefined method [logoutOfWave].

    /var/www/html/vendor/laravel/dusk/src/Browser.php:484
    /var/www/html/tests/Browser/AddSystemsTest.php:20
    /var/www/html/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:67
    /var/www/html/tests/Browser/AddSystemsTest.php:21
    

I have added the service provider to the `config/app.php` file to register it. I'm not sure why it can't find the macro?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
