### ISSUE TITLE
Dusk page assertions don't seem to be working with scopes

### ISSUE THREAD

**Issue by jaygaura** [laravel/dusk#618]
Not sure if this an issue exactly, and there may be a work around this, but here is an example of what I mean.
Say I have a dusk page Page that does some simple assertion like

```
public function assert(Browser $browser) {
    $browser->assertSee('Page title');
}
```

and then I have a test that does something like the following

```
public function testSomeTest() {
        $this->browse(function (Browser $browser) {
            $browser->visit(new Page)
           ->doSomethingOnThePage()
            ->with('#someElementWithinThePage', function ($element) {
                  $element->doSomethingThere();
            })->doSomethingElseOnThePage();
}
```
In the case above the page assertions seem be applied inside the scope as well, in which case they might not work. I would sort of expect the page to be "smart enough" to not apply assertions in limited scope, only inside the page as a whole.

Is this an intended way, an issue, or am I missing something? Again, I am not sure. This is a sort of new territory for me here.

Thanks.

**Comment by staudenmeir** [comment]
I agree that this is a bug.
