### ISSUE TITLE
Dusk failing to login

### ISSUE THREAD

**Issue by xKairu** [laravel/dusk#621]
Laravel: 5.7.28
Dusk: 5.0.1
Nova: 1.3.1
laravel-mongodb: 3.4.5

I'm testing some websocket code however I'm having an issue with Dusk being unable to authenticate. When the browser opens, it immediately gets sent to a Whoops page with the following error:

`[2019-03-05 14:54:13] local.ERROR: Argument 1 passed to Illuminate\Auth\SessionGuard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given, called in /Users/kyle/Code/eventgo/vendor/laravel/dusk/src/Http/Controllers/UserController.php on line 46`

This is my test: https://gist.github.com/xKairu/a99a2424a205dd7f56a17922880a6ca3
Which fails at line 36 as the action on line 35 requires auth, resulting in the broadcasted event not firing for line 36 to pick up on.

If I dump the provider in the Dusk UserController, I get the EloquentUserProvider. I'm passing in a user model/user ID, so it's meant to call `retrieveById`, but if I dump anything from that method, I get nothing, as if it's not being called. I'm using Nova + laravel-mongodb with my user table being in MySQL with hybrid relations, if it matters.

**Comment by staudenmeir** [comment]
What versions of Laravel and Dusk are you using?

Can you create a minimal application that lets us reproduce the issue?

**Comment by xKairu** [comment]
Laravel: 5.7.28
Dusk: 5.0.1

I can try but I'm using Laravel Nova so I'm not sure if it would help much.

**Comment by driesvints** [comment]
Can you try to upgrade to 5.8 and see if the problem persists?

**Comment by driesvints** [comment]
Hmm, actually never mind. It should work on 5.7 as well. 

I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by xKairu** [comment]
Controller: https://paste.laravel.io/2948e191-47f9-46f7-876d-060118ed6a6b
Broadcasted event: https://paste.laravel.io/64b77b5b-013f-4f97-8d02-1e65d135d066
Poll model: https://paste.laravel.io/6d1fdb36-ed17-4bfb-aa5f-8e0110b2b831
PollOption model: https://paste.laravel.io/8476f8ea-c2e1-4fb7-b9bc-1a34611e81ea
PollResponse model: https://paste.laravel.io/67a38110-84d2-4ace-905d-2dd7128bd5ae
User model: https://paste.laravel.io/3baaabbf-7274-4edc-b3fc-e3b6db1733e5
api.php route: https://paste.laravel.io/e9c68514-4e12-4478-9c7e-dd7259211376
auth config: https://paste.laravel.io/8426f43b-f59f-442b-98c1-0ddd045285b6
env: https://paste.laravel.io/3436b560-bd7a-480c-964a-a729be86c874

Although the error happens before Dusk ever hits my code (at `/_dusk/login/:user`) and it happens on every test (I login on all), it's just that this one test actually requires user data in the backend and the rest for now don't. I tried making an example application with Dusk, Nova and mongo but couldn't reproduce it.

**Comment by staudenmeir** [comment]
It's really difficult to help you without a sample application. The fact that you can't reproduce the issue suggests (to me) that it isn't caused by Dusk.

**Comment by nbyloff** [comment]
This might be a similar issue but I am no longer able to remove query scopes in Laravel Dusk tests only. My app authenticates with Laravel Spark and I have a `CurrentTeamScope` global that is applied to most models; basically `$query->where('team_id',$var);`

When I run tests manually in my browser, it works as expected. It only returns rows with the matching `team_id`.

This is my test query that passes, and the same query that fails during Dusk test.

**Comment by staudenmeir** [comment]
@nbyloff Can you provide a minimal application?

**Comment by nbyloff** [comment]
@staudenmeir Yes, probably not today, but I will link one here. Thanks

**Comment by nbyloff** [comment]
In this repo I used homestead to get the same environment. There are two tests in `VerifyBugTests`.

* The first one shows the first step in a lot of my tests. During start up I create a couple database objects then try and fetch them while removing the global scopes. I cannot fetch anything because the scopes are not removed anymore. Or...they get removed and put right back before the query. It is the `CurrentTeamScope` that uses `Auth::check()` and `Auth::user()`. Works fine in production, but even though I use `actingAs` AND `removedGlobalScope`, it fails.

* The second test is a new TokenMismatchException that just started popping up for me after I jumped to 5.X. That test was written months ago and has worked fine until recently. (You will get the same session query Expception because of the `CurrentTeamScope`, but if it's removed, that is the error we get).

Please let me know if this is what you were looking for.

https://github.com/nbyloff/dusk_test

**Comment by staudenmeir** [comment]
@nbyloff I don't see how these issues are related to Dusk.

`withoutGlobalScope[s]()` is completely independent of Dusk and it works for me: `select * from "answers"`

`$this->actingAs()->withSession()->post()->assertJson()` is a standard Laravel HTTP test, not a Dusk browser test.

**Comment by nbyloff** [comment]
@staudenmeir the only reason I came here is b/c these methods work fine outside of Dusk in production but fail when running them within Dusk. I thought it might be a scope issue. not playing nice with mongodb or something I don't know about. 

But I will admit I thought the same thing as you, this just seemed like the best place to start since `withoutGlobalScope` only fails in the dusk scenario for me.

I'll move on.

**Comment by staudenmeir** [comment]
@nbyloff Regarding the scope: Have you checked the executed queries or the query result?

**Comment by nbyloff** [comment]
It never gets to that point of showing me queries or showing results b/c it tries to run the query with the `CurrentTeamScope` still applied even after removal. And the scope throws an error b/c it has a `Auth::user()` requirement

**Comment by staudenmeir** [comment]
I think there's a misconception: A global scope is always applied, calling `withoutGlobalScope[s]()` then removes it retroactively.

**Comment by staudenmeir** [comment]
@nbyloff Your global scope is applied during `Answer::firstOrCreate()`.

**Comment by nbyloff** [comment]
It isn't impacting the create `firstOrCreate` though, only get. This is the scope and that Exception gets thrown b/c even though I remove it for my get() query, it gets put back. I am assuming this is probably a mongodb library issue?

````
public function apply(Builder $builder, Model $model)
  {
  	if (!Auth::check()) {
  		throw new \Exception('Session error while running query');
		}
    $user = Auth::user();
    return $builder->where('team_id', '=', $user->currentTeam->id);;
  }
````

**Comment by staudenmeir** [comment]
What do you mean by "It isn't impacting the create firstOrCreate though, only get."?

Take a look at the exception stacktrace: It's coming from the first `Answer::firstOrCreate()` call.

**Comment by nbyloff** [comment]
Sorry for the delay, I was away for a week. I meant I don't have any problems creating models in the DB, only fetching them because of the scope. 

I do see where the exception is coming from in this test so I am working to update it.

**Comment by driesvints** [comment]
Closing pending inactivity by original author.
