### ISSUE TITLE
Browser Navigation Forward

### ISSUE THREAD

**Issue by digitalgrease** [laravel/dusk#623]
Hi,

I am using a `forward()` equivalent of the `back()` method on `Browser` and would like to submit a PR for the feature?

**Comment by driesvints** [comment]
What would this actual do? Can you show a specific example with some code?

**Comment by digitalgrease** [comment]
So for example we are testing an application where we visit a URL and it displays the contents of a folder with images.
When we click to view a single image we want a modal/popup to display the image with the file and other properties. We want a new URL to be pushed onto the history when we open this modal.
Then, when we close the modal, the original URL is then pushed onto the history.
We want to test that clicking forward in the browser reopens the modal/popup.

```
    public function test()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs($this->user)
                ->visit('/image#/folder/1')
                ->waitUntilMissing('div.loading-spinner')
                
                // Assert a single image can be opened in a modal popup.
                ->mouseover('...')
                ->click('...')
                ->waitUntilMissing('div.loading-spinner')
                ->assertPresent('div.modal')

                // Assert "X" closes the image popup.
                ->click('svg[data-icon="times"]')
                ->assertMissing('div.modal')
                
                // Assert forward reopens the image popup.
                ->forward()
                ->waitUntilMissing('div.loading-spinner')
                ->assertPresent('div.modal')
            ;
        });
    }

```

**Comment by digitalgrease** [comment]
Here is the implementation I have in my local copy.

```
    /**
     * Navigate to the next page.
     *
     * @return $this
     */
    public function forward()
    {
        $this->driver->navigate()->forward();

        return $this;
    }
```

**Comment by driesvints** [comment]
Okay, you may send in a PR if you like but it's up to Taylor to decide upon it eventually. Please make sure to provide a thorough explanation in your PR comment and add tests for the new feature. Thanks!
