### ISSUE TITLE
Explicitly select W3C mode

### ISSUE THREAD

**Issue by sauladam** [laravel/dusk#624]
Platform: Linux / Ubuntu 18.04
ChromeDriver: 2.45
Chrome: 72.0
Laravel: 5.8
Dusk: 5.0

I was having an issue where remote driver started up correctly (I could see the chrome-driver running on port 9515) but then timed out (fresh install, default settings, just the unmodified example test):

```bash
1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"chrome","platform":"ANY","chromeOptions":{"binary":"\/snap\/bin\/chromium","args":["--disable-gpu","--headless","--window-size=1920,1080"]}}}

Connection timed out after 30001 milliseconds
```

Running a POST request to `http://localhost:9515/session` gave me this:
```json
{
    "sessionId": "ef94d81b7d25c56377a17e9de2c20d15",
    "status": 33,
    "value": {
        "message": "session not created: Missing or invalid capabilities\n  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-46-generic x86_64)"
    }
}
```

So it had something to do with the session. After googling for about 2 days I found this issue on the chromedriver project: [Issue 1997: New Session is not spec compliant](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1997). So the session creation seems to have some issues on ChromeDriver 2.45 that have to do with W3C compliance and requires to explicitly select W3C mode (at least in this specific setup, I guess).

So, in `DuskTestCase.php` I'v added this to the desiredCapabilities in the `driver()` method:

```php
return RemoteWebDriver::create(
            'http://localhost:9515', DesiredCapabilities::chrome()
            ->setCapability(ChromeOptions::CAPABILITY, $options)

            // select W3C mode
            ->setCapability('alwaysMatch', ['goog:chromeOptions' => ['w3c' => true]])
);
```

And now everything is working. Still doesn't work with Chromium though.

Not sure if I'm the only one with this issue, maybe somebody can confirm?

**Comment by staudenmeir** [comment]
I'm using ChromeDriver 2.45 on Windows and Homestead, but I haven't had any issues.

Have you tested the latest ChromeDriver 2.46?

**Comment by sauladam** [comment]
Just tested it with ChromeDriver 2.46 - seems to work without the W3C stuff with Chrome (but not Chromium - still times out no matter what).

So maybe we could bump the ChromeDriver version that Dusk ships with? Or just add the W3C flag since it does not seem to break anything (not 100% sure about that though). 

It's a really weird issue and I find it hard to believe that I'm the only one. But maybe it's just really one of those "works on my machine ™" things.

**Comment by nbyloff** [comment]
Just FYI for any Googlers out there, I had this error earlier and I think my specific issue had to do with manually stopping tests before completion. Subsequent tests got this same POST timeout error. Then I ran this:

````
ps -aux | grep chrom
````

Then killed all the chrome/chromium processes I had running. Error went away for me, so try that as well.

**Comment by sauladam** [comment]
Yeah, that might be an issue as well. In my case there was only one test and it didn't even get to that point.

I guess this issue can be closed since it doesn't seem to be consistently reproducable. But I hope it will be of some help for other Googlers becuase googling for the timeout message just gives old solutions that already have been implemented in the current version of Dusk.
