### ISSUE TITLE
laravel dusk zoom out page not clickable

### ISSUE THREAD

**Issue by softyaco** [laravel/dusk#629]
hi i have this problem thats if i did this css code to my website 
`html{
	zoom:70%;
}`
i gat this problem 

`1) Tests\Browser\ReportsTest::testExample
Facebook\WebDriver\Exception\UnknownServerException: unknown error: Element is not clickable at point (1430, 389)
  (Session info: chrome=73.0.3683.75)`
so how can i make the tests work with zoom out page thanks

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
