### ISSUE TITLE
In windows 10, does laravel dusk always open the 'chrome' browser?

### ISSUE THREAD

**Issue by josealgardataborges** [laravel/dusk#63]
Just a quick question, in windows 10, does laravel dusk always open the 'chrome' browser? I see the dusk tests like if i was using the browser. i see the input getting filled in, with username, password, for instance. Isn't it supposed to do all this stuff 'hidden' from view, just expecting the console output? It gets worse, when i use 2 browser tests, the computer almost comes to a halt. very very slow, like 30 seconds for a simple login test.

**Comment by josealgardataborges** [comment]
and eventually i get this: http://prntscr.com/e11ns9

**Comment by alex-LE** [comment]
I get the same timeout error. It seems that the Symfony ProcessBuilder has a default timeout of 60s.
My test is currently running > 70s and so i get the timeout. If is set the timeout to a higher value, it works.

Even if i split my tests into smaller classes/files i get the timeout.

Dusk might set a higher timeout by default, or let the user define it.

**Comment by KayLeung** [comment]
Either Chrome or Firefox is not a headless browser. You could try PhantomJS or wait to see if anyone bind it to nighmare.js

**Comment by deleugpn** [comment]
Can this be closed?

**Comment by josealgardataborges** [comment]
@deleugpn If it's a feature not a bug, please do close it.

**Comment by deleugpn** [comment]
It is indeed a feature. Not only that, it's the core concept of Dusk. The goal is to run the tests on an actual browser to have a better sense of the behavior of your application. It is possible to run Dusk on a headless machine using Xvfb. My CentOS can run a simple login test in a couple of seconds with 1 CPU Core and 1500MB of RAM.
