### ISSUE TITLE
Incomplete list of element types for function "InputValue"

### ISSUE THREAD

**Issue by ostapski** [laravel/dusk#633]
- Dusk Version: 5.02
- Laravel Version: 8
- PHP Version: 7.1.27
- Database Driver & Version:

### Description:
Function "InputValue missing "SELECT" type of the element.
When used on a "SELECT" - function->getText() is called instead of ->getAttribute()
returning all options of select (instead of 1)

![201903276cld7no3](https://user-images.githubusercontent.com/2835357/55062345-1c241300-5076-11e9-90fd-195a7c9d8109.png)

as well .... - Text area - should not be in the list ....

```
    public function inputValue($field)
    {
        $element = $this->resolver->resolveForTyping($field);
        return in_array($element->getTagName(), ['input', 'textarea'])
                        ? $element->getAttribute('value')
                        : $element->getText();
    }
```

### Steps To Reproduce:

Call ->assertInputValue($field, $value) 
On "SELECT" type of element (with more than 1 options inside)

**Comment by staudenmeir** [comment]
> Text area - should not be in the list

See #237.

**Comment by driesvints** [comment]
Isn't this more of a case where the wrong assertion is used? Can you please post your entire test?

**Comment by ostapski** [comment]
> 
> 
> Isn't this more of a case where the wrong assertion is used? Can you please post your entire test?

is "assertInputValue" not meant to be used on selects ?
calling "getText()" on it is not exactly a correct way to fetch selected value is it ?

**Comment by driesvints** [comment]
A select isn't an input. I think you're looking for https://laravel.com/docs/5.8/dusk#assert-selected

Can you please post the entire test?

**Comment by zoispag** [comment]
@driesvints consider it closed! The wrong assertion was indeed used in our test.
