### ISSUE TITLE
Laravel Dusk 5.0 the selection can't get default option

### ISSUE THREAD

**Issue by haiphan2710** [laravel/dusk#635]
I have a problem, this is a test case:
public function it_can_create_questions()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs($this->user)
                    ->visit('/nova/resources/questions/new')
                    ->waitForText('New Question')
                    ->assertSelectHasOptions('#purpose', ['instant_earners'])
                    ->type('@translations_text_en', 'What is your favourite beer?')
                    ->select('#purpose', 'instant_earners')
                    ->select('#type', 'single_choice')
                    ->press('Create Question')
                    ->waitForText('Question Details')
                    ->assertSee('Question Details');
        });
    }
select('#purpose', 'instant_earners') => this selection can't get default value
So can't execute because the selection not require (error in screenshot when fail assert)
Please tell me know solution for this issue

Thanks!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
