### ISSUE TITLE
Dropdown menu in a dialogue gets behind instead of showing on top of it.

### ISSUE THREAD

**Issue by usamabaig** [laravel/dusk#636]
- Dusk Version: 4.0.3
- Laravel Version: 5.7.25
- PHP Version: 7.2.15

### Description:
The frontend is in VueJS `2.5.22` and Vuetify.
I am try to test a scenario where a dialogue is open and in that dialogue, there is a multi select dropdown where multiple options can be choosed.
![Screenshot](https://user-images.githubusercontent.com/32928864/55400298-e21bab00-5566-11e9-938b-14fce067efde.png)

I am trying to test this using dusk. Now if I first type something in the name input and then click on multi select dropdown using dusk, the test pass fine.
```
$browser->loginAs($this->user)
                    ->visit(new UsersPage)
                    ->click('@edit-btn-' . $user->id)
                    ->whenAvailable(
                        '.v-dialog__content--active',
                        function (Browser $dialog) {
                            $dialog
                                ->type('@name-input', 'some name')
                                ->click('@roles-field')
                                ->waitFor('.v-select--is-menu-active');
                        }
                    );
```
But if I click to open dialogue and then click on the multi select dropdown, the dropdown hides behind the dialogue

```
$browser->loginAs($this->user)
                    ->visit(new UsersPage)
                    ->click('@edit-btn-' . $user->id)
                    ->whenAvailable(
                        '.v-dialog__content--active',
                        function (Browser $dialog) {
                            $dialog
                                ->click('@roles-field')
                                ->waitFor('.v-select--is-menu-active');
                        }
                    );
```

![failure-DataMonster_Tests_Browser_UsersTest_ensures_user_can_edit_new_users_roles-0](https://user-images.githubusercontent.com/32928864/55400420-48a0c900-5567-11e9-884f-c4622272b03e.jpg)

See the dropdown is hidden behind the dialogue and it throws error 
`Element <div class="v-input--selection-controls__ripple"></div> is not clickable at point (401, 630). Other element would receive the click: <div class="container grid-list-md">...</div>`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
