### ISSUE TITLE
assertVueContains no longer accepts arrays

### ISSUE THREAD

**Issue by asjsrep** [laravel/dusk#637]
- Dusk Version: 5.0.2
- Laravel Version: 5.8.7
- PHP Version: 7.1.4
- Database Driver & Version:

### Description:
assertVueContains is documented as asserting an array has a given value:

>  Assert that the Vue component's attribute at the given key
>       is an array that contains the given value.

 Commit [1985616f82b702f29f9a302657e6bf3f65c5e8de ](https://github.com/laravel/dusk/commit/1985616f82b702f29f9a302657e6bf3f65c5e8de ) changes the functionality to do a string search. Resulting in the error:

`ErrorException: mb_strpos() expects parameter 1 to be string, array given`

### Steps To Reproduce:

->assertVueContains('array', 'array-value', '@vue-component')

**Comment by driesvints** [comment]
Can you perhaps post a html snippet of the code that's tested and an example test? Would help me to figure the best way to solve this.

**Comment by asjsrep** [comment]
Sure:

HTML
 ```
<html>
<body>
<script src="https://unpkg.com/vue"></script>
<div id="app" dusk="vue-contains-test">
    <ul>
        <li v-for="item in items">{{item}}</li>
    </ul>
</div>
<script>
    new Vue({
        el: '#app',
        data: {
            items: ['item 1', 'item 2']
        }
    })
</script>
</body>
</html> 

```
Example test

```
 $this->browse(function (Browser $browser) {
            $browser->visit('/vue-contains-test')
                ->assertVueContains('items', 'item 1', '@vue-contains-test');
        });
```


Expected result: Test pass
Current result: `ErrorException: mb_strpos() expects parameter 1 to be string, array given`

**Comment by driesvints** [comment]
Thanks. I sent in a PR. Will be merged an released soon.
