### ISSUE TITLE
Mocking time

### ISSUE THREAD

**Issue by ice-blaze** [laravel/dusk#647]
Is there a way to mock time during a Dusk test?

I tried to use `Carbon::setTestNow(Carbon::create(2000, 01, 01));` but if my test fail and I display current date in the blade template, it displays today :/

**Comment by staudenmeir** [comment]
Your approach doesn't work because the Dusk test and your application run in separate processes.

Do you want to mock the time in all Dusk tests or only a single one?

**Comment by ice-blaze** [comment]
It would be ideally to change the time in only one test. For exemple:

```
...
    public function testMyExample()
    {
        $this->browse(function (Browser $browser) {
            $products = factory(Loan::class)->create();
            Carbon::setTestNow(Carbon::create(2019, 05, 22));
            $browser->doAction();
            Carbon::setTestNow(Carbon::create(2019, 05, 26));
            $browser->assertLoanIsLate();
    }
...
```

**Comment by staudenmeir** [comment]
You can (ab)use the `.env` file to achieve this:

```php
public function testMyExample()
{
    $this->browse(function (Browser $browser) {
        $loan = factory(Loan::class)->create();

        $path = base_path('.env');
        $env = file_get_contents($path);
        file_put_contents($path, $env."\nMOCK_TIME=2019-05-22");

        $browser->doAction();

        // Only necessary, if you are not using a .env.dusk.local file.
        file_put_contents($path, $env);

        $browser->assertLoanIsLate();
    }
}
```

Put this somewhere in your application, e.g. in `AppServiceProvider::boot()`:

```php
if (env('MOCK_TIME')) {
    Carbon::setTestNow(new Carbon(env('MOCK_TIME')));
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ice-blaze** [comment]
@staudenmeir I'll try tomorrow and keep you up to date.

@driesvints The issue was more about a feature than a solution on my specific problem. I still open the issue because I was quite sure there were no solution with a Dusk function. So the question now is: should Dusk have this kind of function? (and not using a workaround with `.env` files) I have the feeling it should because for example laravel have schedulers, and it would help to test them too. Maybe there is already something that I didn't found on the internet.

Also I guess some people would say "don't use Dusk to test this kind of things, unit tests are fine". I might be wrong but I prefer end2end tests. But I guess it's another topic.

**Comment by ice-blaze** [comment]
@staudenmeir It works but it breaks the laravel authentication. I tryied removing the `csrf` and add a very big `session.lifetime` but none works. Because it's the authentication I guess it's not part of the scope of this issue.

**Comment by staudenmeir** [comment]
> So the question now is: should Dusk have this kind of function?

Even if we wanted, I don't think we could add such a feature.

**Comment by ice-blaze** [comment]
@staudenmeir Then how are devs testing things like cron job? Do they need to use work around with env variables?

**Comment by staudenmeir** [comment]
Dusk is only meant for Browser tests. How would you use it to test cron jobs?

**Comment by ice-blaze** [comment]
For example if you want to send an email after 1 hour if the user didn't see the notification on the website.

**Comment by staudenmeir** [comment]
Dusk is not meant for tests like this.

**Comment by ice-blaze** [comment]
Ok, thank you for your insight and time.

**Comment by elsodev** [comment]
Just for future reference, actually here's a trick to get browser process's carbon date in synced with your test process. 

https://nedex.io/how-to-time-travel-in-laravel-dusk-using-carbon/

**Comment by tpaksu** [comment]
I just released a package with the same idea (thanks @staudenmeir) can you check it? it uses cookies to deliver the time to the browser, and a middleware to check the cookie and act as it traveled time. https://github.com/paksuco/dusk-time-travel

**Comment by Balex70** [comment]
> I just released a package with the same idea (thanks @staudenmeir) can you check it? it uses cookies to deliver the time to the browser, and a middleware to check the cookie and act as it traveled time. https://github.com/paksuco/dusk-time-travel

Thanks for your package. It works great!
