### ISSUE TITLE
Failed to connect to localhost port 9515: Connection refused

### ISSUE THREAD

**Issue by APdevelopments** [laravel/dusk#648]
- Dusk Version: 2.0
- Laravel Version: 5.5
- PHP Version: 7.2
- Database Driver & Version:

### Description:
I want to create a test which I will use from Controller so I write:

```
<?php

namespace App\Http\Controllers\Modules;
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Laravel\Dusk\ElementResolver;
use Exception;

use Facebook\WebDriver\Chrome\ChromeOptions;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Laravel\Dusk\Browser;
use Laravel\Dusk\Chrome\ChromeProcess;

class TestController extends Controller {



  public function test() {

    $process = (new ChromeProcess)->toProcess();
    if ($process->isStarted()) {
      $process->stop();
    }
    $process->start();

    $options      = (new ChromeOptions)->addArguments(['--disable-gpu', '--headless', '--no-sandbox']);
    $capabilities = DesiredCapabilities::chrome()
      ->setCapability(ChromeOptions::CAPABILITY, $options);

          $driver = retry(1, function () use ($capabilities) {
      return RemoteWebDriver::create('http://localhost:9515', $capabilities, 60000, 60000);
    }, 50);

    $browser = new Browser($driver, new ElementResolver($driver, ''));
    $browser->resize(1920, 1080);
    $browser->visit('https://example.com/login')->click('#.btn > form > div.auth-form-body.mt-3 > input.btn.btn-primary.btn-block');
    $browser->driver->takeScreenshot(base_path('tests/Browser/screenshots/logged.png'));

  }


}
```
When I run this script using localhost:8000/test I got this message:

> Facebook \ WebDriver \ Exception \ WebDriverCurlException Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"chrome","platform":"ANY","chromeOptions":{"binary":"","args":["--disable-gpu","--headless","--no-sandbox"]}}} Failed to connect to localhost port 9515: Connection refused

**How I can solve this problem?

Current I use WAMP server on Win10 for local testing but then I will move the code on Linux Ubuntu 18.**

I tried some test with artisan commands and works fine but I cant run with from controller. Why?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by Tarasovych** [comment]
@APdevelopments [give it a shot](https://github.com/laravel/dusk/issues/50#issuecomment-275155974)
