### ISSUE TITLE
Adding assertHasOption and assertHasOptions

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/dusk#65]
It would be very nice to have an assert if the dropdown menu contains given value(s). For example:

```
->assertHasOption('@countries', 'Finland');
->assertHasOptions('@countries', ['Finland', 'Sweden]);
```
I tried to look to the Facebook Webdriver API to make a PR but it went little bit over my head. Maybe somebody more capable would like to implement this?

**Comment by splatEric** [comment]
you can implement additional assertions as macros ... I wrote up an example of it here: https://medium.com/@splatEric/writing-tests-with-laravel-dusk-bb755c0dcb1f#.5hj9en9b8

I would imagine the intention is to avoid proliferating too many additional assertions in the core, but I could be wrong ...
