### ISSUE TITLE
Insert data into DB in `headless` mode

### ISSUE THREAD

**Issue by atefBB** [laravel/dusk#650]
Hi. I'm using `dusk` for scrapping data from a website, and I'm trying to `insert` data into an existing `mysql` DB, this scenario works in `non-headless` mode but not in `headless` mode.
Is that the `default` behavior with `headless` mode or I'm missing a thing?
Any information could help.
Thank you.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by atefBB** [comment]
@driesvints Thank you for reference !
I think it's a `missing part` in documentation.
I think that testing (/interracting with) DB connection is a commen use case !
Hope to see `illuminate` for this issue in the documentation.

**Comment by staudenmeir** [comment]
The (non-)headless mode is not related to the database connection in any way.

**Comment by atefBB** [comment]
@staudenmeir did you that you cannot use database in `headless` mode or what?

**Comment by staudenmeir** [comment]
No, I meant that the (non-)headless mode doesn't affect the database connection.

The issue in your code must be somewhere before the database connection is used.

**Comment by atefBB** [comment]
My code work fine in `non-headless` mode (The data is inserted into DB) but not in `headless` mode. So the issue occurs in `headless` mode.
