### ISSUE TITLE
Can i use assertTrue in Tests\Browser\Pages?

### ISSUE THREAD

**Issue by Thanikaikumaran** [laravel/dusk#658]
I have write function with assertTrue in page file and i used that function on DuskTestCase.
```
class MyPage extends Page
{
   public function validation(Browser $browser){
       $browser ->clickLink('Sources') ;
       $this->assertTrue(count($browser->driver->findElements(WebDriverBy::xpath('//*[@id="home"]'))) > 0);
    }
}

class MyTest extends DuskTestCase
{
    public function test001()  {
        $this->browse(function (Browser $browser) {            
            $browser->visit(new MyPage)
                    ->validation();
     });    
    }
}
```
Error: Call to undefined method Tests\Browser\Pages\MyPage::assertTrue()

Can anyone help me?

Thank you.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by staudenmeir** [comment]
Use static assertions:

```php
use PHPUnit\Framework\Assert;

class MyPage extends Page
{
    public function validation(Browser $browser)
    {
        $browser ->clickLink('Sources');

        Assert::assertTrue(count($browser->driver->findElements(WebDriverBy::xpath('//*[@id="home"]'))) > 0);
     }
}
```

**Comment by Thanikaikumaran** [comment]
Thank you @staudenmeir. it is working now
