### ISSUE TITLE
UnexpectedAlertOpenException: unexpected alert open: {Alert text : Are you sure?}

### ISSUE THREAD

**Issue by disitec** [laravel/dusk#66]
I am getting this exception when I click the delete button

How could I expect a confirm alert in screen and then press OK?

**Comment by andremellow** [comment]
You can use 
$browser->acceptDialog();

**Comment by deleugpn** [comment]
Can this be closed?

**Comment by Lyfeway** [comment]
`$browser->dismissDialog()` I think can close alert.
But I can not find api how to interact with javascript `confirm()`.

**Comment by greatwitenorth** [comment]
I have something like this:
```
$this->browse(function (Browser $browser) {
            $browser->visit('/')
                ->type('name', 'Jonh')
                ->type('email', '')
                ->type('phone', '555-555-5555')
                ->click('.btn-next')
                ->assertDialogOpened("Email is required");
        });
```

When I run the tests I see this error:
```
1) Tests\Browser\PickupFormTest::testMustFillRequiredToProceed
Facebook\WebDriver\Exception\UnexpectedAlertOpenException: unexpected alert open: {Alert text : Email is required
Please provide a valid email}
```

Shouldn't ```assertDialogOpened()``` expect the alert to open and verify the correct text? Why is it throwing an ```UnexpectedAlertOpenException```?

**Comment by taufek** [comment]
I think if you do below it will passed (added `acceptDialog` at the end)

```
$browser->visit('/')
                ->type('name', 'Jonh')
                ->type('email', '')
                ->type('phone', '555-555-5555')
                ->click('.btn-next')
                ->assertDialogOpened("Email is required")
                ->acceptDialog();
```

**Comment by amree** [comment]
I think this is related to Chrome's bug itself. The bug has been fixed, but it hasn't been released yet.

Basically you can't verify the message in the dialog as the dialog has been closed automatically.

For now, you can either use js library for the popup or just test what happens after the dialog was closed.

Bug ticket: https://bugs.chromium.org/p/chromium/issues/detail?id=718235

**Comment by eduardocruz** [comment]
Having the same issue and using `->acceptDialog();` didn't work.

**Comment by staudenmeir** [comment]
Please post the relevant parts of your code.

**Comment by splatEric** [comment]
although this is closed, I came across this because I was having some issues with this. It turned out that the message I had in my `assertDialogOpened` didn't exactly match the message that was being displayed, which was then triggering the exception regardless of any other actions I had in place.

Long and short of it, make sure you are accepting a dialog with the correct text.

**Comment by nick66551** [comment]
Hi All, maybe you need `$browser->waitForDialog($seconds = null);` to wait until alert dialog appear.

**Comment by 35grain** [comment]
> Adding a slight delay did the trick, even though to my eyes the alert comes up instantly after the previous action.
