### ISSUE TITLE
Facebook\WebDriver\Exception\UnrecognizedExceptionException: invalid argument

### ISSUE THREAD

**Issue by latifasaee** [laravel/dusk#660]
laravel verison:  5.7
 `"laravel/dusk": "^5.3",`

I am getting the error and am not sure what is wrong. Any help would be greatly appreciated! 

Warning: TTY mode is not supported on Windows platform.
PHPUnit 7.5.14 by Sebastian Bergmann and contributors.

DevTools listening on ws://127.0.0.1:54711/devtools/browser/59cc17d2-8d02-4258-9702-8504dcae8bd5
E                                                                   1 / 1 (100%)

Time: 2.52 seconds, Memory: 12.00 MB

There was 1 error:

1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\UnrecognizedExceptionException: invalid argument
  (Session info: headless chrome=75.0.3770.142)
  (Driver info: chromedriver=75.0.3770.140 (2d9f97485c7b07dc18a74666574f19176731995c-refs/branch-heads/3770@{#1155}),platform=Windows N
T 10.0.17134 x86_64)

C:\dev\walker\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:158
C:\dev\walker\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php:331
C:\dev\walker\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php:565
C:\dev\walker\vendor\facebook\webdriver\lib\Remote\RemoteExecuteMethod.php:40
C:\dev\walker\vendor\facebook\webdriver\lib\WebDriverNavigation.php:85
C:\dev\walker\vendor\laravel\dusk\src\Browser.php:139
C:\dev\walker\tests\Browser\ExampleTest.php:19
C:\dev\walker\vendor\laravel\dusk\src\Concerns\ProvidesBrowser.php:67
C:\dev\walker\tests\Browser\ExampleTest.php:21

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.

`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
