### ISSUE TITLE
Update Chrome driver to support browser v74

### ISSUE THREAD

**Issue by blakethepatton** [laravel/dusk#665]
We are running unit tests with dusk in circle ci, recently our tests started failing because chrome had updated to version 74. When running tests we get the error: `Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: Chrome version must be between 70 and 73`. It makes sense for dusk to be updated/upgraded to work with the newer version of chrome.

**Comment by staudenmeir** [comment]
Please fill out the issue template.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/dusk/issues/651 and try a support channel: 

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
