### ISSUE TITLE
Please change "dusk" attribute to "data-dusk"

### ISSUE THREAD

**Issue by adrienne** [laravel/dusk#666]
Currently the documentation says the following:

> Dusk selectors allow you to focus on writing effective tests rather than remembering CSS selectors. To define a selector, add a `dusk` attribute to your HTML element. Then, prefix the selector with `@` to manipulate the attached element within a Dusk test

This creates invalid HTML. Can you please change it (or at least allow a configuration option) so that instead of `dusk` the relevant attribute is `data-dusk`? All custom attributes in HTML are supposed to be prefixed with `data-`.

**Comment by driesvints** [comment]
Feel free to send in a pr

**Comment by adrienne** [comment]
@driesvints - I was just annoyed enough to do this. Here. https://github.com/laravel/dusk/pull/669

**Comment by pataar** [comment]
FWIW: https://github.com/laravel/dusk/pull/1012

**Comment by rossjcooper** [comment]
For anyone who comes here from Google you can now do this and it is documented here https://laravel.com/docs/10.x/dusk#dusk-selectors

**Comment by dualklip** [comment]
> For anyone who comes here from Google you can now do this and it is documented here https://laravel.com/docs/10.x/dusk#dusk-selectors

Thank you @rossjcooper . That what exactly I needed
