### ISSUE TITLE
Dusk not working because Chrome driver minor version different from installed Chrome version

### ISSUE THREAD

**Issue by manogi** [laravel/dusk#667]
- Dusk Version: 5.5.0
- Laravel Version: 5.8.33
- PHP Version: 7.3

### Description:

I get this error. I know something like this this has been reported before, but the solution seems to be to install the exact same Chrome version on my Mac as the driver version Dus uses, and I don't know how I can do that. 

Can someone help, please?

```
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created
from disconnected: unable to connect to renderer
  (Session info: headless chrome=76.0.3809.100)
  (Driver info: chromedriver=76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}),platform=Mac OS X 10.14.6 x86_64)
```

**Comment by driesvints** [comment]
Please see https://github.com/laravel/dusk/issues/641

**Comment by manogi** [comment]
Thanks, but unfortunately there is no solution in that issue which helps me - plus comments are closed there. You wrote „make sure to use the the same version....“ but how should I do that? It is the patch version which is different and I cannot upgrade my browser to .126 - that does not seem to be available. Also I can‘t downgrade the version used in Dusk to .100, so I basically cannot use Dusk.

**Comment by driesvints** [comment]
Doesn't https://laravel.com/docs/5.8/dusk#managing-chromedriver-installations work for you?

**Comment by manogi** [comment]
No, unfortunately that only lets me install the patch version .126, while my Chrome browser can't be updated from .100 to .126.

**Comment by manogi** [comment]
Wait! If you are looking into this, please stop!
I found out that the differing versions are NOT the problem, but a missing entry in my `/etc/hosts` file. For anybody who sees this, the entry
```
127.0.0.1  localhost
```
must exists in that file. Sorry for the trouble, I don't know when and how I removed that entry.

**Comment by staudenmeir** [comment]
Only the first three parts of the version number match: http://chromedriver.chromium.org/downloads/version-selection
