### ISSUE TITLE
$browser->loginAs(1) throws server exception but WebDriver does not fail.

### ISSUE THREAD

**Issue by tvanrielwendrich** [laravel/dusk#675]
- Chrome Driver version: 77
- Dusk Version: 5.0.x-dev (updated less than an hour before this post)
- Laravel Version: 5.8.35
- PHP Version: 7.93.9
- Database Driver & Version: MariaDB 10.3

### Description:
When attempting to authenticate the browser for my application using the loginAs method, the browser does not throw an error even though the server responds with 500.

I'd much rather know why I can't authenticate in the first place but it's surely intereresting. 

Getting the browser to take a screenshot of the output shows:
```php
$browser->loginAs(AdminDetails::first()->user->id)->screenshot('failed_login')
```
![kaas](https://user-images.githubusercontent.com/50411291/64706611-14d0b480-d4b2-11e9-8222-809eea27255c.png)

When `dump()`'ing `AdminDetails::first()->user()->email` I do see the correct email address from the seeder, so the user must surely exist.

The only interesting bit about my environment is that I use a dockerized Google Chrome and MariaDB container because of the mess with MySQL 8.0 and 5.7 version incompatibility...

**Comment by tvanrielwendrich** [comment]
After further inspection it seems it cannot find the user by it's ID in the `Laravel\Dusk\Http\Controllers\UserController`. The provider is failing. But it's strange that the the Client and Server just continue without a proper error. nothing like "Exception, server threw a 500 at me". Or "this user does not exist".

**Comment by Bubalubs** [comment]
I have same problem and you get the same error page as your screenshot when you go to /_dusk/login/1

**Comment by Bubalubs** [comment]
Okay this is very weird, if you use `/_dusk/login/2` or `/_dusk/login/3` it works fine only the ID 1 isn't working?

In my test I can do this to make it work and pass:
```
$user = factory(User::class)->create();
$user2 = factory(User::class)->create();

$this->browse(function ($browser) use ($user2) {
    $browser->loginAs($user2)
        ->visit('/dashboard')
        ->assertPathIs('/dashboard');
    });
```

However this doesn't work:
```
$user = factory(User::class)->create();

$this->browse(function ($browser) use ($user) {
    $browser->loginAs($user)
        ->visit('/dashboard')
        ->assertPathIs('/dashboard');
    });
```

It just doesn't seem to like the ID 1? I will try look more into it.

**Comment by driesvints** [comment]
I can reproduce this. I have no idea what's happening. First I thought it was something environment related but that doesn't seems to be the case. Tested with a vanilla Laravel install with dusk and the following test case:

```php
<?php

namespace Tests\Browser;

use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\DuskTestCase;
use Laravel\Dusk\Browser;

class ExampleTest extends DuskTestCase
{
    use RefreshDatabase;

    /**
     * A basic browser test example.
     *
     * @return void
     */
    public function testBasicExample()
    {
        $this->browse(function (Browser $browser) {
            factory(User::class)->create();

            $browser->loginAs(1)->screenshot('failed_login');
        });
    }
}
```

This reproduces the error from above. Afaik the user should be seeded and available for the test.

**Comment by tvanrielwendrich** [comment]
Hi Dries, thanks for responding. 
The code I used would have failed before loginAs, because AdminDetails::first()->user would have been unable to retrieve a user id. So yes, that would mean the user is indeed seeded for me too.

**Comment by driesvints** [comment]
I found out what's wrong. You shouldn't use the `RefreshDatabase`. If you use `DatabaseMigrations` instead, everything works as expected.

I glanced over this at first as well but there's a note in the docs about this here: https://laravel.com/docs/6.x/dusk#migrations
