### ISSUE TITLE
window7 is not can use chrome 

### ISSUE THREAD

**Issue by kinyou** [laravel/dusk#679]
- Dusk Version: v5.5.1 
- Laravel Version: 5.8.35
- PHP Version: 7.1.1 
- Database Driver & Version:  mysql  v5.7.5

### Description:
i install laravel\dusk success but when i run the php artisan dusk 
it can not use chrome

### Steps To Reproduce:
Starting ChromeDriver 77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
