### ISSUE TITLE
Configuration File for Dusk? Support for alternative testing directories

### ISSUE THREAD

**Issue by edmundluong** [laravel/dusk#68]
Hi,

I was wondering if it would be possible to add a configuration file for Dusk so that we may use an alternative name for our testing directory.

In my project, we have renamed our `tests` directory to `app-tests`, but the `purgeScreenshots` method in `DuskCommand` expects the testing directory to be named `tests`: 

 https://github.com/laravel/dusk/blob/master/src/Console/DuskCommand.php#L97

Thoughts? Thanks and best regards.

**Comment by rBrda** [comment]
+1

I was just about to suggest the same. It would be great to include Dusk tests in my packages.

**Comment by dducro** [comment]
+1

I'm also looking for a way to include dusk tests in packages, any info on adding this in the future?

**Comment by i5nicca** [comment]
+1

Will be nice to have configuration file.

**Comment by driesvints** [comment]
Gonna close this in favor of https://github.com/laravel/dusk/issues/393
