### ISSUE TITLE
Provide warning when configuration is cached

### ISSUE THREAD

**Issue by splatEric** [laravel/dusk#681]
I ran into a slightly frustrating issue today, where I had cached my configuration during some previous work, and then was having trouble with dusk not picking up the dusk specific env configuration (because the application was sticking with the cached configuration).

I was wondering whether you would be amenable to one of either:
1. Displaying a warning to users that cached configuration may cause problems from the dusk command.
1. Automatically clearing the cached configuration as part of the dusk command when dusk configuration was detected.

I'd be happy to implement either and submit a PR, but wanted to see whether it was something that would be welcomed before making the submission? And of course which route you would prefer to take.

**Comment by driesvints** [comment]
It's unfeasible to display this every time. This is a common issue that pops up a lot and is documented in the Laravel documentation. 

https://laravel.com/docs/6.x/configuration#configuration-caching

> You should typically run the php artisan config:cache command as part of your production deployment routine. The command should not be run during local development as configuration options will frequently need to be changed during the course of your application's development.

**Comment by splatEric** [comment]
well I guess my point is that that documentation is quite far removed from the dusk documentation, and so not an immediately obvious connection. 

One can certainly argue I made a mistake to have cached it (it was actually me running a production `make` command locally).

But it's not unfeasible, it's a simple check to `isConfigurationCached` within the `DuskCommand` to then display a helpful warning message.
