### ISSUE TITLE
Chrome Flashes instead of Running Tests

### ISSUE THREAD

**Issue by Binternet** [laravel/dusk#685]
- Dusk Version: dono, I assume 5.4 like laravel?
- Laravel Version: 5.4.36
- PHP Version: 5.6.32
- Database Driver & Version: MySQL 5.6.38

### Description:
Chrome is currently on version 78.0.3904.70 and ChromeDriver is also on 78.0.3904.70
yet when I run `php artisan dusk` chrome just flashes and no tests are performed.

I've updated dusk via `npm` since when I try to update it via `php artisan dusk:update` i'm getting:

```
$ php artisan dusk:update

In UpdateCommand.php line 174:

  Undefined offset: 1
```

### Steps To Reproduce:
`php artisan dusk`

**Comment by Binternet** [comment]
Seems to be running OK now if i'm manually running the `chromedriver`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by Dalot** [comment]
I am currently having the same issue and I am running Laravel 5.8.

I'm sorry about the strange characters, they are happening on git bash, not being able to solve it.

$ php artisan dusk:chrome-driver 78
O sistema não conseguiu localizar o caminho especificado.

```
  ?[41;1m ErrorException ?[49;22m : ?[33mfile_get_contents(): SSL: A operao foi concluda com xito.
?[39m

  at ?[32mC:\Users\Dalot\Documents\SafeMinds\Datalink\gcp\vendor\laravel\dusk\src\Console\ChromeDriverCommand.php?[39m:?[32m249?[39m
    245|         }
    246|
    247|         $streamContext = stream_context_create($contextOptions);
    248|
  > 249|         return file_get_contents($url, false, $streamContext);
    250|     }
    251| }
    252|

  ?[33mException trace:?[39m

  ?[36m1   ?[39m?[33mfile_get_contents("https://chromedriver.storage.googleapis.com/LATEST_RELEASE_78")?[39m
      ?[32mC:\Users\Dalot\Documents\SafeMinds\Datalink\gcp\vendor\laravel\dusk\src\Console\ChromeDriverCommand.php?[39m:?[32m249?[39m

  ?[36m2   ?[39m?[33mLaravel\Dusk\Console\ChromeDriverCommand::getUrl("https://chromedriver.storage.googleapis.com/LATEST_RELEASE_78")?[39m
      ?[32mC:\Users\Dalot\Documents\SafeMinds\Datalink\gcp\vendor\laravel\dusk\src\Console\ChromeDriverCommand.php?[39m:?[32m157?[39m

  ?[32mPlease use the argument ?[39m?[31m-v?[39m?[32m to see more details.?[39m
```

**Comment by driesvints** [comment]
Is the problem also happening for Chrome 77?

**Comment by Dalot** [comment]
It's happening for chrome 78 like the original post. Was also happening for chrome 77, well, that was actually the reason I just updated chrome but ended having the same issue.

**Comment by driesvints** [comment]
I can run Dusk just fine with Chrome 78:

```
 $ php artisan dusk                                                                                                                                                       ~/Sites/debug
PHPUnit 8.4.2 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 894 ms, Memory: 16.00 MB

OK (1 test, 1 assertion)
```

**Comment by Dalot** [comment]
I was having a problem with ssl, probably because of our local network, not sure what's the problem and I was not being able to update chromedriver to latest version -> 78.

I was running a package to update chrome drivers and changed momentarily every link from https://chromedriver.storage.googleapis.com to HTTP protocol and now it's working fine.
