### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function Laravel\Dusk\Console\pcntl_async_signals()

### ISSUE THREAD

**Issue by aFluxx** [laravel/dusk#688]
- Dusk Version: 5.6.0
- Laravel Version: 6.4.1
- PHP Version: 7.3.9
- Database Driver & Version: Dusk runs on MySQl, but I'm not sure how to get the version
- ChromeDriver: 78.0.3904.70

### Description:

I haven't used Dusk in a while, today I tried to run it and I got a `Call to undefined function` error.

```
 Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function Laravel\Dusk\Console\pcntl_async_signals()

  at C:\Users\Arne\Desktop\simsala\vendor\laravel\dusk\src\Console\DuskCommand.php:254
    250|      * @return void
    251|      */
    252|     protected function setupSignalHandler()
    253|     {
  > 254|         pcntl_async_signals(true);
    255| 
    256|         pcntl_signal(SIGINT, function () {
    257|             $this->teardownDuskEnviroment();
    258|         });

  Exception trace:

  1   Laravel\Dusk\Console\DuskCommand::setupSignalHandler()
      C:\Users\Arne\Desktop\simsala\vendor\laravel\dusk\src\Console\DuskCommand.php:196

  2   Laravel\Dusk\Console\DuskCommand::setupDuskEnvironment()
      C:\Users\Arne\Desktop\simsala\vendor\laravel\dusk\src\Console\DuskCommand.php:170
```

### Steps To Reproduce:

Run: `php artisan dusk`

I will try de-installing & re-installing dusk as a next step.

**Comment by aFluxx** [comment]
Some more information:

I used to run all my dusk tests on my host (Windows) machine.
If I run dusk in vagrant, everything works fine.

My best guess is that my host machine is missing the pcntl extension, but I can't find out how it used to work on my host.

**Comment by lokmanm** [comment]
They added a dependency for `ext-pcntl` and now every Laravel installation running on anything other than Vagrant will not work. I haven't found any workarounds on this.

**Comment by driesvints** [comment]
Going to close this over https://github.com/laravel/dusk/issues/689

You can temporarily circumvent this with https://github.com/laravel/dusk/issues/689#issuecomment-551031718

**Comment by zahirzohair** [comment]
I have the same type of issue on laravel 6.0. basically i updated laravel 5.8 to 6.0 and installed dusk on it and then run: php artisan dusk .  it gives me this error: 
In DuskCommand.php line 251:

  Call to undefined function Laravel\Dusk\Console\pcntl_async_signals()

any solution please? Thanks!

**Comment by miztizm** [comment]
Hello, I'm experiencing the same error with version 8.2 and PHP 8.2. Pcntl is installed and activated.
