### ISSUE TITLE
Issue with ext-pcntl

### ISSUE THREAD

**Issue by lk77** [laravel/dusk#689]
- Dusk Version:5.6.0
- Laravel Version: 6.4.1
- PHP Version: 7.3.1
- Database Driver & Version: mysql 5.7

### Description:

A dependency has been added in 5.6.0 to ext-pcntl, and it's breaking everything, the extension needs to be added to the docker test image. Why such a change on a minor update ? 
This type of changes should go to next major version 6.0 i think.

thanks.

**Comment by leecrosdale** [comment]
@lk77 was there a fix you found for this?

**Comment by lk77** [comment]
@leecrosdale i reverted to 5.5 for now due to another issue, 
but you need to enable pcntl in php, for example for docker :
```
RUN docker-php-ext-install pcntl
```

**Comment by leecrosdale** [comment]
Ah ok, a couple of devs here are running windows, where PCNTL isn't available. 

We ended up doing

`composer install --ignore-platform-reqs`

which seems to work for now!

**Comment by lk77** [comment]
yes, we had the same issue for windows.
Honestly i think this should be an optional dependency.

**Comment by driesvints** [comment]
Hmm, that indeed seems to have broken Windows support. We'll try to reverse it later today.

**Comment by driesvints** [comment]
This was the PR btw: https://github.com/laravel/dusk/pull/682

**Comment by driesvints** [comment]
I send in a PR here: https://github.com/laravel/dusk/pull/692

If anyone can verify that this works on Windows that'd be great.

**Comment by asbiin** [comment]
@driesvints I can confirm it "works" on Windows == I can install it without `--ignore-platform-reqs`, and it can run tests.
