### ISSUE TITLE
Exit code 0 on failed tests

### ISSUE THREAD

**Issue by petermein** [laravel/dusk#690]
- Dusk Version: 5.6
- Laravel Version: 6.0.4
- PHP Version: 7.2.23
- Database Driver & Version: multiple
- PHPUnit: 8.4.2
- Environment: CircleCi and Local

### Description:
When looking at our CircleCi tests and local tests, we noticed even when test failed the exit code returned from the `php artisan dusk` command is still 0. This means even if you publish test results the test will be marked as successfull 

### Steps To Reproduce:

- Run in bash `php artisan dusk && echo "$?" || echo "$?"` (with atleast 1 failing test)
This will display an exit code of 0 in our tests. 

```E                                                                   1 / 1 (100%)

Time: 9.05 seconds, Memory: 44.25 MB

There was 1 error:

1) Tests\Browser\Tests\TwoFactorLoginTest::testTwoFactorLogin
Facebook\WebDriver\Exception\TimeOutException: Waited 5 seconds for callback.

/var/www/vendor/laravel/dusk/src/Concerns/WaitsForElements.php:261
/var/www/vendor/laravel/dusk/src/Concerns/InteractsWithElements.php:296
/var/www/tests/Browser/Tests/TwoFactorLoginTest.php:36
/var/www/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:67
/var/www/tests/Browser/Tests/TwoFactorLoginTest.php:43

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
0
```

**Comment by mnabialek** [comment]
It can be true. I noticed this yesterday when upgraded Dusk to latest.

**Comment by petermein** [comment]
There was a return statement missing in the last update when adding the SIGINT. 
I've added a PR #691

**Comment by petermein** [comment]
PR #691 is merged @driesvints could you create a new version and push it to packagist?

**Comment by driesvints** [comment]
@petermein new version will be released tomorrow on release day.
