### ISSUE TITLE
Runs test cases starting with the same name

### ISSUE THREAD

**Issue by carlosalzate74** [laravel/dusk#694]
- Dusk Version: 5.5
- Laravel Version: 5.8
- PHP Version: 7.3
- Database Driver & Version: Postgres 10

### Description:
Not sure if it is a bug. I have two test cases named testEditUser and testEditUserPermissions. When I run  php artisan dusk --filter testEditUser, it runs both, one after the other.

Is it an expected behavior?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
