### ISSUE TITLE
Not able to click modal in dusk dashboard

### ISSUE THREAD

**Issue by papithanandagopal** [laravel/dusk#695]
- Dusk Version: 4.0.#
- Laravel Version: 5.6.
- PHP Version: 7.1.3
- Database Driver & Version:

### Description:
Unable to click modal in dusk dashboard mode, but what's irony about this it works in normal mode
Command for dashboard dusk to run :php artisan dusk:dashboard
Command to run normal mode:php artisan dusk

### Steps To Reproduce:
Anchor Link is like 
<a href="#" id="edituser">Edit User</a>

Modal is called by using
jquery function
$('#edituser').click(function(event) {
    $('#userEditModal').modal('show');
    $.get('/getdata', function(data) {
         $("#app_id").append("<option value=''>Please choose</option>");
        $.each(data.app, function(array, value) {
          $("#app_id").append("<option value=" + value['id'] + ">" + value['name'] + "</option>");
        });
    }
}

The test case is working when the comman php artisan dusk is triggered
But in order to see the whole test case status and the dashboard 
When the command php artisan dusk:dashboard the testing get terminated in this specific test case the upcoming scenarios are not working 

I believe this is a bug incase if this is already solved kindly share the link 
By the way this is my first bug reporting

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
