### ISSUE TITLE
Artisan Dusk keeps restarting chrome and doesn't test anything

### ISSUE THREAD

**Issue by RicoNijeboer** [laravel/dusk#700]
- OS: MacOS 10.14.6
- Dusk Version: 5.6.2
- Laravel Version: 6.6.0
- PHP Version: 7.3.7
- Database Driver & Version:
  - MySql 5.7
- Chrome Version: 78.0.3904.108

### Description:
When I try to run `php artisan dusk` PHPUnit starts, but then I keep getting a Chrome that opens but instantly closes. I think the reason this happens is because of the Chrome version I use on my laptop.

### Steps To Reproduce:
1. Create a dusk test environment
2. Create a basic dusk test
3. Execute `php artisan dusk`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by sagar-noovosoft** [comment]
@RicoNijeboer ```php artisan dusk:chrome-driver```
