### ISSUE TITLE
DatabaseMigrations is causing an error in Dusk test

### ISSUE THREAD

**Issue by jfsullivan** [laravel/dusk#708]
- Dusk Version: v5.7.0
- Laravel Version: v6.8.0
- PHP Version: 7.4.0
- Database Driver & Version: MySQL 8.0.18

### Description:
When I add the DatabaseMigrations trait to my Dusk test I get the error below.  If I remove it I get an error that the table doesn't exist, which makes sense because the migration doesn't run.  The migrations run fine when run manually.

Here is the error output....

> 1) Tests\Browser\HomePageTest::home_page_shows_upcoming_sessions
> ErrorException: Trying to access array offset on value of type null
> 
> /home/vagrant/Code/BogeyBrain/vendor/laravel/telescope/src/Watchers/QueryWatcher.php:46
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:347  
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:196  
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Database/Connection.php:833
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Database/Connection.php:687
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Database/Connection.php:640
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Database/Connection.php:338
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php:99
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php:48
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Database/Console/WipeCommand.php:67
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Database/Console/WipeCommand.php:46
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Container/Util.php:36
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Container/Container.php:590
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Console/Command.php:202
> /home/vagrant/Code/BogeyBrain/vendor/symfony/console/Command/Command.php:255
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Console/Command.php:189
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Console/Command.php:242
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Console/Command.php:214
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/FreshCommand.php:41
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Container/Util.php:36
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Container/Container.php:590
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Console/Command.php:202
> /home/vagrant/Code/BogeyBrain/vendor/symfony/console/Command/Command.php:255
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Console/Command.php:189
> /home/vagrant/Code/BogeyBrain/vendor/symfony/console/Application.php:1011
> /home/vagrant/Code/BogeyBrain/vendor/symfony/console/Application.php:272
> /home/vagrant/Code/BogeyBrain/vendor/symfony/console/Application.php:148
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Console/Application.php:93
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Console/Application.php:185
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:273
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Foundation/Testing/PendingCommand.php:136
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Foundation/Testing/PendingCommand.php:220
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithConsole.php:56
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Foundation/Testing/DatabaseMigrations.php:16
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:119
> /home/vagrant/Code/BogeyBrain/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:82
> /home/vagrant/Code/BogeyBrain/vendor/laravel/dusk/src/TestCase.php:23

### Steps To Reproduce:

1. Create a Dusk Test
2. Add the DatabaseMigrations trait to the test.
3. Run the test.

**Comment by driesvints** [comment]
I can use the trait just fine on a MySQL and Sqlite database. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
