### ISSUE TITLE
Reset selector scope when switching window/frame context

### ISSUE THREAD

**Issue by alecpl** [laravel/dusk#722]
Let's consider this code:
```
$browser->with('.dialog', function ($browser) {
    $browser->withinFrame('#dialog-frame', function($browser) {
        $browser->assertVisible('.test');
    });
});
```
The assert will always fail because it will be looking for `.dialog .test` selector (or sth like that, I'm writing from my memory).

You may consider it rather a limitation not a bug, but I think it would make sense to reset the selector scope whenever switching to another iframe/window context.

Dusk 5.8.1.

**Comment by driesvints** [comment]
Please fill out the issue template.

**Comment by alecpl** [comment]
What info do you need? Is the code sample/description not clear enough? PHP 7.4.1, Dusk 5.8.1. I'm not using Laravel Framework.

Looking at the code of `Browser::withinFrame()`, I guess you should reset `$this->resolver->prefix` before calling callback function and set it to previous value after the callback.

**Comment by driesvints** [comment]
We only support using the package with the framework, sorry.

**Comment by alecpl** [comment]
I understand your time is limited, (I'm open source developer too), but did you at least verify the issue does not exist in a supported environment? Should I lie next time I create a ticket here with a real bug report?

**Comment by browner12** [comment]
I would not consider this a bug, and would not change the functionality.

If you don't want your iFrame assertions to be scoped to `.dialog`, move them out of that call.

**Comment by alecpl** [comment]
Fair enough. I understand that the behavior change would be a BC break. It's just I'm pretty sure 99% of the time you don't want to "inherit" the scope inside an iframe.

**Comment by browner12** [comment]
i'm struggling to understand why you would not move the assertion outside of the scope call then?

**Comment by alecpl** [comment]
I could but I might prefer such order:
```
$browser->with('.dialog', function ($browser) {
    $browser->assertSeeIn('.header', 'Dialog title');
    $browser->withinFrame('#dialog-frame', function($browser) {
        $browser->assertVisible('.test');
    });
    $browser->assertSeeIn('.footer', 'Whatever');
});
```
So, yes, I have dialogs with iframes. It would be more code to escape the scope for iframe. I can live with that, the real code is more complicated anyway, so it don't have to be a bad thing.
