### ISSUE TITLE
Keys method is broken after php-webdriver update

### ISSUE THREAD

**Issue by ahtinurme** [laravel/dusk#732]
- Dusk Version: v5.9.0
- Laravel Version: v6.14.0
- php-webdriver/webdriver Version: 1.8.0
- PHP Version: 7.4.2
- Database Driver & Version: MySQL 5.8

### Description:
Dusk keys() function is broken after php-webdriver/webdriver update.
Seems that webdriver expects string, but dusk inputs array.

Output from test:
<img width="645" alt="Screenshot 2020-02-11 at 12 32 00" src="https://user-images.githubusercontent.com/282119/74229445-0e49a180-4ccb-11ea-91c5-8c7d53ad9362.png">

From test:
<img width="556" alt="Screenshot 2020-02-11 at 12 39 36" src="https://user-images.githubusercontent.com/282119/74229743-a47dc780-4ccb-11ea-8345-434cee37db9b.png">

The keys function:
<img width="584" alt="Screenshot 2020-02-11 at 12 31 02" src="https://user-images.githubusercontent.com/282119/74229431-07229380-4ccb-11ea-8541-4ff7a30ae053.png">

<img width="799" alt="Screenshot 2020-02-11 at 12 31 14" src="https://user-images.githubusercontent.com/282119/74229499-2caf9d00-4ccb-11ea-96b6-f85903f1afca.png">

What webdriver is doing:
<img width="557" alt="Screenshot 2020-02-11 at 12 30 55" src="https://user-images.githubusercontent.com/282119/74229536-40f39a00-4ccb-11ea-8294-1cd8dc2cff7a.png">

### Steps To Reproduce:
1. Install latest Dusk
2. Update dependencies with "composer update"
3. Use $this->keys() method inside a Dusk test.
4. See the test fail with "array to string conversion".

**Comment by ahtinurme** [comment]
Also, it seems that dragging (dragLeft, dragRight)  is broken, but I cannot create an exception other than nothing happens...

**Comment by driesvints** [comment]
@ahtinurme I've reported this to php-webdriver's repo. Seems like they now automatically enable the w3c protocol which changes the behavior for some methods. Can you weigh in here and also provide the missing versions they ask in the issue? https://github.com/php-webdriver/php-webdriver/issues/758

The dragging issue might be related to https://github.com/php-webdriver/php-webdriver/issues/757. Feel free to also weigh in there with any info you might have.

**Comment by ahtinurme** [comment]
@driesvints Added my weigh in and following the issues.
Thanks for the quick reply!

**Comment by driesvints** [comment]
We've locked Dusk on `^1.7 <1.8` for now until the issues are fixed.

**Comment by OndraM** [comment]
Php-webdriver 1.8.1 which includes the fix has just been released :rocket:

**Comment by driesvints** [comment]
Cool. I've removed the maximum constraint and set 1.8.1 as the new minimum. Will be in tomorrow's release.
