### ISSUE TITLE
Operation timed out ChromeDriver

### ISSUE THREAD

**Issue by rauldeheer** [laravel/dusk#740]
- Dusk Version: **5.9**
- Laravel Version: **6.1**
- PHP Version: **7.2.21**
- Database Driver & Version: **MySQL 5.7.26**
- Chrome version: **80.0.3987.116**
- OS: **macOS Catalina 10.15.3**

### Description:
If I run `php artisan dusk` it will show this message 9/10 times:

```
Time: 53.97 seconds, Memory: 26.00 MB

There was 1 error:

1) Tests\Browser\RequestAccountTest::requestAccountFormTest
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session/ee572e334d5b7ecd5b56736f861aa31b/element/0.26325793063635383-9/click

Operation timed out after 30001 milliseconds with 0 bytes received
```

So sometimes it works 3 times straight, but most of the time it will produce the above output 20 times straight. I am unable to run any tests.

### Steps To Reproduce:

1. Create a new Laravel application.
2. Install dusk.
3. Install the Chrome driver.
4. Update Chrome if necessary.
5. Create a simple test.
6. Run test.

Thank you for helping in advance.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by rauldeheer** [comment]
@driesvints I don't see why this is not a valid bug report. Many people all over the internet complain about this issue. 

Please correct me if I'm wrong, but Isn't this a bug in Dusk itself?

Sources:
https://github.com/laravel/dusk/issues/440
https://stackoverflow.com/questions/49837939/laravel-dusk-chrome-driver-timeout
https://laracasts.com/discuss/channels/laravel/laravel-dusk-process-exceeded-timeout

**Comment by daniel-g-wood** [comment]
I had the same problem. Installing the latest version of the Chrome Browser fixed it for me, using these instructions here:
https://stackoverflow.com/questions/39541739/chromedriver-error-chrome-version-must-be-52-using-nightwatch/45227939#45227939

**Comment by paulocjota** [comment]
I have Ubuntu and the ungoogled chrome (Chromium). Tried everything to work with Chromium, none worked, then just installed the normal chrome and everything works like a charm:

Download:
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

Instalation:
sudo apt install ./google-chrome-stable_current_amd64.deb
