### ISSUE TITLE
Dusk not respecting server APP_ENV settings when backing up environment

### ISSUE THREAD

**Issue by itsjustanthony** [laravel/dusk#741]
Vagrant Homestead
- Dusk Version: 5.9.1
- Laravel Version: 6.11.0
- PHP Version: PHP 7.4.1 (cli) (built: Dec 18 2019 14:44:22) ( NTS )
- Database Driver & Version: mysql Server version: 5.7.28-0ubuntu0.18.04.4 (Ubuntu)

### Description:
When using a server defined APP_ENV variable dusk will not back up the correct environment files.

Assuming you have:
`.env` , 
`.env.[ENV_1]` , 
and
`.env.dusk.[ENV_1]`

And have set APP_ENV:
`EXPORT APP_ENV=[ENV_1]`

Running dusk will back .env.dusk.[ENV_1] to .env, but leave .env.[ENV_1] alone. 

When the request hits the server, though, the server has defined $APP_ENV, so .env.[ENV_1] is loaded instead of .env

Pull request: #742 

### Steps To Reproduce:
`EXPORT APP_ENV=[ENV_1]`
`cp .env .env.[ENV_1] # (or edit as desired)`
`php artisan dusk`

#### Expected Results
.env -> .env.backup
.env.[ENV_1] -> .env.[ENV_1].backup
.env.dusk.[ENV_1] -> .env

(this pattern removes the problem without ignoring the server, using the same methodology currently employed by dusk)

#### Actual Results
.env  -> .env.backup
.env.dusk.[ENV_1] -> .env
.env.[ENV_1] -> !! No change !!

Proposed Fix:
In 
`DawnCommand::backupEnvironment()`
- Back up all files that look like .env* except $this->duskFile()
- Move $this->duskFile() to .env

In
`DawnCommand::restoreEnvironment()`
- Restore all files that look like .env*.backup ( following the current backup naming logic )

**Comment by driesvints** [comment]
No plans on supporting this sorry.
