### ISSUE TITLE
Calling Browser::assertSee() function on ErrorView causes WebDriverCurlException

### ISSUE THREAD

**Issue by iNviNho** [laravel/dusk#743]
- Dusk Version: 5.9.2
- Laravel Version: 5.8.37
- PHP Version: 7.4.3
- Database Driver & Version: Mysql 5.7

### Description:
Hello guys,

Today i spent couple hours debugging error:

```
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http GET to /session/e1c63e402c50bd8dcb9a25a740fddc89/screenshot

Operation timed out after 10001 milliseconds with 0 bytes received
```

This error is caused when you call `assertSee` function on a ErrorView.

### Steps To Reproduce:

1. Trigger ErrorException from your blade file. For example call `htmlspecialchars` with array as a first parameter to trigger something like this:

![image](https://user-images.githubusercontent.com/15668038/75553588-fb5bfe80-5a38-11ea-8669-d2facda1ac0e.png)

2. In your dusk test, try to call `assertSee` on this error view

```
        $this->browse(function(Browser $browser) use($client, $authorizationUser) {
           ...
            $browser->assertSee('Company details');
           ...
        });
``` 

3. And instead of getting an error like `Could not see Company details` i get

```

1) Tests\Browser\BusinessUserAmlTest::test_it_shows_business_aml_questionnaire
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session/e1c63e402c50bd8dcb9a25a740fddc89/log with params: {"type":"browser"}

Operation timed out after 10000 milliseconds with 0 bytes received

/var/www/html/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:297
/var/www/html/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:565
/var/www/html/vendor/php-webdriver/webdriver/lib/Remote/RemoteExecuteMethod.php:40
/var/www/html/vendor/php-webdriver/webdriver/lib/WebDriverOptions.php:156
/var/www/html/vendor/laravel/dusk/src/Browser.php:369
/var/www/html/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:161
/var/www/html/vendor/laravel/framework/src/Illuminate/Support/Collection.php:475
/var/www/html/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:162
/var/www/html/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:78
/var/www/html/tests/Browser/BusinessUserAmlTest.php:67

```

4. I also tried to run the chrome driver manually with `--verbose` option and this was the ouput

```
[1582894546.452][DEBUG]: DevTools WebSocket Command: Page.captureScreenshot (id=142) 995E5B26B92D87435149256994E28C6B {

}
[1582894556.453][SEVERE]: Timed out receiving message from renderer: 10.000
```

So after hours of debugging i just fixed my blade template and dusk tests continue working. I think that errors like this should not end up with `WebDriverCurlException` :))

Have a nice day.

**Comment by driesvints** [comment]
Can you provide a test app to reproduce the problem? Please commit your customchanges separately from the base skeleton.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
