### ISSUE TITLE
Invalid implementation of assertUrlIs 

### ISSUE THREAD

**Issue by mnabialek** [laravel/dusk#745]
- Dusk Version: 5.6.0
- Laravel Version: 6.17.1
- PHP Version: 7.3.13
- Database Driver & Version: Doesn't matter

### Description:

It seems actual implementation of `assertUrlIs` is very misleading. When you pass in there full url with query string assertion will fail although url is exactly the same

### Steps To Reproduce:

Write test like this:

```php
$this->browse(function (Browser $browser) {
    $browser->visit(config('app.url').'/login?test=abc')
        ->assertUrlIs(config('app.url').'/login?test=abc');
});
```

and assuming you have `/login` url set up, you will get:

> Actual URL [http://localhost/login?test=abc] does not equal expected URL [http://localhost/login?test=abc].
Failed asserting that 'http://localhost/login' matches PCRE pattern "/^http\:\/\/localhost\/login\?test\=abc$/u".
>
> /usr/share/nginx/html/vendor/laravel/dusk/src/Concerns/MakesUrlAssertions.php:32

So assertion fails and it says that http://localhost/login?test=abc is not the same as http://localhost/login?test=abc

**Comment by driesvints** [comment]
<img width="750" alt="Screenshot 2020-03-03 at 20 46 29" src="https://user-images.githubusercontent.com/594614/75813319-1360b480-5d90-11ea-84ab-a7eb64e41192.png">

**Comment by mnabialek** [comment]
@driesvints But this is very misleading in my opinion. Query string is part of url I believe, so either this method should verify also query string or it should be renamed to avoid confusion.
