### ISSUE TITLE
Proposal: Add timeouts to most asserts

### ISSUE THREAD

**Issue by haringsrob** [laravel/dusk#749]
Hi there,

Already using dusk for quite some time. Recently I noticed that it would benefit (it benefits me to start with) to let asserts wait for a certain behaviour.

I have currently implemented some asserts on my end using a trait.

The idea is that, especially when testing with js based front-ends, there are no page loads (vue + vue router). 

The dusk testing system however runs too fast. What I did up till now was something like this:
```
$browser->waitUntilMissingText('bar');
$browser->assertDontSee('bar');
```

I started overwriting some assertions, to avoid myself from this repetitive checking and basically let the asserts try a couple of times before failing..

Example:
```
    public function assertDontSee($text)
    {
        return $this->waitUsing(
            null,
            100,
            function () use ($text) {
                return $this->assertDontSeeIn('', $text);
            },
            'Failed waited for to be missing: ' . $text
        );
    }
```

I can make a pr for this, but I first want to validate if this:

- Is a path dusk wants to take;
- There maybe is a better way of doing this;

Kind regards,
Harings Rob

**Comment by driesvints** [comment]
There's already `$browser->pause(1000);`: https://laravel.com/docs/7.x/dusk#waiting-for-elements
