### ISSUE TITLE
Curl error

### ISSUE THREAD

**Issue by kerimkuscu** [laravel/dusk#753]
- Dusk Version: "^5.0",
- Laravel Version: "^7.0"
- PHP Version: "^7.4"
- Database Driver & Version:

### Description:
I just got a chrome driver Version error. I solved this problem with the 

`php artisan dusk:chrome-driver` 

command. But then I ran my test and came up with the following error.

`Facebook\WebDriver\Exception\WebDriverCurlException : Curl error thrown for http POST to /session/eb4b2a274a47a67f00984a2d94797209/frame with params: {"id":null}
`
I'll share the test I want to run.

```
/**
     * @test
     *
     * @throws Throwable
     */
    public function can_click_add_button()
    {
        $this->browse(function(Browser $browser) {
            $browser
                ->loginAs(User::first())
                ->visitRoute('admin.access_code.index')
                ->on(new AccessCodesPage)
                ->waitUntilMissing('@processing')
                ->click('@create-button')
                ->waitFor('@access-code-modal')
                ->assertSeeIn('@access-code-modal-header', 'Generate')
                ->waitFor('@access-code-modal-close-button')
                ->click('@access-code-modal-close-button')
                ->waitUntilMissing('@access-code-modal');
        });
    }
```

I've done a lot of research, but I can't find a solution.

**Comment by driesvints** [comment]
I can run the command just fine.

**Comment by kerimkuscu** [comment]
@driesvints Can you explain to me why he made this mistake?

**Comment by driesvints** [comment]
Ah sorry, my bad I misread. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by kerimkuscu** [comment]
@driesvints Thank you. I'll take my chances.
