### ISSUE TITLE
Ending slash in APP_URL cause login to fail in v6.0

### ISSUE THREAD

**Issue by lk77** [laravel/dusk#763]
- Dusk Version: 6.0 or 5.5 (not same result)
- Laravel Version: 7.5.2
- PHP Version: 7.3.4
- Database Driver & Version: mariadb 10.2

### Description:

Hello,

It seems that dusk does not handle ending slash in APP_URL,
i can see this on laravel telescope :

```
404 //_dusk/login/47017
```

### Steps To Reproduce:

- Add a slash to APP_ENV at the end (ex : https://web/)

- Try to login with dusk

- See that the login url is wrong, with a double slash at the start

- On 5.5 : it's working even with the wrong url

- On 6.0 : it's not working anymore -> 404

thanks.

**Comment by driesvints** [comment]
That's because we recently removed the support for `//` urls in Laravel which aren't correct. I'll send in a pr to trim the trailing slash.

**Comment by driesvints** [comment]
PR: https://github.com/laravel/dusk/pull/764

**Comment by lk77** [comment]
Ok, thanks !
