### ISSUE TITLE
Scrolling an element into view

### ISSUE THREAD

**Issue by u01jmg3** [laravel/dusk#765]
I realise the [`scrollTo($selector)`](https://github.com/laravel/dusk/blob/6.x/src/Browser.php#L328-L337) method was added to the core of Dusk.

However, it might be useful to make use of the [`Element.scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) JavaScript API which ensures the selected element is actually in view? [Browser support](https://caniuse.com/#feat=scrollintoview) is also good for this API as well as support for [`document.querySelector`](https://caniuse.com/#feat=queryselector).

```php
/**
 * Scroll element into view at the given selector.
 *
 * @param  string  $selector
 * @return $this
 */
public function scrollIntoView($selector)
{
    $selector = addslashes($this->resolver->format($selector));

    $this->driver->executeScript("document.querySelector(\"$selector\").scrollIntoView();");

    return $this;
}
```

**Comment by driesvints** [comment]
Sure feel free to PR
