### ISSUE TITLE
DevToolsActivePort file doesn't exist (Dusk, Homestead, Virtualbox 6.1)

### ISSUE THREAD

**Issue by moxyrus** [laravel/dusk#768]
- Dusk Version: 6.1.0
- Laravel Version: 7.8.1
- PHP Version: 7.4.5
- Database Driver & Version: Virtualbox 6.1
- Vagrant: Vagrant 2.2.7
- Homestead: 10.8.0

### Description:
Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\UnknownErrorException: unknown error: Chrome failed to start: exited abnormally.
(unknown error: DevToolsActivePort file doesn't exist)
(The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
/home/vagrant/code/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:139
/home/vagrant/code/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:370
/home/vagrant/code/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:136
/home/vagrant/code/tests/DuskTestCase.php:40
/home/vagrant/code/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:200
/home/vagrant/code/vendor/laravel/framework/src/Illuminate/Support/helpers.php:404
/home/vagrant/code/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:201
/home/vagrant/code/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:95
/home/vagrant/code/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:65
/home/vagrant/code/tests/Browser/ExampleTest.php:21

### Steps To Reproduce:
1. composer create-project --prefer-dist laravel/laravel ./
2. composer require laravel/homestead --dev
3. php vendor/bin/homestead make
4. vagrant up
5. vagrant ssh
6. composer require --dev laravel/dusk
7. php artisan dusk:install
ChromeDriver binaries successfully installed for version 81.0.4044.69
8. php artisan dusk
get error in the description
9. changed file DuskTestCase.php
https://gist.github.com/moxyrus/d0828153e95e3a932fd77618132dceed
10. I get the same error

**Comment by staudenmeir** [comment]
What's the result of `/usr/bin/chromium-browser --version` in the Vagrant machine?

**Comment by moxyrus** [comment]
> What's the result of `/usr/bin/chromium-browser --version` in the Vagrant machine?

ChromeDriver 81.0.4044.69 (6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776})

**Comment by staudenmeir** [comment]
The output should be completely different. How did you install Chromium? Are you using the `webdriver: true` setting in your `Homestead.yaml`?

**Comment by moxyrus** [comment]
I got the next error after clear installation with "webdriver: true":
"session not created: This version of ChromeDriver only supports Chrome version 81"

then typed command:
`php artisan dusk:chrome-driver 81`

After that I got the same error:
""session not created: This version of ChromeDriver only supports Chrome version 81""

After that I added the next line to "after.sh" file:
`sudo cp ~/code/vendor/laravel/dusk/bin/chromedriver-linux /usr/bin/chromium-browser`

After that all I get the error in the description.

**Comment by staudenmeir** [comment]
What's the result of `/usr/bin/chromium-browser --version` now?

**Comment by moxyrus** [comment]
> What's the result of `/usr/bin/chromium-browser --version` now?
`ChromeDriver 81.0.4044.69 (6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776})`

Sorry, but, do you have any errors at all?

**Comment by staudenmeir** [comment]
> I got the next error after clear installation with "webdriver: true":

When did you do that? After https://github.com/laravel/dusk/issues/768#issuecomment-622027739?

**Comment by moxyrus** [comment]
After, because I got the error `This version of ChromeDriver only supports Chrome version 81`

**Comment by staudenmeir** [comment]
And `/usr/bin/chromium-browser --version` still returns the same result as before?

**Comment by moxyrus** [comment]
It was before some kind of `ChromeDriver 80....`

After updating it got `ChromeDriver 81.0.4044.69 (6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776})`

**Comment by staudenmeir** [comment]
> sudo cp ~/code/vendor/laravel/dusk/bin/chromedriver-linux /usr/bin/chromium-browser

I just saw this line, it removes the Chromium browser and explains the whole behavior.

Remove the line and create a completely new Vagrant machine (with `webdriver: true`).

**Comment by moxyrus** [comment]
`/usr/bin/chromium-browser --version`
Now it is: Chromium 80.0.3987.163 Built on Ubuntu , running on Ubuntu 18.04

and th error the same: `unknown error: DevToolsActivePort file doesn't exist`

**Comment by staudenmeir** [comment]
Dusk installed the latest ChromeDriver, but that only works with Chromium 81.

You can downgrade the driver with `php artisan dusk:chrome-driver 80`.

**Comment by moxyrus** [comment]
Ok, but nothing changed. The error the same 

1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\UnknownErrorException: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

/home/vagrant/code/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:139
/home/vagrant/code/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:370
/home/vagrant/code/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:136
/home/vagrant/code/tests/DuskTestCase.php:42
/home/vagrant/code/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:200
/home/vagrant/code/vendor/laravel/framework/src/Illuminate/Support/helpers.php:399
/home/vagrant/code/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:201
/home/vagrant/code/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:95
/home/vagrant/code/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:65
/home/vagrant/code/tests/Browser/ExampleTest.php:25

**Comment by staudenmeir** [comment]
The exact same setup works for me. We'll have to see if more people report this issue.

**Comment by driesvints** [comment]
Since you're specifically having this problem with Homestead I think it's best that you open an issue on their repo.

**Comment by lupinitylabs** [comment]
For anyone else running into this issue, please have a look at my SO answer I put together after hours of research... https://stackoverflow.com/questions/56278372/dusk-test-for-browser-devtoolsactiveport-file-doesnt-exist/64509560#answer-64509560

Hope it helps. Essentially you need to make sure to have the `webdriver` feature activated in your homestead config and are running Chromium in headless state.

**Comment by daraul** [comment]
I got this error when doing `php artisan dusk --browse`. I had to run chromedriver manually: `vendor/laravel/dusk/bin/chromedriver-linux` to get around it.

**Comment by shemgp** [comment]
In my case, I found out that I needed to add `--no-sandbox` to `tests/DuskTestCase.php` since I was running on root on an lxd container.

I found out about the error by running: `vendor/laravel/dusk/bin/chromedriver-linux --log-level=ALL` and in another terminal running `php artisan dusk`. It will display the logs and I was able to deduce the problem from there.

**Comment by HeadStudios** [comment]
> The exact same setup works for me. We'll have to see if more people report this issue.

I can confirm this issue happens to e too

**Comment by rivassh** [comment]
to me (on docker) this error occurred:
```
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
[1764:1764:0918/023300.125996:FATAL:zygote_host_impl_linux.cc(207)] Check failed: . : Operation not permitted (1)
[
```
