### ISSUE TITLE
Error when trying to update chrome driver

### ISSUE THREAD

**Issue by nessor** [laravel/dusk#770]
- Dusk Version: 6.1.0
- Laravel Version: 7.10.2
- PHP Version: 7.4.5
- Database Driver & Version: MariaDB 10.4.11

### Description:
An error appears when trying to load the current chrome version (php artisan dusk:chrome-driver):

```
ErrorException 

  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14095126:SSL routines:ssl3_read_n:unexpected eof while reading

  at C:\GitLab\PROJECT\webpage\vendor\laravel\dusk\src\Console\ChromeDriverCommand.php:168
    164|      * @return string
    165|      */
    166|     protected function latestVersion()
    167|     {
  > 168|         return trim(file_get_contents($this->latestVersionUrl));
    169|     }
    170| 
    171|     /**
    172|      * Download the ChromeDriver archive.

  1   C:\GitLab\PROJECT\webpage\vendor\laravel\dusk\src\Console\ChromeDriverCommand.php:168
      file_get_contents("https://chromedriver.storage.googleapis.com/LATEST_RELEASE")

  2   C:\GitLab\PROJECT\webpage\vendor\laravel\dusk\src\Console\ChromeDriverCommand.php:143
      Laravel\Dusk\Console\ChromeDriverCommand::latestVersion()
```

### Steps To Reproduce:
1. Run the command php artisan dusk:chrome-driver

**Comment by driesvints** [comment]
I can run this command perfectly fine.

**Comment by kangzoel** [comment]
Same here. It seems, it's caused by the https from the URL. My current workaround is changing directly the `src\Console\ChromeDriverCommand.php` file on **line 249**.

Change 
```
        return file_get_contents($url, false, $streamContext);
```
to
```
        return file_get_contents(str_replace('https:', 'http:', $url), false, $streamContext);
```

Then I can do:
```
php artisan dusk:chrome-driver 72
php artisan dusk:install <= this will throw an error, but it can be ignored
```
After that, `php artisan dusk` will work without any problem.

**Comment by nessor** [comment]
I had tested it again yesterday on another computer of mine. There it worked. But this one still has PHP 7.4.4 installed.
I want to try it again in the coming days on the computer where it didn't work with PHP 7.4.4

But thanks for the workaround! I will try that too!

**Comment by mroswald** [comment]
I had exactly the same problem on PHP 7.4.5 (xampp), why was this closed? Is there a fix available or no meant to be fixed?

**Comment by Racterrus** [comment]
Same error! Reopen error, please!
laravel/dusk                       v5.11.0 
laravel/framework                  v6.18.14  The Laravel Framework.
PHP Version: 7.4.5

**Comment by DanVeira** [comment]
Dusk doesn't work at all at the moment. Several errors on installation and then can't even run it after hacking away the installation.

```
file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14095126:SSL routines:ssl3_read_n:unexpected eof while reading
```
` file_get_contents(https://chromedriver.storage.googleapis.com/LATEST_RELEASE): failed to open stream: An attempt was made to access a socket in a way forbidden by its access permissions.`
```
1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 83
```

**Comment by nessor** [comment]
@driesvints I think there is a problem with PHP 7.4.5 in some cases.

**Comment by driesvints** [comment]
I can still run the command just fine (on PHP 7.4.5). All of these issues are probably temporary hiccups or related to your network provider.
