### ISSUE TITLE
SSL operation failed when running dusk:install

### ISSUE THREAD

**Issue by LarsWiegers** [laravel/dusk#779]
- Dusk Version: 6.1.0
- Laravel Version: 7.2.0
- PHP Version: 7.4.5
- Database Driver & Version: mysql 10.4.11-MariaDB

### Description:
When running php artisan dusk:install, i get the following error:
```
  ErrorException 

  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14095126:SSL routines:ssl3_read_n:unexpected eof while reading

  at E:\backend\vendor\laravel\dusk\src\Console\ChromeDriverCommand.php:168
    164▕      * @return string
    165▕      */
    166▕     protected function latestVersion()
    167▕     {
  ➜ 168▕         return trim(file_get_contents($this->latestVersionUrl));
    169▕     }
    170▕
    171▕     /**
    172▕      * Download the ChromeDriver archive.


```
### Steps To Reproduce:
As far as i know:
1. Install laravel
2. install dusk
3. run dusk:insall

**Comment by driesvints** [comment]
Works fine for me.

**Comment by LarsWiegers** [comment]
Hi @driesvints thx for checking out my issue, got any ideas what could make this error happen? I know that if i go to the link in the browser it does work. Just fyi im running windows 10 maybe that has something to do with it.

**Comment by lafo8020** [comment]
Hi, same issue here on Windows 10 + Xampp 7.4.5

Dusk Version: 6.1
Laravel Version: 7.0
PHP Version: 7.4.5

**Comment by clanofartisans** [comment]
Please note that I've posted the solution here: https://github.com/laravel/dusk/issues/786
