### ISSUE TITLE
[Doc] Missing dusk option referenced in the doc

### ISSUE THREAD

**Issue by MarceauKa** [laravel/dusk#78]
Hi!

### Doc indicates

The `dusk` command accepts any argument that is normally accepted by the PHPUnit test runner, allowing you to only run the tests for a given group, etc:

```
php artisan dusk --group foo
```

### But...

```
unrecognized option --group foo
```

The `DuskCommand` doesn't reference this option.

**Comment by JVMartin** [comment]
@MarceauKa Hey there - you simply have a typo.

It should be:
```bash
php artisan dusk --group=foo
```

I have tested this feature and it does work.

**Comment by MarceauKa** [comment]
@JVMartin why the option is not referenced in the command? (`Laravel\Dusk\Console\DuskCommand`)

For the typo, all of others artisan commands work for me:
Ex: `artisan db:seed --class CustomSeeder` or `artisan db:seed --class=CustomSeeder`

**Comment by deleugpn** [comment]
Isn't it easier to just use `--something=value` instead of referencing every PHPUnit command inside DuskCommand?
