### ISSUE TITLE
loginAs failed because curl error with with params: {"id":null}

### ISSUE THREAD

**Issue by davidsun3000** [laravel/dusk#780]
- Dusk Version: v6.2.0
- Laravel Version: v7.13.0
- PHP Version: 7.2.11
- Database Driver & Version:

### Description:
dusk example with loginAs failed with curl error params: {"id":null}
dusk example without loginAs works fine. 

### Steps To Reproduce:
1. loginAs
installed php dusk, then install chrome-driver (81) and chromium-browser 81.0.4044.138. 
ran php artisan dusk command with following code:

$user = factory(User::class)->create();
        $this->browse(function (Browser $browser) {
            $browser->visit('http://todo.test')
                ->loginAs(User::find(1))
                ->visit('http://todo.test/home')
                ->assertSee('Tasks');

And got:
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session/e331057f3466cc213dff0ab723771d05/frame with params: {"id":null}

2. no loginAs
with following code:
        $user = factory(User::class)->create();
        $this->browse(function (Browser $browser) {
            // Log::info("User: ", dd($this->user));
            // dd($this->user);
            // $browser->loginAs(User::find(1))
            //     ->visit('http://todo.test/home')
            //     ->assertSee('Tasks');
            $browser->visit('http://todo.test')
                // ->loginAs(User::find(1))
                // ->visit('http://todo.test/home')
                ->assertSee('Laravel');

results:
Time: 9.8 seconds, Memory: 26.00 MB

OK (2 tests, 2 assertions)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by davidsun3000** [comment]
I have checked this forum and saw previous reporting with no solution. 
I also have searched all these forums you have listed, and found no similar case. 
Thus I would have to post here, since I have just use the newly installed dusk package.
