### ISSUE TITLE
Unable to find meta elements

### ISSUE THREAD

**Issue by jordyvandomselaar** [laravel/dusk#781]
- Dusk Version: 6.2.0
- Laravel Version: 7.13.0
- PHP Version: 7.4.2
- Database Driver & Version: N.A

### Description:

Dusk is unable to find meta elements using

```
$browser->elements('meta')
```

It also cannot find `head` and `body` tags.

I need this because I'd like to to test for correct OG tags and other meta tags.

### Steps To Reproduce:

1. Setup Dusk project
2. Try finding meta tags

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by jordyvandomselaar** [comment]
So, it's intended? @driesvints

**Comment by driesvints** [comment]
Dusk only does assertions for elements within the body tag. That method is also an internal method and not documented. It only fetches elements within the body tag.

**Comment by jordyvandomselaar** [comment]
Thanks for the response =), that makes sense!

**Comment by jordyvandomselaar** [comment]
If anyone stumbles upon this issue, here's a workaround:
Set the prefix to HTML inside your test so it begins crawling from the HTML element instead of the body element.

```php
<?php
$this->browse(
    function (Browser $browser) {
        $browser->resolver->prefix = 'html';
        $this->assertSame('nl_NL', $browser->attribute('@og:locale', 'content'));
    }
);

```
