### ISSUE TITLE
ChromeOptions::CAPABILITY is deprecated

### ISSUE THREAD

**Issue by mattkingshott** [laravel/dusk#782]
- Dusk Version: 6.x
- Laravel Version: 7.14.1
- PHP Version: 7.4.6
- Database Driver & Version: N/A

### Description:

The file `stubs/DuskTestCase.stub` currently contains the following code:

```php
return RemoteWebDriver::create(
    'http://localhost:9515', DesiredCapabilities::chrome()->setCapability(
        ChromeOptions::CAPABILITY, $options
    )
);
```

However, `ChromeOptions::CAPABILITY` is deprecated. 

An examination of the `ChromeOptions` class would appear to suggest that it should be replaced with `ChromeOptions::CAPABILITY_W3C`. Unfortunately, switching over introduced an issue with the arguments section e.g. `--headless` not being applied.

### Steps To Reproduce:

None. Standard within Laravel Dusk.

**Comment by driesvints** [comment]
If it's deprecated but not broken then we could look at replacing it in the next major release. Appreciating a pr for this if possible.

**Comment by mattkingshott** [comment]
On closer inspection, this "appears" to an issue with the underlying Facebook WebDriver. 

The code within Dusk is correctly setting the arguments in the Chrome capabilities, but something within the `RemoteWebDriver::create()` method is causing the arguments not to be applied.

Closing this for now as I'm reasonably confident that it is something that needs fixing in the underlying package (as an aside, there are many deprecated references in the package as well so I'm guessing that it is currently a WIP).
