### ISSUE TITLE
A way to break selector scope

### ISSUE THREAD

**Issue by Infamoustrey** [laravel/dusk#783]
When writing components that sometimes render elements outside of a certain scope I find myself needing to break the selector scope that I'm in. Take the popular [Select](https://material-ui.com/components/selects/) component from [Material UI's react library](https://material-ui.com/) for example. Portions of the component aren't necessarily within the same css selection scope. The resulting html looks something like this(abbreviated for comprehension).

```html
<div class="mui-select">
   <label>My Label</label>
   <div>...input display</div>
</div>

... other portions of the page

<div class="mui-menu">
  <ul>
     <li class="select-option">1</li>
     <li class="select-option">2</li>
     <li class="select-option">3</li>
  </ul>
</div>

```

Now if I define a [component class in dusk](https://laravel.com/docs/7.x/dusk#components) for this, I walk myself into a corner as everything in the component would be scoped into the `.mui-select` class. Afaik there wouldn't be any way to select the `.mui-menu` from the component class. If there is please let me know and I'd be happy to do that.

Right now however, I'm getting away with this by temporarily removing the scope then adding it back which works fine, but feels clunky.

```php

class SelectInput extends BaseComponent
{

   // selector info, elements

    public function selectFromDropdown(Browser $browser, string $value)
    { 
        $prefix = $browser->resolver->prefix;
        $browser->resolver->prefix = "";
        $browser->within('.mui-menu', function ($browser) use ($value) {
           // do unscoped stuff
        });
        $browser->resolver->prefix = $prefix;
    }
}

```

If that seems like a good way to access it, then maybe we could add a method to allow a way to break the scope. So in `Laravel\Dusk\Browser` we could add something like:

```php
// not sure what the name would be for such a function
public function breakScope(Closure $callback) {
    $prefix = $browser->resolver->prefix;
    $browser->resolver->prefix = "";
    $callback($this)
    $browser->resolver->prefix = $prefix;
}
```

**Comment by driesvints** [comment]
I see the problem here indeed. Although I think components are a little out of scope for what you're trying to do there might be an opportunity for the callback method you described. Feel free to send in a PR and definitely make sure to explain it thoroughly so Taylor has a good idea at what you're trying to solve.
