### ISSUE TITLE
Chrome binary not found although dusk:install said it's installed (and install it)

### ISSUE THREAD

**Issue by felixdorn** [laravel/dusk#789]
- Dusk Version: 6.3.0
- Laravel Version: 7.17.1
- PHP Version: 7.4.6

### Description:
On Linux with a fresh Laravel install and `chromium-browser` not installed, dusk fails when excuting a command with `unkown error: cannot find Chrome binary`. However, as in the documentation, the command `php artisan dusk:install` should install this driver. And the command output is even more explicit :

```
Dusk scaffolding installed successfully.
Downloading ChromeDriver binaries...
ChromeDriver binaries successfully installed for version 83.0.4103.39.
```

So it should work ? But after some digging, I found something strange : the error comes from the `HttpCommandExecutor@execute` (makes sense), but the error is from the response of the chrome driver API. (See [this line](https://github.com/php-webdriver/php-webdriver/blob/main/lib/Remote/HttpCommandExecutor.php#L321) and [this one](https://github.com/php-webdriver/php-webdriver/blob/main/lib/Remote/HttpCommandExecutor.php#L321))

So, if the ChromeDriver exists and respond why the error says that it doesn't exists.
I might be missing something, or the documentation might be unclear.

### Steps To Reproduce:
Reproducable for sure and Linux Mint without any Chromium based browser, maybe it "works" also for other OS, I can't test that.

- `composer create-project laravel/laravel`
- `composer require laravel/dusk`
- `php artisan dusk:install`
- `php artisan dusk`

Expect an error like that :

```
1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\UnknownErrorException: unknown error: cannot find Chrome binary
```

**Comment by staudenmeir** [comment]
Dusk provides the Chrome _driver_, you need to install the _browser_ (e.g. `chromium-browser`) yourself.

**Comment by driesvints** [comment]
See the answer above.

**Comment by shengslogar** [comment]
This is about the tenth time I've forgotten this. This should be pinned somewhere.

**Comment by felixdorn** [comment]
Glad I'm not alone!
