### ISSUE TITLE
Chrome version number and chrome driver check broken by google again

### ISSUE THREAD

**Issue by lionslair** [laravel/dusk#796]
- Dusk Version: 6.x
- Laravel Version: 7.x
- PHP Version: 7.4.x
- Database Driver & Version:

### Description:
Google seem to have changed how they use the version file again. https://chromedriver.storage.googleapis.com/LATEST_RELEASE

Is currently showing 85.0.4183.38 which is the beta version of chrome see http://chromedriver.chromium.org/

So if they are using the latest file as latest version that could be beta the install of chrome and the version drive now breaks again.

This page http://chromedriver.chromium.org/downloads/version-selection effectively says to get the chrome stable version. 
Extract the version number and then use the major version number part to download the correct chrome driver.

If they are going this route we now will need a 

https://chromedriver.storage.googleapis.com/LATEST_STABLE  in order top keep using what we use now.

**Comment by driesvints** [comment]
This seems like a hiccup to me. In any case there's no other url we can retrieve it from.

> Extract the version number and then use the major version number part to download the correct chrome driver.

We can't do that as the content can change at any time.

That page also says:

> In addition, the version of ChromeDriver for the current stable release of Chrome can be found at https://chromedriver.storage.googleapis.com/LATEST_RELEASE.

Which seems to me the only way to do this. The fact that beta version gets shown here might indicate a pending release.

It also says:

> However, using on this file may be less reliable than methods described above.

However, that only indicates fixed versions and not a true "latest release". Therefor there's nothing we can really do here but hope that Chrome will add the proper version to their own documented url.
