### ISSUE TITLE
assertAttribute for class attributes

### ISSUE THREAD

**Issue by nessor** [laravel/dusk#797]
Hi there,

I have not found an assert function to check set class attributes of an HTML element. So I helped myself with the assertAttribute method by setting $attributes to 'class'.

But in the assertAttribute a PHPUnit::assertEquals is used:
https://github.com/laravel/dusk/blob/db10ac70d01f332614a54cd7f1fe4757066db7cc/src/Concerns/MakesAssertions.php#L559-L576
Here the order of the passed attributes is crucial. But classes in HTML don't care about the order. Would a new method assertClassAttributes and assertHasClassAttributes be helpful?

**Comment by nessor** [comment]
If others have the same problem. My current workaround:
```php
$this->assertCount('1', $browser->driver->findElements(WebDriverBy::xpath("//nav[contains(@class, 'nav-transparent')]")));
```

But the feature would still be really chic ;-)

**Comment by driesvints** [comment]
Feel free to attempt a pr 👍
