### ISSUE TITLE
ElementResolver's format() replaces the part of css selector matching other elements shortcut key.

### ISSUE THREAD

**Issue by dsamburskyi** [laravel/dusk#799]
- Dusk Version: 6.4.1
- Laravel Version: 7.22.4
- PHP Version: 7.4.6
- Database Driver & Version:

### Description:
resolver->format() replaces the part of selector matching the element shortcut. 
What that means is when there's a 'registered' element with the key (for example "title"), any occurrence of that key ("title") in other elements selector would be replaced with the key's value, 
like
```
'title'      => '[data-testid=title]',
'subitle' => '[data-testid=subtitle]',
```
The 'subtitle' element selector would resolve to `[data-testid=sub[data-testid=title]], thus triggering "Invalid selector" error.

### Steps To Reproduce:
Have registered element shortcuts where one element key is a part of another element selector.

**Comment by driesvints** [comment]
I don't see an easy solution to this other than to make use of more specific selectors in your tests sorry. If you have a practical solution we'd appreciate a PR.
