### ISSUE TITLE
Page Shorthand Selectors not working (or I could not understand how to use it)

### ISSUE THREAD

**Issue by Eliraz-TTK** [laravel/dusk#80]
I created a page (test) and added the following shorthand selectors:
```
 public function elements()
    {
        return [
            '@loginButton' => '#login-submit',
            '@username' => '#login-input-email',
            '@password' => '#login-input-password',
            '@forgot-password' => '.login__bottom-form-link',
            '@logo' => '.login__logo-image'
        ];
    }
```

in the assert method of the page I tried to do the following:

```
 public function assert(Browser $browser)
    {
        $browser->assertPathIs($this->url());
        $browser->waitFor('@loginButton')
            ->assertSeeIn('@loginButton', 'Sign In');
    }
```

and it's not working as I expected. it doesn't find the selectors.
however, if I change the shorthand to this form:

```
 public function assert(Browser $browser)
    {
        $browser->assertPathIs($this->url());
        $browser->waitFor('#login-submit')
            ->assertSeeIn('#login-submit', 'Sign In');
    }
```

it works as expected.

So what am I doing wrong here?

**Comment by splatEric** [comment]
The assert method in the Page object is called before the resolver on the Browser is given the elements:

https://github.com/laravel/dusk/blob/master/src/Browser.php#L121-L135

So basically at the moment, the element shortcuts are available everywhere apart from the assert method of the page.

**Comment by brandonferens** [comment]
@Eliraz-TTK Think of the Page object really as more of a helper than a place to fully test things. I personally would leave the assert method as
```
public function assert(Browser $browser)
{
    $browser->assertPathIs($this->url());
}
```
In your actual test file you would do (assuming your Page class is called `MyPage`)
```
public function testMyTest()
{
    $this->browse(
        function ($browser) use ($mood) {
            $browser->visit(new MyPage)
                ->waitFor('@loginButton')
                ->assertSeeIn('@loginButton', 'Sign In');
        }
    );
}
```

Another approach might be to create a custom method in the `MyPage` class like this:
```
public function seeLoginButton(Browser $browser)
{
    $browser->waitFor('@loginButton')
        ->assertSeeIn('@loginButton', 'Sign In');
}
```
Then in your test above you would write
```
public function testMyTest()
{
    $this->browse(
        function ($browser) use ($mood) {
            $browser->visit(new MyPage)
                ->seeLoginButton();
        }
    );
}
```

**Comment by deleugpn** [comment]
Can this be closed?

**Comment by troccoli** [comment]
I would like this to be fixed too.

If I have an `assert` method in my page then I would expect to be able to assert anything and in the same way as in other tests.

**Comment by driesvints** [comment]
No plans on changing this behavior. I think @brandonferens explains it well above.
