### ISSUE TITLE
File permission set wrong after pulling in with composer

### ISSUE THREAD

**Issue by brandonferens** [laravel/dusk#81]
The binary files within `bin` are set to `0664` after I install dusk. I ran `chmod -R 0755 vendor/laravel/dusk/bin` to fix this, but I have a feeling this will just get overwritten when updating the package. I'm assuming that permissions are not set right somewhere, either on my machine or with the dusk package. Either way, quite a few people seem to be having similar issues. Any thoughts or finger pointing (at me) would be appreciated.

**Comment by georaldc** [comment]
Mine was set to 0755 after upgrading from Laravel 5.3 to 5.4. I wonder if it's an OS issue (I have a centos setup through docker)

**Comment by brandonferens** [comment]
Perhaps. I initially had the issue on Dusk 1.0.3. Subsequent versions have been fine.

**Comment by thelfensdrfer** [comment]
I had to chmod the `chromedriver-driver` executable.

**Comment by browner12** [comment]
thanks for this. I can finally get Dusk to work! of course it had to be a permissions issue.

not sure how we fix this so `composer update`s don't revert it.

**Comment by thinsoldier** [comment]
Where is `chromedriver-driver` located?

**Comment by thelfensdrfer** [comment]
In the same path, `vendor/laravel/dusk/bin/`.

**Comment by AlexCW** [comment]
This worked for me, thanks! However only outside of homestead. In homestead the process just run indefinitely and does not run the tests.

**Comment by savaged** [comment]
I have upgraded from 5.3 to 5.4 on Homestead and am trying to use Dusk. I get the same issue: after running `php artisan dusk` the process runs until it times out.

**Comment by driesvints** [comment]
Heya. This might be something for the docs. Feel free to send in a PR there.
