### ISSUE TITLE
"Route [dusk.login] not defined." - Only in one enviornment.

### ISSUE THREAD

**Issue by WDC** [laravel/dusk#812]
- Dusk Version: 6.4
- Laravel Version: ^7.0
- PHP Version: 7.4
- Database Driver & Version: SQLite 3

### Description:
On my MacBook I am able to successfully run my Dusk-based browser tests using the command `php artisan dusk`. However, when I deploy using a BitBucket Pipeline thanks to a Docker image that installs PHP 7.4 and SQLite, I get the following error for every single one of my tests:

```1) Tests\Browser\AssessmentsTest::testCanVisitGoal
Symfony\Component\Routing\Exception\RouteNotFoundException: Route [dusk.login] not defined.
```
<img width="799" alt="image" src="https://user-images.githubusercontent.com/1221004/92602259-eaa80300-f27b-11ea-8194-df21d969c41c.png">

### Steps To Reproduce:

1. Push to BitBucket `master` which executes a Pipeline deployment operation.
2. Wait until the `php artisan dusk` step in the process happens.
3. After each test fails, see the same error (above) for all.

**Comment by WDC** [comment]
I resolved this error by specifying a non-`production` enviornment, that is, I forced `APP_ENV=local` before running Dusk.

**Comment by lukebouch** [comment]
I have a similar issue. I keep getting the error "Route [dusk.login] not defined."

<img width="1095" alt="CleanShot 2022-05-02 at 19 57 04@2x" src="https://user-images.githubusercontent.com/25229123/166344307-0a625d43-f9a6-4424-a8fc-7db034aea4ab.png">

**Comment by lukebouch** [comment]
Oh... I just had to run `php artisan optimize:clear` and now it's working.
