### ISSUE TITLE
phpunit reports "deprecated schema"

### ISSUE THREAD

**Issue by ravenshill** [laravel/dusk#813]
- Dusk Version: 6.6
- Laravel Version: 8.0.4
- PHP Version: 7.3.22-1 (ubuntu)
- Database Driver & Version: n/a dont know

### Description:
run the command 
php artisan dusk
-- The test run successfully however a warning is displayed

PHPUnit 9.3.8 by Sebastian Bergmann and contributors.

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

### Steps To Reproduce:
upgrade to laravel/framework 8.0* and consequently to php/phpunit 9.0
run the command 
php artisan dusk

**Comment by driesvints** [comment]
You probably have an outdated stub: https://github.com/laravel/dusk/blob/6.x/stubs/phpunit.xml
