### ISSUE TITLE
All Dusk Tests Fail With "A facade root has not been set."

### ISSUE THREAD

**Issue by WDC** [laravel/dusk#814]
- Dusk Version: ^6.4
- Laravel Version: ^7.0
- PHP Version: 7.4
- Database Driver & Version: SQLite3

### Description:
When running Dusk tests locally using `php artisan dusk`, the browser tests executed as expected. However, when pushing to a BitBucket Pipeline that utilizes a PHP 7.4 Docker image to run `php artisan dusk` I receive the following error with 100% of my tests:
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/1221004/92964138-9fd7e800-f441-11ea-9edf-f46a62fc12b5.png">

I have changed the `APP_ENV`, `APP_URL`, `DB_CONNECTION` enviornment variables, but in each case the same error is encountered for all of the browser tests inside of `./tests/Browser/*`.

The start of all of the browser test files looks like this:
```
<?php

namespace Tests\Browser;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Laravel\Dusk\Browser;
use Tests\DuskTestCase;

class OrdersTest extends DuskTestCase
{
    public function setUp(): void
    {
        parent::setUp();
    }
```

### Steps To Reproduce:
1. Run `php artisan dusk` inside of a BitBucket Pipeline running on a Ubuntu 20.04 PHP 7.4 container image.
2. See the "A facade root has not been set." error.

Any help would be greatly appreciated!

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by realtebo** [comment]
same problem here. Did you find any solution?

**Comment by nicekiwi** [comment]
@realtebo For me, the issue was the `dusk:install` command did not create the stub methods required in the `DuskTestCase` file, so I had to create the following method inside `./tests/DuskTestCase`, as of Laravel 10 with Dusk 8.2.

```
public function createApplication()
    {
        $app = require __DIR__.'/../bootstrap/app.php';

        $app->make(Kernel::class)->bootstrap();

        return $app;
    }
```

**Comment by richard015ar** [comment]
thank you @nicekiwi that did the job for me as well!
