### ISSUE TITLE
Clear() method not working on vue.js inputs. Dusk v6.1.0.

### ISSUE THREAD

**Issue by xvetrax** [laravel/dusk#818]
- Dusk Version: 6.1.0
- Laravel Version: 8.0
- PHP Version: 7.3
- Database Driver & Version:

### Description:
Clear() method not working on vue.js inputs. Dusk v6.1.0.

### Steps To Reproduce:
Open any project based on Vue.js,  and when trying to clear inputs with clear() method nothing happened.  Type() method does not clear inputs too.

**Comment by driesvints** [comment]
I don't think this was ever meant to specifically work with VueJS as Vue catches all browser specific calls to it. We already have specific Vue assertions so this might need a specific `clearVue` method. Feel free to send in a PR if you want.

https://laravel.com/docs/8.x/dusk#assert-vue

**Comment by rez0sk** [comment]
I've made a `clearVue` macro which resolves this issue.


```
Browser::macro('clearVue', function ($selector) {
    $element = $this->resolver->format($selector);
    $this->script("document.querySelector('$element').value = ''");
    $this->script("document.querySelector('$element').dispatchEvent(new Event('input'))");

    return $this;
});
```
