### ISSUE TITLE
Client Certificate Auth

### ISSUE THREAD

**Issue by albertovincenzi** [laravel/dusk#835]
I hope that this could be considered as an interesting feature.
I have to connect to a remote website which require client SSL certificate. I have many of them, so I must choose one for every request I want to do. I tried to figure out any possible solution but seems that in whole PHP world, this is not possible. I mean, you can use phantomjs with ssl-client-certificate-file argument but you can't interact with forms.

Do you think could be an option to set a parameter in dusk to use such certificate for connection to the host?

**Comment by driesvints** [comment]
I think it's best that you attempt a PR to show exactly what you want to achieve. Thanks.
