### ISSUE TITLE
[RFC] Additional options for dusk:page command on creating test class

### ISSUE THREAD

**Issue by gabbydgab** [laravel/dusk#84]
### Overview

A short-cut in creating **_DuskTestCase_** from a **_Dusk\Page_**.

**Proposed:**
```php artisan dusk:page --test <name>```
```php artisan dusk:page -t <name>``` (using alias)

**Example:**
 ```php artisan dusk:page -t CheckoutPage``` 
Will create the following files **_CheckoutPage.php_** and _**CheckoutPageTest.php**_

Sample Output:
```
tests/Browser
├── CheckoutPageTest.php
├── Pages
│   ├── CheckoutPage.php
│   └── Page.php
└── screenshots
```

### Page Scaffolding:
To have a default value on the URI, additional option is used:

**Proposed:**
``` php artisan dusk:page --uri=<uri> <name>```

**Example:**
``` php artisan dusk:page --uri=/checkout CheckoutPage```
```php
   /**
     * Get the URL for the page.
     *
     * @return string
     */
    public function url()
    {
        return '/checkout';
    }
```

### Summary:

Using the following command: **_```php artisan dusk:page --uri=/checkout --test CheckoutPage```_**

 - Will generate two (2) files: **_CheckoutPage.php_** and **_CheckoutPageTest.php_**
 - Will return **_```/checkout```_** for Page::url() method

**Comment by driesvints** [comment]
Since this has been open so long and no-one has expressed the need to also want this I'm closing this.
