### ISSUE TITLE
loginAs working but not for backend

### ISSUE THREAD

**Issue by robov** [laravel/dusk#842]
When I try to call my backend
            $browser->loginAs(User::find(1))
                ->assertAuthenticated()

This assertion is ok, so I expect the user to be logged in
When I then visit my page

            $browser->loginAs(User::find(1))
                ->assertAuthenticated()
                ->visit('/projects')

Then I get an error on my controller as Auth::user() returns NULL

I am developing a package and I use orchestra testbench and orchestra testbench dusk with no custom middelware or authentication guards

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
