### ISSUE TITLE
[6.x] assertVue and assertVueIsNot do not accept arrays

### ISSUE THREAD

**Issue by mattkingshott** [laravel/dusk#845]
- Dusk Version: 6.10.0
- Laravel Version: 8.19.0
- PHP Version: 8.0.0
- Database Driver & Version: N/A

### Description:

The methods `assertVue` and `assertVueIsNot` do not work with `arrays` due to the error message dumping the supplied `$value` into a string. This causes an array to string conversion error.

```php
PHPUnit::assertEquals(
    $value,
    $this->vueAttribute($componentSelector, $key),
    "Did not see expected value [{$value}] at the key [{$key}]."
);
```

A simple check needs to be added to see whether the provided value can be converted to a `string`. If not, then maybe it should not be included at all. Instead perhaps simply say:

```php
"Did not see expected value at the key [{$key}]."
```

**Comment by driesvints** [comment]
Hey @mattkingshott. That's right. These weren't meant to be used with arrays. See the DocBlocks here: https://github.com/laravel/dusk/blob/6.x/src/Concerns/MakesAssertions.php#L878

**Comment by mattkingshott** [comment]
Hey @driesvints.

I realise that, however the companion `assertVueContains` method for arrays expect what you supply to be contained WITHIN, you cannot simply supply an array and expect it to be EQUAL.

I need to be able to compare like for like, not contained within.

**Comment by driesvints** [comment]
@mattkingshott I'm not sure I follow? `assertVueContains` also expects a string: https://github.com/laravel/dusk/blob/6.x/src/Concerns/MakesAssertions.php#L916

**Comment by mattkingshott** [comment]
Hmm... okay, but the docs says:

"Assert that a given Vue component data property is an array and contains the given value:"

https://laravel.com/docs/8.x/dusk#assert-vue-contains

**Comment by mattkingshott** [comment]
Either way, IMO, there needs to be a way to test that a vue attribute is equal to a PHP array.

**Comment by driesvints** [comment]
Ah yes, that's done for you inside the test method itself here already: https://github.com/laravel/dusk/blob/6.x/src/Concerns/MakesAssertions.php#L924-L927

**Comment by mattkingshott** [comment]
Yes, I see that, but there is no way to simply test that a Vue attribute is EQUAL to a PHP array. You only have the means of testing whether the Vue attribute CONTAINS a PHP array e.g.

```php
$value = [1, 2, 3];

PHPUnit::assertContains
```

I need to do:

```php
$value = [1, 2, 3];

PHPUnit:: assertEquals
```

**Comment by driesvints** [comment]
I'm a bit at a loss sorry. If you want to add something feel free to send in a PR 👍

**Comment by mattkingshott** [comment]
No problem, before I submit a PR, let me try and lay it out clearly:

Right now, you have two assertions, `assertVue` and `assertVueIsNot`. These allow you to test that a given `string` (`$value`) matches the value of a Vue attribute.

If you supply an `array` to these methods, they fail, not because of PHPUnit, but because the custom error message simply embeds `$value` into the `string`:

```php
"Did not see expected value [{$value}] at the key [{$key}]."
```

This causes an `array` to `string` exception.

There are also two companion assertions, `assertVueContains` and `assertVueDoesNotContain`, which do accept an `array`, however they expect the `array` to be nested within the Vue attribute. They do not expect it to be equal to it.

The solution, IMO, is not another method, but to simply adjust the existing `assertVue` and `assertVueIsNot` methods and have them check the type of `$value` prior to composing the error message e.g.

```php
/**
 * Assert that the Vue component's attribute at the given key has the given value.
 *
 * @param  string       $key
 * @param  mixed        $value
 * @param  string|null  $componentSelector
 * @return $this
 */
public function assertVue($key, $value, $componentSelector = null)
{
    $message = in_array(gettype($value), ['array', 'object']) ? '' : "[{$value}]";

    PHPUnit::assertEquals(
        $value,
        $this->vueAttribute($componentSelector, $key),
        "Did not see expected value {$message} at the key [{$key}]."
    );

    return $this;
}
```

**Comment by driesvints** [comment]
> There are also two companion assertions, `assertVueContains` and `assertVueDoesNotContain`, which do accept an array, 

This isn't true. They don't accept an array atm if you look at their DocBlocks.

I don't think using `mixed` is a good solution. Why don't you just use `assertVue` a few times after each other for the values that you're trying to check?

**Comment by mattkingshott** [comment]
> This isn't true. They don't accept an array atm if you look at their DocBlocks.

My apologies. You are correct.

> I don't think using `mixed` is a good solution. Why don't you just use `assertVue` a few times after each other for the values that you're trying to check?

I'm not sure how to do that given that I'm trying to compare two arrays and not an array containing an array. In any event, I just decided to create a macro with the desired functionality.

Thanks for the discussion though 👍

**Comment by lk77** [comment]
Hello,

same issue here, tests were broken by v6.10.0, i overrided the methods for now in my base browser class

```
class Browser extends DuskBrowser
{
    /**
     * Assert that the Vue component's attribute at the given key has the given value.
     *
     * @param  string  $key
     * @param  string  $value
     * @param  string|null  $componentSelector
     * @return $this
     */
    public function assertVue($key, $value, $componentSelector = null)
    {
        PHPUnit::assertEquals(
            $value,
            $this->vueAttribute($componentSelector, $key)
        );

        return $this;
    }

    /**
     * Assert that a given Vue component data property does not match the given value.
     *
     * @param  string  $key
     * @param  string  $value
     * @param  string|null  $componentSelector
     * @return $this
     */
    public function assertVueIsNot($key, $value, $componentSelector = null)
    {
        PHPUnit::assertNotEquals(
            $value,
            $this->vueAttribute($componentSelector, $key)
        );

        return $this;
    }
}
```

**Comment by driesvints** [comment]
Like I've said several times already: arrays were never supported. Please send in a PR if you want this to be supported.

**Comment by lk77** [comment]
I disagree with that, prior to that change, the methods were indeed supporting arrays, even if the docblock says otherwise.
Code dictate docblock, not the other way around.

if you really want to make arrays unsupported you have to do something like :

```
public function assertVue(string $key, string $value, $componentSelector = null)
```

which causes an error :

```
must be of the type string, array given
```

**Comment by mattkingshott** [comment]
This is what I was trying to say. It used to work even if not officially so. 

Technically it still does, it’s only the bespoke error message that throws the error because it tries to convert the array to a string.

**Comment by driesvints** [comment]
> if you really want to make arrays unsupported you have to do something like :

I disagree sorry. The docblocks are very clear at what you can pass.

**Comment by lk77** [comment]
I think this should be noted on the documentation that only strings are supported and not arrays or ints or floats.

i don't read docblocks to be honnest i just check the doc for available methods and use them.

i'm sure 95% of people who are using both dusk and vue are using those methods wrong.

**Comment by driesvints** [comment]
I'm sorry but I'm going to close this discussion as I feel it won't lead to anything. I've already stated several times that the current behavior is the expected behavior. The DocBlocks indicate what you can pass to the method. This should not be noted in the docs and the current docs don't show usage of the array as a value anywhere.

I've also stated several times that we might be willing to accept a PR to implement array support. You're free to send one in if you like. Thanks.
