### ISSUE TITLE
waitFor, whenAvaible not working when using Safari web driver

### ISSUE THREAD

**Issue by Etkalo** [laravel/dusk#849]
I'm trying to execute tests on MAC Safari using Browserstack service I'm faced an issue that the
$browser->waitFor('@dusk-selector');
$browser->whenAvaible('.css-class-selector');
etc...
Not working.
But on an iPhone Safari it works well.

I'm always getting
_Facebook\WebDriver\Exception\TimeoutException : Waited 15 seconds for selector [@btn-sign-in]._
Although the element is on the page

Tell me if I can help and provide more details.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
