### ISSUE TITLE
Exit code on test failure

### ISSUE THREAD

**Issue by mikaeljorhult** [laravel/dusk#85]
Would it be possible for the dusk command to forward the exit code emitted by PHPUnit?

Right now Dusk seem to always exit with an exit code of zero indicating no errors even if one or more tests failed. For CI, like Travis, it would be awesome to have the exit code from PHPUnit forwarded so failures can be caught.

**Comment by rap2hpoutre** [comment]
May be fixed if accepted: https://github.com/laravel/dusk/pull/92

**Comment by mikaeljorhult** [comment]
Works fine with you changes @rap2hpoutre! Nice work!
