### ISSUE TITLE
Dusk not launching Chrome browser without --headless argument

### ISSUE THREAD

**Issue by RalpinMcDjango** [laravel/dusk#854]
- Dusk Version: 6.11.1
- Laravel Version: 8.23.1
- PHP Version: 7.3.26
- Database Driver & Version: none

### Description:
When using the standalone chromedriver , the Chrome browser without the headless argument won't open. While trying to find a solution i noticed this functionality was previously supported by Dusk, has this support been dropped?

### Steps To Reproduce:
Create project: `composer create-project laravel/laravel duskTest`
Install Laravel Dusk: `composer require laravel/dusk`
Run Dusk config: `php artisan dusk:install`
Fetch correct chromedriver for installed Chrome version (just in case): `php artisan dusk:chrome-driver --detect`
Remove arguments from `DuskTestCase.php`: 
```
$options = (new ChromeOptions)->addArguments([
    //    '--disable-gpu',
    //    '--headless',
    //    '--window-size=1920,1080',
]);
```
Run example test: `php artisan dusk`

The error that is thrown:
```
1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\UnknownErrorException: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

The `ExampleTest.php` will pass with the `--headless` argument included.

**Comment by crynobone** [comment]
I can confirm removing `--headless` does work locally, however you will need to enable it for some (if not all) CI environment.

**Comment by RalpinMcDjango** [comment]
Ah ok, this must be an issue on my local environment. I'll close this
