### ISSUE TITLE
Would `ifAvailable()` be useful to compliment `whenAvailable()`?

### ISSUE THREAD

**Issue by u01jmg3** [laravel/dusk#880]
Whilst using Dusk I find myself using a method I've called `ifAvailable()` which is very similar to `whenAvailable()` except that if the element doesn't become available whilst waiting the given amount of time, it proceeds without failing.

Is this a feature you would be interested in having in Dusk? I find myself using it for modals that may or may not need to appear depending on the role of the user logged in.

**Comment by driesvints** [comment]
Feel free to attempt a PR to see if Taylor would accept it 👍
