### ISSUE TITLE
Replace `.env.dusk.local` within PHPUnit for PhpStorm support 

### ISSUE THREAD

**Issue by ludgerey** [laravel/dusk#883]
Currently the `.env.dusk.local` file is replaced when `php artisan dusk` is called. This works fine and is required if you want to use a separate database for testing, which I prefer with all my tests.

But however if you want to use PHPUnit without the `artisan` wrapper, then this file won't get replaced, all tests fail. So why do I want to do that? PhpStorm has great build in support for PHPUnit which includes a UI, easy one-click running of single tests, integrated XDebug support, etc. But this obviously works only with PHPUnit directly.

Since I am not the only one having this issue, there have been [some solutions out there](https://stackoverflow.com/questions/48070169/phpstorm-laravel-dusk-w-a-testing-database), which improve `DuskTestCase.php`. The replacement of the `.env` file then is inside the scope of PHPUnit and everything works perfectly.

So, wouldn't it be great to have this integrated by default?

Here is my version of the `DuskTestCase.php`:

```php
<?php

namespace Tests;

use Dotenv\Dotenv;
use Facebook\WebDriver\Chrome\ChromeOptions;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Laravel\Dusk\TestCase as BaseTestCase;

abstract class DuskTestCase extends BaseTestCase
{
    use CreatesApplication;

    public static function basePath($path = '') {
        return __DIR__. '/../' . ($path ? DIRECTORY_SEPARATOR.$path : $path);
    }

    // [ ... ]

    public static function setUpBeforeClass(): void
    {
        if (file_get_contents(self::basePath('.env')) !== file_get_contents(self::basePath('.env.dusk.local'))) {
            copy(self::basePath('.env'), self::basePath('.env.backup'));
        }
        copy(self::basePath('.env.dusk.local'), self::basePath('.env'));
        Dotenv::createMutable(self::basePath())->load();

        parent::setUpBeforeClass();
    }

    public static function tearDownAfterClass(): void
    {
        copy(self::basePath('.env.backup'), self::basePath('.env'));
        unlink(self::basePath('.env.backup'));
        Dotenv::createMutable(self::basePath())->load();

        parent::tearDownAfterClass();
    }

    // [ ... ] 
}
```

**Comment by driesvints** [comment]
Atm we don't plan on working on this ourselves but feel free to try a PR to see if Taylor would accept it 👍

**Comment by kiddtang** [comment]
Really hope it can be running directly in the PHPStorm

**Comment by jaap** [comment]
Thanks @ludgerey. Took me 2 hours to figure out there's a difference in running dusk from the command line vs running trough PHPstorm.

**Comment by njoguamos** [comment]
> Thanks @ludgerey. Took me 2 hours to figure out there's a difference in running dusk from the command line vs running trough PHPstorm.

Thanks. Am glad you figured this out. I had the same problem and am no longer running dusk test on PHPStorm.

**Comment by jadersbr** [comment]
It took me 3 days to discover this, sadly...
