### ISSUE TITLE
Dusk unstable windows random sizes, tests screenshots failing

### ISSUE THREAD

**Issue by cerw** [laravel/dusk#885]
- Dusk Version: v6.13.0 (v5 affected too)
- Laravel Version: v8.29.0 (6 7 too)
- PHP Version:  7.4.15 (from 7.0 too)
- Database Driver & Version: Mysql  / MariaDB (any really)

### Description:
Dear Laravel team,  

First of all sorry for quite a long bug report, trust me that tried (and exhausted)  all my option before I submit this issue. We love Laravel and all its glory and ecosystem. We also love QA and in recent months we can not get our test to prove that. :( 

We have been having an issue with dusk for the last few months, I have tried everything I could think of, improving dusk test code, different OS, different chrome(driver) Versions, node version, trying to debug test code and resize on every line, debug all JS code look for resize function, tune _(see method driver bellow)_ ChromeDriver setup And still we have failed :( and it seems to spread to many projects, not just one, they all using Laravel/Dusk, don't share any codebase. So that makes me think its something not related to our code. 

Then we found these - #858, #856 and I thought that would do it, but it did not. 

So here is what's going on: the test is passing and failing in random order, on the latest Chrome89 in Mac they all seem to pass 90% but in Linux, in CD/CI they fail 100%, most common errors: 

- ```Facebook\WebDriver\Exception\TimeoutException: timeout: Timed out receiving message from renderer: 10.000```
- ```Facebook\WebDriver\Exception\NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#email"}  (Session info: chrome=89.0.4389.82)```

They all seem to be related with the wrong size of the browser window, that will break chromedriver and also the selector of course, as some of the browser window is **0 x 0** . 

We have few tests and they take screenshots in latest project they produce around **112** screenshots. They all should be same size, as we do not modify (resize) screen, and before this bug ( I call it Cancer!) it was all same size, now these are the sizes: 

```
993x1392
1008x101
1008x1104
1008x170
1008x193
1008x479
1016x1235
```
Then there are the ones who failed and they have no screenshot as they had no viewport at all. 

If you can shine some light on this that would be great, as I have burned days on this and going bit mad 😩 

Thank you, if you still reading :)

Petr

DuskTestCase.php@driver
```php
protected function driver()
    {
        $resolution = env('RESOLUTION', '1366,1024');
        if (env('HEADLESS') === "0") {
            $options = (new ChromeOptions)->addArguments([
              '--window-size='.$resolution,
              '--log-level=1',
              '--verbose'
            ]);
        } else {
            $options = (new ChromeOptions)->addArguments([
                '--disable-gpu',
                '--log-level=1',
                '--headless',
                '--no-sandbox',
                '--window-size='.$resolution,
                '--verbose',
            ]);
        }
        return retry(5, function () use ($options) {
            return RemoteWebDriver::create(
                'http://localhost:9515',
                DesiredCapabilities::chrome()->setCapability(
                    ChromeOptions::CAPABILITY,
                    $options
                ),
                90000,
                90000
            );
        }, 50);
    }
```

### Steps To Reproduce:

```./vendor/bin/phpunit ```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new dusk-issue-885 --github="--public"
```

After you've posted the repository, I'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by cerw** [comment]
@driesvints sorry I am stil working on getting the repo to you guys.
