### ISSUE TITLE
Adding $element->getText() to assertSeeIn message

### ISSUE THREAD

**Issue by lk77** [laravel/dusk#892]
Hello,

i'm making an issue prior to any attempt to make a pull request,
i would like to see the result of $element->getText() method in the message of methods like assertSeeIn :

```
    /**
     * Assert that the given text is present within the selector.
     *
     * @param  string  $selector
     * @param  string  $text
     * @return $this
     */
    public function assertSeeIn($selector, $text)
    {
        $fullSelector = $this->resolver->format($selector);

        $element = $this->resolver->findOrFail($selector);
        
        $elementText = $element->getText();

        PHPUnit::assertTrue(
            Str::contains($elementText, $text),
            "Did not see expected text [{$text}] within element [{$fullSelector}]. Saw [{$elementText}] instead."
        );

        return $this;
    }
```
Currently the only way to see what is wrong is to look at the screenshot, but the logs won't say what it saw in the element.

if you approve such changes i will make a pr for assertSeeIn / assertDontSeeIn / assertSeeAnythingIn / assertSeeNothingIn

thanks.

**Comment by driesvints** [comment]
I think that's useful yes. Feel free to attempt a PR to see if Taylor would accept it.
