### ISSUE TITLE
Retry functionality with timeouts

### ISSUE THREAD

**Issue by deepsidhu1313** [laravel/dusk#893]
Is it possible to add retry function like

```php
$browser->retry($max_retries,$timeout_for_each_try)->assertSee('Some Text');
```
where `$max_retries` can be used to set the number of tries before failing the test and `$timeout_for_each_try` can be used to set the timeout of each try. For example if max retries are set to 5 and timeout set to 1 sec, in best case scenario test will pass in first try and in worst case scenario it will pass in 5 seconds or fail after 5 seconds.

**Comment by crynobone** [comment]
I normally just use.

```php
$browser->waitFor('Some Text', $maxSeconds)->assertSee('Some Text');
```

**Comment by driesvints** [comment]
See the above.
