### ISSUE TITLE
Browser auto-closing after using `--browse` option

### ISSUE THREAD

**Issue by AnandPilania** [laravel/dusk#894]
- Dusk Version: 6.15.0
- Laravel Version: 8.5.15
- PHP Version: 8.0.3
- Database Driver & Version: MySQL 8.0.23

### Description:
Hi, I'm trying to use `magic-test-laravel` package for browser testing. This package executes `dusk` command with `--browse` option. (same result when executing separately) But every time browser auto-closing after few seconds.

### Steps To Reproduce:
Using as-is test files generate by `dusk:install`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
