### ISSUE TITLE
Improve on-boarding and DX for developers trying to start a good testing habit

### ISSUE THREAD

**Issue by damms005** [laravel/dusk#900]
Hi,

I am slowly and progressively improving my code testing skill; and I believe that there will also be some other developers that are just starting to build this same code-testing habit and will at one time or the other try our Laravel Dusk.

For some reason, `.env` was used to run my Dusk tests instead of `.env.dusk.local`. This was catastrophic, as all my data was wiped because I needed to use `refreshDatabase()` in one of the tests.

IMHO, Dusk can reduce the inadvertent usage of `.env` by explicitly requesting that a CLI flag be set to explicitly use `.env` if no `.env.dusk.{environment}` is found.

For example, the flag may be named `allow-unsafe-migration` or something like that. So if Dusk is ran as `php artisan dusk` and there is no `.env.dusk.{environment}` available, then it should not default to using `.env` (maybe throw an exception or something). However, if Dusk is ran as `php artisan dusk --allow-unsafe-migration` and there is no `.env.dusk.{environment}`, then Dusk can default to using `.env` because it will then be clear than the user is conscious of the fact that the `.env` will be used.

This will further create a lower entry barrier for developers that are just building the habit of code-testing, so that they are not met with the frustration of inadvertent wiping of their local test data.

I can make a PR for this if accepted

**Comment by driesvints** [comment]
Feel free to attempt a PR to the docs 👍
