### ISSUE TITLE
invalid argument (Session info: headless chrome=91.0.4472.77)

### ISSUE THREAD

**Issue by mustafaeida** [laravel/dusk#903]
- Dusk Version: ^6.15
- Laravel Version: ^8.12
- PHP Version: 8.0.3

### Description:
i have this error 

invalid argument (Session info: headless chrome=91.0.4472.77) 

when if try 
        $browser->visit('/');
but when i try 
        $browser->visit('https://www.google.com');
there is no any error 

code : 

        $process = (new ChromeProcess)->toProcess();
        $process->start();
        $options = (new ChromeOptions)->addArguments(['--disable-gpu', '--headless']);
        $capabilities = DesiredCapabilities::chrome()->setCapability(ChromeOptions::CAPABILITY, $options);
        $driver = retry(5, function () use($capabilities) {
            return RemoteWebDriver::create('http://localhost:9515', $capabilities);
        }, 50);
        $browser = new Browser($driver);
//        $browser->visit('https://www.google.com');
        $browser->visit('/');
        $browser->screenshot(base_path('tests/Browser/screenshots/'.date('Y-m-d-H-i-s') . '.png'));
        $browser->quit();
        $process->stop();

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
