### ISSUE TITLE
Unable to use dusk with v-select

### ISSUE THREAD

**Issue by Benoit1980** [laravel/dusk#908]
"laravel/framework": "6.2"
 "laravel/dusk": "^6.11"

Hello,

It looks like Dusk is unable to find the v-select elements:
```
<v-select v-model="product_description_results" label="description"
:options="product_descriptions" placeholder="Type in your description" dusk="dusk-select-description"></v-select>
```

```
I tried:
->click('@dusk-select-description')
->click('#dusk-select-description') //Replaced it with an id on the v-select
```

But I keep seeing this error:
```
Facebook\WebDriver\Exception\NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#dusk\2D select\2D description"}
```

What is very strange is that this works with a normal select.

Any work out please? I cannot find any good workout on the net that works in my case.

Thank you,

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
