### ISSUE TITLE
Compatibility should match php versions mentioned in composer.json. Actually only the latest passes!

### ISSUE THREAD

**Issue by chilio** [laravel/dusk#946]
- Dusk Version: 6.19
- Laravel Version: 8.0
- PHP Version: 8.0
- Database Driver & Version: Does not matter.

### Description:
As of Laravel docs and composer we could have lines in composer require: like 
"php": "^7.3|^8.0"
for optional versions (php 7.4 of course should be considered here also)

### Steps To Reproduce:
If you try to run Dusk with php 7.3 or php 7.4 you'll receive this error:
`Composer detected issues in your platform:`

`Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.25.`

However, composer passes without problems, only Dusk fails!

This seems like an inconsistency with composer accepting optional former versions and Dusk accepting only the latest one.

**Comment by chilio** [comment]
To make it clear `require: "php": "^7.3|^7.4|^8.0"` does not resolve this issue also.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
