### ISSUE TITLE
TypeError on default laravel installation with sail

### ISSUE THREAD

**Issue by matsava** [laravel/dusk#947]
- Dusk Version: 6.19.2
- Laravel Version: 8.72.0
- PHP Version: v8.0.12
- Database Driver & Version:

### Description:
A default laravel installation with sail and dusk currently fails with the following error:
`> sail dusk
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 00:04.852, Memory: 20.00 MB

There was 1 error:

1) Tests\Browser\ExampleTest::testBasicExample
TypeError: Facebook\WebDriver\Remote\JsonWireCompat::getElement(): Argument # 1 ($rawElement) must be of type array, string given, called in /var/www/html/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php on line 211

/var/www/html/vendor/php-webdriver/webdriver/lib/Remote/JsonWireCompat.php:21
/var/www/html/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:211
/var/www/html/vendor/laravel/dusk/src/ElementResolver.php:373
/var/www/html/vendor/laravel/dusk/src/Concerns/MakesAssertions.php:177
/var/www/html/vendor/laravel/dusk/src/Concerns/MakesAssertions.php:152
/var/www/html/tests/Browser/ExampleTest.php:20
/var/www/html/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:69
/var/www/html/tests/Browser/ExampleTest.php:21`

### Steps To Reproduce:

1. curl -s "https://laravel.build/selenium?with=mysql,selenium" | bash
2. cd selenium && ./vendor/bin/sail up -d
3. ./vendor/bin/sail composer require --dev laravel/dusk
4. ./vendor/bin/sail artisan dusk:install
5. Change APP_URL in .env 
6. ./vendor/bin/sail artisan dusk

**Comment by matsava** [comment]
Hi @driesvints, yeah sorry, that's what I wanted to type actually. This problem occurs when running `sail dusk` not with `artisan`. Were you able to give it a try? I'm on an Apple M1 if that changes anything.

**Comment by driesvints** [comment]
I can run `sail dusk` fine. I don't think this is M1 related tbh as it's a type error. Most likely you need to run a `composer update`.

**Comment by matsava** [comment]
Yeah that's what I thought, but then again it was a new installation so everything were up-to-date when I run `sail composer update`.

**Comment by driesvints** [comment]
I think it's best that you try a support channel as I don't think this is Sail related:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by matsava** [comment]
For anyone following this issue in the future, this seems like php-webdriver issue. Everything works fine when using firefox. https://github.com/derekmd/laravel-dusk-firefox
