### ISSUE TITLE
DUSK_HEADLESS_DISABLED not checked properly

### ISSUE THREAD

**Issue by Navi2016** [laravel/dusk#948]
- Dusk Version: 6.19.2
- Laravel Version: 8.72.0
- PHP Version: 7.3.22
- Database Driver & Version: MySQL 5.7

### Description:

When installing Dusk a DuskTestCase.php is generated. It contains this part:

`    /**
     * Determine whether the Dusk command has disabled headless mode.
     *
     * @return bool
     */
    protected function hasHeadlessDisabled()
    {
        return isset($_SERVER['DUSK_HEADLESS_DISABLED']) ||
               isset($_ENV['DUSK_HEADLESS_DISABLED']);
    }
`

But this checks whether DUSK_HEADLESS_DISABLED has been set, and does not check it's value. So when setting:
DUSK_HEADLESS_DISABLED=false in .env.dusk

It returns true even though it's set to false.

### Steps To Reproduce:

Install fresh laravel
composer require --dev laravel/dusk
php artisan dusk:install
DUSK_HEADLESS_DISABLED=false in .env.dusk

**Comment by driesvints** [comment]
Don't set `DUSK_HEADLESS_DISABLED=false`. Only set `DUSK_HEADLESS_DISABLED=true` if you need it.

**Comment by Navi2016** [comment]
Don't you think that's kind of counter intuitive? Spend a few hours on why it wasn't working and picking up the proper command line params. Another dev had set this value and turning it to false should work.

Seems like a pretty easy fix? Would you like me to write it?

**Comment by driesvints** [comment]
Yeah sure, feel free to PR something 👍

**Comment by crynobone** [comment]
@driesvints is correct, the proper usage is actually via `php artisan dusk --browse` to run without **headless** or  `CI=true php artisan dusk` (which will be populated by most CI) to run with **headless**
