### ISSUE TITLE
Laravel Octane ignore APP_ENV change in .env.dusk

### ISSUE THREAD

**Issue by clmntgr** [laravel/dusk#949]
- Dusk Version: 6.19.2
- Laravel Version: 8.72.0
- PHP Version: 8.0.3
- Database Driver & Version: pgsql (no idea for the version)
- Laravel Octane: 1.0.19 (swoole)

### Description:
When running Laravel Dusk tests against an Octane server not all environment variables are updated with the content of `.env.dusk` (.env.dusk.local` in my case).

I think the issue come from here (https://github.com/laravel/octane/blob/1.x/src/Commands/StartSwooleCommand.php#L82), the Swoole server is started using the `APP_ENV` environment variable and it will take precedence over any `.env` changes.

### Steps To Reproduce:

If the description is not enough I will create a new app to reproduce but any app with Dusk & Octane will demonstrate the problem.

**Comment by crynobone** [comment]
> When running Laravel Dusk tests against an Octane server not all environment variables are updated with the content of .env.dusk (.env.dusk.local` in my case).

It seems that `php artisan serve` also return the same as Octane server. 


```php
// routes/web.php

Route::get('dusk-test', function () {
    return env('APP_ENV');
});
```

```php
// tests/Browser/ExampleTest.php

$this->browse(function (Browser $browser) {
    $browser->visit('/dusk-test')->assertSee('local')->assertDontSee('dusk');
});
```

```ini
# .env
APP_ENV=local
APP_URL=http://localhost:8000

# .env.dusk
APP_ENV="dusk-test"
APP_URL=http://localhost:8000

# .env.dusk.local
APP_ENV="dusk-local-test"
APP_URL=http://localhost:8000
```

![image](https://user-images.githubusercontent.com/172966/143013464-b10727ee-6518-4b0a-8c3b-7eb688439d1b.png)

**Comment by driesvints** [comment]
Since we only gotten one request for this, I'm going to close this. We're open to PR's for adding support for this. Thanks
