### ISSUE TITLE
Managing browser permissions with Laravel Dusk

### ISSUE THREAD

**Issue by piljac1** [laravel/dusk#951]
**DISCLAIMER: I know it isn't an issue per say, but haven't had any luck on the support channels you're suggesting, so I'm guessing that it is either an hidden feature, or impossible at the moment.**

Hi guys! I wanted to test a "copy link" on the Web app I'm working on and I ran into browser permissions issues when trying to access the clipboard content while testing. Of course, that default behavior makes sense, because Google Chrome prompts the user and ask for permission to access the clipboard. However, I haven't found a way to tell Dusk to enable specific permissions. I found the following Cypress example that is probably the appropriate way of doing it, but I don't know if there's a Dusk equivalent. 
```js
cy.wrap(Cypress.automation('remote:debugger:protocol', {
  command: 'Browser.grantPermissions',
  params: {
    permissions: ['clipboardReadWrite', 'clipboardSanitizedWrite'],
    origin: window.location.origin,
  },
}))
```
Thanks in advance!

**Comment by driesvints** [comment]
We can't provide support with Cypress sorry. Please continue to try one of the support channels.

**Comment by piljac1** [comment]
@driesvints That's not what I asked... I asked if something similar was possible with Dusk...

**Comment by driesvints** [comment]
@piljac1 like I said: we don't provide support here, sorry.
