### ISSUE TITLE
Can I do some non testing operations with laravel dusk?

### ISSUE THREAD

**Issue by WhiteDragon29** [laravel/dusk#952]
After consulting the document, I found that Dusk can only do some test operations? For example, I want to often use commands to simulate my browsing an e-commerce website to refresh the current page. Check whether the product inventory is sufficient, can I place an order? Simulate real-life operations? How will I complete the development of similar behavioral operations?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
