### ISSUE TITLE
Dusk is failing to run

### ISSUE THREAD

**Issue by abbieben07** [laravel/dusk#955]
- Dusk Version: 6.20.0
- Laravel Version: 8.78.1
- PHP Version: 8.1.1
- Database Driver & Version: 15.1 Distrib 10.4.22-MariaDB

### Description:
I have used Laravel Dusk in a project in 2020  on a GCP VM and it worked, fast forward I have a new project I deployed on GCP VM and I can't get Laravel Dusk to run properly. I followed the instruction on the documentation and I also installed the latest version of google chrome and chromium.

### Steps To Reproduce:
`php artisan dusk`

`1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\UnknownErrorException: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

/opt/bitnami/apache2/htdocs/laravel/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:139
/opt/bitnami/apache2/htdocs/laravel/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:372
/opt/bitnami/apache2/htdocs/laravel/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:131
/opt/bitnami/apache2/htdocs/laravel/tests/DuskTestCase.php:46
/opt/bitnami/apache2/htdocs/laravel/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:219
/opt/bitnami/apache2/htdocs/laravel/vendor/laravel/framework/src/Illuminate/Support/helpers.php:234
/opt/bitnami/apache2/htdocs/laravel/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:220
/opt/bitnami/apache2/htdocs/laravel/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:98
/opt/bitnami/apache2/htdocs/laravel/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:66
/opt/bitnami/apache2/htdocs/laravel/tests/Browser/ExampleTest.php:21`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
