### ISSUE TITLE
Curl error thrown for http POST to /session

### ISSUE THREAD

**Issue by vignesh-krishnamoorthy** [laravel/dusk#961]
### Version details:

- Dusk Version:   **6.15**
- Laravel Version:  **8.4.0**
- PHP Version:   **7.3.33**
- Platform:  **CentOS Linux release 7.9.2009**
- Browser:  **Google Chrome 97.0.4692.99**

### Description:

  While using laravel/dusk on a Linux computer, I encountered the following problem. I've tried everything suggested in https://github.com/laravel/dusk/issues/588. Nothing seems to be working for me. I've also given full permission to the dusk directory. As it is in Windows, it worked flawlessly. Different approaches or solutions are appreciated. Thank you very much.

#### Error:

```
Facebook\WebDriver\Exception\WebDriverCurlException

  Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","goog:chromeOptions":{"args":["--disable-gpu","--headless","--no-sandbox"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"ANY","chromeOptions":{"args":["--disable-gpu","--headless","--no-sandbox"]}}}

Failed to connect to localhost port 9515 after 0 ms: Connection refused

  at vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:332
    328▕             if (is_array($params) && !empty($params)) {
    329▕                 $msg .= sprintf(' with params: %s', json_encode($params, JSON_UNESCAPED_SLASHES));
    330▕             }
    331▕
  ➜ 332▕             throw new WebDriverCurlException($msg . "\n\n" . $error);
    333▕         }
    334▕
    335▕         $results = json_decode($raw_results, true);
    336▕

```

#### Code:

```
$process = (new ChromeProcess)->toProcess();
$process->start();
$optionParams = ["--headless","--disable-gpu", "--no-sandbox"];
$options = (new ChromeOptions)->addArguments($optionParams);
$capabilities = DesiredCapabilities::chrome()->setCapability(ChromeOptions::CAPABILITY, $options);
RemoteWebDriver::create('http://localhost:9515', $capabilities);
```

CC:  @driesvints

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Can you also try with the latest Dusk and Laravel versions?

Thanks

**Comment by vignesh-krishnamoorthy** [comment]
Okay @driesvints. Thank you for your response.
