### ISSUE TITLE
Dusk and Vue3 not working together

### ISSUE THREAD

**Issue by MrKoopie** [laravel/dusk#966]
- Dusk Version: 6.22.1
- Laravel Version: 9.1.0
- PHP Version: 8.1.2
- Database Driver & Version: MySQL, 8.0.28-0ubuntu0.21.10.3

### Description:
I tried to run Dusk on Vue 3. Using the type or key methods I have tried to manipulate input fields. From what I can see, data is being entered into the input fields. With Vue2, the data is processed within Vue. With Vue3, this does not. By opening the page that I was testing in Chrome and running Dusk afterwards, you can see that Dusk manipulates the fields but Vue does not get updated.

I had this issue initially on MacOS. To make sure that my development environment is not the issue, I have ran this using sail as well.

Result: The data is not being processed by Vue3 and this breaks further testing.

So far I have not seen any reports here nor a remark on the Dusk page about being incompatible with Vue3.

### Steps To Reproduce:

For Vue3:
1. Clone https://github.com/MrKoopie/dusk-vue3-test
2. Run sail dusk

Result: this fails.

For Vue2:
1. Clone https://github.com/MrKoopie/dusk-vue3-test
2. Edit resources/views/welcome.blade.php
3. Change the Vue library to v2 by commenting.
4. Run sail dusk

Result: this works.

**Comment by derekmd** [comment]
Your Vue 3 sample app has a JavaScript error that is captured in `tests/Browser/console/*.log`.

![nein-vue](https://user-images.githubusercontent.com/823566/154601195-49f8c7ea-81fe-43de-9f79-678870bac665.png)

It needs to be updated to mount the DOM using Vue 3's style: https://vuejs.org/guide/introduction.html

```javascript
Vue.createApp({
    data() {
        return {
            email: 'dan',
            password: null
        };
    }
}).mount('#app');
```

After making that change in file resources/views/welcome.blade.php, command `php artisan dusk` on the dusk-vue3-test repo passed green for me.

**Comment by MrKoopie** [comment]
@derekmd Thank you for looking into this. You are correct. I did not check that particular log, but I did check the browser log. I found that when you open the browser on the URL you are testing, that Dusk actually uses this tab to test with. Or, at least this is what I thought. There, no errors were found in a test with InertiaJS. And, no console log is created.

Upon further inspection, I found that it had issues with connecting to BrowserSync, however, this should not fail the script. So, I looked further, and I was misled. I thought that having a tab opened with the URL that was being tested in DUSK would work. As it turns out, it does not work this way. While Dusk does type the data in your browser, it does not properly process. As you can see in my recording, Dusk does succeed in the console, but the browser (where Dusk wrote some data) failed. The solution in this case was to add a pause, or to prevent time-out luck, waitForText is probably even better.

You can see my recording here: https://vimeo.com/679034373/6a27f649bf

I hope these findings helps others when they make the unlucky assumption that this should work in the browser.
