### ISSUE TITLE
[Request] Proposal for Browser class

### ISSUE THREAD

**Issue by brandonferens** [laravel/dusk#97]
All of the stubs reference the Browser class at `Laravel\Dusk\Browser`. My proposal is that a Browser class is installed within the tests that extends `Laravel\Dusk\Browser`. Not exactly sure the best/most logical place for this file, perhaps `tests/Dusk/Browser.php`.

The reason for this is that I have created some custom methods on the browser like `loginAsUser()` and `loginAsAdmin()`. I also set those users into the object and are made available as `$browser->user`. This is just part of my use case, but I can see the potential for people needing this kind of flexibility on their browser object.

If you would like, I can create a PR with the necessary code to accomplish this feature.

**Comment by brandonferens** [comment]
Thanks @sileence, that is very close to what I created in my DuskTestCase!

**Comment by deleugpn** [comment]
Should this be closed?

**Comment by browner12** [comment]
no, i think his is different. 3b2e5c4 is just a little optimization.

I'm all for this update, for the exact use cases you suggested.

**Comment by brandonferens** [comment]
No, this should be closed. 3b2e5c4 is a much better approach than what I came up with. You can now add something like this to your `DuskTestCase`:

    /**
     * Create a new Browser instance.
     *
     * @param  \Facebook\WebDriver\Remote\RemoteWebDriver  $driver
     * @return \Laravel\Dusk\Browser
     */
    protected function newBrowser($driver)
    {
        return new MyOwnBrowser($driver);
    }

This would then override the default class and would load your custom browser class.

Within that custom browser class, you could have a method like this:

    /**
     * @var int
     */
    protected $adminId = 1;

    /**
     * @var \App\Models\User
     */
    public $user;

    /**
     * Log into the application using a given user ID or email.
     *
     * @return $this
     */
    public function actingAsAdmin()
    {
        $this->user = User::find($this->adminId);

        return $this->loginAs($this->user);
    }

This allows you to do something like this within your dusk test

    $browser->actingAsAdmin()->visit('/admin/page');

**Comment by browner12** [comment]
ahh, got it now.  The intent is that you override the `newBrowser` method if you want a custom browser.

**Comment by brandonferens** [comment]
Exactly.
