### ISSUE TITLE
Freshly generated DuskTestCase.php throws "Undefined type Tests\CreatesApplication"

### ISSUE THREAD

**Issue by Kaos-Industries** [laravel/dusk#974]
- Dusk Version: 6.23
- Laravel Version: 8.12
- PHP Version: 8.0.15

### Description:

I'm trying to set up Laravel Dusk to test my Laravel site as part of a larger Github Action CI/CD workflow. 

Following [the documentation](https://laravel.com/docs/8.x/dusk), I ran:

```
composer require --dev laravel/dusk
php artisan dusk:install
```

The latter command created a `tests/Browser` directory and a `tests/DuskTestCase.php` file.

The problem is that when I open up `DuskTestCase.php` Intelephense immediately complains:

    Undefined type 'Tests\CreatesApplication'

I also get a slightly different, but clearly related, error when running the GitHub Action:

    PHP Fatal error:  Trait "Tests\CreatesApplication" not found in /home/runner/work/mysite/mysite/tests/DuskTestCase.php on line 10

I have the following in my `composer.json`:

	"autoload-dev": {
		"psr-4": {
			"Tests\\": "tests/"
		}
	}

...and have also run `composer dump-autoload` locally.

**What's going on here? Why does the example test file generated by Dusk seem to ship with an error and what can I do to fix it?**

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
