### ISSUE TITLE
Empty page after pressing button with Laravel Dusk - widely reported, likely a bug

### ISSUE THREAD

**Issue by Kaos-Industries** [laravel/dusk#975]
- Dusk Version: 6.23
- Laravel Version: 8.83.6
- PHP Version: 8.0.15
- Chrome Driver Version: 100.0.4896.60

### Description:

I'm trying to use the following test for my site's Stripe Element forms:

    <?php

    namespace Tests\Browser;

    use Illuminate\Foundation\Testing\DatabaseMigrations;
    use Laravel\Dusk\Browser;
    use Tests\DuskTestCase;

    class PaymentsTest extends DuskTestCase
    {
        use DatabaseMigrations;

        /**
        * A Dusk test example.
        * 
        * @return void
        */
        public function test_payments_are_working()
        {
            $this->browse(function (Browser $browser) {
                $browser->visit("/manufacturers/oneplus")
                ->type('email', "customer@example.com")
                ->press('Continue')
                ->waitForLocation('/payment')
                ->waitFor("#paypal-button-container iframe")
                ->withinFrame('#paypal-button-container iframe', function($browser) {
                    $browser->click(".paypal-button");
                })
                ->waitFor(".paypal-checkout-sandbox-iframe")
                ->withinFrame('.paypal-checkout-sandbox-iframe', function($browser) {
                    $browser->click(".paypal-checkout-close");
                })
                ->waitFor('.__PrivateStripeElement iframe')
                ->withinFrame('.__PrivateStripeElement iframe', function($browser) {
                    $browser
                    ->pause(1000)
                    ->keys('input[placeholder="1234 1234 1234 1234"]', 4242424242424242)
                    ->keys('input[placeholder="MM / YY"]', '0125')
                    ->keys('input[placeholder="CVC"]', '123')
                    ->select('select[name="country"]', 'GB')
                    ->keys('input[name="postalCode"]', 'SW1A 1AA')
                    ->pause(500);
                })
                ->clickAndWaitForReload("@stripe-payment-button")
                ->pause(10000) // for debugging purposes
                ->assertSeeAnythingIn(".text-success");
            });
        }
    }

The entire test works right up until the Stripe payment button is clicked, after which the page becomes blank and any assertions fail with their respective errors, such as "no such element":

    Time: 00:19.175, Memory: 30.00 MB

    There was 1 error:

    1) Tests\Browser\PaymentsTest::test_payments_are_working
    Facebook\WebDriver\Exception\NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"body .text-success"}
    (Session info: headless chrome=100.0.4896.75)

Looking at the screenshot generated by my GitHub Action workflow at the point of failure, I can see that immediately after the button is pressed it becomes a blank page instead of redirecting to the expected route, even though prior to this all the routes are working. 

**What I've Already Tried:**

* Setting `APP_URL` in `.env.dusk.testing` to `http://127.0.0.1:8000` and running Dusk with `php artisan dusk --env=testing`
* Adding a step to run migrations in my GitHub Action, which was missing from the [example in the documentation](https://laravel.com/docs/8.x/dusk#running-tests-on-github-actions)

Given that: 

a) I've ruled common solutions to this issue out, 
b) The test works absolutely fine on my local machine, and 
c) StackOverflow has *many* unresolved issues of the exact same scenario:

https://stackoverflow.com/questions/70757721/laravel-dusk-test-fails-on-ci-github-actions-but-succeeds-locally
https://stackoverflow.com/questions/65910820/laravel-dusk-tests-fail-in-github-ci-but-work-locally
https://stackoverflow.com/questions/63892778/laravel-dusk-error-when-testing-on-github-actions
https://stackoverflow.com/questions/71915128/pressing-button-in-laravel-dusk-test-results-in-blank-screen-on-github-actions

...I can only conclude that this is either a bug with Laravel Dusk or a serious omission from the Dusk documentation on how to integrate it with GitHub Actions. This is **not** an issue which can be resolved on a support forum because I and the several others above have already attempted it to no resolution, which leaves the ball in the court of the Dusk devs to determine whether this is a bug or not.

Feel free to request if any further code, such as my markup or GitHub workflow .yml file, is needed.

**Comment by DanielGSoftware** [comment]
I'm currently experiencing the same issue for a test. After a button is clicked to redirect the page, I get a empty page as a result. Hope we can solve this! :)

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
I'll re-open this once a repo has been provided. Thanks
