### ISSUE TITLE
Intercept response from ajax

### ISSUE THREAD

**Issue by spartyboy** [laravel/dusk#977]
Tried Intercepting response from ajax when we click on a button and the page uses ajax to submit. this is possible in python's playwright using 
`async with page.expect_response('**api/assgsygsgj)`
but how do i replicate this behaviour to get the content of a response from ajax and assert a value is present in that json

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
