### ISSUE TITLE
Chromedriver install fails with  SSL operation failed with code 1. OpenSSL Error messages: error:0A000126:SSL routines::unexpected eof while reading

### ISSUE THREAD

**Issue by euperia** [laravel/dusk#979]
I'm submitting this in the hope it will save others from trawling the internet for answers 😃 :

- Dusk Version: 6.24.0
- Laravel Version: 9.11.0
- PHP Version: 8.1.6
- Database Driver & Version: n/a
- OS & Version: Ubuntu 22.04

### Description:
Installing dusk and/or chrome-driver throws an SSL exception.

> **NOTE: THE PROBLEM IS WITH PHP AND NOT DUSK!!**

This issue is caused by a compatibility issue between PHP and OpenSSL 3.0.  A fix has been added to PHP and will be available in PHP 8.1.7 (currently on PHP 8.1.6 at time of writing).

See:
* [https://github.com/php/php-src/issues/8369](https://github.com/php/php-src/issues/8369)
* [https://github.com/php/php-src/commit/74f75db0c3665677ec006cd379fd561feacffdc6](https://github.com/php/php-src/commit/74f75db0c3665677ec006cd379fd561feacffdc6)

### Steps To Reproduce:

```
/var/www/web$ php artisan dusk:install
Dusk scaffolding installed successfully.
Downloading ChromeDriver binaries...

   ErrorException 

  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A000126:SSL routines::unexpected eof while reading

  at vendor/laravel/dusk/src/Console/ChromeDriverCommand.php:217
    213▕         if ($this->option('proxy')) {
    214▕             $streamOptions['http'] = ['proxy' => $this->option('proxy'), 'request_fulluri' => true];
    215▕         }
    216▕ 
  ➜ 217▕         return trim(file_get_contents($this->latestVersionUrl, false, stream_context_create($streamOptions)));
    218▕     }
    219▕ 
    220▕     /**
    221▕      * Detect the installed Chrome / Chromium major version.

      +27 vendor frames 
  28  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by ethanclevenger91** [comment]
@euperia temporary workaround? downgrade to PHP 8.0?

**Comment by euperia** [comment]
@ethanclevenger91 I guess so if you're not using and 8.1 specific features.

PHP 8.1.7 was officially released yesterday.  Hopefully it will find its way into Ubuntu 22.04 soon, even if it is only in the Ondřej Surý PPA.
