### ISSUE TITLE
Connection refused for subdomain routes within Laravel Sail

### ISSUE THREAD

**Issue by jspekken** [laravel/dusk#981]
- Dusk Version: 6.24.0
- Laravel Version: 9.17
- PHP Version: 8.1.7
- Database Driver & Version: MySQL 8.1

### Description:

I have two routes. One normal route to the root URL, and one within a domain group (subdomain). When I execute the "normal" route, everything works fine and the tests pass. But when I run tests on the subdomain route the webdriver exits with: `unknown error: net::ERR_CONNECTION_REFUSED`.

When I run `php artisan route:list` I see this:

```
...
GET|HEAD   / ................................................ no-domain-route
GET|HEAD   test.laravel.test/test .............................. domain-route
...
```

When I execute curl for the subdomain:

```
curl test.laravel.test/test -I
HTTP/1.1 200 OK
Host: test.laravel.test
...
```

```php
// routes
Route::get('/', function () {
    return view('test-view');
})->name('no-domain-route');

Route::domain('test.laravel.test')->group(function () {
    Route::get('/test', function () {
        return view('test-view');
    })->name('domain-route');
});

// Dusk tests...
public function test_it_can_visit_a_normal_domain(): void
{
    $this->browse(function (Browser $browser) {
        $browser->visitRoute('no-domain-route')->assertSee('very cool');
    });
}

public function test_it_can_visit_a_subdomain()
{
    $this->browse(function (Browser $browser) {
        $browser->visitRoute('domain-route')->assertSee('very cool');
    });
}
```

### Steps To Reproduce:

Github repository: https://github.com/jspekken/laravel-dusk-test

**Comment by driesvints** [comment]
Can you re-create the repo with the below command please? Right now, all your changes are in one commit, making it hard to debug.

```bash
laravel new bug-report --github="--public"
```

Also: are you running `sail dusk`? https://laravel.com/docs/9.x/sail#laravel-dusk
