### ISSUE TITLE
Add scrollIntoView() to all Browser manipulation calls

### ISSUE THREAD

**Issue by Dhermann27** [laravel/dusk#985]
I was pleasantly surprised to learn that scrollIntoView(selector) had been added ages ago to the Browser object, but my idea is why I'm calling it at all: it seems like all browser manipulation calls should execute this method as a precursor to the action. I cannot imagine a usecase where a developer would be expecting to receive this exception:

```
Facebook\WebDriver\Exception\ElementClickInterceptedException: element click intercepted: Element is not clickable at point (880, 1221)
  (Session info: headless chrome=103.0.5060.53)
```

I'm preparing to add a bunch of scrollIntoView() calls to my tests to make them more resilient but I'd love to see this added in a future release.

Cheers,
Dan

**Comment by driesvints** [comment]
Heya, feel free to attempt a PR to see if Taylor would accept it 👍
